### ISSUE TITLE
auto assign when creating issues

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#1013]

**Comment by ashumz** [comment]
Hi @iffyuva, 

Sorry for the delay in response! We actually only auto assign your pull requests to you if you open one that has either a GitHub closing keyword (fixes/resolves/closes, etc) followed by an issue reference, or Waffle's "Connect" keywords (connect to, connects to, connects, connected to). There is no way to turn this off at this time. Previously we auto-assigned all PR's with issue refs, regardless of what they were preceded by. We made this more deliberate by enforcing the rules above -- so hopefully this helps you!

**Comment by ashumz** [comment]
[+1](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/701318792)

"Can I auto-assign issues? If I'm filtering issues based on my username, would be awesome to be able to automatically assign so that I don't have to change the filter."

**Comment by iffyuva** [comment]
@ashumz thanks for updating me.

**Comment by alexbw** [comment]
That comment form before is me, I'm kind of interim PM on a project, and auto-assigning, or at least, having a tabbable "assign" field son issue creation, would really speed and streamline the "issue dumping" process before sprints.

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
