### ISSUE TITLE
Additional keyboard shortcuts

### ISSUE THREAD

**Issue by agibson22** [waffleio/waffle.io#1015]
For example, when assigning a task, it would be great if I could use the arrow keys to traverse the autocomplete dropdown of usernames.

**Comment by kwiens** [comment]
+1

**Comment by kelseyq** [comment]
I'd like a keyboard shortcut to add a (non-board) tag

**Comment by ashumz** [comment]
[+1](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/ashley@waffle.io/conversations/970049843)

"I would love some more keyboard shortcuts, like Trello.
Specifically I would love to be able to comment on, add labels to or assign people to issues without using the mouse."

**Comment by bgvo** [comment]
+1

More shortcuts as Trello

**Comment by charlesfracchia** [comment]
Pressing the <spacebar> key when a dropdown is selected  should open the dropdown and allow the user to select the item using the <arrow keys>

**Comment by carolclark** [comment]
I would like a shortcut to open the card I'm looking at for editing.

**Comment by hcurotta** [comment]
I'd like a shortcut that allows me to go straight to filtering by milestone/label. Alternatively, hit f to filter then be able to use the arrow keys to jump down to the milestone filter.

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
