### ISSUE TITLE
support Gogs integration

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#1034]
https://github.com/gogits/gogs

[internal] https://app.intercom.io/apps/fb774a034de340cde33822ae0c071ad60efe899f/conversations/416282044

**Comment by Unknwon** [comment]
What are the API sets that waffle.io needed? 

Give me a list so I can add those to Gogs and help on this ticket. :D

**Comment by homeyer** [comment]
From the [GitHub API](https://developer.github.com/v3/) we rely on:
- authentication (oauth)
- issues
- milestones
- pull requests
- repositories

Even if the APIs are compatible, I can't guarantee we'll integrate with Gogs.

**Comment by rody** [comment]
I would love to see that happening too ! :+1:

**Comment by AlexDunmow** [comment]
Is there any progress on this?

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208

**Comment by rezam90** [comment]
Hi, Any plan to support Gitea?
