### ISSUE TITLE
support case insensitive labels in Waffle.io

### ISSUE THREAD

**Issue by kmanzana** [waffleio/waffle.io#1037]
For example, if someone has their column in Waffle.io configured to use the label `in progress`, it should still pull in issues with labels of `In Progress`

**Comment by ashumz** [comment]
[+1](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/679257857)

**Comment by ashumz** [comment]
[+1](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/720543691)

**Comment by ashumz** [comment]
[+1](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/724594093)

**Comment by ashumz** [comment]
Our new column interface helps with the issues that resulted from this
