### ISSUE TITLE
Filter by label - ability to exclude cards by label (ie: filter out all cards with label: duplicate)

### ISSUE THREAD

**Issue by danlshields** [waffleio/waffle.io#1045]
connects #3651

**Comment by lukeberry99** [comment]
+1, in need of this

**Comment by trapridge** [comment]
+1

**Comment by mcfa77y** [comment]
+1

**Comment by wdoug** [comment]
+1

**Comment by mstaplet** [comment]
+1

**Comment by emkman** [comment]
huge +1 here. For some context: I have Crashlytics create issues automatically every time we have an app crash and I want to be able to exclude these until they have been properly evaluated and labeled/organized.

**Comment by sgredell** [comment]
+1 We would like to have this ability in Waffle Takeout as well.

**Comment by courte** [comment]
+1

**Comment by warmwind** [comment]
+1

**Comment by jkruse14** [comment]
+1

**Comment by simeondrage** [comment]
+1

**Comment by ekeren** [comment]
For me it would be fine even if you don't supply a UI for this, just a query param that I can add: (like -label statement ) 
How to see all bugs (already supported)    :  https://waffle.io/rollout/rollout?label=bug
How to see all none bugs tickets(missing) :  https://waffle.io/rollout/rollout?-label=bug

**Comment by tylerjustinfisher** [comment]
+1 to what ekeren said above -- just a simple labels:not:LABELNAME would be great

**Comment by jblindberg** [comment]
+1

**Comment by tamram** [comment]
+1

**Comment by kellihsf** [comment]
Hi all, 👋 

You are now able to filter by NOT a certain label in Waffle. Check out the gif below to see how it works or try it out on your own board!

For the +1s on this issue, do you prefer to type in the "not label name" in the filter (not currently supported) or is this enough to get by? 

![exclude_label_filters 1](https://user-images.githubusercontent.com/4775572/45449570-c916df80-b692-11e8-837f-184110c1ed25.gif)
