### ISSUE TITLE
Increase number of cards per page.

### ISSUE THREAD

**Issue by willwarren** [waffleio/waffle.io#1055]
At the moment, on my laptop, I can see 3 cards per column.  I would like to have a view of the cards where you just the issue number and title.

This way you get a more complete view of the sprint which is great for the scrum stand-up meeting each morning

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
