### ISSUE TITLE
include repo name in modal view for multi-repo boards

### ISSUE THREAD

**Issue by ashumz** [waffleio/waffle.io#1056]
From a user: "for a multi repo dashboard the name of the repo should be shown in the ticket overlay."

**Comment by homeyer** [comment]
[+1](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/688505314)

**Comment by agibson22** [comment]
[+1](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/696667413)

**Comment by jewzaam** [comment]
+1

**Comment by n2diving** [comment]
+1
