### ISSUE TITLE
color cards based on type

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#1061]
https://twitter.com/jkeiser2/status/479682130981552128

**Comment by charlesccmon** [comment]
Yes, that will be really helpful. I'm trying to group the smaller issues under an Epic, there's no way to quite do that with the small tag, it's really hard to read. +1

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
