### ISSUE TITLE
Waffle in different languages

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#1064]
- [ ] german: https://app.intercom.io/apps/fb774a034de340cde33822ae0c071ad60efe899f/conversations/426288807

**Comment by kellihsf** [comment]
- [ ] Spanish: 
https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/5357313613

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
