### ISSUE TITLE
GitHub Enterprise/Takeout Delivery & Installation (Behind Firewall)

### ISSUE THREAD

**Issue by ashumz** [waffleio/waffle.io#1106]
From a potential customer: "I would like to know if there is any chance of installing waffle behind the firewall? 
GH:E is installed inside our network, and there is no way I can get security to open a port from outside."

**Comment by virtix** [comment]
+1

**Comment by kcsasquatch** [comment]
:+1:

**Comment by jrossi** [comment]
+1

**Comment by baroldgene** [comment]
I hate to be "that guy" but if you're searching for a self-hosted option that is not quite as good but similar, I came across this: https://enterprise.huboard.com/dashboard

**Comment by eenewbsauce** [comment]
test

**Comment by cmevident** [comment]
@ashumz any progress on this i see this was last summer.

**Comment by jonbrenner** [comment]
+1

**Comment by BrandonJoyce356** [comment]
+1

**Comment by kristinmc0215** [comment]
+1

**Comment by witoff** [comment]
+1.  I'd be happy to pay for an on-prem waffle behind our firewall.

**Comment by Kmaschta** [comment]
+1

**Comment by homeyer** [comment]
Everyone - Waffle Takeout, our on-premises edition, is out for delivery.

Announcement: http://blog.waffle.io/waffle-takeout-is-ready-for-delivery/

Get started: https://takeout.waffle.io
