### ISSUE TITLE
badge pull request banner should hide when declined on a per repo basis rather than "per user" via local storage - connects to #3284

### ISSUE THREAD

**Issue by ashumz** [waffleio/waffle.io#1113]
currently if you ever decline to have a badge PR for any Waffle repo, we store the decline in local storage and you will not see the banner for any repos going forward. We should do this on a per repo basis now that our architecture allows it.

**Comment by cireficc** [comment]
I have a different idea: store that info per-repo **_in the database_**. Looks like #1318 proposes that.

I almost exclusively browse in incognito mode, so local storage is wiped out when I close the window. I have to click "No thanks" every time I start working, which could happen multiple times per day...

**Comment by homeyer** [comment]
badge banner is gone!
