### ISSUE TITLE
Combine or stack issues

### ISSUE THREAD

**Issue by wvengen** [waffleio/waffle.io#1125]
Sometimes there are several issues describing aspects of a single topic. It would be great to be able to group them in waffle.io, showing them as a pile of cards and, for example, providing a tabbed view of these issues when clicking on it (reorderable).

I have a column called "Stalled" which would really benefit from this.

This would be a workaround for Github missing issue dependencies.

fixes #1996

**Comment by zbeekman** [comment]
This seems to be two separate issues:
 1. GH/waffle issue dependencies like #595 and #803 and
 1. a condensed/stacked/grouped view based on these dependencies or some other criteria

**Comment by johntmyers** [comment]
Gonna +1 this. PR's get made their own issue, and for a group that follows feature branch workflow, when a PR gets opened on a branch - you know have two issues that are shown separately, even though they are technically the same thing. The actual feature branch and the PR for that branch -- which may remain open as more work gets done on the branch prior to merging.

**Comment by ghosalmartin** [comment]
closes #2118

**Comment by kellihsf** [comment]
Waffle now supports [epics](https://help.waffle.io/epics/epic-basics) for tracking related work!
