### ISSUE TITLE
move cards based on commit messages

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#1161]

**Comment by ehausen** [comment]
+1

Blossom does this apparently, for example:
"Tried to fix this, but there is problem with alpha module, waiting for it  [blocked]"

**Comment by sfitts** [comment]
Another example of this is when you decide to address a second issue as part of an existing branch.   The branches name ties it to the initial issue and you could wait until the PR to reference the second and have it closed, but there is currently no way (that I could see) to attach it before that point.  Having the ability to reference the issue in a commit to the existing branch would solve that problem.

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
