### ISSUE TITLE
Quick toggle to filter on own tickets

### ISSUE THREAD

**Issue by CodingMammoth** [waffleio/waffle.io#1193]
A toggle at the top/left bar to filter on own tickets (assigned) would be quite powerful when working in bigger teams.

It's kind of addition of #971 but in stead of adding it to a filter, it would be nice to have a toggle: show 'all tickets' <-> 'show my tickets'

**Comment by CodingMammoth** [comment]
@kellihsf You closed the other ticket as well with 'wont fix', so this feature request isn't going to be implemented?

Waffle is a tool to check your current tickets and planning, when working with bigger teams, you really want to filter easily on your tickets. It require now a few clicks and it's quite hidden: -> Filter -> Assigned -> (wait for loading...) -> Click yourself (luckily at the top). Same process to see all tickets again.

What's the reason behind 'wont fix' ? Sounds like a small thing that improves the UX quite a lot :/

**Comment by kellihsf** [comment]
hi @CodingMammoth,

This is being closed for now  because there is a workaround for this by filtering by assignee (as you mentioned).  It just not something that's on our roadmap, but if we continue to get requests for this, we'll considering adding it back to our 'Ideas' column.  Thanks!
