### ISSUE TITLE
timeline feature for milestone progress

### ISSUE THREAD

**Issue by ashumz** [waffleio/waffle.io#1196]
[customer requested](https://app.intercom.io/apps/fb774a034de340cde33822ae0c071ad60efe899f/conversations/445092408) - Need a timeline feature (like http://timeline.knightlab.com/) to show all the milestones.

**Comment by jonbrenner** [comment]
+1

**Comment by awilkie** [comment]
Roadmap features: shows milestone blocks from Github (linear, sequential); imports a user created markdown file that has other streams of work (concurrent, overlapping  - see this for ideas -http://ramblings.mcpher.com/Home/excelquirks/recursionlink/roadmap-generation)

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
