### ISSUE TITLE
navigation keyboard shortcuts

### ISSUE THREAD

**Issue by burtonjc** [waffleio/waffle.io#1208]
- g+p focuses project dropdown
- g+s goes to current project's settings
- g+b goes to current project's board
- g+m goes to current project's metrics

**Comment by 5amfung** [comment]
In addition to @burtonjc suggestion.

```j``` to go down one card
```k``` to go up one card

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
