### ISSUE TITLE
show latest activity

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#1230]
It's hard to know what's changed since the last time you logged in.

Customer requested: https://twitter.com/DanBangWTFRajib/status/492292584833028097

**Comment by ashumz** [comment]
[+1](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/676386685)

"I think you need a better why of showing which issues have been commented on - I often miss the little alert. The issue should be highlighted in a way that shows at a glance what has been commented on. Maybe an activity feed would be best."

**Comment by elia** [comment]
+1

**Comment by ashumz** [comment]
[+1](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/1341094056)

**Comment by nvkelso** [comment]
+1

**Comment by SSDina** [comment]
+1

**Comment by alrz** [comment]
+1

**Comment by wilau2** [comment]
+1 for activity feed

**Comment by homeyer** [comment]
Since launching our slack integration we've relied on the slack channel feed to show us historic activities.

Would people still find an activity feed in waffle useful?

**Comment by pdurbin** [comment]
As I mentioned on [a mailing list](https://groups.google.com/d/msg/dataverse-dev/7BeuyP5yAsc/L3RGV136CQAJ) I've been happy enough with the Slack integration for answering the question "Who moved what card when?"

That said, sure, I'd be happy for Waffle to show activity the way Trello does in the [example](https://trello.com/b/ySoeAeCc/ui-ux) below:

![screen shot 2017-01-30 at 12 50 30 pm](https://cloud.githubusercontent.com/assets/21006/26523128/a72df332-42de-11e7-823f-492ae739a7a7.png)

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
