### ISSUE TITLE
ability to customize URI for board

### ISSUE THREAD

**Issue by ashumz** [waffleio/waffle.io#1236]
from a [user](https://app.intercom.io/apps/fb774a034de340cde33822ae0c071ad60efe899f/conversations/463646215):

"Please add ability to change URI for board or provide an override on board creation. Having it default to the primary source is OK but in some cases I would like to aggregate several repos with specific names into a more generic board. Specific example, repos:
- lightblue-docs-overview 
- lightblue-docs-user 
- lightblue-docs-developer

The default board URI is the primary source: 
- https://waffle.io/lightblue-platform/lightblue-docs-overview

Instead, it would have been nice to have a more generic name like: 
- https://waffle.io/lightblue-platform/lightblue-docs"

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
