### ISSUE TITLE
Make it possible to move an issue between states in the issue's detailed-view

### ISSUE THREAD

**Issue by pieteromvlee** [waffleio/waffle.io#1242]
When I'm working on an issue I usually have it opened up in Waffle. Once I'm done with it I always make the mistake of thinking I can drag the title of the issue and move it to the next column in our workflow.

Unfortunately that's not possible. If that's not something that can be added, it would be nice if we could make the title of the issue at least selectable with the mouse so that I can copy-paste it for my commit message.

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
