### ISSUE TITLE
send PATCH requests to GitHub, we're overwriting data right now.

### ISSUE THREAD

**Issue by marydavis** [waffleio/waffle.io#1256]
_Dependent on https://github.com/waffleio/waffle.io/issues/3081_
AC:
- [ ] all browser requests for cards to the API should be PATCH requests with only the information that was changed on a card/issue.

via [email report](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/465254010)

**Comment by homeyer** [comment]
Original report: "Moving tickets around on waffle appears to overwrite assignments made on Github. I expected it would only do that if I changed the assignment as well."

**Comment by homeyer** [comment]
[customer reported](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/675167941) - open dialog, change title in GitHub, change label in Waffle. Old title is persisted with label change from Waffle.

**Comment by JWGmeligMeyling** [comment]
:+1:

**Comment by electrical** [comment]
I found the same issue. Assigned a label to an issue, change something in waffle and the label got removed.

**Comment by ehausen** [comment]
Could not replicate.
The issue might show the old title for awhile but will update.

Can you still replicate this?
Do you have to be really fast? or?

**Comment by jankeesvw** [comment]
I also ran into this issue yesterday, this kind of data loss is pretty bad.

**Comment by burtonjc** [comment]
Refer to https://github.com/waffleio/waffle.io/issues/3079 for more details on the fix

**Comment by burtonjc** [comment]
We think this will fix https://github.com/waffleio/waffle.io/issues/2735 as well. Just need to verify that once it is out.
