### ISSUE TITLE
badge for private repos?

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#127]

**Comment by KeyboardCowboy** [comment]
This would be great for our private repo.  We have a lot of developers as well as technical stakeholders who refer to tickets on the project.  We use a 5-tier priority labeling system, and it would be great if I could add badges for each of the 5 priorities to the README to show them a birds-eye-view of what is outstanding.

**Comment by zbeekman** [comment]
+1

**Comment by jmeyer2k** [comment]
+1

**Comment by kiwiroy** [comment]
:+1:

**Comment by codekiln** [comment]
:+1:

**Comment by IanVS** [comment]
+1 for showing the number of stories

**Comment by rvion** [comment]
+1

**Comment by elia** [comment]
please! also for custom columns

**Comment by barriosnahuel** [comment]
+1

**Comment by toejough** [comment]
+1

**Comment by donatj** [comment]
:+1:

**Comment by jadengore** [comment]
:+1:

**Comment by cpostma-rally** [comment]
[+1](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/1102743212)

**Comment by naru0504** [comment]
:+1:

**Comment by liddellj** [comment]
:+1:

**Comment by BlueT** [comment]
:+1: 

didn't expect that we can't use badge for private repos.

**Comment by b52** [comment]
+1

**Comment by joramkruijer** [comment]
+1

**Comment by donny-dont** [comment]
Would be great to have this in takeout :+1:

**Comment by toshimaru** [comment]
+1 I'd like to get a badge for private-repo :smiley_cat:

**Comment by segfly** [comment]
Same here. Came here via google while trying to figure out why my repo was showing a ? for the number of issues.

**Comment by rafaelbarreto87** [comment]
+1

**Comment by kpse** [comment]
+1

**Comment by taojason** [comment]
+1

**Comment by paulpdaniels** [comment]
:+1:

**Comment by hassan-k** [comment]
👍

**Comment by timothybarraclough** [comment]
👍

**Comment by jafaeldon** [comment]
:+1:

**Comment by onejgordon** [comment]
👍

**Comment by JuanchiRios** [comment]
:+1:

**Comment by rpavez** [comment]
👍

**Comment by aureliosaraiva** [comment]
:+1:

**Comment by homeyer** [comment]
✨ Badges for private repos ✨

From your Waffle board, click the share icon on the sidebar to find the Waffle badge and follow the link to copy the code to add it to your readme.

![image](https://user-images.githubusercontent.com/84629/32379510-5662110a-c073-11e7-98b2-4ea2b876dd53.png)

more details: https://help.waffle.io/faq/github-badge/where-can-i-find-the-code-for-my-github-readme-badge
