### ISSUE TITLE
Time in column on card

### ISSUE THREAD

**Issue by James1x0** [waffleio/waffle.io#1270]
Just a feature request to:
- Have "time in column" on card
- Be able to set notifications [emails] for stale cards

**Comment by rnelson0** [comment]
Possible enhancement, optional setting to add a visual aging effect to the card when it's been 1, 2, 4, etc. weeks without modification. Transparency, a brittle effect, etc.

**Comment by mm53bar** [comment]
Love this idea. I think just a simple "number of days in this column" would be a great enhancement.

**Comment by JasonDalton** [comment]
+1

**Comment by davidBBC** [comment]
This would be amazing +1

**Comment by kellihsf** [comment]
We're tracking "cycle time" feature request on [#1574](https://waffle.io/waffleio/waffle.io/cards/5460daa0d613f614d44821b5). Closing this as a duplicate!
