### ISSUE TITLE
Color cards based on repository

### ISSUE THREAD

**Issue by soltveit** [waffleio/waffle.io#1273]

**Comment by RickMohr** [comment]
+1 would help a lot.

**Comment by ehlersd** [comment]
+1

**Comment by mrmechko** [comment]
+1

**Comment by rossjones** [comment]
Yup, this would make out backlog MUCH more manageable, otherwise it's hard to see work out which repo the issue is from.  +10

**Comment by charlesccmon** [comment]
+1

**Comment by nathanjones** [comment]
+1

**Comment by dwowens** [comment]
+10

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
