### ISSUE TITLE
add icon for fluid

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#1285]
fluidapp.com

http://webmasters.stackexchange.com/questions/23696/whats-the-fluid-icon-for

**Comment by zackkatz** [comment]
I generated an icon using http://appicontemplate.com/osx/

Let me know if you want the PSD file for this: ![waffle-fluid-icon](https://cloud.githubusercontent.com/assets/870979/12400808/86da2fb8-bddf-11e5-9b0b-b2bcfd0c35c4.png)

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
