### ISSUE TITLE
Milestone Burndown Graph

### ISSUE THREAD

**Issue by kmanzana** [waffleio/waffle.io#1297]
Add burnup chart to team metrics.

Also related to #1153.

**Comment by agibson22** [comment]
[offer to beta test](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/687983296)

**Comment by rmacasieb** [comment]
Cool!

What should I use to sign in/up?

On Wed, Jan 14, 2015 at 9:06 AM, Alex Gibson <notifications@github.com>
wrote:

> offer to beta test
> <https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/687983296>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/waffleio/waffle.io/issues/1297#issuecomment-69951063>.
>



-- 
Romy Macasieb
Product Management
Walker & Company Brands, Inc.

-- 
*We make health and beauty simple for people of color.*

<http://walkerandcompany.com>

**Comment by agibson22** [comment]
[+1](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/689517738)

**Comment by dcs619** [comment]
We just moved our sprint planning over to Waffle since you implemented story point sizes.  Great work!  We'd love to see the burndown chart too!

**Comment by agibson22** [comment]
[+1](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/696288059)

**Comment by cmitz** [comment]
+1

**Comment by wordmuncher** [comment]
+1

**Comment by abargmann** [comment]
+1 (see #1775)

**Comment by kylejaster** [comment]
+1

**Comment by jperl** [comment]
+1

**Comment by kwiens** [comment]
+1

**Comment by homeyer** [comment]
also consider showing issue burnup when not associated to a milestone (by date range?)

**Comment by gustavosotnas** [comment]
@homeyer I do not think so, because, at least in Scrum projects, the chart is labeled with the points of complexity ("Size" number on each card) on the vertical axis and the vertical axis the points that were planned to compose the sprint, starting from maximum points of sprint (speed of the team) to zero.
The chart delimiter is the duration of Sprint, which in this case would be the Milestone due date.

I do not know if that's what you are thinking of making. But the way it is done in most Scrum projects is as follows (images generated in a Scrum project management tool):

![Burndown_11.png](http://blog.myscrumhalf.com/wp-content/uploads/2012/01/Burndown_11.png)
*A burndown chart of a Sprint (can be a GitHub Milestone) without tasks (GitHub issues) completed.*

![Burndown_31.png](http://blog.myscrumhalf.com/wp-content/uploads/2012/01/Burndown_31.png)
*Chart generated during a Sprint, with some complete tasks.*

![Burndown_3_1.png](http://blog.myscrumhalf.com/wp-content/uploads/2012/01/Burndown_3_1.png)
*Chart generated after the completion of a Sprint (can be a closed GitHub Milestone) with incomplete tasks (out of planned)*

![Burndown_3_2.png](http://blog.myscrumhalf.com/wp-content/uploads/2012/01/Burndown_3_2.png)
*Chart generated after the completion of a sprint, with all completed tasks.*

I hope I've helped.

**Comment by JWGmeligMeyling** [comment]
:+1:

**Comment by tyler-ball** [comment]
:+1: and I would be happy to help test the feature if there was any current work on it!

**Comment by bennage** [comment]
:thumbsup: +1

**Comment by bslavin** [comment]
+1

**Comment by teasp00n** [comment]
+1

**Comment by nilnullzip** [comment]
+1.

Love waffle. Just right. Burndown is the one feature that I really miss.

**Comment by dpedoneze** [comment]
+1. this would be awesome! Also if we could filter by milestones too :)

**Comment by jag3773** [comment]
+1

**Comment by subsy** [comment]
Another vote here

**Comment by kofalt** [comment]
The Milestone Burnup metric is [currently listed](https://waffle.io/waffleio/waffle.io/metrics) as "Coming Soon", and it was not at all clear what that meant in practical terms. Correct me if I'm wrong, but it doesn't sound like there is any development in progress.

It would be nice if that icon linked to this ticket, to be transparent about its current status. 
As it was, I had to search around to figure out what was up :)

**Comment by davidbenhaim** [comment]
:+1:

**Comment by speete** [comment]
:+1:

**Comment by jeffmcneill** [comment]
So, how about remove the "Milestone Burnup" from the Metrics dashboard if it is indeed not "coming soon"? That would be more honest.

**Comment by gustavosotnas** [comment]
@jeffmcneill I agree with you :+1:

**Comment by jeffmcneill** [comment]
I've moved to the quite amazing http://zenhub.io/ which actually has burndown charts, and everything else Waffle has, plus its inside of Github.

**Comment by homeyer** [comment]
Quick update - we removed the interstitial metrics page that advertises the milestone burnup chart. This doesn't change our plans to eventually ship it, but we don't want to continue misleading customers with the "coming soon" message.

**Comment by marksalpeter** [comment]
+1

**Comment by arbitrarily** [comment]
+1

**Comment by frederickuzel** [comment]
+1

**Comment by ashumz** [comment]
Hi all, 

Quick update to let you know that we have started work again on this feature. When we get a bit further along, we'll either reach out here for early beta feedback or include some mocks of what you can expect once we've got things wired up. 

Thanks for your patience! Our small team has been working hard over the last few months and we're excited to have started work on delivering this for you all. 

Ashley

**Comment by gustavosotnas** [comment]
:smiley:  :+1:

**Comment by tjhanley** [comment]
![frabz-yay-someone-loves-me-1091db](https://cloud.githubusercontent.com/assets/15386/12572253/9b1b6eb4-c39e-11e5-90d9-88cf79e6beb3.jpg)

**Comment by mcqueary** [comment]
+1,000,000,000

**Comment by jkshepperson** [comment]
+1 :)

**Comment by franz-josef-kaiser** [comment]
For everybody [who wants progress](https://github.com/waffleio/waffle.io/milestones/F11102:%20Metrics).

**Comment by bilby91** [comment]
+1

**Comment by gavinr** [comment]
@ashumz any schedule update on this? thanks for everything you guys do providing this tool!

**Comment by ruchim** [comment]
+1

**Comment by oferh** [comment]
+1

**Comment by stewartwebb** [comment]
👍

**Comment by nhuray** [comment]
@ashumz Any news for this feature ?

**Comment by homeyer** [comment]
Sneak peak! 
![image](https://cloud.githubusercontent.com/assets/84629/20165642/5a9f70d0-a6cc-11e6-8de1-dec152adc2cd.png)

Launching soon 🚀

**Comment by desktophero** [comment]
Any thoughts on when this feature would be included in Takeout? (I get shipping it with Waffle.io first, etc.) - curious as I have some folks looking for this type of feature.

**Comment by songawee** [comment]
Hey all, we've released a burndown graph as part of WaffleMetrics - http://blog.waffle.io/wafflemetrics/. Thank you for all for your continued support!

p.s. @desktophero we're actively working on getting the new graphs available in Takeout - stay tuned :)

**Comment by gustavosotnas** [comment]
Better late than never. Good work guys @waffleio :clap: :clap: :clap:

**Comment by songawee** [comment]
Hey @desktophero! We just released metrics for Takeout that includes Throughput and Burndown graphs. Let us know if you have any other questions or comments.

Thanks!
