### ISSUE TITLE
show charts with estimates - starting with throughput graph

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#1319]
If an issue has a label that's a number, treat it as an estimate.

The throughput and burnup charts should respect the estimate.

**Comment by thompaul** [comment]
The benefit of estimating and assigning size to an issue lies in the ability to ascertain velocity. We really need the throughput graph to be based on sum of size rather than number issues to manage our projects. I don't see how size is of any value otherwise.

**Comment by fifigyuri** [comment]
+1 summing the points up in the throughput would make the point really useful, now we do not have the proper tool for tracking.

**Comment by iamhabitat** [comment]
+1 for this too.

**Comment by stepthom** [comment]
+1 for this.

**Comment by ashumz** [comment]
Our throughput graph now has the ability to toggle on throughput by size/points in addition to just the number of issues. You can also exclude labels from the count now (like "duplicate" or "wontfix") 

Let us know if you have questions! 

Ashley
