### ISSUE TITLE
add ability to upgrade to private permissions via home page and only show repos on the dashboard that are accessible with your current scope (see also app #1051)

### ISSUE THREAD

**Issue by marydavis** [waffleio/waffle.io#1328]
add text when searching for repo: "Can't find the repo your looking for? It may be a private repo, click here to authorize"

**Comment by ashumz** [comment]
[+1](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/760575470)

**Comment by ashumz** [comment]
@homeyer can we move on this prior to having an account page? 

- [ ] If logged in with public permissions, should only see public boards for which you are a team member on your dashboard
- [ ] Give visibility to user that they are logged in with public repo scope only with ability to click button/link to upgrade to private permissions 
-[ ] Add language to the Add Board view -- after 'don't see your org repos?' around 'You're logged in with public permissions. Click here to see your private repositories also." (or some variation, to be defined) 

This work will become more important when we add the ability to "Sign Up" from public boards. We'll automatically request public permissions for people and should give them visibility into their permissions levels if/when they first visit the dashboard. 

Adding this to the social share milestone as follow up work.

**Comment by homeyer** [comment]
:+1:

**Comment by marydavis** [comment]
yay!

**Comment by ashumz** [comment]
More on this to be broken off into another card/defined better 


- [ ] If logged in with public permissions, should only see public boards for which you are a team member on your dashboard
- [ ] Give visibility to user that they are logged in with public repo scope only with ability to click button/link to upgrade to private permissions

**Comment by ashumz** [comment]
one way we can show permissions on dashboard -- default view would still be "all" -- we should add the octicons for showing if a repo is private or public also. (to the project picker too, if possible) 

this way you could filter by public or private, and private would stay greyed out if you're logged in with public scope only. If you click "public" tab, we ask for upgraded permissions (straight to oauth upgrade screen) and redirect back to the dashboard after authorizing.

**Comment by ashumz** [comment]
![waffle-permissionsvisibility1](https://cloud.githubusercontent.com/assets/100216/9313625/eab4292e-44f1-11e5-8424-2a9f680574f4.png) 

This would be a good start in showing if a project is public or private -- might help cue the user to know that if nothing happens, they're probably not logged in with the proper permissions (eventually we need to just ask for those permissions when you click on the project if it's one you've Waffled in the past.)
