### ISSUE TITLE
fix card title area height when 150% zoom - cuts off text

### ISSUE THREAD

**Issue by marydavis** [waffleio/waffle.io#1331]
via [email request](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/483871722) 
Forced to use zoom to keep text readable on HiDPI laptop (Chrome on non-OS X platforms doesn't support it natively like it does on Retina)

**Comment by ritch** [comment]
This is a really frustrating bug...

![screen shot 2015-02-19 at 10 28 44 am](https://cloud.githubusercontent.com/assets/462228/6273248/99885c16-b822-11e4-83b2-16c910eca4c7.png)

It looks like you are calculating the `element.style.height` and in my browser (Chrome) its about 10px short (eg. 55px should be 65px)...

**Comment by ritch** [comment]
^^^ I'm on a retina display if that matters...

**Comment by ritch** [comment]
ping @marydavis

**Comment by marydavis** [comment]
thanks @ritch for letting us know, it seems to now also be a bug in Chrome on OS X though FireFox does not seem to have this problem. This will at least make it easier for us to troubleshoot and fix.

**Comment by ritch** [comment]
@marydavis 

More info on this... Here are some detailed repro steps:

 - open a waffle board in a zoomed state (chrome remembers your zoom settings)
 - initially the titles are cutoff (see screenshot above)
 - set zoom to 0 (command + 0 on mac)
 - refresh
 - titles look fine
 - zoom in
 - titles still look fine
 - refresh (once zoomed in)
 - titles appear cutoff

**Comment by lizconlan** [comment]
not sure whether this is the same thing but I get a similar problem - Safari, 11" MacBook Air - when I zoom out far enough to see all the columns at once, the card title appears (roughly) half height, cutting off the issue number

**Comment by homeyer** [comment]
unable to reproduce :)

**Comment by whitequark** [comment]
confirmed fixed (whether in chrome or waffle.io I do not know)
