### ISSUE TITLE
To view a recently added column a refresh is required

### ISSUE THREAD

**Issue by linduxed** [waffleio/waffle.io#1344]
I recently found myself in a situation where I added a new column to one of our projects, but since my colleague rarely refreshes his waffle.io-tab in his browser, he didn't notice and kept putting issues in the  recently-made-wrong column.

While it's only a refresh away from being fixed on his end, it would be good if it wasn't necessary.

I believe column name changes also aren't apparent without a refresh.

**Comment by kellihsf** [comment]
this has been resolved :)
