### ISSUE TITLE
Add last modified time on card view

### ISSUE THREAD

**Issue by flavioribeiro** [waffleio/waffle.io#1361]
I saw on [Github Issues API](https://developer.github.com/v3/issues/#get-a-single-issue) that is possible to get `updated_at` parameter from a given issue. It would be great to have the last modified time on cards view so we can have a notion of when it was opened, closed or moved between columns.

**Comment by andreackinney** [comment]
I would like a date indicating when the issue was created

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
