### ISSUE TITLE
optionally hide or filter pull requests from Waffle board

### ISSUE THREAD

**Issue by ashumz** [waffleio/waffle.io#1368]
We have had requests to be able to hide pull requests, since they are visualized as individual issues and are sometimes distracting, from users' Waffle boards.

 I think this would be best as a per user setting rather than per repo-- ideally just a filter option -- since it may be unique on a per user basis if it is distracting or not to have PR's visualized on the board.

- [ ] use the PR toggle from the throughput graph filter UI
- [ ] still show PRs if they're associated to an issue

**Comment by agibson22** [comment]
[+1](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/689666564)

**Comment by ashumz** [comment]
[+1](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/all/conversations/724420023)

**Comment by ashumz** [comment]
[+1](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/search/conversations/755798777?q=filtered)

**Comment by daniel-garcia** [comment]
+1

**Comment by kwiens** [comment]
+1

**Comment by unchris** [comment]
:+1:
