### ISSUE TITLE
IRC integration

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#1380]
customer requested in [intercom](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/andrew@waffle.io/conversations/486411670)

Ability to nag a channel in IRC, based on time in column. "nag all on freenode #channel if issue in column X has been inactive for more than 2 days".

Ideally, we expose webhooks for card events, and enhance it for optional things like "time in column". Would be straight forward to have an IRC service to consume those hooks and do the right things.

**Comment by mlyle** [comment]
+1

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208

**Comment by mlyle** [comment]
Lame
