### ISSUE TITLE
Waffle.io should remember GH:E credentials for adding additional remote repos

### ISSUE THREAD

**Issue by flimzy** [waffleio/waffle.io#1412]
I have successfully authenticated waffle.io with our GH:E installation, and added one (of many!) of our GH:E repos to the waffle.io board.  However, when I went back to add another remote repo, I had to go through the entire OAuth process again.  Considering we have two dozen or more remote repos that we want to track on the same waffle board, that's quite a lot of extra work.

It would be nice if GH:E integration credentials would be remembered for future use.

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
