### ISSUE TITLE
configure columns to not remove label on close

### ISSUE THREAD

**Issue by kmanzana** [waffleio/waffle.io#1415]
from [intercom](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/conversation/516905968)

**Comment by thedrow** [comment]
I have a problem with this feature too. I created a flow where issues are categorized according to their columns (Bugs, Feature requests etc.) so that the developers can see what's going on more easily. However I don't want to remove the bug/feature label once I move it to another column.

**Comment by kellihsf** [comment]
We haven't seen much activity on this card from the rest of the Waffle user base. We are closing it for now as we prioritize and work on other more highly requested features/integrations.
