### ISSUE TITLE
delete card

### ISSUE THREAD

**Issue by MasseGuillaume** [waffleio/waffle.io#1433]
I cannot delete a card

**Comment by codingmeow** [comment]
Can you implement a feature that hides a card so it is out of view? the board can become very messy if we are not able to hide cards.

**Comment by ashumz** [comment]
Hi @codingmeow, 

Are you using filtered views for your board? This might help reduce the noise if you have specific assignees you want to filter by, or labels you want to see (or not see.) Can you explain a bit more about your use case so we can consider how to solve your problem further? 

Thanks! :) 

Ashley

**Comment by kggp1995** [comment]
Hi @burtonjc , GitHub now offers deletion of GitHub issues on a beta basis. 

However, I just tried deleting the issue directly from GitHub & seems like Waffle is not syncing upwards from GitHub sources.

Would love to have this syncing feature in Waffle, to reflect the counts on epics 😅 .
Is there some WIP on this? Happy to help reproduce this scenario.

**Comment by BAMason** [comment]
@kggp1995 we've been waiting for support from GH to enable us to handle this.  It looks like (as of today) we now receive webhooks when an issue is deleted, so we've begun the work to implement a handler for this use-case with waffleio/waffle.io#3710

Stay tuned!
