### ISSUE TITLE
be able to import existing open pull requests to "Needs Review" or column of choice during PR collab/non collab set up

### ISSUE THREAD

**Issue by ashumz** [waffleio/waffle.io#1441]
For those getting set up with Waffle and have open pull requests already, all of which they want to be auto-tagged with their new convention post-Waffle set up:

"We have a lot of current PRs open, and they don't show up. All _new_ PRs will show up in the Review column, but we are having to manually go through all our repos to add tags to current PRs to get them into review. That's kind of arduous. Can you add a "and all current open PRs" option, please."

**Comment by kellihsf** [comment]
We haven't seen much activity on this card since it was opened from the rest of the Waffle user base. We are closing it for now as we prioritize and work on other more highly requested features/integrations.
