### ISSUE TITLE
gitter.im integration

### ISSUE THREAD

**Issue by ashumz** [waffleio/waffle.io#1454]
[customer request](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/532009354)

**Comment by Bortseb** [comment]
+1 
I would like this too! I have to admit, I was a little dissapointed not to find the Waffle.io button after I saw the HuBoard one...
![2015-02-10 09_53_51- metamaps_metamaps_gen002 - gitter](https://cloud.githubusercontent.com/assets/1617130/6129250/de6af150-b10a-11e4-8757-e273a20d9705.png)

@homeyer , does the above answer mean that I can make this integration happen myself if I really want to?

Some related issues:

Waffle.io + Gitter integration has been proposed before here on Gitter's GitHub:
https://github.com/gitterHQ/gitter/issues/212

They then point to this issue of yours:
#809 
Which seems to have implications for other integrations too:
#806

**Comment by mavam** [comment]
:+1:

**Comment by ashumz** [comment]
[+1](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/806520573)

**Comment by ThePenguin1140** [comment]
:+1:

**Comment by yurinnick** [comment]
+1

**Comment by jdickey** [comment]
:+1: as well.

I'm taking a couple of days to look at tools in this general area for our startup; early leaders seem to be HuBoard and ZenDesk. HuBoard, for example, offers Gitter (and Slack) integration, a generic "outgoing webhook" integration, and a general-purpose API "coming soon". I'm disappointed that Waffle.io, despite some excellent word-of-mouth from happy users is, apart from Github integration, an island apparently designed to upsell Rally services.

Good luck with that.

**Comment by cpostma-rally** [comment]
[+1](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/949063343)

**Comment by cpostma-rally** [comment]
{+1} (https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/965443468)

**Comment by cpostma-rally** [comment]
[+1](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/993243366)

**Comment by Bortseb** [comment]
+1

**Comment by Sesselja** [comment]
+1

**Comment by mauriciomelo** [comment]
+1

**Comment by antonmry** [comment]
+1

**Comment by dmehra** [comment]
:+1:

**Comment by forivall** [comment]
:+1:

**Comment by laughedelic** [comment]
+1

**Comment by Gudui** [comment]
+1

**Comment by faceyspacey** [comment]
+1 this makes little sense as gitter is a more complimentary product to waffle than slack

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
