### ISSUE TITLE
Ability to save filters/have default filters

### ISSUE THREAD

**Issue by ashumz** [waffleio/waffle.io#1458]
[Requested by a customer](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/529788837):
"I find myself wanting to switch between a few sets of filters (e.g. me + unassigned + milestones). Short of bookmarking them (which triggers a reload) could these be saved? Perhaps I'm missing something in the interface."

**Comment by ashumz** [comment]
[+1](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/701205438)

"In addition to my organization's issues, can I see all of the issues assigned to myself? Saved filters with a URL [that are easily accessible via the UI] would be perfect"

**Comment by lieldulev** [comment]
+1

**Comment by Ryanb58** [comment]
+1 

I think this would be very valuable to teams that have multiple projects going on at the same time. 

i.e A Project manager wants the view to default to a specific milestone that they are working on.

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208

**Comment by formspoint** [comment]
+1

**Comment by TJClifton90** [comment]
+1

**Comment by sevurutetration** [comment]
+1
