### ISSUE TITLE
open links in a new tab

### ISSUE THREAD

**Issue by agibson22** [waffleio/waffle.io#1466]
https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/537236809

**Comment by agibson22** [comment]
[+1](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/687873421)

**Comment by atz** [comment]
+1, see also #1722

**Comment by wjblair235** [comment]
[+1](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/conversation/955922982)

**Comment by chrisbeaman** [comment]
+1

**Comment by richgiomundo** [comment]
+1

**Comment by homeyer** [comment]
Shipped! :rocket:
