### ISSUE TITLE
related to #1279 - if add a new column label via Github.com, remove previous column labels

### ISSUE THREAD

**Issue by ashumz** [waffleio/waffle.io#1475]
based on conversation with @homeyer, we already do this for PR's we move to In Progress -- need to add this for label changes that happen within GitHub. 

Use case is a team of developers who work primarily in GitHub and add on additional workflow of adding labels to represent the state of an issue, while the PM views/organizes work within Waffle.

[From a user](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/539334271): 
"If a GitHub issue has multiple labels assigned to it that correspond to different columns, duplicates of that issue appear. For example, if there is an issue with GitHub 'ready' status, and a developer adds the label 'in progress', Waffle shows the same issue in the Ready column and the In Progress column.

It would seem that waffle should filter the GitHub labels that correspond to rows, choosing the on that is furthest down the chain (i.e. to the right)."

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
