### ISSUE TITLE
make it easier to invite collaborators to your project by providing simple invite url

### ISSUE THREAD

**Issue by ashumz** [waffleio/waffle.io#1488]
New users are consistently unsure of how to invite people to their Waffle board. Many don't understand that once a collaborator "Waffles" a board and customizes it, every collaborator will share that same view of the board. 

In the short term, until we can improve our overall invite flow, we can add somewhere in the app where you can invite people to your board using the board URL.

**Comment by marydavis** [comment]
share button in the sidebar was added
