### ISSUE TITLE
open source spotlight: adobe/brackets

### ISSUE THREAD

**Issue by ashumz** [waffleio/waffle.io#1515]
https://docs.google.com/a/rallydev.com/document/d/1_k775hn6UahYBOLtyNsUqAs09lejwZg6C9A7H9tba4I/edit

**Comment by pthiess** [comment]
@ashumz: Happy 2015 to you at Waffle! I saw this was removed from your backlog. I was still hoping that you'd write about the Brackets team and our motivation to use Waffle. If there is anything I could provide you with please let me know! Cheers, Peter :)

**Comment by ashumz** [comment]
Hi @pthiess --

Sorry about the delay! I had messaged you via our in app messenger 2 months ago and hadn't heard back, so wasn't sure if this was still approved or not? Can you check your messages in Waffle or email me directly at ashley@waffle.io and we'll get everything squared away? We very much are excited to feature you guys on our blog! 

Sincerely, 

Ashley

**Comment by pthiess** [comment]
@ashumz Cool - I'll touch base with you at ashley@waffle.io.

Cheers,
Peter :)
