### ISSUE TITLE
Change font color to #fff on orange label (#eb6420)

### ISSUE THREAD

**Issue by agibson22** [waffleio/waffle.io#1519]
[conversation](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/558269699)

**Comment by subhog** [comment]
I've requested the same problem a few days ago.

Could you please refresh the link to your color algorithm? I'd gladly give improving it a try.

**Comment by adambuczynski** [comment]
+1 for this issue, as there are currently inconsistencies with Github:

Github:
![image](https://cloud.githubusercontent.com/assets/490562/12863855/e7767dac-cce1-11e5-831a-e3b224ccad70.png)

Waffle:
![image](https://cloud.githubusercontent.com/assets/490562/12863857/f42e9b42-cce1-11e5-8e54-1eebfd27f660.png)

This is illegible for me.

**Comment by lee-40square** [comment]
This is also present on other colours as well. Can we not use the same algorithm that Github uses?

Also, the link to the algorithm is broken.

**Comment by marydavis** [comment]
Just released the fix for this, the orange labels should now have white text on the Waffle board :)
