### ISSUE TITLE
Ability to "embed" Waffle within another site, much like Youtube

### ISSUE THREAD

**Issue by agibson22** [waffleio/waffle.io#1520]
[conversation](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/alex@waffle.io/conversations/556227338)

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
