### ISSUE TITLE
Add column name to card detail modal

### ISSUE THREAD

**Issue by agibson22** [waffleio/waffle.io#1522]
AG-requested - it's mildly annoying sometimes to open the modal and not have direct visibility into the column.

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
