### ISSUE TITLE
Visual indicators on cards on board view for description

### ISSUE THREAD

**Issue by agibson22** [waffleio/waffle.io#1525]
[conversation](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/560957007)

**Comment by ashumz** [comment]
From @pauldiepenbrock (#1815 closed as duplicate):
"I've noticed that members on my team won't open issues to check for a description if this number is blank. This is a bit annoying since the description is just as important (if not more so) than any additional comments."
