### ISSUE TITLE
Add organisation page

### ISSUE THREAD

**Issue by 21xhipster** [waffleio/waffle.io#1527]

**Comment by jesstelford** [comment]
+1

**Comment by homeyer** [comment]
🎉 Org pages in Waffle are now available! 🎉 
Right now we show you all the projects under that organization that you have permissions to see.

Kudos to @marydavis for leading the charge on this feature! 🚀 

![image](https://cloud.githubusercontent.com/assets/84629/17875672/2428af04-6891-11e6-9718-9313a47dae13.png)

Interest in a board that pulls in all of an organizations repositories lives here: https://github.com/waffleio/waffle.io/issues/1814.
