### ISSUE TITLE
look at forks for auto-move events

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#1533]
When we "waffle" a repo, and when a new user joins a waffle project, look to see if any forks exist for the any of the repos for that user.

If any exist, create a webhook on the fork (but don't create a waffle project!). Listen for branch creates, and any future events like that (branch push, look at commits, etc).

Ideally we tell the user what's happening when they join a project, part of Project On Boarding work. 

Also, if we can detect when a fork is viewed from Waffle, we should tell the user if the upstream is Waffled or not, before we let them create the project. I'm guessing that in most cases a fork shouldn't be waffled, unless it's a fork that's intended to replace the upstream. (see also #1899)

**Comment by fbrbovic** [comment]
Any updates on this feature ?

**Comment by homeyer** [comment]
@fbrbovic, nope. We're focused on improving the core features around auto moving work, not quite ready to pull more situations like this.

**Comment by daniellawman** [comment]
Anything new on this?

**Comment by niemela** [comment]
+1 This would make a huge difference for us as well.

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
