### ISSUE TITLE
Bulk archive issues

### ISSUE THREAD

**Issue by agibson22** [waffleio/waffle.io#1535]
**Acceptance Criteria**
- [ ] Add an "archive all"button  to the Done column
- [ ] update wiki FAQ

**Comment by algard** [comment]
+1 this would work perfectly for our use case.

**Comment by homeyer** [comment]
[+1](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/682815402)

**Comment by jamesmartinduffy** [comment]
+1

**Comment by subsetpark** [comment]
+1

**Comment by teoruiz** [comment]
+1 pretty please with sugar on top.

**Comment by JordanRL** [comment]
+1

**Comment by webninja3** [comment]
+1

**Comment by Ashwell** [comment]
Right now our team uses github milestones for scheduling sprints, would it be possible to auto archive issues when the milestone is closed?

also +1

**Comment by maurizi** [comment]
+1

**Comment by felixkiss** [comment]
+1

**Comment by kdeloach** [comment]
+1

**Comment by sap1ens** [comment]
+1

**Comment by ashumz** [comment]
[+1](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/856748064)

**Comment by bonds** [comment]
+1

**Comment by JeremybellEU** [comment]
+1

**Comment by adamralph** [comment]
Yes, please. We've just added a few repos to a Waffle board and now there are *hundreds* of closed issues in the "Done" column which we need to archive. Without an "Archive all" this is not an exercise any of us are prepared to risk our mental health for.

**Comment by kennygoff** [comment]
+1 Would be a huge help cleaning up old repos that have a large issue history, that have been recently added to Waffle. If this could work with filters, like clearing all done from a specific milestone, that would be even better and help in the long run for sprints.

**Comment by hjiang** [comment]
+1

**Comment by RickMohr** [comment]
+1

**Comment by cdmckay** [comment]
+1

**Comment by MFDW** [comment]
+1

**Comment by iro-d-ori** [comment]
+1

**Comment by starast** [comment]
+1

**Comment by adamralph** [comment]
Has this feature been added?

**Comment by homeyer** [comment]
Yep! Click the box icon in your done column to archive all closed issues.

![image](https://cloud.githubusercontent.com/assets/84629/13681846/7a45c856-e6bc-11e5-9c8f-f879589b1a23.png)

**Comment by adamralph** [comment]
Fantastic, thanks!

**Comment by adamralph** [comment]
This feature has a major bug. (You could argue that it's not a bug, but it's certainly very dangerous and leads quickly to the pit of failure.)

When the board is filtered, clicking the button archives *all* issues, not just the filtered ones. This is has just bitten me on a board which aggregates ~50 repos and now I have no way to restore the view of recently closed issues. This is a major fail.

**Comment by adamralph** [comment]
There is another minor bug - pull requests are not archived when the button is clicked.

**Comment by marydavis** [comment]
@adamralph - ugh, so sorry about that - just now pushing up a fix to hide the button when filtered until we can get the functionality added to only archive filtered cards so no one runs into this in the meantime. i'll also look into the PR's not archiving, they definitely should be.

**Comment by adamralph** [comment]
@marydavis thanks, that's a good interim solution to avoid the problem.

**Comment by marydavis** [comment]
@adamralph that temp fix is now live - although i'm having trouble reproducing the issue you mentioned about the PR's not archiving. Is it all PR's or is there a particular difference between those that do and don't?

**Comment by adamralph** [comment]
@marydavis I can't see any common theme in the PR's. Unfortunately I'm also not sure if it's just some PR's or all PR's that didn't get archived, since I don't know how many there were to start with.

If you want to inspect production, it's this board - https://waffle.io/Particular/PlatformDevelopment

**Comment by marydavis** [comment]
@adamralph ok thanks, i'll see what i can figure out. let me know if you notice anything particular in the future - sorry again we had a rough start, i have really appreciated all of your feedback :)

**Comment by kdeloach** [comment]
Great feature. Thanks!

**Comment by krodyrobi** [comment]
+1
