### ISSUE TITLE
Request: Easy link back to github repo.

### ISSUE THREAD

**Issue by pjf** [waffleio/waffle.io#1537]
Waffle has rapidly become my main view of the [CKAN issues board](https://waffle.io/ksp-ckan/ckan), but it's missing one important thing¹... a link back to the [github repo itself](https://github.com/KSP-CKAN/CKAN). This could be something as simple as an octocat, or even a text link, but it's something I find myself reaching for *all the time*.

Many thanks for a great product! Waffle *totally* rocks.

Apologies if this is a duplicate request.

---

¹ Or I've totally missed the link, that happens too.

**Comment by trayo** [comment]
:+1:

**Comment by mbulkeley** [comment]
+1

**Comment by Swizz540** [comment]
I don't understand why to add a link to the repo's main page is so difficult.

Lot of users requests ask this since more than one year.
But it would take less of five minutes to be done.


*nb : I don't want to be rude. Sorry for my bad english.*

**Comment by ashumz** [comment]
Hi all, 

This is now live in the sidebar of your project. :) 

Ashley

**Comment by pjf** [comment]
Thank you! :)
