### ISSUE TITLE
Make "assigned" filter not case sensitive

### ISSUE THREAD

**Issue by agibson22** [waffleio/waffle.io#1551]
[conversation](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/578978908)

**Comment by McKayDavis** [comment]
+1 on this.  Github usernames are not case sensitive. I'm generating waffle.io URI's based on a source that is all lower-case.  My username, for example, does not work.
