### ISSUE TITLE
add issue with labels

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#1553]
- [ ] try to reuse the label picker from the detail view
- [x] don't show column labels, use a different picker for choosing column (separate picker)
- [x] don't persist in local storage

**Comment by caramev** [comment]
+1 and additional +1 for the default labels to be the ones in the current filter.

**Comment by AntoineInsa** [comment]
+1

**Comment by ashumz** [comment]
also requested by @pardom in #1736 (closed as duplicate)

**Comment by cweber** [comment]
+1

**Comment by heyitsolivia** [comment]
+1

**Comment by ashumz** [comment]
[+1](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/723289882)

**Comment by HoracioChavez** [comment]
+1

**Comment by mohierf** [comment]
+1

**Comment by fallenby** [comment]
+1

**Comment by tomwm** [comment]
+1
