### ISSUE TITLE
add issue with assignee

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#1554]
- [ ] ~~persist selection in local storage~~ not going to persist but will stay until refresh

consider ability to "Assign to me" during issue creation for when users are filtered by "Issues assigned to me" and want to add issues and assign them to themselves, without having to unfilter and reassign [internal thread](https://www.flowdock.com/app/rally-software/rudder/threads/MWOUsJq3EkDy8mKj1IlUP-TNtZU)

**Comment by ashumz** [comment]
requested by user in #1719 (closed as dup)

**Comment by cweber** [comment]
+1

**Comment by heyitsolivia** [comment]
+1

**Comment by shawnohare** [comment]
+1

**Comment by ashumz** [comment]
+1 from @superkhau on #1741 (closed as duplicate)

**Comment by stacy-hunt** [comment]
+1

**Comment by sethlivingston** [comment]
+1

**Comment by sbruschi** [comment]
+1

**Comment by ashumz** [comment]
[+1 - internal Flowdock convo](https://www.flowdock.com/app/rally-software/rudder/messages/2503224)

**Comment by anthonyettinger** [comment]
+1 -- it would be nice to be able to assign to anyone when creating a ticket.

**Comment by cpostma-rally** [comment]
[+1](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/981654029)

**Comment by riccardomessineo** [comment]
+1

**Comment by jdegger** [comment]
+1

**Comment by daguar** [comment]
+1! It really fits with what I think is a natural sprint plan flow:

1. Filter for each teammate
2. Go through all closed issues from prior week and start moving over backlogged issues
3. Add new issues

The (3) there is where the experience is not great right now — in this process, if we're adding a task for someone's sprint with ONLY their issues showing, adding an issue goes to ghostland where we need to unfilter first to assign.

**Comment by shaharmor** [comment]
+1

**Comment by marydavis** [comment]
Hey all, we just released the ability to assign an issue upon creation - just need to refresh to see it :) Enjoy!

**Comment by daguar** [comment]
Thank you! @lippytak is stoked.

**Comment by anthonyettinger** [comment]
@marydavis excellent. I was just explaining to someone yesterday how "its really annoying you couldn't....oh wait they fixed it!"

**Comment by lippytak** [comment]
woohoo
