### ISSUE TITLE
Ability to click the card number in the notification banner

### ISSUE THREAD

**Issue by agibson22** [waffleio/waffle.io#1558]
[conversation](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/582394050)

To define this a bit more, when you click on the banner, you should be directed to the modal of the card that the notification references.

**Comment by unchris** [comment]
:+1: YES!

**Comment by ashumz** [comment]
[+1](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/755311794)
