### ISSUE TITLE
Embed Waffle board in external views (via svg on README)

### ISSUE THREAD

**Issue by ashumz** [waffleio/waffle.io#1567]
We've explored the idea of dynamic Waffle boards as embeddable svg's of Waffle boards for GitHub README's. We need to define what that would entail in order to estimate and prioritize @homeyer 

Related customer requests:
- [Customer wanting to see their board in GitHub](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/1725912533)
- [Customer Request for Waffle in an Iframe](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/585409165) ("We'd love to embed waffle into our documentation so that each user can see what issues they've been assigned. Our long term goal is to have each user sign into our community portal and see all of their issues.")

(Note: we do not plan to go the route of embedding an iframe style view, but the embeddable svg image is something we're considering.)

[Flowdock internal conversation](https://www.flowdock.com/app/rally-software/rudder/messages/1677787)

**Comment by ghosalmartin** [comment]
Effectively its just not having to go  somewhere else, if its all integrated together it would make work flow easier.

**Comment by homeyer** [comment]
[customer convo](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/1809253340)

**Comment by pixelchef** [comment]
Wish this existed for private repos.

**Comment by kellihsf** [comment]
+1 for embedding on company website to show a realtime view of product roadmap.  [from customer convo](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/respond/inbox/unassigned/conversations/14151085667)

**Comment by AnaMSteele** [comment]
Closing this issue for now, as we haven't seen recent activity, and we are not prioritizing in our near term roadmap. Feel free to continue commenting.
