### ISSUE TITLE
Ability to filter by multiple labels (filter by AND not "either/or")

### ISSUE THREAD

**Issue by jlberryhill** [waffleio/waffle.io#1572]
Issues would have to contain all of the labels selected. e.g., selecting "blocked" and "customer requested" would bring up #846 but not #694

**Comment by ashumz** [comment]
[+1](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/696705397)

**Comment by ashumz** [comment]
[+1](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/772667144)
"for filtering labels, I would like to be able to filter for multiple labels. For example, I have a "bug" label and a "Q1'15" label...I want to see cards that are labeled with both, not either (bug AND Q1'15" on the same card)...I only want to see cards labeled with both parameters, not either."

**Comment by andreackinney** [comment]
this would be a REALLY useful feature...in fact, I am actually looking at other programs that offer this feature but I would prefer to stick with waffle

**Comment by igor-kupczynski** [comment]
Was it implemented? Based on @marydavis activity I think so, but I don't see any documentation on how to do this.

**Comment by marydavis** [comment]
@igor-kupczynski yes, we changed labels to filter by 'AND' instead of 'OR'. So if you filter your board using two labels it will only show the cards with both of those labels on them. To filter the board, click on the icon next to the search textbox in the top right corner. This will allow you to choose from many filter options, including labels :)

**Comment by igor-kupczynski** [comment]
Thanks @marydavis for the answer. Actually, I was asking about the opposite - sometimes I'd like the labels to be `OR` :) Based on the answer I think it is not possible at the moment and it is by design. I'm of course ok with that just wanted to know.

**Comment by marydavis** [comment]
Unfortunately, you are right @igor-kupczynski, it is not possible at the moment. We hope to allow the option to do either 'AND' or 'OR' in the future and have a card for it here:  [#1440](https://waffle.io/waffleio/waffle.io/cards/54208c21d613f614d446694a)
