### ISSUE TITLE
change badge color

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#1580]
quote from [customer](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/conversation/595025594): "It would be awesome if I could change the color of the "ready" badge svg. For example in the "Columns" section I could define green for the "In Progress Column" and add a badge for the column that would be green instead of the default blue."

**Comment by zbeekman** [comment]
Also, changing the style would be nice, and format consistent with badges.io would be wonderful

**Comment by metaraine** [comment]
+1

Issues is also discussed here: https://github.com/badges/shields/issues/257

**Comment by richlewis42** [comment]
+1

**Comment by arianf** [comment]
+1

**Comment by rkho** [comment]
+1

**Comment by pravipati** [comment]
:+1:

**Comment by homeyer** [comment]
If you use the Waffle badge hosted by shields.io the badge color is pulled from the GitHub label color! Details on this issue: https://github.com/waffleio/waffle.io/issues/2002#issuecomment-270798828
