### ISSUE TITLE
Select multiple repos for a project

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#1590]
[customer requested](https://twitter.com/SimonCropp/status/533357613774151680)
- [ ] check boxes for multiple sources
- [ ] done button
- [ ] add each selected source one by one
- consider adding the display name text field next to the source name so users can input display name at time of multi-add
- [ ] use on the repository settings screen (Angular in AngularJS woohoo have fun guys!), but remember that it'll be used as part of project creation too

**Comment by ashumz** [comment]
- consider adding the display name text field next to the source name so users can input display name at time of multi-add
