### ISSUE TITLE
create/measure funnel for current onboarding experience

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#1591]
create funnel in intercom to track the on boarding process:
- [ ] first visit to logged-in homepage
- [ ] do they create a project?
- [ ] do they come back?
- [ ] does anyone else join their team?
- [ ] do they create another project, or add a new source to a project?

and...

- [ ] login for the first time from a board view
- [ ] do they create an issue
- [ ] do they create any other projects?

**Comment by wsurles** [comment]
Show william s when you have it.
