### ISSUE TITLE
Integration with Circle CI

### ISSUE THREAD

**Issue by agibson22** [waffleio/waffle.io#1592]
[conversation](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/alex@waffle.io/conversations/604041211)

**Comment by vistik** [comment]
any update on this? :)

**Comment by cpostma-rally** [comment]
[+1](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/949063343)

**Comment by natsn** [comment]
+1

**Comment by kevtufc** [comment]
+1

**Comment by jesstelford** [comment]
+1

**Comment by oferh** [comment]
+1

**Comment by foloinfo** [comment]
+1

**Comment by homeyer** [comment]
Shipped!
