### ISSUE TITLE
investigate how we can be notified when duplicate stories are created

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#1596]
- [ ] splunk alerts?

**Comment by CodeMan99** [comment]
Perhaps add a new "duplicate of #" syntax? Could stack cards like is done for "Connect to #" syntax for visual notification.

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
