### ISSUE TITLE
customer reported pull request showing twice on issue

### ISSUE THREAD

**Issue by ashumz** [waffleio/waffle.io#1603]
[customer report](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/606621259)
"I made a pull request while an issue was in the In Progress lane, and then when I moved it over to the Awaiting Review lane it comes up as being associated with the same pull request twice."

**Comment by homeyer** [comment]
PR tab no longer exists.
