### ISSUE TITLE
Create Pull Request from Issue

### ISSUE THREAD

**Issue by 6twenty** [waffleio/waffle.io#1619]
Using Waffle exclusively means always creating Issues and never Pull Requests (as far as I can tell?). Sometimes these issues need to be changed to pull requests, but there's no simple way to do this. The recommended approach is via the command line using hub or curl: http://stackoverflow.com/questions/4528869/how-do-you-attach-a-new-pull-request-to-an-existing-issue-on-github. It would be awesome if Waffle featured the ability to convert an Issue into a Pull Request!

**Comment by kellihsf** [comment]
We haven't seen much activity on this card from the rest of the Waffle user base. We are closing it for now as we prioritize and work on other more highly requested features/integrations.
