### ISSUE TITLE
Order source repositories by name in Sources list for multi-repo boards

### ISSUE THREAD

**Issue by ashumz** [waffleio/waffle.io#1624]
[from a user](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/621747219): "connected sources should be ordered by their name (of course use the repo name if not renamed) "

**Comment by W3C2I** [comment]
Yes ! Good idea :-)

**Comment by marydavis** [comment]
Sources are now alphabetized in the list :)
