### ISSUE TITLE
When dragging an issue from one column to another, original column continues to scroll downward when you are hovered and scrolling down over target column

### ISSUE THREAD

**Issue by ashumz** [waffleio/waffle.io#1625]
[reported by user](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/622249666)

"Drag an item from one column to the other, then try to drag it down the list and the original column scrolls rather than the target column."

**Comment by ppoulsen** [comment]
+1

**Comment by marydavis** [comment]
@ppoulsen we recently released a new board, which we think fixed this issue - please let us know if you still are experiencing this bug, thx!
