### ISSUE TITLE
Ability for labels to be added to multiple repos at once

### ISSUE THREAD

**Issue by agibson22** [waffleio/waffle.io#1629]
[conversation](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/621111014)

**Comment by cweber** [comment]
Still useful, but did just realize that this is already a feature in github.

**Comment by lindenle** [comment]
:+1:

**Comment by marydavis** [comment]
the waffle label dropdowns contain all labels from across all attached repos. if choose a label not in current repo it will be added :)
