### ISSUE TITLE
invite team members

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#1637]
simple link for inviting team members who are collaborators

**Comment by agibson22** [comment]
[+1](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/706350793)

**Comment by agibson22** [comment]
Look at #1488 and #1012

**Comment by rajputvai** [comment]
+1

**Comment by igorsantos07** [comment]
I'm currently a collaborator on a private repository but not part of the Github team. They're using Waffle but I don't have access to their board. Is it possible to allow board access to collaborators that are not part of the organization?
