### ISSUE TITLE
recognize full urls in PRs to associate to issues

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#1640]
see https://github.com/waffleio/waffle.io/issues/1600#issuecomment-65229004

**Comment by jamesmartinduffy** [comment]
+1

**Comment by homeyer** [comment]
[+1](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/conversation/706768930)

**Comment by sam-github** [comment]
+1

**Comment by marydavis** [comment]
i believe this was fixed, please let us know if it was not :)
