### ISSUE TITLE
Ability to select multiple cards at once

### ISSUE THREAD

**Issue by agibson22** [waffleio/waffle.io#1641]
[conversation](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/626798165)

**Comment by andreackinney** [comment]
+1000000

**Comment by markemeis** [comment]
+1 I'd like to be able to select several cards and add labels.  I realize this can be done in github but I want to stay in Waffle

**Comment by erichs** [comment]
+1, would be really handy to move related cards within Waffle!

**Comment by AnaMSteele** [comment]
Please leave new comments and upvotes on this feature request at #3629 where we are tracking all bulk issue actions in one place. Thank you for helping us prioritize this work!
