### ISSUE TITLE
Create column that displays issues assigned to a single user

### ISSUE THREAD

**Issue by cweber** [waffleio/waffle.io#1643]
There would be an obvious use case for seeing your own tasks, but it would also be helpful for tracking work load for a team.

**Comment by alleyhector** [comment]
:+1:

**Comment by kellihsf** [comment]
We haven't seen any activity on this card since it was opened from the rest of the Waffle user base. We are closing it for now as we prioritize and work on other more highly requested features/integrations. Thank you! :)
