### ISSUE TITLE
Sub-Assignees on Waffle.IO

### ISSUE THREAD

**Issue by relicmelex** [waffleio/waffle.io#1651]
I know github doesn't allow for multiple assignees, but I'm sure there's a fancy way to create a list of sub-assignees (based on the github users list used for Primary Assingees) just in waffle, maybe just in a meta-data object of some kind.

**Comment by cpostma-rally** [comment]
[+1](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/970757780)

**Comment by relicmelex** [comment]
It would be nice if we could pair in waffle though. Also your suggestion can also ruin the integrity of who did what and that's part of the point of version control. Assigning a ticket to two people also may not necessarily mean that both have to work on it, and it could be quite atrocious if you're part of multiple teams to be committing as different users and things all the time. However some sort of maybe part-child relationship or sub-assignees, or multiple assignees as @cpostma-rally noted attached to a single card would be infinitely useful and unobtrusive to versioned (git) work flows. Ideas?

**Comment by marydavis** [comment]
GitHub added multiple assignees, so we did too! Enjoy :)

**Comment by relicmelex** [comment]
This is amazing, didn't see this in my Github till just now. Woooo!!! Thanks!
