### ISSUE TITLE
column scrollbars move horizontally (in front of cards) in Chrome when you scroll down and then horizontally

### ISSUE THREAD

**Issue by ashumz** [waffleio/waffle.io#1658]
[reported by user](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/443099073)

"I'm seeing in Chrome only is one related to scrolling. I am able scroll one column vertically and simultaneously scroll the whole board horizontally. This causes my vertical scroll bar to also move out of position. Not a huge deal, but just creates some usability quirks." 

I am able to consistently replicate the issue.

**Comment by ppvg** [comment]
I've noticed this as well. Scrollbar placement is offset but consistent.

Applies to chrome 41 and 42 (gif below is in 42.0.2311.135).

![scroll](https://cloud.githubusercontent.com/assets/67802/7643404/9b2468b2-fa99-11e4-88fc-a8e773a0a6c6.gif)
