### ISSUE TITLE
Hipchat integration

### ISSUE THREAD

**Issue by agibson22** [waffleio/waffle.io#1665]
[original conversation](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/642401628)

**Comment by mmazour** [comment]
Another :thumbsup: here.  Specifically I'd like a notification when an issue changes columns.  We've used GitHub integration in the past (and still have it in our "firehose" room), but it generates a lot of traffic and we haven't been able to tune it enough to use nondisruptively in our main dev room.

**Comment by kellihsf** [comment]
We haven't seen any activity on this card since it was opened from the rest of the Waffle user base. We are closing it for now as we prioritize and work on other more highly requested features/integrations.
