### ISSUE TITLE
Open PR's no longer visible

### ISSUE THREAD

**Issue by joostdevries** [waffleio/waffle.io#1671]
I cannot see any open PR's linked to issues on my board :-(

Also reported this over [Intercom](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/649903868)

Also added: "I am seeing closed PR's, just not the open ones.."

**Comment by joostdevries** [comment]
Any update on this?

**Comment by burtonjc** [comment]
Sorry about the delay @joostdevries. I was on vacation the past 2 weeks. I am actively working on this again now and it should be out early this week.

**Comment by joostdevries** [comment]
@burtonjc Right now I'm still not seeing open PR's on my board. Is this deployed already?

**Comment by burtonjc** [comment]
@joostdevries, I just sent you a message through [Intercom](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/649903868) to figure this out.
