### ISSUE TITLE
be able to make private board publicly accessible

### ISSUE THREAD

**Issue by kmanzana** [waffleio/waffle.io#1674]
request on [intercom](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/651508706)

**Comment by olyas** [comment]
:+1:

**Comment by Dids** [comment]
This would definitely nice. In my specific use-case, I'd simply want to show a public roadmap to my users, while keeping the repository private. Additionally being able to mark only some tasks as public would be a nice addition.

**Comment by kellihsf** [comment]
Closing as a duplicate of [#3352](https://waffle.io/waffleio/waffle.io/cards/5a4ec58666a373001c2e39df)
