### ISSUE TITLE
change how PRs become "connected to" issues

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#1682]
When a PR references an issue in the title or description, without using the GitHub phrases to close the issue, we should not "connect" the PR to the Issue. This is to avoid situations where you reference an issue for background, like "this PR is in response to issue #123", where the PR should be tracked independently from the issue it's referencing.

Introduce new language, "connected to", "connects to", "connect to", to do soft connections. Example use case - you have 3 PRs for a single issue, but only the last to be merged should actually close the issue. The first two should be connected to the issue and displayed together in Waffle.

full discussion in this doc: https://docs.google.com/a/rallydev.com/document/d/10jShmP6FiCcj4WQ__XRVyC1pbJOQ92Ac2a2oYFZjwzE/edit

Expected behavior:

- [ ]  If a card uses If a PR title/description uses the connected to, connects to, or connect to verbiage, the relevant issue will move to In Progress Start column and be assigned to the PR creator.
- [ ] If a PR title/description does not use the connected to, connects to, or connect to verbiage OR any of the closing keywords, the issue will stay in its current column, with nothing happening to it.

**Comment by ashumz** [comment]
don't push this until intercom message is ready :)

**Comment by ashumz** [comment]
biz-135 takes care of the FAQ portion - and I have the intercom message ready. So just send me a note to let me know when you're ready to deploy this one @burtonjc
