### ISSUE TITLE
documentation for how we automatically move work based on branches and PRs

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#1684]
wait until #1682 is completed.

**Comment by agibson22** [comment]
[see this doc AG](https://docs.google.com/a/rallydev.com/document/d/10jShmP6FiCcj4WQ__XRVyC1pbJOQ92Ac2a2oYFZjwzE/edit)

**Comment by ashumz** [comment]
I updated the FAQ - just needs review

**Comment by ashumz** [comment]
need to update screenshots on https://github.com/waffleio/waffle.io/wiki/Pull-Requests-%26-Automatic-Work-Tracking/
