### ISSUE TITLE
test how PR labels change (or don't change) in specific scenario(s)

### ISSUE THREAD

**Issue by ashumz** [waffleio/waffle.io#1690]
- [x] Close an issue in a commit message with 'closes # 1'. Then create a PR for issue # 1 (not necessarily using closes/fixes keywords.) Merge the PR. Status of issue should be closed. PR label still says "In Progress"? ([According to user](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/conversation/662186071) and [this user](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/673192843))

**Comment by marydavis** [comment]
Following those exact steps I noticed that when the issue was closed and the PR was still open, the PR had the label "in progress". Once the PR was merged the "in progress" label was removed.

**Comment by marydavis** [comment]
I will try to repro with steps listed from customers as well

**Comment by marydavis** [comment]
If you drag an issue to another column that has a PR attached, the issue label changes but the PR column label does not. To repro, attach a PR to an issue in 'ready' then drag issue to 'in progress' - the issue will now have the label 'in progress' but the PR will still have the label 'ready' and not 'in progress'

**Comment by marydavis** [comment]
do we want to create an issue around this or rename this card for the backlog?

**Comment by marydavis** [comment]
[per this doc](https://docs.google.com/a/rallydev.com/document/d/10jShmP6FiCcj4WQ__XRVyC1pbJOQ92Ac2a2oYFZjwzE/edit) this seems as expected

**Comment by homeyer** [comment]
Personal feeling - if you move an issue that has a PR connected to it, we should also "move" the PR, by assigning it a label. What do you think @burtonjc? If we agree, we should create a card for it. Probably won't pull it immediately though.

**Comment by agibson22** [comment]
+1 to @homeyer above

**Comment by burtonjc** [comment]
Seems like users want what @homeyer said. I'm good with that.

**Comment by marydavis** [comment]
create this [card](https://waffle.io/waffleio/waffle.io/cards/54bd5512e88e6903000b1b29) to track adding this functionality
