### ISSUE TITLE
view for a single user, across all repos

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#1691]
In a situation where multi repo doesn't make sense, it would be nice to still have a view for a particular user to see all of their issues.

**Comment by luctus** [comment]
A view for a particular user or all the organization's users.

A user could be represented by a single column, where the "In progress" issues are listed.

**Comment by petergault** [comment]
Yes Please! Show me all of my issues across all of my repos. I'm involved with projects across a bunch of different repos, and I need a central location where I can see everything and move my stuff around. This would be super helpful!

**Comment by kellihsf** [comment]
Related to issue [#990](https://waffle.io/waffleio/waffle.io/cards/537e11b6ebef97b1f959ec4e), so we'll close this as a duplicate.
