### ISSUE TITLE
Show who's online right now

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#1693]
[customer requested](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/684305339).

Use Pusher's api to see who's looking at the board, and show user icons in the top bar. Would be rather handy for standups, and fun to see who's looking at open source boards.

**Comment by edgurgel** [comment]
You guys could use presence channels as they will probably do everything need for free: https://pusher.com/docs/pusher_protocol#presence-channel-events

**Comment by kellihsf** [comment]
We haven't seen activity on this card from the rest of the Waffle user base. We are closing it for now as we prioritize and work on other more highly requested features/integrations.
