### ISSUE TITLE
actions on card for moving up and down

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#1695]
Primarily for mobile users, where DnD isn't very accurate.

I wonder if there's a way to combine that UI with something to move a card to the top or bottom, we've received several requests for that.

[customer requested](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/684226941)

**Comment by marydavis** [comment]
we added to card a menu with options to move card to top or bottom
