### ISSUE TITLE
don't assign card ownership if it's already set

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#1697]
When auto-assigning PRs or Issues, don't assign to the user doing the action if the Issue already has an assignee. We should be overriding what a user already set.

**Comment by songawee** [comment]
in hooks repo

**Comment by adamralph** [comment]
Does this mean the change is released?

**Comment by songawee** [comment]
Hey @adamralph! Yes, I merged in the fix this morning. :ship:
