### ISSUE TITLE
internal server error when authenticating with GitHub

### ISSUE THREAD

**Issue by kmanzana** [waffleio/waffle.io#1700]
reference https://twitter.com/jeffandersen/status/555424195039854593

**Comment by kmanzana** [comment]
turns out it there is a problem of running into the rate limit.  Possibly a bug on our end?  Conversation here https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/users/540f7be9112d3d728d000976/conversations

**Comment by kmanzana** [comment]
Checked out newrelic for erring requests and looked at project configuration, nothing unusual

**Comment by kmanzana** [comment]
Pending response from GitHub.   New metrics might also help determine the problem.  Nothing of assistance looking at project configs, mixpanel, or newrelic.

**Comment by kmanzana** [comment]
GitHub can't share data with us regarding api usage because other applications may be involved.  Reached back out to Jeff so that he can work with GitHub to see what is going on.

**Comment by LucyeoH** [comment]
I'm hitting this when I try and authenticate using GitHub - Public Repos and Private Repos - I get a "Internal Server Error" message. :(

**Comment by kellihsf** [comment]
hi @LucyeoH,

Sorry for the trouble with this! Can you email us at support@waffle.io so we can take a closer look? Thanks! :)

**Comment by LucyeoH** [comment]
Will Do @kellihsf thanks for the fast turn around!

**Comment by kellihsf** [comment]
hey @LucyeoH!

We've actually fixed this on our end so you should be good to go! If not, let us know and we'll be happy to help. :)
