### ISSUE TITLE
investigate some PRs not staying connected to their issue cards

### ISSUE THREAD

**Issue by burtonjc** [waffleio/waffle.io#1703]
As per these conversations:
  - [one](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/jacob@waffle.io/conversations/690025786)
  - [two](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/jacob@waffle.io/conversations/687423343)
  - [three](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/691580993)
  - [four](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/691609711)

**Comment by ashumz** [comment]
[another conversation here](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/jacob@waffle.io/conversations/691670534)
