### ISSUE TITLE
Cmd+click doesn't work if PRs are expanded

### ISSUE THREAD

**Issue by MandaBrown** [waffleio/waffle.io#1724]
Cmd+click is a great way to quickly open linked PRs, and the expanded PR view is great for us because we have a lot of info in our PR labels.

But Cmd+click to open a linked PR doesn't seem to work when the PRs are expanded!

**Comment by MandaBrown** [comment]
This is especially painful now that the Pull Request tab is removed from the issue modal, it's kind of a pain to switch the PR expanded view just to be able to navigate to the PR.

**Comment by marydavis** [comment]
@MandaBrown - you can click on the comment icon on the PR to open the PR link even in the expanded view, this should at least help in the meantime :)

**Comment by MandaBrown** [comment]
Ah, that does help, thank you!

**Comment by ashumz** [comment]
[+1](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/705701799)

**Comment by ashumz** [comment]
[+1](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/704242236)

**Comment by ashumz** [comment]
[+1](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/706429516)
