### ISSUE TITLE
add support for .5 value in story point size

### ISSUE THREAD

**Issue by ashumz** [waffleio/waffle.io#1725]
[From a user](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/694806830):

"On the agile teams I have been a part of, the story point tends to take on the meaning of one developer day. It is true that one could scale down the point size so that one point is 1/2 or 1/3 of a day and that this would not per-se violate agile principles. However, you would be asking your customers to adjust their perhaps long-standing and time-tested practices (i.e., the settled value of a story point) in order to use your product."

In reference to how Rally does this, stories with 1 point or lower will be mapped to "very small" for tshirt sizes, the same as stories with a size of 1.

**Comment by ashumz** [comment]
[+1](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/694937209)

**Comment by Saulis** [comment]
+1

**Comment by ashumz** [comment]
Moving this to #1830 - where we will be tracking the development of custom size values. Closing this request out as a duplicate for now
