### ISSUE TITLE
grey out connected repositories in "Add Issue" dropdown for multirepo boards if the source repository has issues disabled. For single repo boards, grey out add issue functionality entirely.

### ISSUE THREAD

**Issue by ashumz** [waffleio/waffle.io#1731]
[customer reported](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/698591227)

"we have 2 private repositories with proprietary software, so we have the open source repository that lets anybody report bugs to us.

We have issues turned off on the private repos so that all bug reports, both by internal employees and external community members, come in through the public repo.

So, I would consider it a bug that you can "Add Issue" to a repository for which issues have been disabled. I would request that you consider fixing it.

For us internally, it would be nice to be able to use the Add Issue form for people to be able to submit issues to any of our projects in one place."

**Comment by burtonjc** [comment]
I don't think we should remove it from the source list. Can we still show it but grey it out or something and have a tooltip on hover to explain why you can't pick that source for Add New? Also, for a single repo board, we should disable the Add Issue button entirely, again with a tooltip explaining why.

**Comment by ashumz** [comment]
yeah, I like the idea to grey it out and have it say "issues disabled, private" or "issues disabled, public" next to where the source is labeled as public or private in the source dropdown. I also like the idea of disabling the add issue button once we show the banner that Kelton is doing for #811 for single repo boards.

**Comment by kellihsf** [comment]
We haven't seen much activity on this card since it was opened from the rest of the Waffle user base. We are closing it for now as we prioritize and work on other more highly requested features/integrations.
