### ISSUE TITLE
Cumulative flow diagram on metrics page

### ISSUE THREAD

**Issue by agibson22** [waffleio/waffle.io#1732]
[customer conversation](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/705853057)

**Comment by erichexter** [comment]
It would be awesome to have a cumulative flow diagram for items as they work thru the columns of the kanban board.  I would imagine you would be able to calculated the times from the add/remove label history on each issue.

![image](https://cloud.githubusercontent.com/assets/114692/5939273/f764609e-a6c7-11e4-8efd-1aba3d6f70d3.png)

**Comment by ashumz** [comment]
Hi @erichexter! 

We actually have an open card for this particular request already: #312 

I'm going to move your great comments over to that card to consolidate the feedback. We also have an open card for general metrics enhancements here (#1327): https://waffle.io/waffleio/waffle.io/cards/53f27af882b317f7d9adafa2

Thanks! Sorry for any confusion -- just trying to keep everything consolidated and make sure that your vote gets added in the proper place. :) I'll be closing this one out as a duplicate, so feel free to subscribe to one of those two cards to get any updates on forward movement! 

Cheers,

Ashley
