### ISSUE TITLE
API access for Waffle (cards, projects, columns, user, providers, webhooks)

### ISSUE THREAD

**Issue by ashumz** [waffleio/waffle.io#1733]
internal: see app#764 

Requested from several users, specifically those who would like to be able to get the sizing data or any additional metadata stored from Waffle cards.

**Comment by ashumz** [comment]
[+1](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/705306376)

"is waffle planning to have an API so that issue estimates can be reported on? right now we use fibonacci labels for card estimates, which don't get summed in waffle columns, but can be reported on. waffle estimates have a nice UI in columns, but can't be reported on."

**Comment by sam-github** [comment]
+1

**Comment by ashumz** [comment]
[+1](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/708349674)

"My team would love to see an integration for: https://ducksboard.com/. We'd love to see that "throughput" graph (for PR's only) on our Ducksboard. Or if ya'll have an API endpoint that could deliver that graph, we can "do the integration" ourselves. "

**Comment by ashumz** [comment]
[+1](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/722292709)

"I am looking to add a repo to waffle.io using Github's api, is the possible? ... In the short I am looking to be able to add repos with Chef, not through a GUI. "

**Comment by ashumz** [comment]
[+1](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/728026710)
"Any type of API currently? Is there a way we could help generate/code a report/graph to make it available to us (or to all waffle)?"

**Comment by jtrinklein** [comment]
+1

**Comment by iamhabitat** [comment]
+1

**Comment by cayblood** [comment]
+1

**Comment by jwalgran** [comment]
+1

**Comment by jperl** [comment]
+1 We would like to be able to archive cards via an API.

**Comment by ashumz** [comment]
+1 for being able to access size

**Comment by kwiens** [comment]
+1 We're using numeric labels on issues to track size and we'd like to be able to synchronize this with waffle sizes

**Comment by SPopenko** [comment]
+1

**Comment by stepthom** [comment]
+1

**Comment by kwiens** [comment]
What does 'needs review' -> 'in progress' -> 'blocked' -> 'closed' mean?

**Comment by irbull** [comment]
With this item closed, does that mean that there is API access to waffle.io now? Are there links / pointers for how we can use this API?

**Comment by kwiens** [comment]
Good questions! I'm interested as well.

**Comment by burtonjc** [comment]
@kwiens, @irbull Waffle now has an API, but it is not publicly available yet. Namely, we need to build the front end pages for managing your OAuth client applications and such. We will make sure and announce when everything is ready for prime time!

**Comment by kwiens** [comment]
Awesome! We're on the edge of our seats.

**Comment by fjaguero** [comment]
Hi, at Mozilla Hispano we are waiting for that API. It will let us create weeklyy email notifications, column size restrictions alerts, etc. Thanks!

**Comment by mstratman** [comment]
Has this been delivered? If so, where and how can I get access? Thanks

**Comment by maurop123** [comment]
Is this still being worked on?
