### ISSUE TITLE
Assign label from "Add issue" dialog.

### ISSUE THREAD

**Issue by pardom** [waffleio/waffle.io#1736]
My workflow generally involves filtering by labels or milestones. I don't know if the gihub API allows it, but it would be nice to be able to assign labels and milestones while adding an issue via Waffle.

**Comment by ashumz** [comment]
Hi @pardom, 

We have two open issues for this, so I'm going to close this one out as a duplicate and tag you in the open issues we have for adding issues with labels and milestones. We plan to pull this work within the next few months. 

Thanks! 

Ashley

**Comment by pardom** [comment]
Cool, thanks!
