### ISSUE TITLE
don't create stories in Agile Central for connected PRs

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#1738]
It's a nightmare to manage PRs in Rally, when they're already represented by a story.

how should we handle a PR that wasn't associated, but now is?

option: don't show any PRs in Rally.

**Comment by ashumz** [comment]
@homeyer what about teams who only use the Waffle integration to bring PR's into Rally (in addition to their issues)? I think that might be a valid use case to consider before doing this work
