### ISSUE TITLE
investigate: increase timeouts?

### ISSUE THREAD

**Issue by samdeane** [waffleio/waffle.io#1739]
I live in a fairly remote place, and currently have a rather unreliable connection! We're talking a ping that varies from 40ms up to 1000ms+ :(

I very often get errors reported when updating a card, and quite often things like the "Assign someone to this card" popup fail to populate properly.

I'm not sure, but given the nature of my connection, I wonder if you're timing out certain requests a bit too aggressively for me. Could be unrelated, but it might be worth looking at.

**Comment by ashumz** [comment]
Hi @samdeane, 

We're in the process of investigating the issue you're running into. We're moving it into "Ready" on our board so we can look into the problem and let you know if/how we can help. 

Thanks! 

Ashley

**Comment by kmanzana** [comment]
@samdeane, just took a look into this for you.  Our server is configured using the default Node.js timeouts of 2 minutes, so no aggressive timing out.  Some of the errors you may be seeing could be real errors or problems with our server keeping up with load as well.

Sorry to say that there is nothing we can do to help you on this with the exception of improving overall app performance.
