### ISSUE TITLE
Filtering "No Label" / "Unlabeled"

### ISSUE THREAD

**Issue by ritch** [waffleio/waffle.io#1740]
This is supported on github like this:

https://github.com/strongloop/loopback/issues?q=is%3Aopen+is%3Aissue+no%3Alabel

Is this possible in waffle? I don't see it in the UI. Even if there is a workaround that would be helpful for now (eg. manually set the url).

**Comment by ashumz** [comment]
Hi @ritch, 

We don't have this functionality available right now, although your backlog column (or whatever column is set to "backlog issues" in Settings->Columns) will show all issues that are not labeled with a corresponding column label name (ie: ready, in progress by default). 

If you don't mind, can you explain a bit more about why this would be useful to your workflow so we can better understand your request? How often would you use a filter like this?

Thanks! :)

Ashley

**Comment by ritch** [comment]
> If you don't mind, can you explain a bit more about why this would be useful to your workflow so we can better understand your request?

Essentially this is for ensuring we are triaging all issues. Our backlog is full of hundreds of issues spanning a lot of repositories. Some are labeled "bug"; some are labeled "enhancement" etc. These labeled issues are still in the backlog, but we know someone has atleast looked at them and labeled them. Issues without a label need to be triaged by someone. Thats where this filter comes in. It makes it easy to know which issues haven't been looked at (if there is another way to do this, that would also be great eg. "find issues where comment count is 0".

With some clever columns we might be able to get around this, but some labels (bug, feature, enhancement, needs-info, etc) do not correspond to columns in our waffle board(s). Also for some labels (eg. "bug") we do not want to lose the label when moving it from "bug" to "in-progress".

Hope that helps... I guess we'll be using GitHub directly until something like this is available.

>  How often would you use a filter like this?

Very often... It would be our default view for triaging issues.

**Comment by ashumz** [comment]
Thanks @ritch! We'll work on trying to get this fit in soon, as it sounds like it'd be very high value for your team and is also something we've heard requested from open source teams who deal with triaging large numbers of issues.

@team: We should add an "Unlabeled" option the same way GitHub does: 

![screen shot 2015-03-26 at 2 01 10 pm](https://cloud.githubusercontent.com/assets/100216/6853273/a34b8a48-d3c0-11e4-8e86-0ca0f1b97f76.png)
