### ISSUE TITLE
padding in issue modal sidebar could use a little work

### ISSUE THREAD

**Issue by JonathanReeve** [waffleio/waffle.io#1746]
The design of Waffle's issue modal sidebar feels like it needs some work. Some things are centered (the label "ASSIGNED," the indicator "OPEN") but the rest is left-justified. Some of these indicators are in all-caps, others aren't. Those things that are centered appear to be inconsistently centered--"ASSIGNED" and "OPEN" don't appear to line up correctly. There doesn't appear to be enough padding between "ASSIGNED" and the avatar below. "Labels" and "Milestone" have gear icons next to them, but "Assigned" has a link labeled "Edit." One might also ask why there needs to be both a gear icon and a down-arrow icon, if both have roughly the same meaning in this context. 

Compare Waffle's sidebar: 

![selection_494](https://cloud.githubusercontent.com/assets/1843676/6004313/e36b88cc-aacf-11e4-990c-9dc327ed02d6.png)

To GitHub's: 

![selection_489](https://cloud.githubusercontent.com/assets/1843676/6003985/bad154de-aacd-11e4-986a-f0de08ba5b08.png)

GitHub's design is incredibly satisfying, in my opinion--subtle grays, consistent spacing, consistent sizes of elements, I have a feeling our team would be more likely to use Waffle's issue interface more if the design were a little bit nicer. Here's a quick 5-minute sketch of some fixes to some of these issues: 

![selection_493](https://cloud.githubusercontent.com/assets/1843676/6004298/c88c01d0-aacf-11e4-9f87-cb50f22bb280.png)

Not perfect, but a step in the right direction.

**Comment by dpedoneze** [comment]
+1

the milestone is broken here

![image](https://cloud.githubusercontent.com/assets/5757502/8995812/35458228-36ea-11e5-892c-ffe40a8b6e1b.png)

**Comment by burtonjc** [comment]
This happens when your milestone has a title of 3 or less characters.

**Comment by dpedoneze** [comment]
You can just update this css code @ `main.css:1364` :smile: 

```css
.modal.detail-modal .modal-content .modal-body .card-sidebar .milestone-pill {
  white-space: normal;
  max-width: 150px;
  /* set minimum width and align text */
  min-width: 40px; 
  text-align: center;
}
```

Cheers.

**Comment by marydavis** [comment]
We just added support for multiple assignees and in the process fixed a lot of the issues with our modal sidebar. Hope you enjoy the changes :)
