### ISSUE TITLE
Have size of card follow the issue to source board for multirepo boards

### ISSUE THREAD

**Issue by woisme** [waffleio/waffle.io#1749]
From board to board.

Ability to add a size on a card that belongs to a source on a multirepo board and have that size carry over to any board that includes that source (primary board for that source included.)

**Comment by iamhabitat** [comment]
+1 on this. Would be great to be able to track issues company wide on one big board.

**Comment by ehlersd** [comment]
+1 Definitely!

**Comment by mohierf** [comment]
Really +1 !

**Comment by marksalpeter** [comment]
+1!

**Comment by bilby91** [comment]
+1

**Comment by homeyer** [comment]
🚀 shipped!
