### ISSUE TITLE
Parent repo disappeared from multi-repo board (amongst other things)

### ISSUE THREAD

**Issue by cweber** [waffleio/waffle.io#1750]
We have since deleted the board, but we had some unexplained bug (after several weeks of use), where the parent repo for a multi repo board suddenly disappeared. It looked like we also lost several of the other repos that we had added.

We were then unable to add any new repos to the board and had to delete it and start over.

(Seemingly related, but even more strange: While this was happening, a third board was added to our waffle for a repo that we had never set up. When we entered the repo we wanted, it took us to the ghost board and then we toggled to switch (again) to the real board and everything was fine...save for all of the other multi-repo problems we were having.) cc @boblannon, @heyitsolivia and @ngrad

**Comment by boblannon** [comment]
+1

**Comment by ashumz** [comment]
Hi @cweber and @boblannon, 

Sorry to hear you ran into this.

We're currently investigating issues around what you experienced. Thanks for letting us know and we'll keep you posted. Let us know, in the mean time, if you run into anything else. 

Ashley

**Comment by homeyer** [comment]
I just resolved these issues, please let us know if you keep seeing this behavior.
