### ISSUE TITLE
Make label statistic

### ISSUE THREAD

**Issue by bvitinshtein** [waffleio/waffle.io#1752]
Hi , 
Can you pleas add another graph statistic to labels

**Comment by ashumz** [comment]
Hi @bvitinshtein, 

Can you clarify what you mean by another graph statistic to labels? Are you suggesting this in reference to the throughput metrics? 

We have an open card for metrics enhancements here: https://waffle.io/waffleio/waffle.io/cards/53f27af882b317f7d9adafa2

We'd love for you to add additional comments to that card directly, as it is our main point of reference for metrics-based enhancements for the future. 

Thanks! :)

Ashley
