### ISSUE TITLE
Allow custom size "schemas" (tshirt sizes, non-fibonacci numbers)

### ISSUE THREAD

**Issue by davetron5000** [waffleio/waffle.io#1753]
I love the new size feature's UX, however the sizes in that list don't correspond to how my team does sizing.  We only need e.g. S/M/L.

It would be great if it were possible to change the "schema" for a project and set the sizes.  Right now, we are using labels, but being able to change the size w/out going into the ticket view is pretty handy.

**Comment by jonturneratduke** [comment]
second this. We use fractional days (quarter, half, full, or two), but hours would work equally well (2,4,8,16).

**Comment by treystout** [comment]
+1 on S/M/L (or just let me define custom tags for sizes)

**Comment by nicksloan** [comment]
Agreed. This would be amazing.

**Comment by ashumz** [comment]
Hi all, 

I'm consolidating your feedback into a single card (#1830) for customizing size values. Thanks for sharing your thoughts and we'll definitely be considering this for the future (hopefully sooner than later! :)) Feel free to comment on the new card as well-- not necessary though. I'll be linking this card so all of your feedback is available to our team for consideration when it's time to pull this work. 

Best,

Ashley
