### ISSUE TITLE
milestone filtering breaks on page refresh

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#1757]
Add a milestone filter and refresh the page. When the page refreshes, the milestone filter is eliminated:

Specifically, this URL: 
[board url]?milestone=Sprint%20%232:%20Jan%2029,%202015%20-%20Feb%2011,%202015

Becames this URL on refresh: 
[board url]?milestone=none,none,none

[customer reported](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/718604972)

child of #3651

**Comment by jonwolski** [comment]
This seems to happen when the milestone has a space in its name.

**Comment by kellihsf** [comment]
Looks like this has been fixed! 👍
