### ISSUE TITLE
Improve the look of Notification banner when on top of open "Add Issue" menu 

### ISSUE THREAD

**Issue by ashumz** [waffleio/waffle.io#1759]
reported by [user](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/720324270)

**Comment by ashumz** [comment]
@dferranti -- after investigating, our notification banner is always centered, so depending on your screen width, the notification may or may not overlap the add issue functionality. 

Do you have any specific suggestions on a view you'd prefer?

Thanks!

**Comment by dferranti** [comment]
Ashley, I do not want that screenshot shared publicly, need you to remove it *immediately*.

Also need you to confirm when it is gone.

Dan
