### ISSUE TITLE
Difficulty throughput graph (throughput by story points/velocity)

### ISSUE THREAD

**Issue by meshy** [waffleio/waffle.io#1768]
It would be great if we could see a throughput graph that was multiplied by issue size.

This would allow us to see our velocity on a project that is corrected for difficulty.

**Comment by jclif** [comment]
+1

**Comment by iamhabitat** [comment]
+1

**Comment by kwiens** [comment]
+1

**Comment by marydavis** [comment]
we added a toggle to view "Count by Size" on the throughput chart - closed by issue #1794

**Comment by meshy** [comment]
Thank-you!

**Comment by kwiens** [comment]
This is fantastic, thank you so much! This shows radically different data than closed issues / PRs over time.

More detailed reporting would be wonderful — you can imagine throughput by person by week, throughput per milestone per day / week, etc.
