### ISSUE TITLE
Conjoined throughput graph

### ISSUE THREAD

**Issue by meshy** [waffleio/waffle.io#1769]
I work at an agency managing a great many projects. It would be fantastic if we could see our throughput across all projects to get a better idea of our productivity.

**Comment by meshy** [comment]
It would be even better if this was combined with #1768!

**Comment by ashumz** [comment]
Hi @meshy, 

I know this request is a bit old, but was doing some backlog cleaning and wanted to reach out. :) 

did you know that if you add multiple sources to a board you can view the throughput by source and for all of the sources/repos? 

Ashley

**Comment by meshy** [comment]
Hi @ashumz, thanks, that's good to know!
