### ISSUE TITLE
Burndown Reports

### ISSUE THREAD

**Issue by abargmann** [waffleio/waffle.io#1775]
I'd love to be able to generate sprint burndown charts from the point system that you all added. 

I'm not sure how many people are using waffle as such, but here's a use case: 

You have, in addition to the standard backlog and ready columns, the following columns: 

1.  Committed 
2.  In progress 
3.  Done 

A user can set a day of the week for when a sprint starts and a sprint interval (like 1 week or 2 weeks).  

On the day of the week that is the sprint start date, you tally the total number of points on cards in the committed column.  This is the commit for the sprint. 

As a card moves to done, the points on the card are deducted from the total commit.  The burndown chart would have points on the x axis and days of the week on the y axis.  At the end of each day, it'd take the number of points yet to be completed from the commit and plot a point.

**Comment by abargmann** [comment]
my bad, probably a duplciate of #1297

**Comment by homeyer** [comment]
Thanks @abargmann! Closing as a duplicate, following #1297 is the best place to keep track of our progress.
