### ISSUE TITLE
duplicate columns created

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#1776]
[customer conversation](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/738224121).

I was able to reproduce it once. I didn't double click. Sounds like a race condition.

**Comment by homeyer** [comment]
idea: better UI for waiting for column to appear (spinner, disable add button, etc).

**Comment by homeyer** [comment]
solution is probably to rewrite the column UI, and fixing a few things on the way, like edit column description

**Comment by mohierf** [comment]
I had the same problem with one of my board : https://waffle.io/ipm-france/knm/settings/columns

Two *Column1* columns are created. When I rename one of them and drag to its position in my board, everything is fine, but the second Column1 is still present. Both columns seem to be independent ... but when I delete the Column1, both of them are deleted !

**Comment by ashumz** [comment]
Hi @mohierf -- a refresh of the page should clear up the misfit column for now (it is a display issue, but there should still be a single column created after refresh.) 

Thanks! 

Ashley

**Comment by mohierf** [comment]
Thanks @ashumz ... I saw today that a page refresh made the job.

**Comment by ashumz** [comment]
[+1](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/748613102)

**Comment by lukeberry99** [comment]
I noticed that clearing my cache 'fixed' the issue for me, not sure if that's related or not.

**Comment by ashumz** [comment]
[+1](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/775519750)

**Comment by uderic** [comment]
This also happens to me. Refreshing the page does resolve the issue.

After clicking 'Add Column' I simply refresh every time.

**Comment by nditada** [comment]
same thing here

**Comment by wizardamigos** [comment]
I have the same problem

**Comment by wizardamigos** [comment]
After a lot of refreshing, clicking, changing the problem disappeared.

**Comment by jacebrowning** [comment]
+1
