### ISSUE TITLE
group tasks from different repos

### ISSUE THREAD

**Issue by marcelog** [waffleio/waffle.io#1780]
when having multiple repos in the same board it would be nice to have a way to group isses from the same repos, perhaps by color, or by another visual sign, maybe a backlog per repo before throwing tasks in the main backlog?

**Comment by rossjones** [comment]
+1, even with support for colour it would be really useful to group them together in any particular column to get an idea of which are currently the most worked on.

**Comment by Surgo** [comment]
+1

**Comment by kellihsf** [comment]
related to [#1758](https://waffle.io/waffleio/waffle.io/cards/54d3eb4962f79303002caec3), closing as a duplicate
