### ISSUE TITLE
Show a list of In-Progress Issues in the Readme.

### ISSUE THREAD

**Issue by imthatguyhere** [waffleio/waffle.io#1781]
Make a pull request and merge it automatically (if possible, if not the user can do it). Have it include a list of all the issues currently in progress and links to them. 

This would be outstanding!

**Comment by mohierf** [comment]
+1

**Comment by iamhabitat** [comment]
great idea. +1

**Comment by igorsantos07** [comment]
+1

**Comment by kellihsf** [comment]
We haven't seen much activity on this card from the rest of the Waffle user base. We are closing it for now as we prioritize and work on other more highly requested features/integrations. Thank you! :)
