### ISSUE TITLE
Org overview

### ISSUE THREAD

**Issue by missinglink** [waffleio/waffle.io#1786]
I would love to see an organization overview screen such as: http://mapbox.github.io/github-org-browser/

When embracing a modular architecture and splitting up discrete functionality, you end up with a million repositories to watch over, each having it's own issues.

**Comment by yadah** [comment]
+1

**Comment by homeyer** [comment]
waffle.io/:owner exists now! It's a bit barebones, but you can at least find what boards exist for an org.

**Comment by missinglink** [comment]
thanks @homeyer 

IMHO this issue is not resolved as https://waffle.io/pelias does not provide an overview of work on-going across a whole project.

We currently use a 'root' repository with the same name as our org for project-wide issue tracking and documentation https://waffle.io/pelias/pelias, using waffle we can then use the 'project settings' to add all the boards underneath our org.

This gives a pretty good overview of the project, however it requires that we manually add each new repo as it's created (not the end of the world)

Is it possible to create an aggregate view as per above to be hosted at waffle.io/:org instead?

A little off-topic but we also have issues syncing tags using this approach.

Thanks!
