### ISSUE TITLE
Drag and drop images to issues

### ISSUE THREAD

**Issue by Gabriel-p** [waffleio/waffle.io#1789]
The commenting system in Github allows adding images to issues or comments in issues simply by drag and drop.

It'd be nice if Waffle allowed this, or at least warn the user because if you write a comment/issues and then try to drop an image inside it, the browser will navigate away from Waffle (since it doesn't support drag and drop) thus losing whatever you had written.

**Comment by ashumz** [comment]
Hi @Gabriel-p, 

We currently have an open issue for this request on #846 -- also viewable [here](https://waffle.io/waffleio/waffle.io/cards/53567b62ebef97b1f9599a7f). 

I'll be closing this out as a duplicate but will reference the request in our original issue for this request. 

Thanks! 

Ashley

**Comment by jerjerlam** [comment]
Uh... sorry but still can't drag and drop images...
