### ISSUE TITLE
sort connected sources alphabetically in settings/sources

### ISSUE THREAD

**Issue by sam-github** [waffleio/waffle.io#1792]
Lists should be sorted, its very hard to find things in long lists in the absence of sorting.

**Comment by ashumz** [comment]
@sam-github, 

How would you prefer them to be sorted? Are you using the filter feature or is this for when you aren't sure of the name of the repository?

Thanks for the request! 

Ashley

**Comment by sam-github** [comment]
lexically sorted. and its for when I don't want to type out the whole name.

**Comment by ashumz** [comment]
Hi @sam-github, 

Just to confirm, you are referring to the source list under "Add Issue" rather than the source list in Settings->Sources, correct?  

Thanks!

Ashley

**Comment by sam-github** [comment]
I'm referring to https://waffle.io/strongloop-internal/scrum-nodeops/settings/sources, titled

```
Configure your sources
Add a source to interact with more than one repository on your board.
```

**Comment by sam-github** [comment]
To elaborate, if you want to scan the list to make sure a repo is there, you have to scan the whole list, scanning a lexically sorted list to find something is much faster.
