### ISSUE TITLE
Rename Waffle Board

### ISSUE THREAD

**Issue by mhowe-gl** [waffleio/waffle.io#1793]
Currently our Waffle Board is named after the first repo we connected. We've since connected multiple other repos, so the name of the board is now confusing

**Comment by ashumz** [comment]
Hi @mhowe-gl, 

We have an open request for this on our board (#1392) viewable [here](https://waffle.io/waffleio/waffle.io/cards/5407eef182b317f7d9ae350e). I'll be closing this out as a duplicate but will reference your request on our original card. 

Thanks! 

Ashley
