### ISSUE TITLE
Use size totals to measure velocity

### ISSUE THREAD

**Issue by betamatt** [waffleio/waffle.io#1794]
Cards can have sizes (which makes me so happy) but once they end up in the done bin you can only measure the total points for the last two weeks. It would be great to be able to compare that against previous two week intervals to serve as a velocity estimate.

**Comment by kwiens** [comment]
+1

**Comment by elia** [comment]
+1

**Comment by RickMohr** [comment]
+1 
Note that our two-week sprints start on a Friday and end on a Thursday, so just seeing weekly totals for Monday - Sunday wouldn't do it for us.
