### ISSUE TITLE
Column on/off buttons should be depend

### ISSUE THREAD

**Issue by ScarlettCode** [waffleio/waffle.io#1795]
If I turn a switch on for a specific column is should allow me to turn that switch on for other columns. For example if I turn" Collaborator PR start" on for Column 1 and 2 then it fails because it doesn't know which column to go to. The UI should allow two buttons in the same row to be on at the same time

**Comment by ashumz** [comment]
Hi @ScarlettCode, 

Right now you can only turn on one option per column in order for things not to get funny on you. However, we're planning to clean up the column UI in the next few months to be a lot more intuitive, and we'll keep this feedback in mind!

We're tracking this issue (and I've added your feedback from this issue) here: https://waffle.io/waffleio/waffle.io/cards/5345b5a4ebef97b1f9598df0
