### ISSUE TITLE
Feature request: non-duplicating 'closed' columns.

### ISSUE THREAD

**Issue by RobiFerentz** [waffleio/waffle.io#1796]
Add the option to have columns AFTER a closing column, without duplicating in previous closing columns.
My use case is simple: An issue is closed in the master branch, but there are 2 more stages after that that I need to track, 1) staging - the closed issue code has been deployed to the staging environment, 2) Production - the code is live on production.

In the current situation, closing columns after the first will leave duplicates of the issue in the previous closing column and non-closing columns after a closing one will reopen the issue.

**Comment by homeyer** [comment]
tracking on #616
