### ISSUE TITLE
Closed cards appearing in backlog occasionally

### ISSUE THREAD

**Issue by ashumz** [waffleio/waffle.io#1798]
[Customer reported](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/760495922)

[Flowdock thread](https://www.flowdock.com/app/rally-software/rudder/messages/2235771?filter=search&query=backlog)

**Comment by ashumz** [comment]
[+1](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/762036219)

**Comment by jeffbrown** [comment]
Some data points which may help.  Both https://github.com/grails/grails-core/issues/667 and https://github.com/grails/grails-core/issues/674 are presently marked closed and are appearing in the backlog at https://waffle.io/grails/grails-core.  Maybe something to do with tags that are on those issues?

**Comment by homeyer** [comment]
sync process rebuilt, this shouldn't happen anymore!
