### ISSUE TITLE
Unify coloring of pull requests so standalone PRs can self-indicate their status (open, merged)

### ISSUE THREAD

**Issue by tnrich** [waffleio/waffle.io#1810]
It would be nice if the same green vs white coloring scheme used for linked open vs closed pull requests could also be used for unlinked pull requests:

For example, in the image below, issue 803 is an open pull request, but it is colored white, not green. Yet, right above it, there is a green pull request linked to an issue. 
![image](https://cloud.githubusercontent.com/assets/2730609/6720098/0bfb8010-cd7d-11e4-87f0-03f365bff25d.png)

**Comment by ashumz** [comment]
Hi @tnrich, 

Agreed - this would be a nice addition for being able to indicate if the PR is open for standalone PR's! We'll see what we can do. :)

Ashley
