### ISSUE TITLE
multiselect sources for multirepo boards

### ISSUE THREAD

**Issue by ashumz** [waffleio/waffle.io#1813]

**Comment by jakespace48** [comment]
this would be great. If i could show multiple repos on one board it would be a great help.

**Comment by ashumz** [comment]
Hi @jakespace48, 

You can show multiple repos on a board at any time! :) This card is specifically for being able to select multiple sources at one time when adding your sources. 

To get started adding additional sources to your board, navigate to Settings->Sources and add any repositories for which you are a collaborator. Note that this will change the display of your board for you and all team members. 

You can also find information on the details behind multirepo support here: https://waffle.io/blog/2014/04/23/get-more-done-with-multi-repo-support/

Let us know if you have questions by reaching out using the question mark icon in the sidebar. :)

Cheers,

Ashley

**Comment by ashumz** [comment]
+1 from user on Twitter and +1 from Strongloop users

**Comment by ashumz** [comment]
Occasionally, if you try to add too many repos at once you'll hit the rate limit

See [internal convo](https://www.flowdock.com/app/rally-software/rudder/messages/2548110)

**Comment by ashumz** [comment]
duplicate of #1590
