### ISSUE TITLE
Card Descriptions should increment the number next to the comment-icon on the card

### ISSUE THREAD

**Issue by pauldiepenbrock** [waffleio/waffle.io#1815]
I've noticed that members on my team won't open issues to check for a description if this number is blank. This is a bit annoying since the description is just as important (if not more so) than any additional comments.

**Comment by ashumz** [comment]
Hi there, 

We're already tracking similar functionality here: https://waffle.io/waffleio/waffle.io/cards/54467229d613f614d447b3da

Closing this out as a duplicate -- feel free to follow the above mentioned issue for updates! We do plan to do this work, but it will likely be an indicator of description versus an increment to comment count. :)

Ashley
