### ISSUE TITLE
GIthub referencing feature

### ISSUE THREAD

**Issue by luan-cestari** [waffleio/waffle.io#1822]
Better references between issues and PR comments (using @ and #): autocomplete feature; cross-repository references (autocomplete and closing) ;

**Comment by elia** [comment]
:+1:

**Comment by ashumz** [comment]
Hi @luan-cestari and @elia, 

You'll want to follow this issue: https://waffle.io/waffleio/waffle.io/cards/5367faf3ebef97b1f959b4c4 for updates. We're planning on doing this in the near future, but haven't pulled it into our immediate backlog yet. Subscribe to the card in GitHub for additional updates and notification of forward progress. :)

As for the # recognition, we don't have this planned yet -- but one thing you can do to get all of this functionality from GitHub is use command+click or control+click (depending on your OS) on the Add Issue button to quickly open another tab with the Add Issue screen from GitHub.

For cross repo references, we'll most likely started recognized URL refs, but would love to hear what else you have in mind!

Ashley
