### ISSUE TITLE
Voting/Like&dislike

### ISSUE THREAD

**Issue by luan-cestari** [waffleio/waffle.io#1824]
Voting feature on issues/PRs  Just up/down votes button storage as a label or as a description in the issue. With that issues could be voted if it is relevant or Pr could be merged after reaching % of team's approval  or etc

**Comment by CyberStrike** [comment]
+1

**Comment by ashumz** [comment]
We do plan to do this in the future! We actually have an open issue available for this here: https://waffle.io/waffleio/waffle.io/cards/53440db224ceb40200d90fab

I added both of your +1's and will be closing this as a duplicate. 

Thanks!
