### ISSUE TITLE
Blocker feature

### ISSUE THREAD

**Issue by luan-cestari** [waffleio/waffle.io#1825]
Blocker feature: There could be an special label that would change the card color and make it move to the highest possible position in the stack if the card (PR/issue) has this flag. Other features mentioned could also trigger this feature (for example the next feature)

**Comment by ashumz** [comment]
Already tracking this request here: https://waffle.io/waffleio/waffle.io/cards/53445c8eebef97b1f9598d89

Added your feedback and +1. Thanks! 

Ashley
