### ISSUE TITLE
Columns randomly being deleted

### ISSUE THREAD

**Issue by brianellin** [waffleio/waffle.io#1831]
Our waffle had "Ready" and "Needs Attention" columns, which just randomly were deleted / disappeared from our board. Adding a "Ready" column back, and it was deleted again.

Very scary bug that entirely breaks our company workflow.

**Comment by marydavis** [comment]
@brianellin yikes, that doesn't sound good. We have been looking into this and have not been able to replicate this issue or find any errors that would cause this problem. Would you mind contacting us through the '?' button in the app sidebar? This way we can get some more specifics from you that you may not want public.
