### ISSUE TITLE
Is there more than one way to archive a card?

### ISSUE THREAD

**Issue by caseypt** [waffleio/waffle.io#1834]
Cards are being archived when they shouldn't be.

Is there another way to archive cards other than opening the issue modal and clicking archive?
 
We've noticed several issues (at least 9 that we've found) get archived, but no one clicked the archive button. Reopening the issue brought them back onto the board.

Also, just FYI, we are using a multi-repo board.

**Comment by caseypt** [comment]
Here's an example of an issue that was archived in some other way than through the modal: https://github.com/azavea/nyc-trees/issues/876

To put it another way, we didn't want this card to be archived, but somehow it got archived.

We can bring these back by reopening them, then dragging them from the backlog to the done column, which closes them again, but they remain on the board.

**Comment by ashumz** [comment]
Hi @caseypt, 

Sorry for the confusion! The Done column clears out cards every 7 days, so if a card is older than 7 days and hasn't had any updates made to it in that time, it will be removed from the board. To get it back, you can update the card, or reopen it as you mentioned. 

Hope this clears things up! Let us know if we can help further. 

Ashley

**Comment by caseypt** [comment]
Thanks! Is there anyway to disable this behavior? We work in two weeks sprints and review all the cards we completed at the end of the sprint. This is made difficult by some cards being auto-archived.

**Comment by ashumz** [comment]
There's no way right now to disable this behavior, but there are a few workarounds that could work for you!

I've seen teams use a Done column that doesn't close issues (if you use GitHub's closing keywords this could be a problem, but you could also check in to Waffle's Connect keywords(https://github.com/waffleio/waffle.io/wiki/FAQs#prs-connect-keywords).

 I've also seen teams go to GitHub for all of the cards for a given sprint and add a label (ie: sprint review) which will trigger all of the cards to be updated and to show up in the Done column again. 

Hope this helps! If you have additional questions, the quickest route to support is via the question mark icon on the sidebar. :)

Cheers,

Ashley

**Comment by caseypt** [comment]
Thanks for the tips.

What about making the auto-archive days configurable?
