### ISSUE TITLE
Text other than "Ready" for README badges

### ISSUE THREAD

**Issue by cheerfulstoic** [waffleio/waffle.io#1839]
I would like to be able to use text other than "Ready" for my waffle badge.  Ideally it would be nice if I could display the counts for three columns in my README with different badges for each

**Comment by CodeMan99** [comment]
This is completely possible. See [CodeMan99/nanorc](https://github.com/CodeMan99/nanorc) for an example.

**Comment by cheerfulstoic** [comment]
Oh, excellent, thanks!  I wasn't able to find any examples.  Maybe some docs would be good.  I'm happy, though ;)
