### ISSUE TITLE
Find and use project's `CONTRIBUTING` file

### ISSUE THREAD

**Issue by cheerfulstoic** [waffleio/waffle.io#1841]
GitHub lets you specify a `CONTRIBUTING` file:

https://github.com/blog/1184-contributing-guidelines

It would be great if waffle.io showed this to users when they go to create a new issue in waffle.  You could even improve on the GitHub workflow my showing the contribution guidelines at the time of creating the issue (whereas GitHub only links to them)

**Comment by wdoug** [comment]
:+1:

**Comment by cheerfulstoic** [comment]
GitHub also added templates for issues and pull requests, so that's cool:

https://github.com/blog/2111-issue-and-pull-request-templates

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
