### ISSUE TITLE
Reordering with filters on

### ISSUE THREAD

**Issue by marek-saji** [waffleio/waffle.io#1845]
Most of the time, when I try to reorder cards and have filters on (I often work with just things assigned to me or noone), reordering works far from reliable:

- some times after dropping a card it lands somewhere at the end of the column, instead at place I've dropped it

- some times, it appears to be dropped correctly, but after page refresh it shows up in other position in the column

**Comment by ashumz** [comment]
Hi @marek-saji, 

Thanks for reporting these issues. We are aware of the issues that occur when filtered and will be working on refactoring how ranking in Waffle works within the coming weeks. You can follow our progress on this open card for issue #1307 - https://waffle.io/waffleio/waffle.io/cards/53ea6d9682b317f7d9ad84c9 

I'll be adding your feedback to that card directly and closing this out as a duplicate. Thanks for your patience as we work to get this resolved and improve your overall experience with Waffle. 

All the best, 

Ashley

**Comment by marek-saji** [comment]
thanks, I could not find that issue. glad it's being tajen care of. {:
