### ISSUE TITLE
One issue; 2 boards

### ISSUE THREAD

**Issue by pioneerroad** [waffleio/waffle.io#1854]
Working on an app that has separate server and client repos, but many of the jobs relate to server and client. Would be great if it were possible to simultaneously add one issue to 2 different repos, rather adding issue once on each waffle board.

**Comment by homeyer** [comment]
The Waffle team works across a dozen repos to build Waffle.io, here's how we do it:
- an issue exists in a public repo, so our roadmap is public. Issues we don't want to share with the public we put in other repos, related to what code it will touch.
- we open Pull Requests across multiple repos, for one issue. We use absolute issue refs, like waffleio/waffle.io#1854, to reference issues vs just the number.
- In Waffle, we have all our repos on one board. The issue refs clue Waffle in, so Waffle shows the PRs from different repos on the issue they reference.

See if that works for you, let us know if it doesn't.
