### ISSUE TITLE
design column interface

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#1857]
**Acceptance Criteria:**
- [x] Support editing description
- [x] maybe handle saving all columns at once, vs each individually?
- [x] support validation, to prevent users from being dumb - double backlogs, etc. Maybe redesign how the toggles work? Make them easier to understand, they're confusing right now.
- [x] option to choose existing label, or create new. This is to prevent users from having a label that doesn't match the case of an existing label.
- [x] even if we don't implement, consider in the design how to handle multiple "done" columns (a column for closed issues with a label). This would have to consider the auto-hide of issues after a week, whether to remove it, customize it, etc.

**Comment by marydavis** [comment]
![screen shot 2015-04-16 at 10 39 39 am](https://cloud.githubusercontent.com/assets/176437/7183431/6cbe756a-e425-11e4-985b-f63da9363fb5.png)
