### ISSUE TITLE
Blocker Hieracrchy

### ISSUE THREAD

**Issue by jghibiki** [waffleio/waffle.io#1859]
Allow users to assign an an issue 0 or more blockers, or other tasks that must be completed before this task can be worked on.

**Comment by brollb** [comment]
+1

The task could also be auto moved to "ready" when it is no longer blocked.

**Comment by mauroservienti** [comment]
We'd like to have this one as well, even in the form of `Blocked by #` similar to the `Connects to #` thing

**Comment by kellihsf** [comment]
Waffle now supports [issue dependencies!](https://help.waffle.io/dependencies)
