### ISSUE TITLE
Multple Simultaneous Boards

### ISSUE THREAD

**Issue by noelhenson** [waffleio/waffle.io#1862]
We are working on a complex project with multiple interrelated GH repos. When we are working with two waffle boards open, issues added in one board seem to appear in both.

**Comment by noelhenson** [comment]
This issue is being further characterized.

**Comment by ashumz** [comment]
Hi @noelhenson, 

Please provide additional details if possible. Sounds like you need one board, with the additional repo(s) connected as sources. You might have to delete the project/board for the connected sources to get the ideal behavior. 

Let us know if you're still having issues! 

Ashley

**Comment by noelhenson** [comment]
Ashley,

Thank you for the quick response.

Actually what we have (for the sake of argument) are two repros for a 
client/server project. One repro is for the client side app, the other 
for the server. If both are open, in separate tabs, then new issues 
added in  one tab appear where they should but then, a moment later, 
appear in the other tab as well.

I am working of further characterization of the issue as well as step 
for reproduction of the issue.

Have a great day!

Noel

**Comment by ashumz** [comment]
Hi @noelhenson,

Thanks for the info! When you have full repro steps, would you mind submitting them via the question mark icon in the app (located on the sidebar)? That way if you have any sensitive information to share such as repository name or screenshots with data, we can keep it private and off of the public board. 

We'll be keeping an eye out for your report and appreciate your diligence in getting us repro steps so we can further look into the issue! 

All the best, 

Ashley

**Comment by ashumz** [comment]
Hi @noelhenson, 

I'm closing this out for now and will contact you via the Waffle app! 

Cheers, 

Ashley
