### ISSUE TITLE
Autocomplete collaborators/participants nicknames

### ISSUE THREAD

**Issue by freemanoid** [waffleio/waffle.io#1865]
Add autocompletion of collaborators and issue participants nicknames (like @someone) for comments and issue description editors.

**Comment by ashumz** [comment]
Hi @freemanoid, 

We do plan on doing this within the next few months and are tracking it on #925 here: https://waffle.io/waffleio/waffle.io/cards/5367faf3ebef97b1f959b4c4

Closing this out as a duplicate, but please do follow/subscribe to that issue for updates! 

Ashley
