### ISSUE TITLE
Ability to create columns based on *multiple* labels and/or milestones

### ISSUE THREAD

**Issue by gracecanfield** [waffleio/waffle.io#1868]
It would be great to be able to create a new column that corresponds to multiple labels and or milestones. 
Use case: I want to create a column that displays issues that are high priority and ready to begin work. I'd like to be able to create a column that includes cards that are labeled both "High Priority" and "Ready".

**Comment by lo1tuma** [comment]
Related: #1438 #1876, #387.

**Comment by kellihsf** [comment]
This is related to issue [#1438](https://waffle.io/waffleio/waffle.io/cards/541c60ac82b317f7d9aec848), we'll close this as a duplicate.
