### ISSUE TITLE
Ability to add labels when first creating a card

### ISSUE THREAD

**Issue by gracecanfield** [waffleio/waffle.io#1869]
Right now, unless I have a column set up that is set in the waffle.io settings as a "backlog" column, when I enter a new issue, it disappears and isn't available anywhere on the board...i have to go back into actual GitHub to add a label to make it appear on one of my boards. If I could add a label during the issue entry process on waffle.io, that would make it automatically show up on Waffle.io in the appropriate column.

**Comment by ashumz** [comment]
@gracecanfield, 

Good news! We're working on that now (and it's almost done.) :) 

Issue #1553, also viewable here: https://waffle.io/waffleio/waffle.io/cards/5453c68e7abdfe69daba5b91

Closing this out as a duplicate, but have no fear -- we'll deliver soon! 

Ashley
