### ISSUE TITLE
Allow user to collapse a column

### ISSUE THREAD

**Issue by jcoyne** [waffleio/waffle.io#1873]
I'd like to collapse a column so that I can see more details on the columns that I currently care about.

**Comment by CodeMan99** [comment]
Less is more. Remove the unnecessary columns instead? In other words, consider why the columns you want to hide exists, and determine if the cards in that column actually can be in a different column by simply changing the definition slightly.

If you really want to see only certain cards, consider using labels manually and filter by those.

If you really want to consider a single column, use github and filter by label.

**Comment by jcoyne** [comment]
@CodeMan99 My team needs the other columns, but certain members of the team don't  For example. a project manager needs to see the "Backlog" and the programmers only want to see "Ready" "In Progress" and "Done".  If you don't want it in waffle, that's fine. Using labels could work, but then we lose the drag to a different column feature.

**Comment by CodeMan99** [comment]
The general solution to that problem is to have multiple boards. Since one board is a limitation of waffle, maybe this isn't a great tool for your workflow.

Hiding columns on a board really defeats the purpose of that board. Unless your board is trying to accomplish more than one workflow, which again, the industry says "use more boards".

**Comment by jcoyne** [comment]
Yeah, it just feels like the perfect tool with ONE tiny issue. ;)

**Comment by roll** [comment]
:+1: 

Even just vertical collapsing without horizontal moving will be great.

**Comment by ashumz** [comment]
Hello!

Wanted to let you know we already have an open issue for this here: (#317) https://waffle.io/waffleio/waffle.io/cards/53440db224ceb40200d90f98

I will be closing this one out as a duplicate and referencing it in the above issue. We agree that columns should be collapsible and are planning to add that feature in the future!

All the best, 

Ashley
