### ISSUE TITLE
New issues insert at top/bottom

### ISSUE THREAD

**Issue by jcoyne** [waffleio/waffle.io#1874]
If I've sorted a column, then I create new issues, the new issues go to the top, messing up the ordering i've done.  If there was an option "new issues go to (top/bottom)" that would be helpful.

**Comment by idris** [comment]
:+1:

**Comment by CodeMan99** [comment]
I assume this isn't an option because of infinite scrolling. If your "opened/unplanned" column has a lot of cards (like waffleio's own board) it will take a while to get to the bottom of the list. (Related conversation on #1875.)

#1740 is a better solution.

**Comment by bfirsh** [comment]
:+1: New issues at the bottom of the backlog please.

**Comment by ashumz** [comment]
We're currently tracking this on #359. Until we rework the way cards are ranked on Waffle boards, we can't pull this option. Once we've completed that work (#1307), we'll be able to consider doing this. Closing this out as a duplicate. Please track #359 to follow progress. 

Thanks all! 

Ashley
