### ISSUE TITLE
Short URL for my assigned task

### ISSUE THREAD

**Issue by sbruschi** [waffleio/waffle.io#1877]

**Comment by CodeMan99** [comment]
Short URL versus what? This issue is not clear.

If this is a github url, perhaps [git.io](https://github.com/blog/985-git-io-github-url-shortener) will help.

**Comment by ashumz** [comment]
Hi @sbruschi, 

Can you clarify what you mean by a shortened URL? Are you referring to the link to the card modal view being shortened? 

Thanks! :)

Ashley
