### ISSUE TITLE
Add Milestones from the add issue dialog or another dialog

### ISSUE THREAD

**Issue by AndyWendt** [waffleio/waffle.io#1883]
Having to go to github to manage issues is a little cumbersome and annoying.

**Comment by shacharz** [comment]
+1
This is especially true when milestones are cross repos, having to open them in each repo in github is even more cumbersome. Adding a milestone should give you the option to either select a repo to add the milestone to, or with multi-repo boards select all of them.

**Comment by janusdn** [comment]
+1

**Comment by PierrickP** [comment]
+1 @shacharz create milestones on multi-repo will be terrible !

**Comment by shacharz** [comment]
I think this should be expended to labels

**Comment by stevecox** [comment]
+1

**Comment by ReinoutWoortman** [comment]
+1

**Comment by laughedelic** [comment]
+1

**Comment by lindenle** [comment]
+1 I would also like to see this for labels. This would be especially useful for boards that cover more than one repo.

**Comment by marydavis** [comment]
We added this feature and the same for labels :) Checkout this article for more details: https://help.waffle.io/faq/milestones/how-do-i-create-a-new-milestone-in-waffle and https://help.waffle.io/waffle-boards/labels/how-do-i-create-a-new-label-in-waffle
