### ISSUE TITLE
Add business value to tickets

### ISSUE THREAD

**Issue by codingjoe** [waffleio/waffle.io#1887]
To ensure the best performance for your business, it's not to uncommon to assign business points, which represent the value that will be generated by solving a ticket.

As a plus it would be cool to prioritise tickets by value per size, to ensure maximum efficiency.

**Comment by codingjoe** [comment]
@kellihsf why was it closed?

**Comment by kellihsf** [comment]
hi @codingjoe,

This is being closed for now because it's not on our current roadmap.  If we continue to get requests for this, we'll consider adding it back to our 'Ideas' column. Thanks!

**Comment by codingjoe** [comment]
Understood

**Comment by MattB9** [comment]
Thats a real shame... I'm struggling to find a good way to prioritize our backlog without other ways (other than Estimate) and us going through the backlog and manually reordering it every week. Capturing business value or points would be so much better.
