### ISSUE TITLE
Waffle.io's own badge is confusing.

### ISSUE THREAD

**Issue by CodeMan99** [waffleio/waffle.io#1890]
Currently [this repo](https://github.com/waffleio/waffle.io) has a waffle badge that isn't very clear as to what column it should be displaying.

Currently the README.md has

```markdown
[![Stories in Ready](https://badge.waffle.io/waffleio/waffle.io.svg)](http://waffle.io/waffleio/waffle.io)
```

Would be great to see

```markdown
 [![Stories in Progress](https://badge.waffle.io/waffleio/waffle.io.svg?label=waffle%3Ain%20progress&title=In%20Progress)](http://waffle.io/waffleio/waffle.io)
```

Which displays:  [![Stories in Progress](https://badge.waffle.io/waffleio/waffle.io.svg?label=waffle%3Ain%20progress&title=In%20Progress)](http://waffle.io/waffleio/waffle.io)

I would write this as a PR if I knew what column you actually want to display. :no_entry_sign:

**Comment by marydavis** [comment]
@CodeMan99 agreed! Just updated, thanks :)
