### ISSUE TITLE
Transfering a repo from one org to another

### ISSUE THREAD

**Issue by jcoyne** [waffleio/waffle.io#1895]
If you transfer a repo from one organization to another on github, the change does not appear on my multi-project waffle board.

**Comment by jcoyne** [comment]
When this happens all subsequent API  calls fail:

"Unable to fetch users from Github"
"Unable to save card #10"

**Comment by homeyer** [comment]
@jcoyne, for now, you'll have to delete your project and recreate it. You won't lose any labels, but you'll have to recreate your columns and you'll lose the ranking of issues.

**Comment by jcoyne** [comment]
@homeyer yes, that's what I did. But it's pretty confusing when this happens, and I wonder if it would be helpful for other people who do this.

**Comment by homeyer** [comment]
Oh definitely, thanks. Marking it as a bug as well, so we can consider handling it on our side.

**Comment by homeyer** [comment]
fixed a while ago :)

**Comment by cabloo** [comment]
@homeyer I just transferred a repo from a user to an organization and lost all my rankings/sources/card sizes. Is there any way to transfer those to the new repo?

**Comment by kellihsf** [comment]
hi @cabloo After transferring a repository in GitHub that is tied to a Waffle project, you'll simply visit your original Waffle project URL (prior to the rename). We'll automatically redirect your project to its new URL and will carry over your project configuration, including columns, rank, and sizes. 

Did you create an additional Waffle project for this repo? 

If so, you will have to recreate your original project configuration in this case, but your original project URL will continue to redirect as expected. Creating an additional new project will result in overriding your original project configuration and it will not be recoverable, including card rank, column configuration, and sizes.

**Comment by cabloo** [comment]
@kellihsf thanks for that, I did end up creating a new waffle project for the repo which did wipe the ranks, etc. Would have been nice if it had a way of knowing that the new repo had been transferred from my original repository.

**Comment by kellihsf** [comment]
@cabloo thanks for the reply, glad we got this sorted! We do have a section on this in our [FAQ](https://help.waffle.io/hc/en-us/articles/225555287-I-renamed-or-transferred-my-repo-in-GitHub-What-happens-to-my-Waffle-project-s-for-that-repo-), but maybe it would be more helpful if that info was located somewhere on the board?

**Comment by cabloo** [comment]
@kellihsf I was hoping for more like something along the lines of:

When I go to create the new waffle project on the transferred repo, it would check my other repos to see if any had been transferred to the new one. If the new repo was indeed a transfer, it would move all the ranks, etc. over.

**Comment by homeyer** [comment]
Unfortunately a transferred repo doesn't tell us it was transferred, we can only detect it by watching for the redirect from the original. So when creating a new project we'd have to add the overhead of fetching all the existing repos of waffle projects for this condition. 

Any other thoughts on how to detect it?

**Comment by cabloo** [comment]
I couldn't find any evidence that [webhooks](https://developer.github.com/webhooks/) would broadcast an event for a transfer, but perhaps this could be tested? I think that would be the ideal solution here.

**Comment by homeyer** [comment]
that would be ideal, we haven't seen any published when that happens. I'll reach out to github support with the idea at least.

**Comment by cabloo** [comment]
Thanks! That seems like something they should really have.
