### ISSUE TITLE
More github links

### ISSUE THREAD

**Issue by roll** [waffleio/waffle.io#1898]
It will be great to have more easy accessible links to github. For example:

![2](https://cloud.githubusercontent.com/assets/557395/7469838/1ff9ce94-f318-11e4-9ed7-50526f4255d2.png)

![3](https://cloud.githubusercontent.com/assets/557395/7469916/eb735806-f318-11e4-990b-15c1c03af284.png)

**use C-Click instead**
![1](https://cloud.githubusercontent.com/assets/557395/7469841/22a7097c-f318-11e4-8afe-889086ae80d3.png)

size: 0.5 :bowtie: time-to-save: priceless

**Comment by homeyer** [comment]
@roll, did you know you can command-click the number to open a new window with the issue from GitHub?

**Comment by roll** [comment]
@homeyer, no I had no idea, thanks. Do you have any magic to get github issues main page in one click?)

**Comment by homeyer** [comment]
Nope, no hidden command-click for that one :)

**Comment by marydavis** [comment]
@roll another is you can command-click the 'add issue' button to open the GitHub new issue page in new window :)

**Comment by roll** [comment]
Thanks. But I still think more links (issues, prs, labels, milestones) will be helpful ;)
