### ISSUE TITLE
Waffle doesn't give an option to add new milestone

### ISSUE THREAD

**Issue by shubhamchaudhary** [waffleio/waffle.io#1900]
Steps to reproduce:
I enter new milestone string in _"Select a milestone for this issue"_ textbox

Nothing happens

Desired behaviour:
An option to add new milestone appears

**Comment by CodeMan99** [comment]
duplicate of #1883?

**Comment by AndyWendt** [comment]
I would say it is a duplicate.  That is the intended behaviour I am looking for.

**Comment by kellihsf** [comment]
You can now create milestones within Waffle! Read about it here: [Waffle Help Docs](https://help.waffle.io/faq/labels-and-milestones/how-do-i-create-a-new-milestone-in-waffle)
