### ISSUE TITLE
hooks are not being enabled for newly Waffle'd non-org repositories

### ISSUE THREAD

**Issue by ashumz** [waffleio/waffle.io#1903]
current behavior: when a collaborator or a non-org repo Waffles the repo for which they are a collaborator, hooks are not being enabled. 

expected behavior: when a collaborator logs in to a non-organization repository for the first time, hooks should be enabled.

**Comment by homeyer** [comment]
at this point, only the owner can create hooks. emailed github support, we'll see what they say.
