### ISSUE TITLE
Make waffle card urls bound to the GH issue number

### ISSUE THREAD

**Issue by elia** [waffleio/waffle.io#1904]
That would be really convenient as the urls would become really predictable.

There's probably the case of multirepo boards which could maybe use an id in the form of <repo-name>-<issue-id> or fallback to the current system (which I suppose are the internal db ids)

**Comment by niemela** [comment]
+1

**Comment by kellihsf** [comment]
closing as a duplicate of [#1694](https://waffle.io/waffleio/waffle.io/cards/54b421ab579e3b020011ef95)
