### ISSUE TITLE
Use shields.io for the waffle badge

### ISSUE THREAD

**Issue by JWGmeligMeyling** [waffleio/waffle.io#1905]
Use shields.io for the waffle badge. For consistency with other badges.

**Comment by lotyrin** [comment]
Yes please. The current waffle badge is quite noticeably different from any other badges.

**Comment by AlicanC** [comment]
:+1:

This is driving me crazy:
![](https://www.evernote.com/shard/s606/sh/3d66bc9b-1e43-43ee-92d2-a5b8ac1691c4/80da1cd0d7e90704/res/1aecc653-a452-4abe-be1a-a3d65f3c78fe/skitch.png)

**Comment by Gabriel-p** [comment]
+1

**Comment by lexi-lambda** [comment]
:+1:

**Comment by theonlylawislove** [comment]
+1

When will this be completed? It sticks out like a sore thumb!

**Comment by mcoffin** [comment]
I would also really love this. It's getting quite annoying on a few of my projects. It's especially weird because the waffle badge has a noticeably different height, not just texture / padding / etc.

**Comment by bourdeau** [comment]
+1
Tried to `?style=flat` it without success... :(

**Comment by laughedelic** [comment]
+1

**Comment by fluky** [comment]
+++++1

**Comment by mnuessler** [comment]
Yes, please implement this! The current badge can hardly be used in combination with other badges.

**Comment by cireficc** [comment]
👍

**Comment by endrebak** [comment]
This should be so easy to fix!

**Comment by homeyer** [comment]
Thanks to @evancohen, Waffle has shields.io support for badges!

If you’d like to use a shields badge for Waffle, use the pattern `https://img.shields.io/waffle/label/:owner/:repo/:label.svg`. This currently only works for public boards, and doesn’t support the backlog or done columns.

Here’s what a badge for Waffle’s “current iteration” column looks like: 
![badge](https://img.shields.io/waffle/label/waffleio/waffle.io/current%20iteration.svg)

The color of the badge matches the label’s color in GitHub (sweet!).

A few other style options are available, like a flat square version: 
![flat badge](https://img.shields.io/waffle/label/waffleio/waffle.io/idea.svg?style=flat-square)

Just append `?style=flat-square` to the URL. All of the style options are defined here: http://shields.io/#styles

We’re prioritizing some additional badge enhancements, tracked on this milestone: https://github.com/waffleio/waffle.io/milestone/107

**Comment by evancohen** [comment]
You can also use `?label=some%20text` to customize the text on the left.
For instance, you could change "current iteration" to "this iteration"

![test](https://img.shields.io/waffle/label/waffleio/waffle.io/current%20iteration.svg?label=this%20iteration)
