### ISSUE TITLE
Auto tracking branch names containing slashes

### ISSUE THREAD

**Issue by jodastephen** [waffleio/waffle.io#1906]
The branch name `topic/my-work-#80` should automatically transition issue `#80` in the main repo, not try to find repo "topic".

Issue #1686 was closed as won't fix. This issue exists to try and figure out a solution. The current approach makes the rare case of referencing another repo in a branch name the default, while preventing the common case of slash separated branch names (which anecdotal evidence indicates is the most common git naming convention).

There would appear to be a number of options here:

1) A configurable setting per repo to determine how to interpret slash separated branch names, either as cross-repo or single repo.

2) A configurable set of prefixes, probably defining the related repos that should be recognised as cross-repo, with everything else being single-repo.

3) A configurable set of prefixes, determining which issues should be single-repo, instead of cross-repo.

4) Something else...

The proposed workaround of using hyphen instead of slash in branch names is not sensible, simply because it goes against the predominant naming conventions in git. An actual solution is needed here, because this problem (bug) is going to keep on coming up as you gain users....

**Comment by ashumz** [comment]
Hi @jodastephen, 

Thanks for taking the time to make these suggestions and make some really great points. We've removed the wontfix label and will reference this issue as a supporting +1. Do you mind if I close this as a duplicate, as we will have your comments referenced through the open issue, #1686?

Ashley

**Comment by jodastephen** [comment]
Fine to close as duplicate now won't fix is removed. Thanks for the response.

**Comment by ashumz** [comment]
Hi @jodastephen, 

I wanted to let you know that adding the issue number first, with a dash afterwards, will work: 133-feature/notifications

Would this work for you? 

Best, 

Ashley
