### ISSUE TITLE
Investigate: Intercom messages reported to not show properly in Chrome

### ISSUE THREAD

**Issue by ashumz** [waffleio/waffle.io#1908]
Steps to replicate: 
1. duplicate the welcome message and private repo message
2. send to self 
3. view board in Chrome

Expected behavior: 
All appears as normal and each message's text appears properly

Report from [user](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/ashley@waffle.io/conversations/876537342):

"In the bar on the right I see 3 message previews from you. There are a couple lines of text in each preview so I know something is there. If I click into one of the previews then a larger chat Window shows up with nothing in it except your small circular picture; no text.

I'm using Chrome Version 42.0.2311.135 (64-bit) on OSX 10.10.3"

**Comment by ashumz** [comment]
![https://cloudup.com/ct9dw5YFYkX]

**Comment by ashumz** [comment]
![screen shot 2015-05-05 at 9 07 14 am](https://cloud.githubusercontent.com/assets/100216/7636005/257b9f0c-fa32-11e4-97c3-2a10ee76005d.png)

**Comment by homeyer** [comment]
Intercom says they only support non-beta browsers, we're at their mercy on this one :)
