### ISSUE TITLE
ability to configure time frame for throughput graph (by day, monday-monday, etc)

### ISSUE THREAD

**Issue by ashumz** [waffleio/waffle.io#1909]
[requested by user](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/882129464)
"My team would love to see this on the metrics page: Throughput by day in addition to by week, so we can compare week-over-week."

**Comment by bgvo** [comment]
+1

**Comment by songawee** [comment]
This issue has been resolved by the new throughput graph released in WaffleMetrics - http://blog.waffle.io/wafflemetrics/. With the new graph, you are able to specify what start date you would like and it counts up from there.
