### ISSUE TITLE
Refine how automatic work tracking works: defaults, credentials, configuring user for automated actions

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#1915]
For example, when a PR is opened, we assign the "In Progress" label. Today, Waffle determines which user to make that modification as using this logic:
1. If the user who opened the PR is a waffle user, and we have a valid token for them, we assign the label using that user.
2. Otherwise, we grab the first user on the team that we find who has a valid token.

This issue is to let the user we take action as to be configured. Most likely only for the second situation, since the first usually doesn't cause confusion.

Adding to this: 
In the case that a collaborator Waffles a repo to test things out, we need safe defaults. 

Option 1
- prompt users with the option to set up automatic work tracking in columns once the first branch is pushed or pull request is issued for their user. (also add to onboarding message.)
- defaults are set to backlog for all newly created projects 

Option 2
- only move work for team members on the project 
  Downside: could get confusing since it is introducing suggested workflow around PR's (ie: moving them "In Progress") that may or may not be a part of team working agreements. Users might not know how to turn this off easily and revoke access to Waffle out of frustration. 

Next step for option 1 OR 2: 
After project creation, add ability to choose the user you want to have automatic actions assigned to. Have the option to select our "waffle-iron" user to let users know that automatic movement of work exists. Keep the automatic prompted messages to remind users when they push branches or issue PR's that they can configure automatic work tracking options at any time in Settings->Columns
## 

Update 8/31: 
The most painful problem seems to be the automatic assignment of issues to the person for which we have credentials. If we don't have a credential for the person, we should not auto-assign the issue. 

We could still auto-move work with the credential, but as far as assigning, that should either be:
- stopped completely for now or
- stopped for work we move on behalf of someone else's credential 

Unwanted behavior from autoassignment using other people's credentials: 
- incorrect notification emails for assignment (potentially for every issue referenced by a closing/fixes/resolves PR in a repo -- a common workflow convention for teams.) 
- all of these issues that qualify for the above appear in github as assigned to the first person we have a credential for -- which is clearly not intended behavior 

not as big of a deal (because it doesn't result in unwanted/incorrect emails or incorrect issue assignment): 
- incorrect github history

**Comment by jguarShark** [comment]
+1

**Comment by homeyer** [comment]
wafflebot to the rescue! checkout out bot.waffle.io for our fix.
