### ISSUE TITLE
No 'Access-Control-Allow-Origin' bug

### ISSUE THREAD

**Issue by epicleptico** [waffleio/waffle.io#1921]
While accessing a private repo through application we are retrieving the following error

```
XMLHttpRequest cannot load https://api.waffle.io/xilonsolutions/siweb2/cards. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://waffle.io' is therefore not allowed access. The response had HTTP status code 503.
```

user-agent: *Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.152 Safari/537.36*

Google chrome Version:  42.0.2311.152 m

**Comment by braisdesousa** [comment]
Same Here

**Comment by homeyer** [comment]
Can you see if logging out and logging back in fixes it?

**Comment by epicleptico** [comment]
i tryed and nothing happens.

Also tested with Firefox and IE 10 and same error.

Seems that the proper header is not set for a private repo (Tested with public repos and all works)

**Comment by homeyer** [comment]
We fixed the issue on our end, sorry about that!

**Comment by epicleptico** [comment]
thanks a lot !
