### ISSUE TITLE
scrolling collaborators by clicking scrollbar drags card

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#1925]
[customer reported](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/andrew@waffle.io/conversations/886659803).

To reproduce, in FF, have a list of collaborators that requires you to scroll. Grab the scrollbar with your mouse, moving it will move the card.

**Comment by marydavis** [comment]
can not reproduce
