### ISSUE TITLE
drag ordering does not work when moving up

### ISSUE THREAD

**Issue by bradyholt** [waffleio/waffle.io#1926]
When dragging an item from higher to lower position, it saves correctly.  If you drag an item from lower to higher position, it does not save and reverts on next refresh.

**Comment by marleypetro** [comment]
+1

**Comment by mackermedia** [comment]
+1

**Comment by aruehlen** [comment]
+1

**Comment by jsucher** [comment]
+1

**Comment by kellihsf** [comment]
tried to reproduce this, looks like it's been resolved :)
