### ISSUE TITLE
Add label directly from the board

### ISSUE THREAD

**Issue by cmilr** [waffleio/waffle.io#1928]
It would be nice to be able to add labels to cards directly from the board, instead of having to click through to the card.

**Comment by PatrickDattilio** [comment]
+1
A dropdown (like assigning a user) in the bottom left corner  would be perfect

**Comment by cbobbett** [comment]
+1. 
I want to change a label assignment as easily as I can change sizing (directly from card on board).

**Comment by zbjornson** [comment]
+1

**Comment by sibson** [comment]
+1

**Comment by lindenle** [comment]
:+1: I would also like to see the ability to add the label to all repos for a board that spans multiple repos.

**Comment by shaharmor** [comment]
+1

**Comment by kellihsf** [comment]
closing as duplicate of [#625](https://waffle.io/waffleio/waffle.io/cards/53440db124ceb40200d90f5c)
