### ISSUE TITLE
As a User I want to have an integrated view of all my repositories

### ISSUE THREAD

**Issue by dimus** [waffleio/waffle.io#1930]
I have several repositories on which I work simultaneously. When I plan my iteration it is very cumbersome as all the tickets are spread all over the repos. It would be very useful for me to have an integrated view where all my issues appear at the same time, and I can see my iteration much more clear

**Comment by OwenBrotherwood** [comment]
I deceided that my own mult-repo hell could be solved if I created one repo to hold the issues of all repos (a bit like this).
I made an organisation (but a user's forks or own work is ok).
I reference up and down stream issues in an issue. An issue can be a story or a collection of stories (a novel).

This being said :+1: to the issue as it could help many I believe

( https://github.com/sloopback/sloopback-issues/wiki )

---

Just a comment from another waffle.io user
