### ISSUE TITLE
automatic functions for issues and pr's

### ISSUE THREAD

**Issue by OwenBrotherwood** [waffleio/waffle.io#1931]
If one has a public repo, issues and pr's become hard to manage.
Allow for automatic lock on issue or pr creation.(easy one)
Allow for only members of a Github Organisation/ User to create issues and pr's (hard one)

To allow an Organisation to take in issues, but to control how many more +1 comments etc are allowed before an issue is taged and given summary to define a story that can be given a clearer first "comment" if needed or a new issue (or issues if multiple user stories)

Can help to reduce backlog as, before one knows it, an issue can become long before someone has time to read the issue (and then, if long, the issue becomes longer to read

---

https://github.com/sloopback/sloopback-issues/wiki

**Comment by kellihsf** [comment]
We haven't seen any activity on this card since it was opened from the rest of the Waffle user base. We are closing it for now as we prioritize and work on other more highly requested features/integrations. Thank you! :)
