### ISSUE TITLE
Label "in progress" persists if ticket is closed by git comment

### ISSUE THREAD

**Issue by dimus** [waffleio/waffle.io#1932]
If an issue is closed by adding a comment like "Close #443" the issue moves to the Done bucket correctly, but its "in progress" label does not dissapear

**Comment by skotzko** [comment]
Saw something similar today while setting up a board. We had 2 issues that were closed on GitHub about 2 months ago, but still had their `in progress` labels attached. Even though they were long-closed, they were still sitting in the `In Progress` column. Shouldn't have been seen at all.

**Comment by kellihsf** [comment]
i believe this is resolved, unable to reproduce
