### ISSUE TITLE
[investigate] automatic work tracking not working for newly created projects

### ISSUE THREAD

**Issue by ashumz** [waffleio/waffle.io#1934]
I am able to move work in progress with branch names and move cards to review on existing repos, but when I create a new repository, neither action happens in real time.

A user reported this here[https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/916758371]

**Comment by homeyer** [comment]
[support case](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/andrew@waffle.io/conversations/919344643)

**Comment by wjblair235** [comment]
[support case](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/conversation/916421009)

**Comment by wjblair235** [comment]
[support case](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/conversation/921517188)
