### ISSUE TITLE
Prevent duplicate projects from being created

### ISSUE THREAD

**Issue by burtonjc** [waffleio/waffle.io#1938]
mongoose unique index on `project.name`, as a migration that also removes the 60 dupes in prod. reference [this post](http://blog.mongolab.com/2014/03/finding-duplicate-keys-with-the-mongodb-aggregation-framework/)

**Comment by burtonjc** [comment]
I'm not doing an index or cleaning up the dups. Instead, I am just doing a check in code before we create a project to make sure there isn't already one for that repo.

**Comment by meghapg** [comment]
hi
