### ISSUE TITLE
Allow multiple selections of repository sources

### ISSUE THREAD

**Issue by ksuderman** [waffleio/waffle.io#1948]
When configuring the sources (repositories) for a project I would like to have a checkbox beside each GitHub repository so I can add more than one at a time.  Ideally there will also be a textfield for the display name to be used.  This view/page should be the default anytime I want to configure my project's sources.

**Comment by ashumz** [comment]
Hi @ksuderman, 

We're now tracking this on #1590 - closing this one out as a duplicate, but please feel free to follow the progress on that card. I'll add your comments about the text field on adding of sources, too! 

Ashley
