### ISSUE TITLE
Gerrit integration

### ISSUE THREAD

**Issue by mbulkeley** [waffleio/waffle.io#1953]

**Comment by mbulkeley** [comment]
+1

**Comment by aviau** [comment]
Our use case:

We use https://review.openstack.org/ and our repository is mirrored on https://github.com/stackforge/

**Comment by mc706** [comment]
+1

**Comment by kenperkins** [comment]
:+1: We do a bunch of work in both GitHub but also in OpenStack. Being able to have one aggregate view would be amazing for our dev team.

**Comment by kellihsf** [comment]
We haven't seen much activity on this card since it was opened from the rest of the Waffle user base. We are closing it for now as we prioritize and work on other more highly requested features/integrations. Thanks!
