### ISSUE TITLE
Assignee Management on Transition

### ISSUE THREAD

**Issue by travisstokes** [waffleio/waffle.io#1955]
Add two column settings:

1) Set actor as assignee - sets the current actor as the assignee when an issue is moved into the column
2) Clear assignee - removes the current assignee when an issue leaves the column

This will enable smoother transitions between lanes like Development and Testing where the collaborator will change.

**Comment by edhell** [comment]
+1 I would love to have it in waffle :)

**Comment by piether** [comment]
+1

**Comment by Glenndejaeger** [comment]
+1

**Comment by kellihsf** [comment]
We haven't seen much activity on this card since it was opened from the rest of the Waffle user base. We are closing it for now as we prioritize and work on other more highly requested features/integrations. Thank you!

**Comment by adamzolyak** [comment]
Could probably set up this up w/ Zapier.
