### ISSUE TITLE
Progress notify on gitter channel

### ISSUE THREAD

**Issue by vi4m** [waffleio/waffle.io#1961]
It would be fantastic to have a feature, to post on gitter channel some progressbar with current milestone progress. As a developer, i would like to avoid answering every time what's progress of the milestone

So, as I user on gitter channel i will see something like this:

```
(some talking on the public channel)
Milestone 1.0.3 updated:  Progress: [|||||          ]20%
(people cheers up)
```

every time i resolve issue.

**Comment by skotzko** [comment]
+1

**Comment by laughedelic** [comment]
+1

**Comment by kellihsf** [comment]
We haven't seen much activity on this from the rest of the Waffle user base. We are closing it for now as we prioritize and work on other more highly requested features/integrations. Thank you! :)
