### ISSUE TITLE
have the browser window title contain waffle

### ISSUE THREAD

**Issue by cpostma-rally** [waffleio/waffle.io#1971]
It'd be handy if the title for the window wasn't just groupname/repo-name because it conflicts with how GitHub names the windows. Could you add something like " - waffle" perhaps?
[from intercom](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/963999750)

**Comment by agorischek** [comment]
+1

**Comment by homeyer** [comment]
We're going to stick with just having the Waffle favicon distinguish Waffle vs GitHub for now.

**Comment by agorischek** [comment]
Just wanted to point out that Safari does not display favicons in the tab bar, so this design solution doesn't really solve the problem for everyone.
