### ISSUE TITLE
Sometimes, when adding comments in Waffle, 2 identical comments are created.

### ISSUE THREAD

**Issue by autra** [waffleio/waffle.io#1975]
I unfortunately don't have any clear reproducing steps. It usually happens with long comments: when I click on comment, it adds 2 comments instead of one (they also appear in the waffle card detail).

That might not be a waffle bug though

**Comment by kellihsf** [comment]
hi  @autra,

We believe this issue is resolved. If you're still experiencing  this behavior please let us know or open a new issue on our board. Thanks!
