### ISSUE TITLE
show unread comments badge on cards

### ISSUE THREAD

**Issue by michielibiza** [waffleio/waffle.io#1977]
I would like to see on the board which issues have unread comments and mentions

**Comment by ashumz** [comment]
Hi @michielibiza, 

Thanks for the request! Is it important for you to see issues unread by you, or unread by any team member?  Can you elaborate on how often you would use this feature and how it would help you and/or your team?

Thanks! :)

Ashley

**Comment by crisbit** [comment]
+1
I too would like to see on the board which issues are unread by me. I'd use this every time I look on the board after finishing fixing an issue, so I know at a glance where I'm needed next.

**Comment by kellihsf** [comment]
related to [#2444](https://github.com/waffleio/waffle.io/issues/2444)
