### ISSUE TITLE
Changed title not updated on the opened card

### ISSUE THREAD

**Issue by ehausen** [waffleio/waffle.io#1981]
- Change issue title on Github
- Go to Waffle and find the same issue (it still has the old title)
- Open the issue card, the issue title on the mini card on the board will update
- Observe how the issue title on the opened card does not update

**Comment by kellihsf** [comment]
This is related to [#1652](https://waffle.io/waffleio/waffle.io/cards/548191877abdfe69dabb09f2), this issue will be closed as a duplicate.
