### ISSUE TITLE
Title change on Github is not synched automatically

### ISSUE THREAD

**Issue by ehausen** [waffleio/waffle.io#1982]
When changing the issue title on Github, is it not updated on Waffle before that issue card is opened

**Comment by ehausen** [comment]
The title seems to update, if you also do something else on Github, like add label, assignee, or comment. But if you only change the title on Github you have to open the card for the title to update on Huboard

**Comment by kellihsf** [comment]
Related to [#1652](https://waffle.io/waffleio/waffle.io/cards/548191877abdfe69dabb09f2), will close this as a duplicate.
