### ISSUE TITLE
autocreate project from the + button on the dashboard

### ISSUE THREAD

**Issue by ashumz** [waffleio/waffle.io#1985]
we've received feedback from several users that they expect the project to automatically create when taking the action from the dashboard. 
- [x] When  a user deliberately adds a board from the dashboard, we should create the project automatically 
- [ ] Continue to show banner when just navigating to boards that don't have projects created yet.

**Comment by nokout** [comment]
:+1:

**Comment by brentrobbins** [comment]
+1
