### ISSUE TITLE
brainstorm different ways we can notify users to create projects

### ISSUE THREAD

**Issue by ashumz** [waffleio/waffle.io#1987]
Currently users are able to create issues prior to clicking "Create Project." This causes a confusing experience because it appears like Waffle has created the project, but they actually still need to hit "Create Project" in the blue banner. 

2 options: 

- [x] Move banner to top of page so it is more obvious 
- [ ] Grey out Add Issue button until project is created

Ideal solution involves doing both :)

**Comment by homeyer** [comment]
instead, let's disable the add issue button if you can create the project (you won't see the banner if you can't), with a tooltip that tells you to create the project.

**Comment by homeyer** [comment]
action:
 - [ ] design potential options, get agreement with our team, and then show a few users

**Comment by ashumz** [comment]
see also #1985

**Comment by marydavis** [comment]
blocked: should we look into/fix the banner showing up when it shouldn't first?
