### ISSUE TITLE
Move issue to column according to build status

### ISSUE THREAD

**Issue by thedrow** [waffleio/waffle.io#2008]
Having a column that is called "ready for merge/review" (or something else) that pull requests are automatically moved to when the build is sucessful and a column that moves issues back to in progress when the build fails sounds like a good idea.
Any thoughts on this feature request?

**Comment by jackfirth** [comment]
+1, I opened a similar one (#2000)

**Comment by ryansch** [comment]
:+1:

**Comment by laughedelic** [comment]
+1

**Comment by homeyer** [comment]
We've shipped seeing build statuses on cards directly:

![image](https://user-images.githubusercontent.com/84629/33460453-6b2ef520-d5eb-11e7-8787-09cd3a01c3d4.png)

We don't have plans to move cards based on builds passing failing, instead opting towards making it visible so you can keep work as "in progress" or "review".
