### ISSUE TITLE
Issue activity feed.

### ISSUE THREAD

**Issue by Illizian** [waffleio/waffle.io#2010]
Include a log of actions within the Card. (e.g. When a PR is opened and a card is moved to in progress log a link to the Pull Request)

**Comment by JWGmeligMeyling** [comment]
:+1: 
(The title `git log` may be confused with the actual `git log` command output, which gives commit info. I think it should be something like *issue activity feed*.

**Comment by Illizian** [comment]
:+1: agreed - I will edit the title!

**Comment by alrz** [comment]
+1

**Comment by kellihsf** [comment]
We haven't seen much activity on this card since it was opened from the rest of the Waffle user base. We are closing it for now as we prioritize and work on other more highly requested features/integrations. Thank you!
