### ISSUE TITLE
columns show incorrect counts when PRs are attached to issues

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#2012]
[intercom](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/1005955949)

**Comment by homeyer** [comment]
Broken on initial load, fixed after filtering and clearing the filter.

**Comment by skotzko** [comment]
+1

**Comment by ashumz** [comment]
@skotzko are you still seeing this issue? It appears to be fixed on our end but just checking to be sure. 

Ashley
