### ISSUE TITLE
badge should show count of issues across all repos - connects to #3288

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#2019]
the badge only works for the primary repo, does not count cards across repos on multirepo boards.

**Comment by skotzko** [comment]
+1

**Comment by sils1297** [comment]
+1

**Comment by mcqueary** [comment]
This is my primary use case, as I am managing something like 21 repos currently. I use one "meta-repo" [nats-io/roadmap](http://github.com/nats-io/roadmap) as the root of my waffle board. While some things are reported in aggregate (throughput graph, yay!), having the badges count cards across repos would be some very tasty syrup!

**Comment by Alisuehobbs** [comment]
Great news! We've updated our badge to be customizable with all columns. Check out our help doc for instructions on how to get the new badge and let us know what you think!

 https://help.waffle.io/faq/github-badge/where-can-i-find-the-code-for-my-github-readme-badge
