### ISSUE TITLE
Unable to access board

### ISSUE THREAD

**Issue by theganyo** [waffleio/waffle.io#2022]
I'm unable to open or even open the configuration of my 2nd board.

**Comment by theganyo** [comment]
I should clarify: The main repo is gone... but I'm unable to access the board config to delete it.

**Comment by homeyer** [comment]
Hey @theganyo, what's the name of the repo? I'll handle deleting it for you.

**Comment by theganyo** [comment]
"theganyo/swagger-node"

Thanks!

**Comment by homeyer** [comment]
done :)
