### ISSUE TITLE
Change the name of a board (esp. if it includes multiple repos)

### ISSUE THREAD

**Issue by marcoherbst** [waffleio/waffle.io#2023]

**Comment by Kmaschta** [comment]
+1

**Comment by JLOWinje** [comment]
+1

**Comment by nokout** [comment]
:+1:

**Comment by pib** [comment]
:+1:

**Comment by kellihsf** [comment]
Renaming is now supported. :) You'll just go to Settings->Sources and click on the pencil icon and enter the new display name. Once you've renamed a board, you'll see the name change on the drop down menu of the repo selection, the tab for that repo, and anywhere the repo is mentioned. (the actual URL will not change though)
