### ISSUE TITLE
Badge snippets nowhere to be found

### ISSUE THREAD

**Issue by ManeBit** [waffleio/waffle.io#2025]
As listed in the Waffle FAQ, https://github.com/waffleio/waffle.io/wiki/FAQs#github-badge-1

Badge snippets/examples are supposed to be generated and shown on the general tab within the settings screen.

**Comment by marydavis** [comment]
@ManeBit currently badges are only available for public repos, this may be the issue you are running into. We have an issue for making badges for private repos here: https://waffle.io/waffleio/waffle.io/cards/53440db224ceb40200d90faa

**Comment by ManeBit** [comment]
Ah, that sounds like my problem. Are there plans to provide support for private repos? It's definitely a handy tool to remind teams of their waffle integration. It's also great for turning the readme.md into a sort of 'progress dashboard'

**Comment by marydavis** [comment]
We hope to, but it is not yet prioritized to be worked on. You can follow that issue to be notified when dev work begins on it :)
