### ISSUE TITLE
"Could not save card" error

### ISSUE THREAD

**Issue by ezra-g** [waffleio/waffle.io#2029]
We did a test run using Waffle.io for sprint planning on a ~6 person team and got some intermittent "Could not save card" errors. Are there any specific guidelines or expectations around how many browsers can concurrently edit cards in a Waffle board?

Potentially related factor: Our Waffle board is connected to 2 repos and during planning we connected to a third repo.

In the screenshot we also have a duplicated "type: feature" label displaying in the UI on a separate card. The label is no longer duplicated.

![pasted_image_7_27_15__11_11_am](https://cloud.githubusercontent.com/assets/349595/8909800/59265f28-3451-11e5-992e-7f96f9996a7d.jpg)

**Comment by ezra-g** [comment]
Possibly related to https://github.com/waffleio/waffle.io/issues/1307.

**Comment by kellihsf** [comment]
hi @ezra-g,

We believe this to be resolved, so we're closing the issue. If you experience this behavior again, please let us know or open a new issue on our board. :) Thanks!
