### ISSUE TITLE
Sharing or bookmarking a link with a filter already in place does not work when accessed later

### ISSUE THREAD

**Issue by bwarner22** [waffleio/waffle.io#2031]
I have a board and have added a filter to that board. I'd like to save that state to come back to quickly at a later and to my team member. However, sharing that url link defaults to the board without the filter.

**Comment by kellihsf** [comment]
hi @bwarner22,

We believe this issue is now resolved. If you see the same behavior please let us know or open a new issue on our board. Thanks! :)
