### ISSUE TITLE
Image Attachments

### ISSUE THREAD

**Issue by dudewheresmycode** [waffleio/waffle.io#2040]
Would be awesome to have the ability to include an image with a new issue or comment. Right now it's the only thing my QA team is having to still do from Github issues.

We have a QA team that only uses the issues part of Github. So I was happy when I found waffle for them. Much easier interface for them to navigate and report issues. But images are still a training challenge.

**Comment by homeyer** [comment]
Hey @dudewheresmycode, going to close this in favor of #846, would you mind moving your comment there?
