### ISSUE TITLE
One of my boards disappeared

### ISSUE THREAD

**Issue by ondrae** [waffleio/waffle.io#2042]
I have been using https://waffle.io/codeforamerica/networkplatform for about a month. It disappeared today!

I visited the waffle url and it asked me to "Create the project". Before doing that, I checked and the github repo still existed.

I use this waffle with a bunch of other repos added as sources. Several of those sources are private repos.

I noticed the other day you switched Github auth permissions to only be for public repos. Did this cause my board to disappear?  I can't seem to re add the private repos.

**Comment by ondrae** [comment]
I'd like to give you access to my private repos again.

**Comment by homeyer** [comment]
Hey @ondrae, can you logout, go to the Waffle.io landing page, and login from there? You should be able to choose private repo scope from there.

**Comment by ondrae** [comment]
That worked. I'll rebuild my board now, thanks.

**Comment by homeyer** [comment]
@ondrae, is your board still missing after logging back in?
