### ISSUE TITLE
civic hackathon + Waffle

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#2043]
themes for NC census hackathon: Entrepreneurship and Social Good

Goals:
- [ ] create ideas for how to have a "Waffle toolkit" for enabling teams to be more effective at a civic hackathon

**Comment by homeyer** [comment]
start.waffle.io: An app on top of Waffle that introduces teams in the ideation/new project phase to a new way to organize work. Once you login with Waffle, you pick a repo from GitHub (or create one), and we customize your columns and pre-create a set of cards for you to start from.

The columns: Backlog, Frame, Build, Measure, Learn

The cards:
 - "Find a problem": How to write a problem definition, and run empathy interviews to find a problem. A task list for what to do.
- "Validate a problem": How to test a set of problem statements. A task list to do that, e.g., problem validation template with instructions on when to stop, when to iterate/pivot, etc.
- "Ideate on a solution": Design thinking divergence and convergence of ideas
- "Test a solution": Rapid MVP development and customer solution interviews
- "How to pitch"

**Comment by homeyer** [comment]
"Getting Started Guide" fork for open data initiatives

**Comment by ashumz** [comment]
moved to waffleio/hackathons#2
