### ISSUE TITLE
if you authorize waffle with your github account and don't have any repos of your own, dashboard keeps spinning with "no repos found" text

### ISSUE THREAD

**Issue by ashumz** [waffleio/waffle.io#2054]
Need to fix the spinning and also add a link to "Add a repository" linking to https://github.com/new

**Comment by ashumz** [comment]
![screen shot 2015-08-13 at 4 51 58 pm](https://cloud.githubusercontent.com/assets/100216/9261414/b5826d1a-41db-11e5-8a25-d6218c6a3858.png)

**Comment by ashumz** [comment]
Text should say: "No repos found. Add a repository in GitHub" with "add a repository in GitHub linking to github.com/new 

Ideally we could do this alongside the permissions work, and text could be "Upgrade your permissions or add a repository in GitHub" if scope==public

**Comment by ashumz** [comment]
Would also really love if we could just add a form for adding a repo through Waffle - it'd be mostly as a 'trial' for people. 

Another option is to have a public issues only demo board owned by a user "waffle-maker/demo" for instance, and use the add collaborator API call to add every user who signs up for Waffle as a collaborator on the board so they can add issues and move them around, and the board would automatically show up in their board list..

**Comment by burtonjc** [comment]
For whoever pulls this, if you are feeling eager, we should add a spinner to the projects container on the home page while projects are loading.

**Comment by burtonjc** [comment]
:+1:
