### ISSUE TITLE
Add time notion

### ISSUE THREAD

**Issue by VeroniqueMDFP** [waffleio/waffle.io#2058]
Hello,

Your tool is great!

However, I would need the notion of time is added (deadline).
Several date fields would be interesting to manage projects. For me, it would take three dates:
- Desired deadline by the customer
- Undertaking within the agency
- Actual delivery date
Thus, a project delivered late would appear in red.

More complex but very useful, if no period is specified desired, it would be nice to set the maximum time for completion of a task type.
Example: If a request with the "maintenance" label is open for more than two months, this task automatically appears in black.

Thank you for this great tool!

**Comment by gavinrogers** [comment]
see #1826

**Comment by kellihsf** [comment]
hi @VeroniqueMDFP,

Thanks for the request! We're already tracking this feature on [#1826](https://github.com/waffleio/waffle.io/issues/1826), so we'll close this out as a duplicate. Thanks!
