### ISSUE TITLE
Some PRs not connecting appropriately

### ISSUE THREAD

**Issue by burtonjc** [waffleio/waffle.io#2059]
[intercom conversation](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/jacob@waffle.io/conversations/1098816276)

**Comment by ashumz** [comment]
Responded to original Intercom message to see if this is still an issue for this user. Potentially will be fixed with new board changes if it is a syncing or duplicate issue still
