### ISSUE TITLE
setup blog SEO

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#2061]

**Comment by marydavis** [comment]
nice to have:
- [ ] put all posts in a category so we no longer have 'uncategorized'

**Comment by homeyer** [comment]
to preserve old links to us, we need to redirect date-style permalinks to the new permalinks. Maybe there's a wordpress plugin?

**Comment by marydavis** [comment]
installed 'Quick Page/Post Redirect Plugin' which might do the trick

**Comment by homeyer** [comment]
got it working with "Redirection" plugin, Quick Page didn't support regex
