### ISSUE TITLE
Ability to add more than one repo to a board

### ISSUE THREAD

**Issue by mal** [waffleio/waffle.io#2062]
Currently trying to fight our way off Assembla, and this is one of the main wants from the management team so they can have an overview of all ongoing work.

**Comment by mal** [comment]
Typical. Found the FAQ section right after posting.

![](http://rs895.pbsrc.com/albums/ac159/GIFsforhire/Facepalm/facepalm.gif~c200)

**Comment by homeyer** [comment]
![image](https://cloud.githubusercontent.com/assets/84629/9411870/ead0b05c-47e5-11e5-87a4-bd5675dead43.png)
