### ISSUE TITLE
Support: Waffle fails to add webhook to private repo (support#35)

### ISSUE THREAD

**Issue by colindownes** [waffleio/waffle.io#2066]
When I log in to waffle as my private repo owner, waffle tries to add a webhook but the address bar shows https://waffle.io/github-callback?code=blah&state=blah and the browser window just says 'Internal Server Error' is there a way to fix this, or to manually add the webhook? 

We did previously have the webhook working so it could be an issue with adding it a second time? 

If I log in as a collaborator waffle works fine, however the updates dont get pushed through.

**Comment by ashumz** [comment]
Hi @colindownes, 

Apologies that we didn't get to this sooner. Have you been able to add the webhook and get everything working properly? We're happy to help if you are still having issues. 

Cheers, 

Ashley

**Comment by colindownes** [comment]
hi @ashumz I still get an internal server error every time I login to waffle as the private repo owner as described above. When I log in as a collaborator, I get the waffle board but I think that the webhook isnt functioning correctly (if issues are updated by others they dont auto update on the board as they used to).
Let me know if there is anything I can do to manually rectify. Thanks!

**Comment by ashumz** [comment]
Hi @colindownes - would you mind revoking access to Waffle from your private repo owner account and then reauthorizing (by logging out and back in, and authorizing GitHub)? Also, can you email the repository name and whether or not it is an organizational account to support@waffle.io? (So we don't leave any identifying information in this public issue, if you prefer.) 

Thanks! 

Ashley

**Comment by ashumz** [comment]
(The problem you're running into might be because Waffle is authorized at the org level, but not at the personal level, or vice versa.)

**Comment by colindownes** [comment]
I did revoke the waffle access and I think its when I log back into waffle it is trying to add the webhook and that is where its failing. I will email the repo name through. Thanks.
