### ISSUE TITLE
Handle removing users from the project team when a project's primary repository is no longer accessible for that user in GitHub

### ISSUE THREAD

**Issue by ymmyk** [waffleio/waffle.io#2070]

**Comment by Linuturk** [comment]
:+1: experiencing this as well.

**Comment by homeyer** [comment]
**Acceptance Criteria**
- [ ] a deleted repo should either auto remove from Waffle, or at least allow the board to be removed from Waffle.

**Comment by ymmyk** [comment]
I should add that my experience isn't a deleted repo, but a private repo I not longer have access to (switched companies).

**Comment by homeyer** [comment]
Oh thanks, created #2258 for deleted repo.

**Comment by homeyer** [comment]
this has been fixed for a while, just lost tracking on this issue!
