### ISSUE TITLE
Repo name gets truncated prematurely

### ISSUE THREAD

**Issue by danielcompton** [waffleio/waffle.io#2082]
![screenshot of safari 8-09-15 5 55 26 pm](https://cloud.githubusercontent.com/assets/811954/9727406/d8aa808a-5652-11e5-84da-c0edb4691f67.png)

It's frustrating that the repo name gets truncated prematurely when there is still plenty of space for the name to stretch out in. Could you expand the amount of space a title can fit in?

**Comment by htmlguy** [comment]
+1

**Comment by debdoop** [comment]
+1 (My organisation use a waffle board for several repos and I can only see the name of the organisation at the moment.) :)

**Comment by homeyer** [comment]
In the project settings, you can change the display name for each repo, to something that fits on the card.

Click the gear to get to the project settings, then under "Sources" click the pencil icon to edit the display name.

**Comment by danielcompton** [comment]
While this is a nice workaround, it's not actually fixing the problem. There's a lot of room left on the card.

**Comment by debdoop** [comment]
Ace thanks! I didn't see this 👍
