### ISSUE TITLE
add issue with column label

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#2083]
When creating a new issue, you should be able to select which column it ends up in.

**Acceptance Criteria**
- [ ] in the add issue menu, show a dropdown to select a column (by column name) for the issue to go to.
- [ ] dropdown is below "Select Labels" 
- [ ] when created, the issue is given the github label for the column
- [ ] the selection persists for the next time you use the add issue menu, like the assignee dropdown
- [ ] don't default to anything, to support the case where there's no inbox column (a new issue won't appear on the board)

[customer requested](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/1140715599).

**Comment by sandcastle** [comment]
:thumbsup:

**Comment by thomasknoll** [comment]
+1

**Comment by WanderingMatt** [comment]
Absolutely. We often file things that we want to immediately put In Progress. Currently, we have to file them, find them in the backlog, and drag them to In Progress.

Alternatively to exposing the labels, you could consider having an "Add Issue" action in each column. That way, you can keep the column labels hidden during creation, but we can still file an issue that immediately gets placed in a particular column.

**Comment by BAMason** [comment]
This is live now, let us know what you think!
