### ISSUE TITLE
update marketing page(s) to link to takeout

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#2089]

**Comment by marydavis** [comment]
- [ ] toggle

**Comment by marydavis** [comment]
are you thinking of a header link like Enterprise, a section on the main landing page, or part of our Enterprise page?

**Comment by marydavis** [comment]
nvm

**Comment by homeyer** [comment]
- [ ] enterprise link opens a new tab for takeout.waffle.io.
- [ ] keep the old enterprise page code, but remove the route to it (so you can't navigate to it)

**Comment by homeyer** [comment]
- [ ] add a block of content for takeout on the landing page
