### ISSUE TITLE
New avatars for about page

### ISSUE THREAD

**Issue by marydavis** [waffleio/waffle.io#2091]
if you don't want your github avatar used then please submit pic

**Comment by ashumz** [comment]
may also want to update language around we work for rally software also

**Comment by homeyer** [comment]
![andrew](https://cloud.githubusercontent.com/assets/84629/12902989/b28bff12-ce81-11e5-81b4-d5576fc090b7.jpg)
![jacob](https://cloud.githubusercontent.com/assets/84629/12902990/b29b4aee-ce81-11e5-8809-fc40b50787c0.jpg)
![kelli](https://cloud.githubusercontent.com/assets/84629/12902992/b2a1597a-ce81-11e5-87c2-bed0f9e82a57.jpg)
![ashley](https://cloud.githubusercontent.com/assets/84629/12902993/b2a1926e-ce81-11e5-8755-f724c3f7e5f6.jpg)
![mary](https://cloud.githubusercontent.com/assets/84629/12902991/b29f549a-ce81-11e5-8a0b-5d49ec54dcbb.jpg)
![nick](https://cloud.githubusercontent.com/assets/84629/12902999/bfc8c16a-ce81-11e5-981f-d0056c464f64.jpg)

**Comment by marydavis** [comment]
need to update with new pics of @ashumz and @marydavis

**Comment by ashumz** [comment]
done! :) fixed andrew's too. lol

**Comment by homeyer** [comment]
lol I just realized that IRL I don't have brown hair.
