### ISSUE TITLE
Pull request connected to issues appears twice in the DONE column

### ISSUE THREAD

**Issue by damienalexandre** [waffleio/waffle.io#2095]
From a week or so,
Pull requests connected to issues and merged appears twice in the DONE column in a project I'm working on.
We haven't change anything to our settings or anything.

I have 14 merged PR, appearing on top of the fixed issues. Here is a screenshot of my DONE column:

![screenshot from 2015-09-16 10 04 38](https://cloud.githubusercontent.com/assets/225704/9899486/794fb3f4-5c5a-11e5-92e5-d54749c3888f.png)

Previously the card for the PR 234 would have been hidden because it's connected to an issue.

Any idea?
Thanks!

**Comment by kellihsf** [comment]
hi @damienalexandre,

We believe this issue to be resolved. If you're still experiencing this behavior, please let us know or open a new issue on our board. Thanks! :)
