### ISSUE TITLE
Project board loads as blank page in Edge browser

### ISSUE THREAD

**Issue by stephenfuqua** [waffleio/waffle.io#2101]
The new Edge browser in Windows 10 loads a [project page](https://waffle.io/stephenfuqua/Tern) without user error - but does not display anything. F12 tool shows the following errors:

SCRIPT1006: Expected ')'
main.min.js (7,105973)

SCRIPT5022: [$injector:modulerr] http://errors.angularjs.org/1.2.27/$injector/modulerr?p0=waffle&p1=Error%3A%20%5B%24injector%3Anomod%5D%20http%3A%2F%2Ferrors.angularjs.org%2F1.2.27%2F%24injector%2Fnomod%3Fp0%3Dwaffle%0A%20%20%20at%20Anonymous%20function%20(https%3A%2F%2Fd2mzqhzagbaems.cloudfront.net%2Fvendor%2Fangular-1.2.27.min.js%3A20%3A488)%0A%20%20%20at%20Anonymous%20function%20(https%3A%2F%2Fd2mzqhzagbaems.cloudfront.net%2Fvendor%2Fangular-1.2.27.min.js%3A20%3A376)%0A%20%20%20at%20Anonymous%20function%20(https%3A%2F%2Fd2mzqhzagbaems.cloudfront.net%2Fvendor%2Fangular-1.2.27.min.js%3A33%3A265)%0A%20%20%20at%20r%20(https%3A%2F%2Fd2mzqhzagbaems.cloudfront.net%2Fvendor%2Fangular-1.2.27.min.js%3A7%3A288)%0A%20%20%20at%20e%20(https%3A%2F%2Fd2mzqhzagbaems.cloudfront.net%2Fvendor%2Fangular-1.2.27.min.js%3A33%3A207)%0A%20%20%20at%20ec%20(https%3A%2F%2Fd2mzqhzagbaems.cloudfront.net%2Fvendor%2Fangular-1.2.27.min.js%3A36%3A307)%0A%20%20%20at%20c%20(https%3A%2F%2Fd2mzqhzagbaems.cloudfront.net%2Fvendor%2Fangular-1.2.27.min.js%3A18%3A168)%0A%20%20%20at%20dc%20(https%3A%2F%2Fd2mzqhzagbaems.cloudfront.net%2Fvendor%2Fangular-1.2.27.min.js%3A18%3A380)%0A%20%20%20at%20Wc%20(https%3A%2F%2Fd2mzqhzagbaems.cloudfront.net%2Fvendor%2Fangular-1.2.27.min.js%3A17%3A415)%0A%20%20%20at%20Anonymous%20function%20(https%3A%2F%2Fd2mzqhzagbaems.cloudfront.net%2Fvendor%2Fangular-1.2.27.min.js%3A216%3A78)
Tern (29,13294)

Since I'm a Firefox user, this doesn't impact me personally. But it may impact some of my stakeholders who want to view the board.

**Comment by homeyer** [comment]
Thanks @stephenfuqua. Any idea if Edge is supported by Angular?

**Comment by stephenfuqua** [comment]
https://angularjs.org/ loads fine in Edge. Unfortunately I'm still a n00b with Angular, otherwise I would happily try to help debug.

**Comment by jtslear** [comment]
This no longer appears to be an issue. Closing.
