### ISSUE TITLE
Suggestion: Card source name title

### ISSUE THREAD

**Issue by James1x0** [waffleio/waffle.io#2102]
At a glance, it's hard to see what repo a card belongs to when working across multiple repos with the same org. If the org wasn't included in the card title, that would help, but even having the full text of the source on the card title as a `title` attribute would save me from having to click on the issue and hover over the issue # to see what url it points to.

Maybe there's an easier way, but for now it's fairly rough.

<img width="225" alt="screenshot at sep 22 09-40-05" src="https://cloud.githubusercontent.com/assets/6146261/10023180/f18e7866-610d-11e5-9cf2-97f89d6a3ed9.png">

P.S. Filters work fine, but for getting a quick look at issues, it's not worth pulling up a filter menu.

**Comment by homeyer** [comment]
Hey @James1x0, you can configured the display names for repos in your project settings to be something shorter. Can you try that?

**Comment by James1x0** [comment]
Excellent, never thought that configuring sources would include display names. It still would be nicer to have that title attribute so I could see longer display names.

**Comment by homeyer** [comment]
![image](https://cloud.githubusercontent.com/assets/84629/10053769/163957ac-61eb-11e5-96ad-f7db3b558405.png)

**Comment by James1x0** [comment]
My thought exactly.
