### ISSUE TITLE
Move issue card into lane based on connected PR label

### ISSUE THREAD

**Issue by tedgoddard** [waffleio/waffle.io#2103]
Having the PR card attached to the issue card is a great feature, and labels on the attached PR should affect which lane the combined card appears in. For instance if a PR has a "ready" label, it should not be necessary for the developer to apply a "ready" label to the associated issue, they should be able to just work on the PR, moving it through the required states.

**Comment by tedgoddard** [comment]
For instance, one strategy would be to base the card lane on the union of labels on the Issue and all attached PRs.

**Comment by ashumz** [comment]
Hi @tedgoddard - 

Thanks for your feedback on this! We're tracking a potential solution on #1622 and would love your feedback there if you have more after checking it out. :) Closing this out as a duplicate, but appreciate you taking the time to add your thoughts!
