### ISSUE TITLE
Show repository name in card detail view

### ISSUE THREAD

**Issue by adamralph** [waffleio/waffle.io#2104]
When viewing a Waffle board with multiple repos, the name of the repo on each card is shown in grey next to the issue number. When viewing the card detail, e.g. https://waffle.io/Org/Repo/cards/123456, the repo name is not shown anywhere.

**Comment by cicorias** [comment]
I'd suggest something visually like color, or label like, or icon

**Comment by adamralph** [comment]
That's fine as an extra, but the name of the repo is essential.

**Comment by jtslear** [comment]
The name of the repo is currently displayed on the top right of the card view.  

![2104 waffle io waffle io 2016-11-18 08-46-39](https://cloud.githubusercontent.com/assets/1965521/20432214/1d28c1c4-ad6c-11e6-8a5d-075367d6f218.png)

**Comment by adamralph** [comment]
thank you!
