### ISSUE TITLE
Permission to Github "Private Organization" not visible

### ISSUE THREAD

**Issue by huggi** [waffleio/waffle.io#2105]
Would like to start using my Github "Private Organization" which I granted access to waffle.io but I can't use/see it in my private waffle account, what's the issue, I don't see any restrictions yet :) ?

**Comment by homeyer** [comment]
Hey @huggi, can you make sure your organization has authorized Waffle? https://help.github.com/articles/requesting-organization-approval-for-your-authorized-applications/

**Comment by huggi** [comment]
Hmm, anything else than: Third-party access? The status there is already: Approved

**Comment by homeyer** [comment]
Any chance you see the option to upgrade your permissions when you open the project dropdown?

![image](https://cloud.githubusercontent.com/assets/84629/10092208/26a61d66-6301-11e5-82c0-12e382d6c65a.png)

**Comment by huggi** [comment]
Give me a sec :)

**Comment by huggi** [comment]
Hold on, I'll guess it's now in sync, is there any "waiting time" for that? I'm sure that was not there before, but I might be wrong :)

**Comment by huggi** [comment]
Ok. Whatever the reason is. It's solved for me, thanks for the instant support. Cheers!

**Comment by homeyer** [comment]
:+1:
