### ISSUE TITLE
Simplify backlog prioritization with "Move to top" and "Move to bottom" shortcuts

### ISSUE THREAD

**Issue by jdl031** [waffleio/waffle.io#2106]
As a product owner, shifting prioritization in Waffle can be a bit clunky. It would be easier if I could easily push a give card to the top or bottom of the board it's in.

**Comment by dirk-thomas** [comment]
This would be a really great improvement. With a growing backlog column it becomes a lot of effort to move cards to the top.

**Comment by burtonjc** [comment]
:+1: [from intercom](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/1294729550)

**Comment by aliilboga** [comment]
Please give some priority to this feature. Thank you.

**Comment by SpainTrain** [comment]
:+1: Key feature when working with prioritized columns.  Thanks!

Related (not quite dupe): #1502

**Comment by wmorgan** [comment]
:+1: from your friends at @BuoyantIO

**Comment by joeljeske** [comment]
+1. Would very much appreciate this.

**Comment by sibson** [comment]
+1, feature we would need before we move from JIRA,

**Comment by Jered** [comment]
:+1: must have feature

**Comment by SirCmpwn** [comment]
Not sure how this is still not done.

**Comment by billmccord** [comment]
+1

**Comment by lamebrain** [comment]
👍

**Comment by antislice** [comment]
+100000 I grumble about this at least once a week

**Comment by joaopapereira** [comment]
+1

**Comment by Nashet** [comment]
+1

**Comment by SirCmpwn** [comment]
I'm impressed - 2 year turnaround for a feature done in 22 hours.

**Comment by marydavis** [comment]
![image](https://media1.tenor.com/images/86ad6e662d9c317f1456629a800f9502/tenor.gif?itemid=4197940)

At least it finally made it :)
