### ISSUE TITLE
Bulk move multiple cards at once

### ISSUE THREAD

**Issue by jdl031** [waffleio/waffle.io#2107]
As a product owner, I often need to prioritize a group of card corresponding to a specific project. It would be helpful to have a way to multi-select cards and move them in a group.

**Comment by rpylipow** [comment]
:+1

**Comment by juanboca** [comment]
Please, this would be very helpful.

**Comment by skcain** [comment]
+1

**Comment by antislice** [comment]
+1 +1 +1

**Comment by kurtwheeler** [comment]
:+1: Any plans to implement this? It seems like pretty important functionality for non-trivial usage. I just created a new board to aggregate multiple existing projects into a single location for planning, which means I have to drag 171 existing issues from Inbox to Backlog one by one :frowning_face:

**Comment by adamzolyak** [comment]
Just chatted w/ a user who deploys once per sprint.  Wanted to be able to move all the cards from one column ("ready to be deployed") to another ("released") at once.  

Also suggested checking out automatic deployment tracking which moves cards for you https://help.waffle.io/tracking-deployed-work/automatically-track-when-work-is-deployed.

**Comment by AnaMSteele** [comment]
Please comment and leave upvotes on #3629 where we are tracking all bulk issue actions in one place. Thank you for helping us prioritize this work!
