### ISSUE TITLE
Renaming GH Repo does not let me delete the old one?

### ISSUE THREAD

**Issue by huggi** [waffleio/waffle.io#2108]
Maybe because I don't know how to handle waffle, but I created a repo with the name Webseiten in german and then I realized that this is an international project and renamed the Repo on Github to Websites, now I have two projects also within Waffle, how do I remove the old project, there is no: I know what I do, but I really wanna delete it button AFAIK, please help :) Thankz!

**Comment by ashumz** [comment]
Hi @huggi - 

We're tracking the official fix for this request here: https://waffle.io/waffleio/waffle.io/cards/55a54551b5a18b1f00c239b6 

Can you let us know the repository name you'd like deleted from your dashboard and we can do it from our end? You can use the question mark icon on the sidebar or email help@waffle.io with the repo name if you prefer it'd be private.

Thanks! :) 

Ashley
