### ISSUE TITLE
Customer question: Throughput screen y axis thrown off by bulk import

### ISSUE THREAD

**Issue by amontalenti** [waffleio/waffle.io#2109]
The basic problem is that we did a bulk import of about 4,000 issues from Lighthouse => Github issues. Waffle now reports that week we did the import as a week that we had a "throughput" of having closed over 3,000 issues (because we imported 3,000 closed issues). This now throws off the graph moving forward. Perhaps there's some way we could exclude a week or simply control the date range?

Here's a screenshot:

![selection_2015-09-26-002](https://cloud.githubusercontent.com/assets/40263/10117920/9709324c-6436-11e5-9662-20e05f5a583c.png)

**Comment by ashumz** [comment]
Hi @amontalenti, 

Would it be possible to label all of the imported issues with a given label, and then exclude that label from your throughput graph? We do this with issues we close as duplicate or 'wontfix' to get more accurate counts.

We also use the "Count by size" feature and size all of our dev issues so we can get an accurate count of throughput for development only issues. Not sure if that's something your team has adopted or might in the future, but it's a great way to gauge progress and productivity if you have issues that are sized differently, as is often the case.

Hope this helps. :) 

Ashley
