### ISSUE TITLE
Get some stats on the board - number of visitors per day to Waffle board

### ISSUE THREAD

**Issue by Grummfy** [waffleio/waffle.io#2110]
Hello,
is there a way to get statistic about the usage of a waffle board?

The idea is to see just the number of  people by day coming on a specific waffle.

Thanks

**Comment by ashumz** [comment]
Hi @Grummfy, 

No way currently to do that. Send an email to support@waffle.io with your board name if you'd like a breakdown from the info we have on our side as a one-off scenario. 

Is the main stat you'd want to know the number of unique visitors per day?

Cheers,

Ashley

**Comment by Grummfy** [comment]
yes.

thanks for your answer

**Comment by Hywan** [comment]
Hello :-),

@ashumz Not necessarily the number of unique visitors, but the number of visitors per day or month would be enough.

**Comment by kellihsf** [comment]
We haven't seen much activity on this card since it was opened from the rest of the Waffle user base. We are closing it for now as we prioritize and work on other more highly requested features/integrations. Thank you! :)
