### ISSUE TITLE
Gantt view of milestone/issues

### ISSUE THREAD

**Issue by carlosjoserg** [waffleio/waffle.io#2111]
I like Kanban boards, but I would find also useful to have a Gantt view of the issues/milestones, including asignees, etc. I think I read another req. about seeing for how long an issue has been open, so this might help.

Check on this relevant work that does that already:
https://github.com/neyric/gh-issues-gantt

Thanks for a great tool.

**Comment by laughedelic** [comment]
+1!!!

**Comment by ta** [comment]
Adding a +1 in a comment as well since https://github.com/waffleio/waffle.io/issues/126#issuecomment-196241223 is not implemented yet ;-)

**Comment by AttilaSATAN** [comment]
+1

**Comment by ecoopnet** [comment]
+1

**Comment by kramer65** [comment]
+100 - We'd be happy to pay for this feature

**Comment by brunovcosta** [comment]
+1!!!!

**Comment by SimonFricker** [comment]
+1

**Comment by ggruszczynski** [comment]
+1

**Comment by Ryanb58** [comment]
+1

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
