### ISSUE TITLE
Points disappear from cards

### ISSUE THREAD

**Issue by caseypt** [waffleio/waffle.io#2112]
Starting this week, we've noticed points being removed from cards when we drag them into the done column. Refreshing the page, or dragging the cards back into the previous column does not bring the points back.

Confirmed behavior of cards not clearing size:
![points](https://cloud.githubusercontent.com/assets/1042475/10293771/56a34274-6b84-11e5-9c06-b8d30ace52b0.gif)

**Comment by KazDragon** [comment]
I'd just like to confirm that I also saw that last night when writing up and estimating a bunch of cards in the backlog column and then moving them en masse to the ready column.

**Comment by caseypt** [comment]
In addition to the behavior I reported above, there are now some cards in the "Done" column that I can not remove points from. I can change the point amount, but when I select "Clear Points", the points disappear for a second, then reappear.

**Comment by ashumz** [comment]
Hi @caseypt & @kazdragon, 

Thank you for reporting this. We will take a closer look and get this resolved as soon as possible. Keep an eye on this issue for updates. Once the Issue is closed, the fix will be deployed live to production within just a few minutes. 

Ashley

**Comment by burtonjc** [comment]
@caseypt & @kazdragon. I just deployed a fix for this. Sorry for the hassle, and thanks again for reporting it!
