### ISSUE TITLE
warn that you must be a collaborator to move cards when cards are clicked on a public board, even if project has not yet been created

### ISSUE THREAD

**Issue by ashumz** [waffleio/waffle.io#2113]
Currently we only warn that you must be a collaborator if the project is already created. 

We should also notify the user that you must be a collaborator even if the project isn't created yet. (If they are a collaborator, they'll see the option to create the project.) 

Why? 

Users who log in to Waffle and navigate to other open source projects in Waffle, for which projects are not yet created, can run into a confusing situation where they click on cards and nothing happens, making the board appear broken ([reported by user](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/1247818495)

**Comment by ashumz** [comment]
This should be really simple -- just remove the condition of "not isPhantom" for the "Only collaborators can update cards" alert. It would also be nice to reword to "Only collaborators can move cards." rather than "Update" since non-collaborators can make certain updates like comments, adding issues, etc.

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
