### ISSUE TITLE
Dragging a card to the bottom of another column can be difficult

### ISSUE THREAD

**Issue by KazDragon** [waffleio/waffle.io#2114]
- Destination column extends past the bottom of the screen; the column has a scrollbar.
- Card is picked up from source column and moved to the bottom of the screen on the destination column.  It scrolls, but only allows dropping in the second-to-last position.
- Card must then be picked up again and, with pixel-perfect accuracy, swapped with the card at the bottom of the destination column.

**Comment by johnmurphy01** [comment]
+1

**Comment by marydavis** [comment]
we've added a way to send a card to the bottom of the column, please reopen this card and let us know if this new feature doesn't solve this issue for you - thanks :)
