### ISSUE TITLE
[Customer Question] Connecting Issues and PRs

### ISSUE THREAD

**Issue by alleyhector** [waffleio/waffle.io#2115]
Been successfully using closing and connecting keywords for pull requests that are associated with certain issues but I have come across a problem wherein if you have more than one commit and/or you title the PR itself (but not necessarily the commit, or update the PR name) it does not connect the cards and there is no way to connect them going forward. Is this a workflow problem or a bug? Not every commit will want its own PR for various reasons.

**Comment by ashumz** [comment]
Hi @alleyhector, 

Can you give an example of when you've run into this? You should be able to use the connects or closes keywords in the PR title or description, along with the issue number, to connect PR's to Issues. You can also do this after the fact, if you forget to use the right language initially, but sometimes you'll have to reload the board in order for our sync process to properly update the connection. 

Let me know of an example you've encountered. You can email support@waffle.io if you prefer to share privately. 

Thanks! 

Ashley

**Comment by alleyhector** [comment]
Was detailing process in an email and instead figured out my error. PR was titled "Closes Issue #5" instead of "Closes #5." New to Waffle and testing out as a sprint management tool so this exercise has helped a lot on our end, though sorry to take up your time.

**Comment by ashumz** [comment]
No problem! Glad you got it figured out. :) Reach out if you have any additional questions.
