### ISSUE TITLE
need to customise size

### ISSUE THREAD

**Issue by MehdiK** [waffleio/waffle.io#2117]
Hi waffle team,

I'm running a project where we don't follow semi-fibo story sizes. We just went for 1, 2, 4 and 8! I just imported our stories into GitHub and setup waffle for it and would love to use the story size feature on waffle; but you only seem to allow semi-fibo numbers. Any chance you could allow customisation of story sizes so I can add 4 in?

P.S. Thank a lot for the awesome product and keep up the great work!

**Comment by ashumz** [comment]
Hi @MehdiK, 

Thanks for reaching out about this - apologies for the delayed response. We're tracking the request on #1830 right now. No custom sizing available yet, but we're planning to make this an option in the future. Thanks for sharing your use case with us! 

Ashley

**Comment by MehdiK** [comment]
Thanks for your response and pointing me to the main issue. And sorry for creating a duplicate issue.
