### ISSUE TITLE
Doubled cards

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#2120]
two cases:
 - https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/1256715259

- https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/1251609151

**Comment by burtonjc** [comment]
I fixed the biggest offender of duplicate cards. There are still some ​_theoretical_​ race conditions, but we would be splitting milliseconds for those to occur.
