### ISSUE TITLE
redesign cards

### ISSUE THREAD

**Issue by marydavis** [waffleio/waffle.io#2129]
some of the feedback received: 
- [x]  header too dark
- [x] too much space around cards
- [x] need more space for repo name

**Comment by homeyer** [comment]
A few issues to keep in mind:
- https://github.com/waffleio/waffle.io/issues/2102: "Suggestion: Card source name title"
- https://github.com/waffleio/waffle.io/issues/1936: "Overview with tiny cards"
- https://github.com/waffleio/waffle.io/issues/1331: "fix card title area height when 150% zoom - cuts off text"
- https://github.com/waffleio/waffle.io/issues/885: "Condensed, compact board view (aka a list view of cards)"
- https://github.com/waffleio/waffle.io/issues/1312: "The card number title should be link to the github issue"
- https://github.com/waffleio/waffle.io/issues/1525: "Visual indicators on cards on board view for description"
- https://github.com/waffleio/waffle.io/issues/1540: "Display text username next to avatar in card header"
- https://github.com/waffleio/waffle.io/issues/1623: "Show checkbox progress bar on card for tasks, indicating task completion, same as #1455"

We don't have to solve for those things, just wanted to pull together any issues related to a card redesign.

**Comment by ashumz** [comment]
+1 on #1312 - or anything we can do to make getting to the issue in GitHub more obvious. One of the top actions users do in Waffle is click on the title of the card from the modal to get to GitHub. Command+clicking isn't obvious. If we can figure out a simple way to get users to GitHub to take advantage of the full issue editing/image upload capabilities of GitHub, we'll make a lot of people happy :)

**Comment by ashumz** [comment]
One idea around that thought: 

I do like that you can click the PR icon on the card view to go to the PR in GitHub. If we don't want to have the issue number link to GitHub, we could entertain the idea of using the open issue icon next to issues which would link to the issue in GitHub (rather than the issue number linking there) (https://octicons.github.com/icon/issue-opened/)

Could be cool to use the issue closed octicon for closed issues as well.

**Comment by ashumz** [comment]
and #1810 - which Mary already mentioned she's considering -- standalone PR's should have the same indication of being open by coloring the PR icon in the head green as well.

**Comment by sandcastle** [comment]
:thumbsup:

**Comment by marydavis** [comment]
here is what we are proposing - would love feedback!

![card design](https://cloud.githubusercontent.com/assets/176437/10677243/2301ac8c-78d9-11e5-9d2f-fbe4b092ee44.png)

**Comment by sandcastle** [comment]
@marydavis - looks great, the colour contrasts are a lot easier on the eyes than the current design. 

The only feedback I would have is that there might not be enough space for the labels on the same line as the other icons. Personally I use labels quite heavily and I know a lot of other repos that do also - a good example would be looking at something like https://github.com/angular/angular/issues. Maybe move the icons on the right to the top line?

**Comment by marydavis** [comment]
thanks @sandcastle! that is great feedback and really appreciate the example. the screenshot doesn't show it, but they would wrap above the icons like they do currently, but will mess around other options :)

**Comment by slaFFik** [comment]
It's hard for eyes to get caught by the task (hard to focus), as everything is so whitish.. Is it possible to preserve somehow this darker card title? I know that this is very subjective, by anyway...

**Comment by GriffinSauce** [comment]
@slaFFik An alternative is to make the shadow a bit heavier, isolating the cards a bit more.

Are you keeping system-default scrollbars? Those also cause some visual clutter when you have 3 columns with scrollbars. Something tiny like Sublime Text could be an option.

**Comment by marydavis** [comment]
Thanks @slaFFik, and good idea @GriffinSauce. Made the shadow slightly heavier which gave the cards more definition and easier to differentiate. Custom scrollbars would be nice, will add a card to hopefully add them in the future :)
