### ISSUE TITLE
allow users jump to next ticket in exploded view

### ISSUE THREAD

**Issue by willgibby** [waffleio/waffle.io#2130]
jump to next ticket in detailed (exploded) view within a column. |<< and >>| like on your ipod. 

could be cool

**Comment by burtonjc** [comment]
Interesting idea. I'm curious to know, what kind of problem you're trying to solve with this?

**Comment by willgibby** [comment]
when backlog grooming/sprint planning we go down the list and have to explode the first ticket, review, close, click the next ticket to explode it in view. 

it would save clicks/inputs if we could jump from ticket to ticket with a keystroke, or single click.

**Comment by wimpers** [comment]
+1

**Comment by kellihsf** [comment]
We haven't seen much activity on this card since it was opened from the rest of the Waffle user base. We are closing it for now as we prioritize and work on other more highly requested features/integrations.
