### ISSUE TITLE
Customer request/question: Boards without Github/Gitlab

### ISSUE THREAD

**Issue by bmalum** [waffleio/waffle.io#2131]
For Managing my Life and Work i have to create a Repo in Github, would it be possible to support Waffle without an Repo?

**Comment by ashumz** [comment]
Hi @bmalum, 

Not today. Not sure we will go in that direction, but we do have many people using Waffle with personal repositories to house their to-do's (I even used it for [planning my wedding](http://waffle.io/ashumz/weddingplanning). It'd be helpful for us to know why this isn't a viable option for you when considering the request. 

Hope you're liking Waffle for everything else so far! :) 

Ashley
