### ISSUE TITLE
Issues in Done column are no longer sorted by date closed/updated

### ISSUE THREAD

**Issue by ashumz** [waffleio/waffle.io#2132]
I think this may have to do with ranking changes @burtonjc 

I noticed this when doing some backlog grooming and a [customer reported it](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/1284167973) -- when you close issues from GitHub, they don't appear at the top of Done. Instead, they end up somewhere in the Done list with no recognizable ordering that I can figure out. :) 

To replicate, close an issue in GitHub. Expected behavior would be that the last closed Issue is at top of Done column. Instead, Issues closed from GitHub, even if they are the latest issue closed, are not always sent to top

**Comment by ashumz** [comment]
The customer also reported that they close Issues various ways, and it seems to be that there is no consistency around the newly closed Issues ranking properly: "it has been weird (unranked) for a couple of weeks -- we close issues by dragging in waffle, closing PR, command line commits,etc."

**Comment by homeyer** [comment]
this will be solved by #2124
