### ISSUE TITLE
ability to filter by label (not just exclude) for throughput graph

### ISSUE THREAD

**Issue by ashumz** [waffleio/waffle.io#2135]
[requested by user](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/1284286162) 

"in 'metrics' being able to 'show only' certain labels would be very useful - i.e we use labels to determine teams so 'show only' [team1] is easier than 'exclude' [team2] [team3] [team-n]"

**Comment by tchalvak** [comment]
+1, I use labels to categorize issues, and being able to see all of the labels of the same type would be appreciated.  In github I just click a label and get all the issues under that label, but in waffle.io they're not clickable.

**Comment by williamcoates** [comment]
:+1: 

We've had to create a milestone 'bugs' instead of using the label 'bug' so that we can use waffles metrics to see how much effort is expended on bugs. Bit awkward...

**Comment by kellihsf** [comment]
Hi all, 👋 

You can now filter the throughput graph by label!

![screen shot 2018-07-24 at 10 01 06 am](https://user-images.githubusercontent.com/4775572/43151011-926ece16-8f28-11e8-8cda-089d703f9eb1.png)
