### ISSUE TITLE
autocomplete GitHub usernames (for collaborators only)

### ISSUE THREAD

**Issue by ashumz** [waffleio/waffle.io#2139]
MVP of #925 (support GitHub @ replies/mentions in card description and comments.) 

**Acceptance Criteria**
- [x] typing `@` shows autocomplete
- [x] lists collaborators from the repo. Shows username.
- [x] typing filters the list (e.g., typing `home` will show `@homeyer`)

Out of scope:
- [x] Don't worry about @ mentions for users in comments or non-collaborators for this iteration
- [x] don't filter by full name
- [x] don't show full name

**Comment by simapatel** [comment]
yup - thats exactly what I'm looking for!

**Comment by metalspawn** [comment]
This would be great

**Comment by MFDW** [comment]
:+1: definitely! this is definitely the core essential thing to include...having to manually type out random/complex names, try to remember them, have to go find them is the bane of my waffle life

**Comment by Hoejsgaard** [comment]
This is exactly what I am looking for, as I can't remember all my team members handles.

**Comment by kwiens** [comment]
Yes, this is all that we need.

**Comment by BlueT** [comment]
:+1:

**Comment by ImINZAYNE22** [comment]
:+1: Definetly A Change I Need (psst... check out #2140 )

**Comment by tbezdeka** [comment]
:thumbsup:

**Comment by yaronyg** [comment]
:+1:

**Comment by lippytak** [comment]
+1 !!

**Comment by alfraser86** [comment]
+1
