### ISSUE TITLE
Maximize a lane so that cards become wider & enable easier ranking

### ISSUE THREAD

**Issue by ljhaywar** [waffleio/waffle.io#2145]
Ranking becomes a challenge once you have to start scrolling to see cards.  Being able to maximize a lane (like the Next Iteration lane) to take up the entire screen would allow for cards to become wider--and for more cards to fit in a single screen without scrolling.

**Comment by tedgoddard** [comment]
+1 A single lane view would allow you to more easily run through all the cards in that lane (such as assign tasks or labels).

**Comment by kellihsf** [comment]
This is being tracked on issue [#2093](https://waffle.io/waffleio/waffle.io/cards/55f7c70e48a2381000a68ec6), this will be closed as a duplicate.
