### ISSUE TITLE
prevent users from accidentally clicking away and losing text due to modal closing on click away

### ISSUE THREAD

**Issue by ashumz** [waffleio/waffle.io#2146]
Potential options:
- grey out the board when modal is live so it's not enticing to click on cards in the background (I've done this many times myself :)) 
- force user to close the modal rather than allowing a click outside of the modal to close it (only if we can figure out a very obvious, in your face way to close the modal so people don't get stuck here.) 
- prompt user to save first if they do click outside of modal 

ideal?
- clicking away would go back to the board view, but if you had typed text in a card comment or description, it would be autosaved

**Comment by yaronyg** [comment]
Please just auto save and please don't grey out. I already filed #2171 because it's super common to be able to see what is under the modal card while filing out the modal card.

**Comment by auroraeosrose** [comment]
Just autosave, this has bit me soooo much

**Comment by marydavis** [comment]
We decided to go with only closing the modal by using the "X" or hitting 'esc' if you are not focused in the text box. We felt autosaving would be a surprise to people since there is a comment button that confirms the submission and want to still allow people to cancel by closing.
