### ISSUE TITLE
When from > 1 source use different visual indication

### ISSUE THREAD

**Issue by cicorias** [waffleio/waffle.io#2148]
Either the card heading color, a "label" like indication or something that visually indicates which Git repo the issue was sourced from. Allow   editing the color from the Sources settings as well.

**Comment by kellihsf** [comment]
hi @cicorias,

This issue is already being tracked on [#1758](https://github.com/waffleio/waffle.io/issues/1758), so we'll be closing this as a duplicate. Thanks!
