### ISSUE TITLE
Comment and Close button

### ISSUE THREAD

**Issue by willgibby** [waffleio/waffle.io#2152]
Copy Github functionality. One button to submit a comment and relocate ticket to done column in one command. 

http://cl.ly/image/1q0Z3F2J3j31

**Comment by kellihsf** [comment]
+1 from [waffleio/waffle.io#2333](https://waffle.io/waffleio/waffle.io/cards/569d77292dccef030002c8cd), closed as a duplicate. 
"While you are correct a user could comment, then close the modal and then move the issue to the done - but that makes it a two step process - while if inside the modal for commenting on an issue in Waffle it would be ideal if you could comment and close the issue inside the modal (such as a single button to close and comment).  

Example: 

Contributor creates a feature request issue that is a duplicate - if you view the issue in Waffle, it would take two steps to reply back to feature request indicating it's a duplicate then dragging the issue to done.  If the close and comment button existed in the modal - you could accomplish both tasks with just one click.

So, long answer - yes I was leaning more towards a close & comment button added to the issue modal in waffle (which would match the issue comment buttons Github has).  FYI - I didn't realize that by dragging the issue to the done column in waffle that it would automatically close the issue (i've been opening issues via the see in github button inside waffle -- in a new tab -- and then closing them on Github).  I guess I just feel a close and comment button in the issue comment modal creates a better user experience."

**Comment by segfly** [comment]
+1 This would help prevent extra notifications for our team from the same issue.

**Comment by zspencer** [comment]
This is also pretty huge for us. It's an accessibility hurdle that we must use the mouse to close tickets in waffle; resulting in some people with limited mobility relying on github over waffle.

**Comment by AlexSneedMiller** [comment]
Is there a timeline we can expect this to be implemented on by any chance?

**Comment by kellihsf** [comment]
Hi all, no immediate plans on this one unfortunately. If/when we do decide to implement this, you'll see it move to our "Planned" column. Thanks!

**Comment by GeoffreyPlitt** [comment]
+1 Would love this feature.

**Comment by homeyer** [comment]
shipped!
