### ISSUE TITLE
Create waffle app for Smartphone

### ISSUE THREAD

**Issue by hezimz** [waffleio/waffle.io#2153]
Android && Apple

**Comment by tbezdeka** [comment]
:thumbsup:

**Comment by MosheBerman** [comment]
This.

**Comment by GreenRaccoon23** [comment]
For organization's sake, here's a link to the issue/request for an Android app.

https://github.com/waffleio/waffle.io/issues/1654#thread-subscription-status

**Comment by TTcrockeTT** [comment]
+1

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208

**Comment by Longri** [comment]
👍+1

**Comment by ncthbrt** [comment]
Would love a mobile app
