### ISSUE TITLE
When archiving a card it no longer disappears immediately

### ISSUE THREAD

**Issue by RickMohr** [waffleio/waffle.io#2155]
Really we need #1535.

But until then...  It was a lot easier to manually archive lots of cards when they would disappear immediately rather than hang around for an unpredictable amount of time.

**Comment by ashumz** [comment]
Hi @RickMohr, 

Thanks for reaching out. We're looking into this on our end and have some work in progress right now which should help us resolve this soon! We'll keep you updated via this card. Thanks for reporting it!

Ashley

**Comment by ashumz** [comment]
As a temporary workaround, using the keyboard shortcut 'r' to refresh the board should show the card as archived.
