### ISSUE TITLE
Add Column Constraints

### ISSUE THREAD

**Issue by mm53bar** [waffleio/waffle.io#2156]
A common thing in kanban boards is a constraint on how much work can be in a column. It would be nice to be able to add a constraint value for each column.

Rather than being a hard constraint (i.e. not allowing a card to be placed in the column), you could start by simply having a red background colour for any column that has more cards than it should.

**Comment by kellihsf** [comment]
hi @mm53bar,

This issue is already being tracked on [#414](https://github.com/waffleio/waffle.io/issues/414), so we'll be closing this as a duplicate. Thanks!
