### ISSUE TITLE
Column counts don't update when dragging from Backlog to Ready

### ISSUE THREAD

**Issue by wogsland** [waffleio/waffle.io#2159]
I set up a new project and noticed that dragging tasks out of Backlog and into Ready didn't update the column counts.

**Comment by ashumz** [comment]
Hi @wogsland, 

Thanks for reaching out! We're currently tracking this issue here: https://waffle.io/waffleio/waffle.io/cards/5628ff64870d4e030005d347

A refresh of the board (quickest way is the keyboard shortcut 'r') should fix the counts for the time being. 

Ashley
