### ISSUE TITLE
Automatically assign a user when he pushes

### ISSUE THREAD

**Issue by vvo** [waffleio/waffle.io#2162]
When a user pushes with a #ref, #fix.. We should automatically assign the issue to him if no one was assigned.

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
