### ISSUE TITLE
add a dark theme

### ISSUE THREAD

**Issue by marydavis** [waffleio/waffle.io#2163]

**Comment by yaronyg** [comment]
+1 The ocean of white is really hard to read

**Comment by nperez0111** [comment]
+1 Too much white

**Comment by jdef** [comment]
+1, perhaps a prototype via stylish?

**Comment by shadowbq** [comment]
https://userstyles.org/styles/browse/waffle

**Comment by marydavis** [comment]
We just released our beta version of a dark theme :) For now, you can toggle it using keyboard shortcut `shift + d +  t`. It currently only works on the board view, not including the card detail modal. Would love any feedback!
