### ISSUE TITLE
Ability to rename  Waffle board - Show display name of primary source if different than repo path for project dropdown and dashboard

### ISSUE THREAD

**Issue by ashumz** [waffleio/waffle.io#2169]
A first increment of #1392* to solve the problem of having a name that 'makes sense' for boards that contain multiple repositories. 

-  [ ] Settings->Sources should list primary source first (bug #1802)
- [ ] If you rename the primary source, this will become the title of your board. The board display name should show for your project dropdown and on your project dashboard 
- [ ] Also set the board's `<title>` attribute to the display/project name for primary source if one exists (currently we show the repo path) 

*url's will not change and the primary source will still only be accessible as a multirepo board

**Comment by eha11** [comment]
:+1:

**Comment by hjiang** [comment]
:+1:

**Comment by jipperinbham** [comment]
:+1:

**Comment by greiber** [comment]
Hi, this is a very important request for companys working with multiple repos. In order to use the kanban board with WIPs we need to combine multiple sources and set a new name for the aggregated board. E.g. Repos: XY-Android, XY-iOS, XY-Web, XY-Backend -> should be viewed as board "XY" with all repos included.

**Comment by liamstask** [comment]
:+1:

**Comment by baldercm** [comment]
:+1:

**Comment by thedrow** [comment]
+1

**Comment by mtahv3** [comment]
:+1:

**Comment by techniq** [comment]
:+1:

**Comment by ashumz** [comment]
+1 from user: 

"It would allow me to more easily get product owners involved. They always get confused by the multiple project in the title."

**Comment by drmaas** [comment]
:+1:

**Comment by gaddamadugus** [comment]
:+1:

**Comment by codingdiscer** [comment]
+1

**Comment by onato** [comment]
:+1:

**Comment by allisonphillips** [comment]
+1

**Comment by vkarpov15** [comment]
Has this actually been deployed yet? I don't see the ability to make these changes.

**Comment by kurttheviking** [comment]
similar issue to @vkarpov15 &ndash; it seems like title is not yet available from within the UI?

**Comment by vkarpov15** [comment]
@kurttheviking TBH I think this is a fundamental limitation of waffle.io's model: right now a board always starts out as the one waffle.io board for one repo and then you can add sources onto it. What you and I are trying to do is create a waffle.io board that's independent of any one repo and then add a bunch of sources onto it.

**Comment by kurttheviking** [comment]
@vkarpov15 correct; that's what I was trying to do
