### ISSUE TITLE
Autocomplete bugs using GitHub # syntax

### ISSUE THREAD

**Issue by yaronyg** [waffleio/waffle.io#2170]
When I need to refer to a bug I want to be able to type '#' followed by a number and start to get autocomplete. I realize this is complicated because Waffle supports multiple repos on a single board but that's why we have computers. :) We just need to union the possible results.

**Comment by sbenders-abbyy** [comment]
Seconding this request. Thank you!

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
