### ISSUE TITLE
Allow modal card to be moved

### ISSUE THREAD

**Issue by yaronyg** [waffleio/waffle.io#2171]
Literally every single day we run into the same problem on stand up:

Step 1 - Oh look, bug 123 is related to bug 213
Step 2 - Click on bug 123 to open it and get the modal dialog
Step 3 - Realize that we already forgot which bug we wanted to link to. Try to move modal dialog so we can see what is under it and thus see the bug number. 
Step 4 - Realize we can't move the modal dialog on top of the screen and so close bug 123
Step 5 - Pay attention to the other bug's number (213) and make sure to remember it this time
Step 6 - Re-open bug 123 and now get the link right to bug 213

If the modal dialog supported being dragged around the screen this wouldn't be a problem.

We have variants of this problem when we need to refer to titles or assignments of other bugs.

**Comment by marydavis** [comment]
@yaronyg thanks for the request! We just released the ability to drag the modal :)

**Comment by yaronyg** [comment]
@marydavis I just tried it out! Thank you!
