### ISSUE TITLE
Support gitflow keywords, because there's probably no repo called "hotfix" or "feature."

### ISSUE THREAD

**Issue by MosheBerman** [waffleio/waffle.io#2178]
Although waffle uses slashes to denote repo names, there's at most one user called hotfix, and one user called feature and one user called develop. For most people, it should be assumed that feature/{name} refers to the gitflow convention, not the user/repo convention.

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
