### ISSUE TITLE
show all possible labels in card detail view, not just the labels from that repo - connects to https://github.com/waffleio/waffle.io/issues/3029

### ISSUE THREAD

**Issue by kellihsf** [waffleio/waffle.io#2184]
Current behavior: The Add Issue dropdown shows labels from all the repos, but when picking labels from the detail modal we only show labels available to the repo the issue exists in.

Technically we should be able to make the detail view do the same thing as the add issue dropdown.

[Customer Requested](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/1358605530)

**Comment by yaronyg** [comment]
+1

**Comment by homeyer** [comment]
It's live!
