### ISSUE TITLE
There is no visual feedback when the system is removing an assignee filter

### ISSUE THREAD

**Issue by yaronyg** [waffleio/waffle.io#2186]
When we run our stand up with Waffle we use filters to focus on the issues of whomever turn it is. You can see our waffle [here](https://waffle.io/thaliproject/thali).

Applying an assigned filter isn't bad. It typically takes between 1 and 2 seconds.

The problem is removing assigned filters. This can take 4 seconds and more. What's worse though is that when one clicks on an assignee to remove them from the filter the click does not cause the check mark to go away.

Here is the current behavior:
1. See the Assigned drop down with an assigned with a check mark next to their name (this is the current assignee that the issues are filtered by)
2. Click on the current assignee name
3. NOTHING happens, there is no visual confirmation that the request to remove the assignee has been accepted
4. Only once the assignee filter has been removed is the check mark by the assignee's name removed

The reason this is really painful is that at least two or three times during a stand up I'm left with the question "I think I clicked to remove the assignee's name but I don't see the filter being removed so is the system being closed or do I need to click again to be sure?" I then click again and sure enough my first click WAS accepted there was just no visual feedback and the second click causes the filter to be added right back! Now I get to go through the whole process all over again.

Please, either speed up removing filters to the point where this isn't an issue or at least provide some kind of visual feedback that the request to remove the assignee has been received and I need to wait until the filter is removed.

**Comment by jonyoder** [comment]
+1. This issue has been driving me crazy on our Waffle boards, as well. I'd love to see, at a minimum, the checkmark removed immediately so I know my click was effective.

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
