### ISSUE TITLE
use a bot account to auto move work

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#2187]
It's confusing when Waffle takes actions on issues with a user's credentials, especially when it's on an issue they didn't create or aren't assigned to.

We built this functionality before GitHub exposed who took each action. Now, we need to change how we do it so users aren't confused and wonder if their account is compromised.

The ideal: Only enable auto work tracking features if a user invites a bot account (waffle-iron?) to a project, during project onboarding.

Easier solution: Enable by default the way we do today, but use the waffle-iron user if it's on the team. Have a project settings page for auto work tracking, where you can disable it altogether, use it how it works today, or invite waffle-iron.

We'll have to figure out how to handle this for takeout too.

**Comment by kellihsf** [comment]
This user prefers to create their own bot account
[internal]
https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/1370697154

**Comment by kellihsf** [comment]
:+1: via [email request](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/1350971426)

**Comment by kellihsf** [comment]
:+1: via [email request](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/1350971426)
prefers to create own bot account
