### ISSUE TITLE
[Support] Team filter

### ISSUE THREAD

**Issue by danjdavies** [waffleio/waffle.io#2188]
Project team board that pulls in users and projects from various boards. Gives user instant visibility to what their team members are up to at a quick glance. For example, I have 3 devs and I am a senior dev. They work on different boards. Hard to see what they are all doing at once plus other people in company are on boards too.

I suppose it could be a super filter

**Comment by ashumz** [comment]
Hi @danjdavis, 

Would you be able to create a multirepository board (in Settings->Sources) for the work for your team and then use filters to distill down the view when you need just a view for your individual user? 

Do note that if you end up connecting all repositories to a single board, you will want to switch to working from that board or make sure that the column labels and set up match exactly for all individual and multirepo boards. 

Let me know if you have questions or if there is a reason this won't work for you. 

Ashley
