### ISSUE TITLE
Support "connects to" for issues as well

### ISSUE THREAD

**Issue by andreasohlund** [waffleio/waffle.io#2190]
The `Connects to` feature is pure gold and it would be great if it worked on issues as well as pulls.

**Comment by homeyer** [comment]
@andreasohlund would just one level of depth work? Issue A connects to Issue B, and not Issue A connects to IssueB connects to Issue C.

**Comment by andreasohlund** [comment]
Yea, one level would be enough (I could see how multi levels can get tricky quick)

**Comment by FezVrasta** [comment]
+1

I'd love to be able to connect more issues to the same PR.

Most of the times my team and me prepare a PR which fixes several issues, so be able to link 1 or more issues to the same PR would be freaking awesome.

Thanks.

**Comment by jasonfarrell** [comment]
+1

Would be incredible if you could somehow mark "progress can't start on this issue until these issues are completed".

**Comment by marcosrjjunior** [comment]
:+1:
