### ISSUE TITLE
Make size more prominent on card when set

### ISSUE THREAD

**Issue by marydavis** [waffleio/waffle.io#2191]

**Comment by jaimecasero** [comment]
would be great if the actual size of the box would be altered depending on size set

**Comment by jaimecasero** [comment]
if not possible, maybe a color convention would do. another way is to follow the animal convnetion -> https://www.scrum.org/Forums/aft/729

**Comment by marydavis** [comment]
@jaimecasero i absolutely love the animal icon idea, that is great! i'm going to add these suggestions to this issue (where we are tracking custom size options): https://waffle.io/waffleio/waffle.io/cards/55117ec86c184e1a003875cb

thank you!!
