### ISSUE TITLE
Add Pomodoro to Waffle

### ISSUE THREAD

**Issue by brucellino** [waffleio/waffle.io#2192]
I would like to see features in waffle that allow application of the [pomodoro](https://en.wikipedia.org/wiki/Pomodoro_Technique) or similar timeboxing techniques. 

Inspiration may be taken from _e.g._ [KANBAN flow](https://kanbanflow.com). 

What is needed is functionality _within_ waffle (I don't think using a plugin would be feasible, but it's worth investigating) to : 
1. Select an issue that is currently being worked on
2. Start a timer (little javascript function may do this)
3. Allocate the time to the "size" of the issue in units of a pomodoro.

This won't be used by everybody, but it could be a nice addon for those who want to have a handle on time management and productivity.

**Comment by brucellino** [comment]
Oops, dupe.

**Comment by jurgob** [comment]
+1

**Comment by kohashi** [comment]
+1

**Comment by marydavis** [comment]
@brucellino [Toggl](https://support.toggl.com/toggl-button-chrome-extension/) has a chrome extension that integrates with Waffle and has a [Pomodoro](https://support.toggl.com/toggl-button-chrome-extension/#pomodoro) timer option :) The integration places the timer within the card detail modal of the card you are working on, here is an example of what it looks like: https://github.com/toggl/toggl-button/wiki/Where-can-I-find-the-Button%3F#waffleio

Would this be something that would work for you?

**Comment by Acaspita** [comment]
+1

**Comment by TTcrockeTT** [comment]
+1

**Comment by dbuarque** [comment]
+1

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
