### ISSUE TITLE
embeddable throughput graph doesn't show points

### ISSUE THREAD

**Issue by kellihsf** [waffleio/waffle.io#2196]
[customer requested](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/1377411528)

Would be great to be able to configure the graph with a query param.

**Comment by niccokunzmann** [comment]
We are estimating issues and I would like to see the throughput graph with the estimated points. The same as I see when I click on ["Count by Size"](https://waffle.io/AllYarnsAreBeautiful/ayab-desktop/metrics/throughput).

**Comment by WayneBooth** [comment]
+1

**Comment by marydavis** [comment]
We haven't seen any activity on this card for awhile from the rest of the Waffle user base. We are closing it for now as we prioritize and work on other more highly requested features/integrations.
