### ISSUE TITLE
ignore old versions of updates when receiving realtime events on new board

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#2198]
current behavior: rapid DnD causes other browsers to get confused.

**Comment by ashumz** [comment]
also PR's are duplicating in scenarios where they are connected as well as not connected to anything (standalone cards) 

I have also seen issues duplicate across browsers when added and then moved to another column (noticed on our board with issue #439)

**Comment by homeyer** [comment]
the `__v` field doesn’t actually keep track of every version. In other words, we can’t rely on it to determine if we’re getting an out-of-order update. http://aaronheckmann.tumblr.com/post/48943525537/mongoose-v3-part-1-versioning

we probably need to create our own `updated_at` field. maybe models mongoose plugin to set it?
