### ISSUE TITLE
Reorder columns

### ISSUE THREAD

**Issue by MattiSG** [waffleio/waffle.io#2200]
Hi,

Columns reordering seems broken. I can't drag-and-drop a column I added to an existing repo.

Reproduced on:

- Sf 9.0.1 / OSX 10.10.5
- FF 40.0.3 / OSX 10.10.5
- Ch 46 / OSX 10.10.5

**Comment by dokie** [comment]
+1 - This was working last week! Confirmed broken on Ch 46, OSX 10.11.1

**Comment by kellihsf** [comment]
Sorry about this issue, it's now been fixed! :)

**Comment by MattiSG** [comment]
Confirmed, thanks!
