### ISSUE TITLE
Basecamp 3 Integration

### ISSUE THREAD

**Issue by brianjking** [waffleio/waffle.io#2208]

**Comment by brianjking** [comment]
@kellihsf May I ask why this was closed and set to wontfix? 

Thanks! Appreciate your time and all that you do!

**Comment by homeyer** [comment]
@brianjking we're focused on serving engineering teams first by integrating deeply with GitHub, and expanding into similar services BitBucket/GitLab. While integrating with other PM tools is interesting it's not on our roadmap.
