### ISSUE TITLE
filter board "issues only" not working reliably

### ISSUE THREAD

**Issue by tansaku** [waffleio/waffle.io#2212]
![](https://www.dropbox.com/s/7broyrjavl8ay3q/Screenshot%202015-11-12%2009.30.21.png?dl=1) has been working well for us, but then recently we have an intermittent issue where the prs all appear briefly as separate tickets in the QA column and then disappear on reload and then come back in again gradually.

It's a bit inconvenient for us - is this is known bug?

This is on https://waffle.io/makersacademy/Engineering

**Comment by marydavis** [comment]
@tansaku sorry for the delay, we've made some changes since this was reported that may have fixed this problem. please let us know if you are still experiencing this issue so we can make sure to fix it :) thanks!
