### ISSUE TITLE
Waffle puts issues in the wrong column

### ISSUE THREAD

**Issue by yaronyg** [waffleio/waffle.io#2213]
This morning we came in to find that our "In Progress" labeled issues were all displaying in the "Backlog" column even though they were clearly tagged with "In Progress". A refresh finally fixed this but until we realized what was going on this really destroyed our stand up.

**Comment by kellihsf** [comment]
Hi @yaronyg,

Sorry you're having trouble with this. We're closing this issue for now because we believe it to be resolved with our latest changes.  Can you let us know if you're still experiencing this behavior? 

Kelli

**Comment by yaronyg** [comment]
I have been moving a bunch of issues around and the only persistent bug I keep running into is #2215. I just moved 5 cards and one failed with that bug.
