### ISSUE TITLE
Waffle takes a long time to load/refresh

### ISSUE THREAD

**Issue by yaronyg** [waffleio/waffle.io#2214]
One of the guys on the stand up needed to load Waffle to follow an issue and Waffle just couldn't complete loading in under a minute. I also had to reload Waffle and had the same issue. This brought the entire standup to a halt.

**Comment by kellihsf** [comment]
Hi @yaronyg,

Sorry you're having trouble with this. We're closing this issue for now because we believe it to be resolved with our latest changes.  Can you let us know if you're still experiencing this behavior? 

Kelli

**Comment by yaronyg** [comment]
I just ran a 'r' test and it took about 8 seconds to do a refresh. Not super speed but certainly nothing that would cause us a problem in normal usage so I agree, this one seems fixed.
