### ISSUE TITLE
Moving cards is failure prone

### ISSUE THREAD

**Issue by yaronyg** [waffleio/waffle.io#2215]
Twice on today's stand up we moved cards only to get an error from Waffle saying they couldn't be moved. But then we were able to move them on the second try. This is incredibly disruptive to the standup.

**Comment by yaronyg** [comment]
BTW, just using Waffle today I've had this bug show up a few more times.

**Comment by ashumz** [comment]
Hi @yarong, 

Before you start your standup, have each person refresh the board (keyboard shortcut 'r') and after adding new cards, for the time being. We pushed some changes earlier today around noon that should clear up some of the other issues you reported, but there is still an open known issue around adding new cards and then reranking or moving existing cards which we are addressing currently.

One thing that would be helpful is if you are repeatedly seeing the error, if you can share the output of your console, we may be able to see if this is something beyond the known issues we are currently working through. 

Thanks, 

Ashley

**Comment by yaronyg** [comment]
I saw your comment right after I hit r! Although I went to look at my console and saw:
13:54:37.706 Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api.waffle.io/projects/550b648f12c62d200048fdb6/cards. (Reason: CORS header 'Access-Control-Allow-Origin' missing).1 <unknown>

A CORS error? That seems odd.

**Comment by kellihsf** [comment]
hi @yaronyg,

We believe this issue is now resolved. If you're still seeing this same behavior, please let us know or open a new issue on our board. Thanks!
