### ISSUE TITLE
Assigning issues experienced failure

### ISSUE THREAD

**Issue by yaronyg** [waffleio/waffle.io#2216]
When we tried to assign an issue we got a failure. That was just odd. It worked on the second try. Normally interment failures aren't a big deal but we have been getting a bunch of different errors today.

**Comment by kellihsf** [comment]
Hi @yaronyg,

Sorry you're having trouble with this. We're closing this issue for now because we believe it to be resolved with our latest changes.  Can you let us know if you're still experiencing this behavior? 

Kelli
