### ISSUE TITLE
research new column interface

### ISSUE THREAD

**Issue by ashumz** [waffleio/waffle.io#2217]
- [ ] ~~Add Planning section to settings/columns~~ will wait until planning interface
- [x] Rename Backlog section to Inbox (leave column name as is.) 

Many of our users have columns prior to their backlog column for new issues, things like "ideas" or "icebox" or "needs grooming" etc. When migrating to the new column interface, they'd have to move these sections to Progress which would be annoying to scroll over and doesn't make much sense. 

We'll add a section in front of Backlog for Planning - should be collapsed since it will be empty by default for new boards and any boards that don't have columns before the backlog. 

If columns exist in the planning column, the planning section would be expanded by default. Since not everyone will use this, if it's not in use it would be collapsed and expandable somehow (Mary will figure out the best interaction for this.) 

Going forward, this could become the planning interface - all columns in "Planning" would end up on the separate planning interface, hidden from the rest of the board.

With this change, we should also rename the section header for Backlog to "Inbox" since the Planning columns will be where the backlogged issues will most likely live (leave the column name as "Backlog", though.)

**Comment by marydavis** [comment]
Realized that adding columns in front of the inbox will break our idea for our planning interface. Decided to reword new column settings to better fit the desired workflow.

**Comment by nparsons08** [comment]
:+1:
