### ISSUE TITLE
Waffle shows a card has not moved when it has!

### ISSUE THREAD

**Issue by yaronyg** [waffleio/waffle.io#2218]
I moved a card from Ready to Backlog. I then changed a different card and suddenly the first card spontaneously re-appeared in the Ready column. So I moved it back. I then changed yet another card and sure enough that very first card? Yup, it spontaneously re-appeared in the Ready column. This time I did a full refresh and sure enough the card was now where i put it. So this appears to be a UX issue.

**Comment by ashumz** [comment]
Hi @yaronyg, 

Sounds like you ran into the issue I mentioned in #2215 - had cards recently been added to the board when this occurred? (Either by you or another team member.) 

Thanks, 

Ashley

**Comment by yaronyg** [comment]
What counts as recent? Our team is spread all over the planet and so there is always lots of work going on with issues in GitHub. But few people are using Waffle for this at this point because of all the problems. :( I'm pretty much the only one left and I saw this problem first thing when I loaded waffle for the stand up.

**Comment by ashumz** [comment]
Hi @yaronyg, I was referring to recent as in after loading the board, but before any refreshes happen. 

But, looking back at your project set up, I still see that you have two Waffle projects, both which share the same repositories, and have different column set ups. This is known to cause issues, as column labels must match. Can you delete the one that has fewer boards connected? Shoot us an in app message to discuss in more detail -- I don't want to provide any sensitive information through the public issue.

**Comment by yaronyg** [comment]
I just deleted the second board. We never used it. In fact, I forgot it even existed. I hope that resolves our problems!

**Comment by jdegger** [comment]
Experiencing this too. This is what happens:

1. I or a team member moves a card to another column
2. It jumps back to the original column after a while without an error
3. After refreshing it show the card in the correct column

Seems like the Github label actually changes but Waffle just decides to put the item back in it's original column. Whenever you try to move a card which jumped back you get the 'Couldn't move card' error.

**Comment by homeyer** [comment]
Most of these issues should be fixed now with our recent board updates.
