### ISSUE TITLE
Add Issue fails and after time out issue button remains greyed out, requiring a refresh to be re-enabled

### ISSUE THREAD

**Issue by yaronyg** [waffleio/waffle.io#2219]
I tried to add a card and after waiting for a bit I got a failure. So I clicked out of the modal dialog and clicked back in using "Add issue" and "add" is now greyed out. Having dealt with this bug before I knew to copy the content of my new issue and then do a refresh and then hit Add issue and then paste it back in.

**Comment by ashumz** [comment]
Hi @yaronyg, 

Thanks for reporting this. We'll look into how we can better handle the Add Issue button if the initial card add fails. We'll also look into any errors you might be receiving to see if there is another underlying problem for your team board that is causing the issues you're experiencing. 

Sorry for the trouble.

**Comment by edweip3** [comment]
I'm seeing this error as well as #2218.  The problems is api.waffle.io is returning 503.  maybe one of your backend API server is not responding to requests. Retrying usually results in success.  Symptoms include board stuck on "ironing your waffle", failed to create issues, fail to move issues. failed to set sizes, etc.

**Comment by homeyer** [comment]
Fixed, thanks everyone!
