### ISSUE TITLE
Unable to expand columns after collapsing in Firefox

### ISSUE THREAD

**Issue by jhibbets** [waffleio/waffle.io#2220]
After clicking on the "collapse" column icon in the upper right of a column (two arrows pointing towards each other --> <--) I am unable to expand the columns. There is nothing to click on and the words appear upside-down with no hyperlinks.

Firefox version 38.2.1 on Red Hat Enterprise Linux 6.

![waffle-broke](https://cloud.githubusercontent.com/assets/3680343/11134185/e3f272d8-8968-11e5-80fc-c6a2ecf726db.png)

**Comment by marydavis** [comment]
hi @jhibbets, sorry that version of Firefox does not support the collapsible columns :( This feature was created using CSS that works with version 40 and up of Firefox. To fix, the collapsed columns are saved in local storage which you can get to and delete using your browser's dev tools.

**Comment by lamanning** [comment]
howdy. same problem here: collapsed all columns and can't get them back. using i.e. 11. how do i get the columns back?

**Comment by jhibbets** [comment]
Hi Laura, While I can't help with IE 11, perhaps these instructions from
StackOverflow could help you:
http://stackoverflow.com/questions/6084099/how-to-view-delete-local-storage-in-firefox#6130392

You basically need to delete the localStorage value in the cookie in order
to reset the columns.

**Comment by kellihsf** [comment]
The issue on IE 11 has been resolved! 😀
