### ISSUE TITLE
Update animated messages in Intercom

### ISSUE THREAD

**Issue by kellihsf** [waffleio/waffle.io#2222]
From issue #4; working on when Ashley & Mary are in town

**Comment by kellihsf** [comment]
- [ ] https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/messages/auto/10477736/show

- [ ] https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/messages/auto/10197476/show

- [ ]   https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/messages/auto/3489037/show

**Comment by ashumz** [comment]
Update the column screenshots also in http://blog.waffle.io/pull-request-configuration/ to include new interface
