### ISSUE TITLE
Remove spam/scam issues and PR.

### ISSUE THREAD

**Issue by BerkeleyTrue** [waffleio/waffle.io#2225]
We get a lot scammers opening up issues with telephone numbers. While Github is quick to remove them, they still show up on our Waffle board with no clear way of removing them.

**Comment by homeyer** [comment]
Oh crazy, I didn't know that happened! Do you know how GitHub handles them?

Waffle listens for webhook updates from GitHub, so your board should automatically update if GitHub cleans up spam issues. Unfortunately there's nothing we can do on our side to make spam in GitHub less prevalent, sorry!

**Comment by homeyer** [comment]
On second thought @BerkeleyTrue, if there are specific cards that GitHub deleted but are showing up on your board, just send us a note and we can clean them up for you. If it gets crazy we'll figure out a way to make it happen automatically :).

**Comment by BerkeleyTrue** [comment]
@homeyer We often get dozens at once. And I've seen them linger on waffle days after. I end up going through them and changing titles to spam and removing their content. This is a very time intensive process.
