### ISSUE TITLE
Total story points are not updating when moving issues to different columns

### ISSUE THREAD

**Issue by kellihsf** [waffleio/waffle.io#2227]

**Comment by James1x0** [comment]
Thanks for opening this. Seems to update after leaving the page for a few minutes. Not sure if it was just a stale refresh or an eventual thing.

Moving from Column 1->2, works.
Moving from Column 2->1, doesn't.

**Comment by homeyer** [comment]
This is now fixed :)

**Comment by James1x0** [comment]
@homeyer :clap: Board feels much more responsive just with that update. Thanks!
