### ISSUE TITLE
Issue with horizontal scroll in FireFox

### ISSUE THREAD

**Issue by bhavanasoni** [waffleio/waffle.io#2230]

**Comment by bhavanasoni** [comment]
![screenshot 2015-11-19 19 26 23](https://cloud.githubusercontent.com/assets/11044015/11288594/75a6598a-8ef3-11e5-9fa3-2e63adc42b84.png)

**Comment by marydavis** [comment]
this should be fixed when [#1307](https://waffle.io/waffleio/waffle.io/cards/53ea6d9682b317f7d9ad84c9) is completed
