### ISSUE TITLE
Inconsistent issue moving between columns (part of #2124)

### ISSUE THREAD

**Issue by mavam** [waffleio/waffle.io#2231]
I encountered a confusing issue recently, when issue numbers had a jump from 99 to 100. What users would expect is that recently closed issues *stack on top* of previously closed issued issues. This appears to happen in many cases, but not when issue number cross the boundary of an order of magnitude, e.g., from 99 to 100. In this case, recently closed issues do not get stack on top, but instead inserted somewhere in the middle.

This confused me, because I couldn't find the issue initially at the top, even though I closed it. Only after scrolling down, I could find it then.

**Comment by ashumz** [comment]
Hi @mavam, 

We are working on a fix for some of our current board issues, this included. In particular, the relevant issue you may want to follow is this: https://waffle.io/waffleio/waffle.io/cards/56158d8da7bf270300a8cdd2

Once that card goes live, many other performance enhancements will, too. We'll look forward to hearing your feedback and making sure your issues have been resolved!
