### ISSUE TITLE
customer question: reports

### ISSUE THREAD

**Issue by barbaracabral** [waffleio/waffle.io#2239]
We are using github to prioritize the issues according Priority and Frequency of the bugs.

It's possivel to use customizable labels to elaborate the reports?

Thanks! :D

**Comment by homeyer** [comment]
Hey @barbaracabral!

You can filter the throughput graph by labels. If you look at our board, we use several different types of labels, like `interrupt` or `techdebt` and `bug`, and `expedite`. These labels help us retrospect to see what type of work we're getting done (how much did we plan, vs how much was unexpected).

I hope that helps!
