### ISSUE TITLE
save Card before Issue, to reduce "Version Mismatch" errors

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#2248]
We're seeing `Version Mismatch` errors in the API rather frequently when dragging cards.

When the GitHub webhook is disabled, these errors are reduced.

Our assumption is that the issue webhook from GitHub is being received and updates the card in the db while the API request to update the card from the client side is still in-flight, which causes the API card update to fail.

**Acceptance Criteria**
- [ ] update the card in our DB in the API request before sending the update request to GitHub, so we're guaranteed to receive the issue webhook from GitHub _after_ the API card update is complete.

**Comment by burtonjc** [comment]
Turns out this solution didn't work, ha. It got rid of the flakiness, but now it just consistently fails every time. Next attempt is to set a flag on cards as we are updating them and then hooks will drop the events that have to do with a flagged card.
