### ISSUE TITLE
Waffle adds a label then removes then removes that same label in GitHub

### ISSUE THREAD

**Issue by kellihsf** [waffleio/waffle.io#2253]

**Comment by kellihsf** [comment]
A user has reported that Waffle labels and un-labels the same label. 

We're not sure what's causing this, will need to look in to it. 

Example of this in public repo: https://github.com/datagovuk/ckanext-dgu/pull/245

**Comment by thierryu** [comment]
@kellihsf, the title repeats "then removes" twice

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
