### ISSUE TITLE
Choose a JS charting library

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#2256]
2 point spike. Let's keep this to a day or two, just enough to be confident we're going in the right direction.

**Acceptance Criteria**
- [x] can support bars, like our throughput graph. If it doesn't support stacked bars that's ok, the throughput graph could be changed to be two bars side-by-side in different colors to represent open/closed.
- [x] can support a burndown graph
- [x] can work inside the app, and inside the graph service to render charts in a README.md.

Consider [chart.js](http://www.chartjs.org/), it seemed like the best when I was looking around (@homeyer).

**Comment by marydavis** [comment]
also look into [chartist-js]( http://gionkunz.github.io/chartist-js/index.html)

**Comment by marydavis** [comment]
i like [http://gionkunz.github.io/chartist-js/index.html](chartist) - they are in SVG and even has the option of  https://github.com/paradox41/angular-chartist.js for an angular directive
