### ISSUE TITLE
card count and size on burndown graph

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#2260]
**Acceptance Criteria**
- [x] like the throughput graph, let the user choose whether to show totals based on the number of cards or the sum of the card sizes.
- [x] show label of axis
- [x] move graph legend closer to graph

The graphs service does not support count vs size for the throughput graph. Ideally, it's a simple configuration option for the chart, so the graph service could accept a query param to toggle it. If it's easy to build with that in mind, awesome. If not, fine to punt.

**Comment by marydavis** [comment]
i'm not sure how the graphs service works so is really hard to build this with that in mind, don't mind changing it once the service is hooked up if needed.

**Comment by homeyer** [comment]
cool, i'm great with doing something and changing it later :)
