### ISSUE TITLE
Make active filter obvious

### ISSUE THREAD

**Issue by scottdelly** [waffleio/waffle.io#2262]
When a filter is on, it's not always obvious. Sometimes I think an issue has gone missing before I realize I left a filter on, especially if the filter is from the drop down and not just a text search. Bonus points: make the drop down filters set text in the filter text box and then make it one click to clear any filter. (e.g. Filter > label > "myLabel" sets the filter text to "label:myLabel" just like github) then typing that text sets that filter and clearing that text clears that filter.)

**Comment by shadowbq** [comment]
I would find this useful as well. Maybe a star next to the filter, a color change, or word summary on hover

**Comment by talbotseb** [comment]
:+1:

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
