### ISSUE TITLE
Support for casting with chromecast

### ISSUE THREAD

**Issue by tjconcept** [waffleio/waffle.io#2265]
- Keep casting when you shutdown your device
- Hide navigation and menu
- Support zooming

**Comment by tjconcept** [comment]
The cast part seems to be incredible simple: https://github.com/boombatower/chromecast-dashboard/blob/gh-pages/sender/main.js
Basically you just ask the chrome cast library to load a specific URL.
Biggest challenge is probably session management. You need a one-time access token for the URL or similar.

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
