### ISSUE TITLE
When editing a comment in the detail modal, esc will clear the value but you cannot undo that.

### ISSUE THREAD

**Issue by burtonjc** [waffleio/waffle.io#2268]
Keeps happening to me where I am typing and try to type a back tic but accidentally hit esc, then I have to start all over.

**Comment by homeyer** [comment]
@marydavis, will this be fixed with the work you're doing on the auto complete stuff?

**Comment by marydavis** [comment]
hitting esc without the autocomplete collaborator dropdown open will blur the textarea and not clear text - if we want the option to clear and undo, that would be another card
