### ISSUE TITLE
ProdPad

### ISSUE THREAD

**Issue by BrookeBango** [waffleio/waffle.io#2269]
Integrate with ProdPad so that issues can be a part of the planning and organization structure

**Comment by jpike88** [comment]
...? Why was this closed? +1

**Comment by kellihsf** [comment]
Hi @jpike88 

This is being closed for now because it's not on our current roadmap and unfortunately, not a lot of interest compared to other feature requests. If we continue to get requests for this, we'll consider adding it back to our 'Ideas' column. Thanks!
