### ISSUE TITLE
Waffle doesn't render tables correctly in the comments in the detail modal

### ISSUE THREAD

**Issue by kellihsf** [waffleio/waffle.io#2272]
This is what it should look like:

![screen shot 2015-12-17 at 10 09 51 am](https://cloud.githubusercontent.com/assets/4775572/11876325/5f1eeccc-a4a6-11e5-85ed-7ac664cdcb40.png)

This is how it looks in Waffle:

![screen shot 2015-12-17 at 10 11 06 am](https://cloud.githubusercontent.com/assets/4775572/11876348/87080f34-a4a6-11e5-9bb7-b119876708be.png)

**Comment by homeyer** [comment]
after 
![image](https://cloud.githubusercontent.com/assets/84629/21867732/bd6e3bf8-d80c-11e6-9bde-50739cfe66ce.png)
