### ISSUE TITLE
Make filter non-case sensitive

### ISSUE THREAD

**Issue by lliss** [waffleio/waffle.io#2273]
When using the "Filter Board" text input at the top of a waffle board, the text is translated to a lowercase version of the string in the URL. It appears that this value is then used to filter the list. For some reason, some project names are treated in a case sensitive manner and are therefore filtered out and do not show in the filtered list.

**Comment by TTcrockeTT** [comment]
+1, wow I have grown to just expect this.

**Comment by homeyer** [comment]
It's case-insensitive now, just forgot to close this issue when we fixed it.
