### ISSUE TITLE
The default "ready" column may be confusing.

### ISSUE THREAD

**Issue by hjiang** [waffleio/waffle.io#2275]

**Comment by hjiang** [comment]
Isn't "Next" more clear?

**Comment by homeyer** [comment]
Hmm, that's a good point. Do we know what other board products default to @ashumz? Pivotal Tracker, Trello, Sprint.ly, LeanKit?

**Comment by gappleto97** [comment]
I typically change this to "queued".

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
