### ISSUE TITLE
More tasks do not load on 4k screen

### ISSUE THREAD

**Issue by peterix** [waffleio/waffle.io#2279]
Normally, more tasks get loaded in when you scroll down. My screen is big enough for there to be no scrollbar - and therefor no need for scroling. This breaks the loading behaviour.

**Comment by marydavis** [comment]
@peterix how many cards fit vertically in a single column before needing to scroll? This will help us determine our next step to fixing this issue :)

**Comment by peterix** [comment]
Looks like about 30 with the dark style I'm using. This is with the screen not rotated and the site not scaled/zoomed in any way.

![screenshot_20160115_201815](https://cloud.githubusercontent.com/assets/203326/12362804/85829554-bbc5-11e5-9e08-b2f164ae464c.png)

With the default style, it's definitely less. Maybe 25?
![screenshot_20160115_202436](https://cloud.githubusercontent.com/assets/203326/12362915/1f662c6c-bbc6-11e5-934f-d74781b74054.png)

**Comment by homeyer** [comment]
I think I'm experiencing something similar. When dropping a card into a column, it sometimes immediately disappears. If I resize the window, it re-appears (in this case, I closed the chrome downloads at the bottom, figured it's the same thing as a window resize). Hard to re-pro tho :).

**Comment by homeyer** [comment]
looks like my issue was unrelated, tracking it here now: https://github.com/waffleio/waffle.io/issues/2336.

**Comment by marydavis** [comment]
@peterix this should now be fixed, let us know if you are still having this issue after refreshing, thx!

**Comment by peterix** [comment]
Yes, this is now fixed.
