### ISSUE TITLE
Selection of repo doesn't work sometimes

### ISSUE THREAD

**Issue by bmunkholm** [waffleio/waffle.io#2284]
Sometimes the repository selection pulldown list (in the top/left corner) stops working. When I click it either nothing happens, small line artifacts are shown a few pixels below the box or the ^ arrow toggles between up/down, but doesn't list anything.

**Comment by kellihsf** [comment]
hi @bmunkholm,

I have seen this issue also, but not on a consistent basis so it's hard to reproduce. I can't promise anything, but I'll bring this up to the team so we can have a closer look at it. Thanks for letting us know about this. :)
