### ISSUE TITLE
Issues being erroneously moved by waffle.

### ISSUE THREAD

**Issue by TheDodd** [waffleio/waffle.io#2286]
We have a board with about 7 different repositories feeding it. One of the repos' tickets always seem to be moved back to the very first column no matter what we do in the ticket.

Most of our repos are private. The one that is causing us issues is a public repo however. Is this a known issue? Is there anything I should do to help diagnose the problem?

**Comment by kellihsf** [comment]
hi @TheDodd,

Sorry for the delay on this! Are you still experiencing this issue? If so, can you email us at support@waffle.io and let us know the name of the repo you're seeing this on? Thanks!

**Comment by kellihsf** [comment]
Hey @TheDodd,

We'll be closing this issue for now. Please email us if you're still having trouble and we'll look into it. :) Thanks!
