### ISSUE TITLE
URL to give read access to waffle board

### ISSUE THREAD

**Issue by robwithhair** [waffleio/waffle.io#2287]
Would be great if I could give read access to my waffle board so a client could see how we were progressing with a project, without giving them access to the private code repository.

**Comment by homeyer** [comment]
Hey @robwithhair, what works for us is having our primary repo be public (waffle.io/waffleio/waffle.io) but also associate private repos that hold our code to it. For example, you don't have access to github.com/waffleio/waffle.io-app, but we see it on our board when we're logged in. Would that work for you?

**Comment by ashumz** [comment]
@robwithhair, just a head's up that I talked with @homeyer about your specific scenario (needing a private primary source and also not being able to move hundreds of issues from your code repo into an Issues only repo easily) + why the above solution doesn't work best for you. 

Moving this back to our inbox for consideration based on your use case-- feel free to add details to the description if you'd like! Nothing planned immediately for the time being, but we'll definitely keep this open and in mind for future users who may be in the same boat.

**Comment by niemela** [comment]
Even better would be if I could give read access to a filtered version of my waffle board. E.g. https://waffle.io/waffleio/waffle.io?milestone=F11099:%20API%20GA or https://waffle.io/waffleio/waffle.io?label=API . 

If you only want support one thing, then labels would of course be the most flexible.

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
