### ISSUE TITLE
Drag cards into collapsed columns

### ISSUE THREAD

**Issue by smcoll** [waffleio/waffle.io#2288]
For example, as a developer, i don't need to see the "Done" column, so i have it collapsed.  But i would like to drag it into that gutter to have it moved.  As it is, i have to expand the column, move it, and then collapse the column again.

**Comment by ashumz** [comment]
<img width="1217" alt="dndforcollapsedcolumns" src="https://cloud.githubusercontent.com/assets/100216/12148384/5830a260-b45b-11e5-975c-870be1ce382c.png">

**Comment by ronanchilvers** [comment]
:+1: This would be a really good usability tweak.

**Comment by bulldetektor** [comment]
+1

**Comment by smorr** [comment]
Would be much appreciated :)

**Comment by thomasknoll** [comment]
+1

**Comment by Topher-the-Geek** [comment]
+1

**Comment by manoochehri** [comment]
+1

**Comment by geneswitch** [comment]
+1 this would be awesome.

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
