### ISSUE TITLE
Do not fire realtime events to the originating client for issue state (open|closed) changes

### ISSUE THREAD

**Issue by burtonjc** [waffleio/waffle.io#2290]
Repro Steps:
1. open a new card
2. drag it into done
3. wait a few seconds and you will see a realtime event

This can cause some bad behavior with archiving because if someone drags a card to done and archives it immediately, the realtime event will com through and re-add the card to the board until a refresh happens.

**Comment by homeyer** [comment]
something changes between when we close it with our request from app (initiated by the UI) and when the hook comes in from GitHub. (That's our guess at least.)

**Comment by ashumz** [comment]
also consider if we want to group these changes with other improvements to realtime events (what the alerts say for automatic work tracking (ie: getting 3 alerts for moving 1 unit (card + PR), moving a card to "done" and having the alert say 'closed' vs 'updated')

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
