### ISSUE TITLE
Change "Add Issue" wording

### ISSUE THREAD

**Issue by ashumz** [waffleio/waffle.io#2291]
The wording "Add Issue" immediately makes people think bug tracker or issue tracker,but Waffle aspires to be more, albeit in a lightweight and simple way. We should leave the noun up to the user, though. :) (One way we could still relate Waffle cards to GitHub Issues would be linking from the current Add Issue dropdown to the GitHub Issue "add" form with prepopulated info as we once discussed as a team.)

Options for changing "Add Issue" wording:

- + 
- Add 
- Add Card

**Comment by niemela** [comment]
FWIW, I think introducing more terminology would just complicate things. 

If your intention is that one should be able to have one of these thingies *without* an underlying GitHub Issue, then (and only then) I think "Card" would be a great name.

(I'm not saying that "Issue" is a great name, I personally much prefer "Ticket" or "Card", but it is what it's called on GitHub).

So, "-1" I guess.
