### ISSUE TITLE
change rally branding inside app

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#2294]
We've been asked to change the Rally branding inside the app to be CA Agile central.

- [x] update rally integration sales gate to be CA Agile central
- [ ] change intercom message when merge

**Comment by marydavis** [comment]
@homeyer should the word 'central' be capitalized?

**Comment by marydavis** [comment]
@homeyer is it still called UE? so CA Agile Central's UE product or just CA Agile Central?

**Comment by marydavis** [comment]
@homeyer we also link to https://www.rallydev.com/product-features/rally-unlimited-edition - do we still link to that?

**Comment by homeyer** [comment]
@marydavis let's go with CA Agile Central, and still link to rally, unless you can find a CA link for it
