### ISSUE TITLE
Make the timeline on the throughput graph adjustable

### ISSUE THREAD

**Issue by kellihsf** [waffleio/waffle.io#2297]

**Comment by kellihsf** [comment]
Customer requested:  trying to create a sprint burndown chart of 1-month to track task completion during our scrum. Adjusting the x-axis timeline on the throughput graph would be helpful

**Comment by kellihsf** [comment]
+1 from [waffleio/waffle.io#2263](https://waffle.io/waffleio/waffle.io/cards/5668bb09fe2c3f370068c04d), closed as duplicate.

"On the metrics screen, it would be nice to be able to filter the metrics not only by week but also by day, hour, year, month or even a specific date range. We have daily deployments so it would be awesome to track our velocity by day."

**Comment by minahaji** [comment]
+1 it would also be helpful if it spanned more than just 7 weeks

**Comment by songawee** [comment]
This issue has been resolved by the new throughput graph released in WaffleMetrics - http://blog.waffle.io/wafflemetrics/. With the new graph, you are able to specify the start date as well as the bucket size.
