### ISSUE TITLE
GoCode Colorado Collaboration

### ISSUE THREAD

**Issue by ashumz** [waffleio/waffle.io#2301]
- [x] add content for template to a fork of Hackshop 
- [ ] create help doc for GoCode attendees
- [x] andrew will build a bot once we get the OK :) (tracked in #2372)
- [x] decide if we can do any custom branding on boards with /gocode/ in url
- [ ] use GoCode style guide colors for labels 
- [ ] Add a "Get Started" card from Elaine's email content

**Comment by homeyer** [comment]
blocked until we have the "go!" from Go Code Colorado.
