### ISSUE TITLE
Link repository by tag only

### ISSUE THREAD

**Issue by apg** [waffleio/waffle.io#2305]
We have waffle board which tracks a lot of different repositories, but because we're only owners of a parts of a few, we need to use a label to find the relevant issues / PRs. 

In order for us to have a global view, however, we need to filter the board by the relevant label, kwyjibo. That means, that on fully owned repos, we must also tag everything kwyjibo. 

It'd be nice to have a repo level setting which filtered automatically. Thus, when I added the "scrabble" repo, which I'm a part owner of, I could say "filter by kwyjibo" for this board, for that repo only.

**Comment by ashumz** [comment]
Hey @apg, 

For the last part of your request, you should be able to filter by source as well as label for a given board to see only issues that belong to that source, with a given label. You would always be able to keep the board filtered by your 'kwyjibo' label, and just toggle the source selection in the filter dropdown for whatever source you'd like to exclusively see.

Beyond filtering by source and label together, is there a larger piece of functionality that you'd need to accomplish this? Apologies in advance if I've misunderstood any piece of your workflow or request!

Ashley

**Comment by apg** [comment]
I think I did a poor job of explaining. Let me use the correct terminology, which should help.

I'm part of a board which encompasses multiple sources. All of these sources are Github repositories which are owned by the organization, but some of them are owned by other teams within the organization. We sometimes have work to do on one of their repositories, `scrabble`, and as such a source has been added to our board, but without any filters, we see all of the work being done to scrabble, not just work relevant to ours.

As a way around this, we've added the label `kwyjibo` to work we own on the repository `scrabble`. But, now there's a problem. We only see *all* of our work work now if *all* issues and PRs have a `kwyjibo` label.

We'd love to be able to see all of our work without an extra step on the repositories we *own*. In other words, it'd be great if we didn't have to add `kwyjibo` to the repositories we own outright. The solution I proposed is that when you add a repository as a source, you can specify a *filter*. This would allow us to add the shared repository `scrabble` and attach a filter of `label:kwyjibo` and wouldn't require us to add `kwyjibo` to all other issues and PRs in the repositories we outright own and don't share. 

Does that describe the situation better?

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
