### ISSUE TITLE
change docs landing page to be dedicated to the API

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#2306]
We'll still use our wiki on GitHub for our core docs for now. So, let's change readme.io to be specific to the API.

**Acceptance Criteria**
- [x] make the page "feel" like API docs. "Getting started with the Waffle API", etc.
- [x] The only section should be "API"
- [x] create pages for what we think we need:
  - [x] Authentication
  - [x] Current User (for the page you have already)
  - [x] Projects
  - [x] Cards
  - [x] Columns

**Comment by homeyer** [comment]
copy the styling of developers.watsi.org :)

**Comment by marydavis** [comment]
always been a fan of https://stripe.com/docs/api#intro styling too :)

**Comment by waffle-with-pears** [comment]
+1 on Stripe styling!

*Ashley McClelland*
Waffle.io
http://waffle.io
