### ISSUE TITLE
Allow hash "#" in pasting into new label color field

### ISSUE THREAD

**Issue by joelworsham** [waffleio/waffle.io#2308]
If you copy/paste a new hex color into the new label color field (when creating a new column and assigning it a label), if you include the hash `#` in the copy/paste, the field will cut off the last character from the hex color, and leave the `#` in the field. Example:

1) Copy color from something (like a color picker) that reads `#ffffff`
2) Paste that into the new label color field
3) Field now reads `##fffff`

It would be great if this field could handle including the `#` in the copy/paste.

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
