### ISSUE TITLE
Have Project Template to Setup Github Issues and Status Column

### ISSUE THREAD

**Issue by mc706** [waffleio/waffle.io#2309]
As a user who uses a lot of boards and starts a lot of projects, it would be greatly helpful if I could template out all of my labels and columns saved that I could apply to a board. 

I should be able to save a list of issues, their names and colors, to my account, and apply that template to a new repo. Since I have started using a more complex labeling system that has a color scheme and name scheme.

Also working on teams, It is helpful to have more than the default columns. Being able to save the setup and apply it to a new project would be greatly helpful

**Comment by WebDevJL** [comment]
@ashumz Any idea when this could be done? Thanks.

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
