### ISSUE TITLE
more granular automatic work tracking actions in Settings->Columns

### ISSUE THREAD

**Issue by ashumz** [waffleio/waffle.io#2311]
Currently if you use the 'connected' keyword in a PR title or description, followed by an issue reference, we'll move that Issue and the PR into "In Progress" and nest the PR beneath the issue. The column we move the issue to is based on your "Work Started" Action in Settings->Columns.

Since this behavior is different than issuing a "closes/fixes/resolves" PR (those go to the column specified for "New Collaborator PR's"column in Settings->Columns), we should differentiate between the actions available based on the type of PR you issue (using the "Connected" keyword, using the "Closing" keyword, or issuing a standalone PR.)

Suggestion: 
New Collaborator PR's would become "New Collaborator PR's", "New Closing PR's", and "New Connected PR's" to allow us to be completely clear where your PR will go based on the language you use. 

The defaults we have today are a great start, but if we were to break down the actions we are taking to be more granular, we'll give users better visibility into what actions we're taking and when/why

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
