### ISSUE TITLE
update language for project creation banner to emphasize "Create Project" action

### ISSUE THREAD

**Issue by ashumz** [waffleio/waffle.io#2312]
Currently says "Like what you see? Create this repo as a project in Waffle to get started. [Let's go!]"
This sounds like you're creating the repo (when it's already created in GitHub) and has caused some confusion. 

Options
- "This GitHub repository doesn't have an official Waffle board yet. Like what you see? [Create Project]"

- The GitHub repository repo/reponame doesn't have a Waffle board yet. Like what you see? [Create Project Now]) 

- Create your Waffle board for this repository to start interacting with your GitHub Issues and Pull Requests [Get Started Now]

Open to language changes -- just need to make the button read "Create Project" and clarify that the repo exists but the Waffle project does not (yet.)

**Comment by ashumz** [comment]
"Like what you see? Create a Waffle board for your repository now.[Let's go!]"

**Comment by kellihsf** [comment]
The entire banner could be reworked... closing this for now, assuming we'll measure the right things when working on the onboarding flow to increase conversions. We don't want to do this work until we can measure (and have time to measure) the impact.
