### ISSUE TITLE
Auto Planned Column

### ISSUE THREAD

**Issue by mc706** [waffleio/waffle.io#2314]
Add ability to add a "Planned" column that can automatically move cards from the backlog or inbox into it when cards are estimated.

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
