### ISSUE TITLE
no horizontal scrollbar displayed

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#2318]
Chrome, OSX.
Try to roadmap board: waffle.io.waffleio/roadmap.

**Comment by marydavis** [comment]
@homeyer this seems to be an issue only when you have collapsed columns - can you confirm?

**Comment by vegad** [comment]
Chrome on Win 7 is missing horizontal scrollbar when any column is collapsed too.

**Comment by kellihsf** [comment]
another user reported same behavior [here](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/2000432292). User is on Chrome Windows 7, not seeing horizontal scroll bars with columns collapsed and uncollapsed.

**Comment by zoni** [comment]
This seems to be browser-independent as I'm running into the same issue with Firefox 45.0 on Linux.

As far as I can tell, it does *only* happen while one or more columns are collapsed. As soon as all are expanded, the scrollbar becomes visible again.

**Comment by TheGrandmother** [comment]
I can confirm this on google-chrome  48.

**Comment by sondangdev** [comment]
I have this issue on Chromium when any column is collapsed too

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
