### ISSUE TITLE
Support filtering by @mentions

### ISSUE THREAD

**Issue by dmehra** [waffleio/waffle.io#2319]
The use case is that I want to see which open PRs have @mentioned me, so I can review them. 

Currently I have to do this in each GitHub repository with [mentions:me](https://help.github.com/articles/searching-issues/#search-by-a-mentioned-user-within-an-issue-or-pull-request) search. 

When you have multiple repos, it's easy to lose track of PRs you were supposed to comment on, but didn't right away, and then work is blocked and you look like a git who's ignoring people's asks for review.

I'd like this to be a filtering option in Waffle so I can do the search across all repos that are linked to my waffle board.

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
