### ISSUE TITLE
Check boxes aren't staying checked when multiple users check boxes

### ISSUE THREAD

**Issue by kellihsf** [waffleio/waffle.io#2325]
Two users have the issue open. The first one checks one box, the second one then checks another box. When the first  user refreshes, only the second user's box has been checked.

**Comment by kellihsf** [comment]
[Customer reported](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/1689741411)

**Comment by declanhart-ThoughtWorks** [comment]
Clarification: any changes made by the first person on the issue (either on waffle or GitHub) are not reflected on the second person's screen and therefore overwritten when a change is made

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
