### ISSUE TITLE
Bug: Showing issues that don't exist in the repository

### ISSUE THREAD

**Issue by fsaravia** [waffleio/waffle.io#2326]
RIght now, waffle is showing me an issue that doesn't exist in the corresponding GitHub repository: http://cl.ly/0e2G2Y421Z42

The corresponding waffle board is https://waffle.io/attm2x/m2x-service

**Comment by kellihsf** [comment]
hi @fsaravia,
Sorry for the delay on this! Are you still experiencing this issue?

**Comment by fsaravia** [comment]
hi @kellihsf,

Yes, I'm still seeing the same card on waffle about the same issue that does not exist (and AFAIK has never existed) on the corresponding repository https://github.com/attm2x/m2x-c/issues/12, please let me know if I can be of any help debugging

**Comment by kellihsf** [comment]
@fsaravia,

Could you email us at support@waffle.io so we can take a closer look? Thanks!

**Comment by fsaravia** [comment]
@kellihsf done!

**Comment by kellihsf** [comment]
Great, thanks! Looking into it now. :)

**Comment by kellihsf** [comment]
hi @fsaravia,

We've responded via our in-app messaging system. We'll close this card for now so we can correspond through there. Thanks!
