### ISSUE TITLE
update Rally cards to CA Agile Central

### ISSUE THREAD

**Issue by marydavis** [waffleio/waffle.io#2330]

**Comment by homeyer** [comment]
what are "Rally cards"?

**Comment by waffle-with-pears** [comment]
All cards on our board referencing "Rally"


On Jan 19, 2016, at 12:52 PM, Andrew Homeyer <notifications@github.com>
wrote:

what are "Rally cards"?

—
Reply to this email directly or view it on GitHub
<https://github.com/waffleio/waffle.io/issues/2330#issuecomment-172932598>.
