### ISSUE TITLE
Closing a issue on github duplicates card on waffle.io

### ISSUE THREAD

**Issue by nbartels** [waffleio/waffle.io#2331]
I have the waffle.io view open in a browser tab and at the same moment someone closes an issue on Github.

The card is duplicated and can be seen in the closed column and in the column of the state before. After reloading everything's fine.

I reproduced this several times.

**Comment by kellihsf** [comment]
hi @nbartels,
Thanks for letting us know about this. We weren't able to reproduce this behavior, so would you email us at support@waffle.io with your project name? We'll be able to look into this further. Thanks!

**Comment by nbartels** [comment]
Just tried again and I cannot reproduce it anymore. So I close this issue.
