### ISSUE TITLE
Unable to move multiple cards from Backlog to Ready Column

### ISSUE THREAD

**Issue by RMCornell** [waffleio/waffle.io#2332]
Been attempting for 12 hours now (not straight) to move cards from the backlog to the ready column. 

It will move one card, but then when I move the next, it will replace the card previously moved with the second card and put the first card back in ready, functionally making it impossible to have more than one card in the ready column. 

Thus far I have:

1. Logged out and back into Waffle.io
2. Cleared Cookies
3. Attempted on different browsers (Chrome/Chrome Canary)

Thoughts?

**Comment by kellihsf** [comment]
hi @RMCornell,

Can you email us at support@waffle.io with your project name so we can take a closer look? Thanks!

**Comment by kellihsf** [comment]
Hey @RMCornell!

We'll be closing this issue for now. Please email us if you're still having trouble and we'll look into it. :) Thanks!
