### ISSUE TITLE
Add ability to close issue from within Waffle project interface.

### ISSUE THREAD

**Issue by DS-Matt** [waffleio/waffle.io#2333]
It's great that you can view and comment on an issue within the Waffle interface, but it would also be nice to be able to close an issue or "comment and close" via that same waffle interface modal.

Thanks!

Matthew

**Comment by kellihsf** [comment]
Hi @DS-Matt,
Would commenting  in the card modal then drag the card over to the  Done column work for you?  (you could archive the card after to remove it from the board) Or were you thinking more along the lines of a close & comment button?

**Comment by DS-Matt** [comment]
Hi @kellihsf -

While you are correct a user could comment, then close the modal and then move the issue to the done - but that makes it a two step process - while if inside the modal for commenting on an issue in Waffle it would be ideal if you could comment and close the issue inside the modal (such as a single button to close and comment).  

Example: 

Contributor creates a feature request issue that is a duplicate - if you view the issue in Waffle, it would take two steps to reply back to feature request indicating it's a duplicate then dragging the issue to done.  If the close and comment button existed in the modal - you could accomplish both tasks with just one click.

So, long answer - yes I was leaning more towards a close & comment button added to the issue modal in waffle (which would match the issue comment buttons Github has).  FYI - I didn't realize that by dragging the issue to the done column in waffle that it would automatically close the issue (i've been opening issues via the see in github button inside waffle -- in a new tab -- and then closing them on Github).  I guess I just feel a close and comment button in the issue comment modal creates a better user experience.  

Thanks! 

Matthew

**Comment by kellihsf** [comment]
Hey @DS-Matt,

Thanks for the feedback on this! This issue is already being tracked at [waffleio/waffle.io#2152](https://waffle.io/waffleio/waffle.io/cards/5629794c8b543738007a0cd8), so we'll close this as a duplicate. I'll add your comments and +1 to the existing issue. You can subscribe to the issue in GitHub and leave any additional comments or feedback around your use case to the existing card.  :)
