### ISSUE TITLE
When commenting on an issue and you hit escape warn the user it will close the dialog and cause their comment to be lost

### ISSUE THREAD

**Issue by billrawlinson** [waffleio/waffle.io#2335]
When you've spent a bit of time typing a comment on an issue in the issue popup if you accidentally hit escape the issue closes and the entire comment is lost.

It would be nice if you were warned about the closing popup so you could stop the close before you lose your work

**Comment by kellihsf** [comment]
hi @billrawlinson, 
This issue has been resolved. Hitting esc now will just blur the text area and not clear text or close the modal. (Hitting esc twice will close out the issue modal.)

**Comment by billrawlinson** [comment]
Awesome.  Thanks for the prompt improvement.
