### ISSUE TITLE
Planning poker integration

### ISSUE THREAD

**Issue by kellihsf** [waffleio/waffle.io#2338]
Have a team be able to vote on issue size within Waffle. A simple interface for voting would be good.

**Comment by jwoodcock** [comment]
As the one that requested this feature, what would be nice is if I could just grab tickets assigned to a milestone, or tag, and pull them into a voting window. This voting window would be similar to what planitpoker.com is doing, based on the point voting system: https://en.wikipedia.org/wiki/Planning_poker. 

Of course other people in my team would need to be able to join and vote. 

Thanks! I know this is not a simple task.

**Comment by TTcrockeTT** [comment]
+1

**Comment by xexeo** [comment]
I second.
It will be a very valuable thing for remote and local groups that are not always face to face.

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
