### ISSUE TITLE
Investigate/fix errors in hooks

### ISSUE THREAD

**Issue by burtonjc** [waffleio/waffle.io#2342]

**Comment by burtonjc** [comment]
Looks like when we auto-assign issues to users, we sometimes try to assign them to users who are not allowed to own the issue. Maybe people with only read access to the repo and they are opening a PR? See [this error](https://rpm.newrelic.com/accounts/783175/applications/5005817/traced_errors/4c61fb-2fbcbcf7-c162-11e5-9b9f-f8bc12425d50) in newrelic for more an example.

**Comment by homeyer** [comment]
Punting on this for now.
