### ISSUE TITLE
Project API Documentation

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#2344]
- [x] describe the project object on the base project page (https://dash.readme.io/project/waffleio/v1.0/docs/project)
- [x] describe what a project is (e.g., a board is a project), and what information is stored on a project.
- [x] describe the source properties, and how they relate to github repos
- [x] document all project API pages, with example requests and responses

**Comment by homeyer** [comment]
Can you add a few things:
- [ ] curl example for GET /user/projects
- [ ] curl example for GET /projects/:id
- [ ] curl example for GET /projects/:owner/:repo
- [ ] curl example for DEL /projects/:id
- [ ] curl example for /projects/:id/sources
- [ ] describe what the properties are for /projects/:id/sources, and add an explanation for the `provider` property
- [ ] curl example for PUT /projects/:id/sources/:id
- [ ] curl example for DEL /projects/:id/sources/:id, and also mention that you can't delete the primary (first) source

**Comment by ashumz** [comment]
moved to card #2452 for extra items
