### ISSUE TITLE
Webhooks API documentation

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#2346]
- [ ] document base webhook page: what is a webhook?
  - [ ] document what type of events you can register to listen for
  - [ ] what the event body looks like
  - [ ] how to check the security header to verify the sender
- [ ] document webhook API sub pages

**Comment by kellihsf** [comment]
blocked by  GET /project/:id/hooks request

opened a card for this: [#2500](https://github.com/waffleio/waffle.io/issues/2500)
