### ISSUE TITLE
Better PR icon visibility with solid backgrounds

### ISSUE THREAD

**Issue by adamralph** [waffleio/waffle.io#2353]
Rather than a coloured icon on a white background, these would be far more visible if they were a white icon on a solid background, similar to those used in GitHub. This would also make it much easier to discern the colours e.g.

![image](https://cloud.githubusercontent.com/assets/677704/12244756/73b80c46-b8a5-11e5-8215-e4c92ca0db07.png)
![image](https://cloud.githubusercontent.com/assets/677704/12244872/f4e390ec-b8a5-11e5-8d3d-8616a80b3705.png)
![image](https://cloud.githubusercontent.com/assets/677704/12244943/402d860c-b8a6-11e5-94f6-3b487a00afaf.png)

(Note that I am using the GitHub colours, as suggested in https://waffle.io/waffleio/waffle.io/cards/566e975d238d9b950091b99a)

**Comment by laughedelic** [comment]
+1

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208

**Comment by adamralph** [comment]
My reaction to this is echoed here:

https://github.com/waffleio/waffle.io/issues/2546#issuecomment-310020838
https://github.com/waffleio/waffle.io/issues/2546#issuecomment-310022479

**Comment by homeyer** [comment]
This one is a `wont fix`, we're going to stick with the GitHub styled PR icons:
![image](https://user-images.githubusercontent.com/84629/27407655-837e1a72-5696-11e7-8fdb-b333ae191003.png)

We are planning on showing merged vs just open/closed: https://github.com/waffleio/waffle.io/issues/1630

**Comment by adamralph** [comment]
@homeyer thanks for the response. I agree that it makes sense to match the icons with those used in GitHub. So, I'll take my campaign for solid icons with a background over to the GitHub guys instead. 😉 

> This one is a `wont fix`...

The comment made when closing the issue contradicts this. It suggests that it is something you want to do, but don't have time for it yet. It would have been better to have made the "won't fix" comment with the explanation when closing the issue.

**Comment by homeyer** [comment]
Agreed, thanks for the feedback.
