### ISSUE TITLE
If a standalone pull request is associated or connected to an Issue *after* it has been created, the PR moves to the column for that Issue (instead of the Issue receiving the same column label as the current PR.)

### ISSUE THREAD

**Issue by ashumz** [waffleio/waffle.io#2355]
(See #2354 for a potential solution to this per conversation with @homeyer about the difficulties around picking up the card/PR association after the PR has been issued.)
## Steps to Replicate
- Create a new Issue in the backlog (ie: `#12`) 
  -> Issue is created with no column label associated and appears in the Backlog column
- Create a pull request not connected to an issue
  -> The PR will appear on your board as a standalone pull request card
- Realize that your new PR actually fixes `#12` and chaange the pull request title to use the proper association language (ie: `"fixes #12"`)
  -> After a refresh (or trigger of the sync process from some other board update), the PR will move to the backlog and be nested/connected beneath `#12`. The Issue will remain without a column label, and the PR will keep it's original label ("In Progress" by default, but customizable and determined by the "New Collaborator PR" action in Settings->Columns.) 

Expected behavior would be for `#12` to receive the same label as the PR, and for the PR and Issue to appear in the appropriate column based on the PR label.
## When Does This Happen?

Fairly often. The two most common cases are: 
- users accidentally use wording like "fixes issue 12" where the language should read `"fixes #12"`. 
- users completely forgot to connect the PR to an Issue and later decide they want to

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
