### ISSUE TITLE
Collapsible columns aren't working on IE

### ISSUE THREAD

**Issue by kellihsf** [waffleio/waffle.io#2366]
Customers reported, both on IE 11

**Comment by kellihsf** [comment]
[Intercom conversation](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/1808119947)

**Comment by kellihsf** [comment]
also reported in [Intercom](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/search/conversations/1515788389?q=internet%20explorer)

**Comment by ChrisM-S** [comment]
Just wondered if anyone has had a chance to look at this one?  If there was some way to reset a column in IE as a workaround that would be great (the columns in chrome work but expanding/contracting these does not fix the same columns when viewed from IE.
many thanks
Chris

**Comment by kellihsf** [comment]
also reported in [Intercom](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/4380242486)

**Comment by kellihsf** [comment]
reported in [Intercom convo](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/6512806626)
