### ISSUE TITLE
Show issue history in comment view

### ISSUE THREAD

**Issue by DS-Matt** [waffleio/waffle.io#2373]
While it is possible to use the "Show in Github" button on a card, it would be nice if the comments view showed the whole history of the issue (like it does on github - using the same icons, timeline style, etc).  

This would include: 
Label assignment and reassignment
Milestone assignment and reassignment
User assignment and reassignment
Commit message references - with the commit hash so you can see the actual code commit when clicking on the link. 

An example would be to look at the cards in Overv.io and how they show issue history.

Thanks!

**Comment by kellihsf** [comment]
Hey @DS-Matt,

Thanks for this request! We're already tracking this issue at [#972](https://github.com/waffleio/waffle.io/issues/972) so we'll close this one as a duplicate. We'll add your comments to the existing issue and you can subscribe to the issue in GitHub to add any additional comments or feedback around your use case to the existing card.
