### ISSUE TITLE
Ability to Create a milestone within Waffle.io

### ISSUE THREAD

**Issue by DS-Matt** [waffleio/waffle.io#2374]
Add the ability to create a new milestone for any of the associated repos on a waffle board from within the waffle.io interface.

**Comment by kellihsf** [comment]
hi @DS-Matt,

Thanks for the request! This issue is already being tracked at [#909](https://waffle.io/waffleio/waffle.io/cards/5363e987ebef97b1f959af6b) so we'll close this issue as a duplicate.
