### ISSUE TITLE
Column background color should match label color

### ISSUE THREAD

**Issue by bulldetektor** [waffleio/waffle.io#2375]
It would be nice if you could use the color of the associated label as background color for the column. E.g. 
Given you have a label _testing_ in GitHub with a color code of **#bfe5bf**
When you configure a column _Testing_ in Waffle to map to the _testing_ label i GitHub
Then the background color of the colunn _Testing_ in your board should be **#bfe5bf**

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
