### ISSUE TITLE
Card stuck

### ISSUE THREAD

**Issue by superkhau** [waffleio/waffle.io#2376]
https://github.com/strongloop/loopback-example-rest-connector/issues/10

The repo has been deleted, but I can't delete the card in waffle. What can I do?

**Comment by homeyer** [comment]
Hey @superkhau, that repo is still listed as a source for the project strongloop-internal/scrum-loopback. Can you go to the project settings and remove it as a source?

**Comment by superkhau** [comment]
@homeyer It worked! TY. ;)

**Comment by homeyer** [comment]
:+1:
