### ISSUE TITLE
Add explanation of how to delete primary board

### ISSUE THREAD

**Issue by kellihsf** [waffleio/waffle.io#2380]
Would be helpful to customers to know where to go in order to delete the primary repo. When deleting a source, the popup says 'Cannot delete primary Waffle project repository' but doesn't say how to/where to delete primary repo.

**Comment by marydavis** [comment]
what do we want it to say instead?

**Comment by kellihsf** [comment]
Maybe just describe where you can go to delete the primary repo. To me the wording sounds like it's not possible at all to do this. I think a  simple 'Go to Project Settings->General to delete main repo' would be good.

**Comment by carrieje** [comment]
I come from Google Search to get this exact information.
In fact I don't even know what a "primary waffle project" is :D Why "primary" ?
And I expected to find my answer here :)

Just so you know that, some users are actually wondering the way you predicted ;-)
(I successfully deleted my board with your leads, thanks).

**Comment by axniks** [comment]
what @carrieje said :D

**Comment by supermanue** [comment]
+1 to @carrieje . I did in fact spend quite a lot of time looking for this on waffle, not intuitive at all.
