### ISSUE TITLE
Unable to see right-most columns if all columns expanded

### ISSUE THREAD

**Issue by aprevost** [waffleio/waffle.io#2382]
My project has 11 columns (more than ideal, I know, but we've done a lot of sorting and prioritizing of issues in our backlog). The only way I can look at the right-most columns is if I collapse at least 7 of the columns further to the left.

In my browser at least (Chrome), there is no longer any scroll bar at the bottom of the window that allows me to scroll over from the left-most column to the left-most column and back if all columns are expanded and they go wider than my screen can display.

This happened when you added the feature to collapse columns - a good feature. But before you added it I was able to scroll from left to right across all 11 of my fully expanded columns no problem. Since you added the collapsible columns feature, I can no longer scroll, I have to collapse columns in order to see my right-most columns. Inconvenient.

**Comment by kellihsf** [comment]
hi @aprevost,

Thanks for reporting this! This issue already exists so we'll close this as a duplicate. We're tracking this issue [here](https://github.com/waffleio/waffle.io/issues/2318) if you want to follow it's activity. :)
