### ISSUE TITLE
Metrics going back more than 7 weeks.

### ISSUE THREAD

**Issue by blakewest** [waffleio/waffle.io#2384]
I'd love to see even just the existing metrics going back at least 1 year. Though I mean, hey, I'd take 3-6 months too. 7 weeks just seems like not enough time to get a sense for whether the velocity of the team is actually changing, or if it's just noise over the last several weeks.

**Comment by songawee** [comment]
This issue has been resolved by the new throughput graph released in WaffleMetrics - http://blog.waffle.io/wafflemetrics/. On the new graph, to go back more than a year, you'll need to update the "Start" parameter. Let us know if you have any other issues or comments. Thanks!
