### ISSUE TITLE
Is there a way to filter on milestones matching a certain pattern?

### ISSUE THREAD

**Issue by andreasohlund** [waffleio/waffle.io#2385]
### Background

We have a board that aggregates multiple repos and we want to filter all issue "currently being patched" across all those repos.

We follow semver so the algorithm to find them is:

`select * from issues where !Milestone.EndsWith("0")`  (Please forgive my pseudo sql here :)  )

Is there a way to do this?

Note: Yes we could write our own automation to make sure that there is some kind of label "being patched" that matches the criteria but wanted to see if waffle supports this OOTB first.

**Comment by kellihsf** [comment]
Hey @andresohlund, sorry for the super late reply, we totally dropped this.

No, there isn't a way to filter based on a pattern right now, but your idea to always label as "being patched" would work well.

We're going to keep this issue open in "ideas" so others who have this same thought can find it.

**Comment by andreasohlund** [comment]
Thanks for the feedback, we've solved this by having a dedicated "things being patched" repo to track so its not urgent for us atm.

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
