### ISSUE TITLE
grey out 'add issue' button if no Waffle project exists for a given repo - causing unneeded errors

### ISSUE THREAD

**Issue by ashumz** [waffleio/waffle.io#2386]
Right now, if a board is part of an org and you try to create an issue, but Waffle is not an approved application for that project, you get an "unable to create card" error. 

We should grey out Add Issue unless we have a project for the repo. This will avoid unneeded errors when org permissions are restrictive of Waffle.

This occurs not just if Waffle access has been revoked, but also if 3rd party restrictions are enabled for an org (and Waffle is not an approved application.) 

If we had a way to check if Waffle was an approved application for an org, or if an org didn't have third party app restrictions enabled (now a default, so we see this a lot more), we could allow non-projects to have issues added. Otherwise, we're likely to have people run into these errors for org boards that have restrictions enabled, and that seems like a worthwhile reason to disable unless the repo is project-ized (after talking with Andrew, sounds like this clears up some amount of complexity on our end, too.) 

Additional benefits include more visibility/attention to the "create project" banner, as I have observed several users starting to add issues to Waffle before realizing they hadn't created the project yet. :) 

other ideas: We have an error that says "No project has been created for this repo"or something along those lines that we could use  if the button is attempted to be clicked or a hover that says 'this project hasn't been created in waffle yet'

**Comment by kellihsf** [comment]
punting on this since we can't tell if it's approved or not. When we have better support for orgs we can rethink it.
