### ISSUE TITLE
Add a simple markdown editor for issue card description (enhancement)

### ISSUE THREAD

**Issue by joseluisq** [waffleio/waffle.io#2387]
It would be awesome that _Issue Card Description_ (textarea) could support 
a _simple markdown editor_ for more a flexible and easy editing.

Now:

![image](https://cloud.githubusercontent.com/assets/1700322/13029869/0ac4eed6-d266-11e5-8ab4-a99b44645760.png)

**Comment by antoineazar** [comment]
:+1:

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
