### ISSUE TITLE
Integer validation for input fields

### ISSUE THREAD

**Issue by prameelapodigiri** [waffleio/waffle.io#2388]
Hi Team,

  I need input integer validation for input field

My piece code here
---------------------------------
var successMessageEntry = entryFactory.textField({
			    id: 'successMessage',
			    description: '',
			    label: 'Success Msg',
			    modelProperty: 'successMessage',
			    validate: function(element, values) {
			      var successMessageValue = values.successMessage;
			      
			      var validationResult = {};
			      var businessObject = getBusinessObject(element),
			       newObjectList = [];

			      var bo = getBusinessObject(element);
			      var assigned = bo.$model.ids.assigned(successMessageValue);

			      var idExists = !!assigned && assigned !== bo;
			      if (!successMessageValue || idExists) {
			        validationResult.id = "Element must have an unique id.";
			      }
			      
			     return validationResult;
			      
			     if (typeof values.successMessage !== 'undefined' && values.successMessage !== '') {
			 	     newObjectList.push(bpmnFactory.create('bpmn:SuccessMessage', {
			 	       text: values.successMessage
			 	     }));
			 	   }
			    }
		  		
			  });
		 group.entries.push(successMessageEntry);

Thanks
-prameela

**Comment by kellihsf** [comment]
hi @prameelapodigiri,

We've responded to this issue via our in-app messaging system! We'll close out this issue so we can correspond through there. Thanks!
