### ISSUE TITLE
Would like to see a milestone progress overview

### ISSUE THREAD

**Issue by cjsaylor** [waffleio/waffle.io#2394]
Not sure where it would be appropriate, but would love to see a progress bar of closed vs. open tickets associated to a milestone.

It would also be helpful if that progress was grouped among multiple projects that share the same milestone.

Similar feature wise to what Github offers:

![image](https://cloud.githubusercontent.com/assets/157755/13122256/1c81bdd6-d584-11e5-8306-97ffbea429c2.png)

**Comment by kellihsf** [comment]
hi @cjsaylor,

Thanks for the request! We're actually already tracking this issue here: [#1623](https://waffle.io/waffleio/waffle.io/cards/547846b47abdfe69dabaf4f3), so we'll close this as a duplicate. I've added your comments to the already open issue. :)

**Comment by kellihsf** [comment]
reopened, was included on the wrong card for a different issue

**Comment by cjsaylor** [comment]
@kellihsf Thanks for looking!

**Comment by laughedelic** [comment]
+1. Another idea for the milestones progress overview is grouping issues on the board by milestones. I saw feature like this in https://overv.io: board is split on horizontal sections one per each milestone. This would be much more convenient (for me) than filtering (which is hidden somewhere and requires at least 3 clicks to access).

**Comment by avengerpenguin** [comment]
+1

**Comment by homeyer** [comment]
Closing this in favor for our milestone burndown feature.
