### ISSUE TITLE
Can a badge track multiple categories?

### ISSUE THREAD

**Issue by gappleto97** [waffleio/waffle.io#2395]
I have two columns for issues in progress. One is for In Progress, where I'm still actively working on it. The other is In Review, where there is little to no work left, except for verifying results.

Is there any way that I could get a badge tracking both of these columns summed?

**Comment by kellihsf** [comment]
hi @gappleto97,

You can track multiple columns with the badges, you'll just change the column name in the badge code snippet (Project Settings->General), but there's no way to get the sum of multiple columns. Thanks!
