### ISSUE TITLE
Import Tasks / Close Tasks in Redbooth

### ISSUE THREAD

**Issue by moxojo** [waffleio/waffle.io#2396]
Our marketing team uses Redbooth (https://redbooth.com) for their project management. As much of what they dream up will end up requiring developers we would like to be able to import / sync tasks to github or waffle where they can then be managed per our developers workflow. 

Right now Zapier provides an import feature when a task is created in Redbooth which then creates an issue in Github. But the integration is not very tight and there is no two way communication. Ideally I would love to see Redbooth and Waffle communicate so that when an issue is being worked on and when it is closed there are status updates in Redbooth and the task is closed automagically when it hits the "done" column in Waffle.

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
