### ISSUE TITLE
Make waffle work without an associated repo

### ISSUE THREAD

**Issue by gappleto97** [waffleio/waffle.io#2397]
It would be super cool if I could also use this as a standard issue tracker for day to day life. I get if that's not a priority though.

**Comment by kellihsf** [comment]
hi @gappleto97 ,

We don't have anything like this available yet. But, your team could create a repo and use issues that aren't connected to code. We do this with our business work and store it on our board alongside other development repos.  Would something this work for what you're looking for?

**Comment by gappleto97** [comment]
Sort of, it's just a lot less convenient. Especially since it exposes those
issues publicly, where this would be less true if it were on your site
alone.

**Comment by connormlewis** [comment]
I also would like to see this functionality. Its the only thing keeping several of the organizations I work with from dropping Trello completely. Currently we use both which causes a large headache and frustration.

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
