### ISSUE TITLE
Autocomplete for team @-mentions

### ISSUE THREAD

**Issue by lloydwatkin** [waffleio/waffle.io#2400]
Would it be possible to get an autocomplete on team names so I can more easily @-mention them?

**Comment by Ma27** [comment]
:+1: would be great!

**Comment by jmgate** [comment]
+1

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
