### ISSUE TITLE
Move to column when closes comment in non-master branch

### ISSUE THREAD

**Issue by baynezy** [waffleio/waffle.io#2401]
When using the close comment (closes #issue number) if it is pushed to an elected branch (e.g. develop) then this should be an action so you are able to auto move to a column.

This would allow features merged into develop in Gitflow to go into a 'Next Release' for example.

**Comment by gappleto97** [comment]
+1

**Comment by baynezy** [comment]
@kellihsf out of interest what is the ci/cd label for?

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
