### ISSUE TITLE
Can "connect to" syntax be used in PR comments?

### ISSUE THREAD

**Issue by PaulWalkerUK** [waffleio/waffle.io#2403]
Someone just submitted a [PR](https://github.com/utPLSQL/utPLSQL/pull/8) where they *referred* to an issue number, but didn't use the waffle keywords `connects to` etc. I've added the special phrase as a comment, but waffle doesn't seem to have picked that up.

*Can* this syntax be used in comments or is it only in the title it can be used? If it *is* only the title, are there any thoughts about extending it to comments?

**Comment by kellihsf** [comment]
hi @PaulWalkerUK,

Unfortunately, we don't support comments yet.  The issue reference has to be in either the title or description of the PR.  No immediate plans on extending to comments at this time. (we do have a request for supporting commit messages on [#793](https://waffle.io/waffleio/waffle.io/cards/53480464ebef97b1f9598f00) ) Thanks!

**Comment by PaulWalkerUK** [comment]
No problem, thanks for the feedback

**Comment by kellihsf** [comment]
You're welcome! :)
