### ISSUE TITLE
Attach files

### ISSUE THREAD

**Issue by rg-net** [waffleio/waffle.io#2406]
Github allows issues. I'd like to be able to attach files in comments and issues via

**Comment by lloydwatkin** [comment]
Yes this would be great, it means the product team (for us) can use just a single app then (rather than having to open github to add images)

**Comment by mattfletcher** [comment]
Duplicate of #846

**Comment by kellihsf** [comment]
hi @rg-net, 

As mentioned above,  we're already tracking this issue on #846 so we'll close this as a duplicate.  Since you've already added your +1 to the  existing issue, I won't add an additional one. Thanks!
