### ISSUE TITLE
[Bug] Browser tab freezes when accessing the wrong route.

### ISSUE THREAD

**Issue by 6temes** [waffleio/waffle.io#2410]
Steps:

- Access https://waffle.io/:company/:project/metrics/throughput
- Wait some seconds
- Access https://waffle.io/:company/:project/metrics/
- Browser tab freezes.

**Comment by kellihsf** [comment]
hi @6temes,

Would you mind emailing us at support@waffle.io with your repo name so we can take a closer look? Thanks!

**Comment by kellihsf** [comment]
This will be fixed when we re-introduce the metrics dashboard page.
