### ISSUE TITLE
AWS codecommit support

### ISSUE THREAD

**Issue by patrickpierson** [waffleio/waffle.io#2411]
Amazon Web Services (AWS) offers private github repos (called CodeCommit) but no issue tracking.  I would love to be able to have waffleio on codecommit to do issue tracking.

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
