### ISSUE TITLE
+1

### ISSUE THREAD

**Issue by mikedomanski** [waffleio/waffle.io#2412]
+1

**Comment by kellihsf** [comment]
hi  @mikedomanski,

Anything we can answer for you?

**Comment by mikedomanski** [comment]
BLUF:  need an ios app for waffle -> GitHub so I can track projects on my mobile device.

Work for the VA, wanted to use Trello, but our wonderful security folks blocked a lot of the functionality outside the firewall/gateways.  The Trello app on ios is great, but my #1 wish list is to have a waffle apt on my mobile.

**Comment by kellihsf** [comment]
@mikedomanski,

I was going to  let you know we have a request for this already on our board but it looks like you beat me to it! We'll be closing out this issue as a duplicate. Thanks!
