### ISSUE TITLE
Backlog column isn't filtered in Firefox

### ISSUE THREAD

**Issue by carolynvs** [waffleio/waffle.io#2413]
Mac OS X Yosemite
Firefox 44.0.2

When I enter a search term in the query box, all columns are filtered as expected _except_ the backlog column. This happens in Firefox only, not Chrome or Safari.

![firefox-filter-problem](https://cloud.githubusercontent.com/assets/1368985/13333464/c81ab30c-dbcc-11e5-9012-78f1fbe42fd9.png)

Note that the backlog did not have a single item filtered out, and the top cards do not contain the search term.

**Comment by cpeterso** [comment]
@carolynvs Do you have any Firefox add-ons installed? Do you see error messages in Firefox's web console? You can open the web console using the keyboard shortcut `OPTION`+`CMD`+`K` or in the `Tools` menu > `Web Developer` menu item > `Web Console` menu item.

I was not able to reproduce the filter problem in my test waffle board using Firefox 44.0.2 on OS X 10.11.

**Comment by carolynvs** [comment]
Thanks, it must have been a rogue plugin. I've nuked them and started over, and it's working fine.
