### ISSUE TITLE
Add ability to export to CSV or similar

### ISSUE THREAD

**Issue by bricin** [waffleio/waffle.io#2415]
Often we need to hand versions of Waffle around to discuss the issues. Today this is slightly painful as screenshots miss the link to the root item.

Exporting to CSV would be great, even PDF would be okay at times.

**Comment by kellihsf** [comment]
hi @bricin,

Thanks for the request! We're actually tracking this request already on [#1264](https://github.com/waffleio/waffle.io/issues/1264). We'll be closing this issue as a duplicate. Thanks!
