### ISSUE TITLE
Less intrusive access right

### ISSUE THREAD

**Issue by DavidNemeskey** [waffleio/waffle.io#2416]
It would be nice if Waffle would not require permissions to -- basically -- my whole account. Users should have the right to
- specify which repositories to give access to
- what level of access they give, e.g.
  - read access only
  - no access to settings (and thereby deletion...)
  - no access to code
  - etc.

**Comment by corysimmons** [comment]
:+1: I don't know why apps do this kind of stuff...

**Comment by homeyer** [comment]
We totally agree, unfortunately GitHub doesn't allow repo specific access, nor do they allow issues-only access.

**Comment by corysimmons** [comment]
What about the other things he mentioned?

**Comment by DavidNemeskey** [comment]
I know that the GitHub access control scheme is not very fine-grained; however, to (human) collaborators at least you can give access on a repository basis, and you can also deny them write access. If an app cannot do that, then would it not be possible to "camouflage" waffle.io as a collaborator or sth?

(Actually, I believe it is in the power of app developers to influence GitHub on such things as changing access right granularity, not users.)

**Comment by homeyer** [comment]
GitHub's new "App" integrations improve the access controls required by products like Waffle. It's not a small task to move Waffle over, but we're thinking through it.
