### ISSUE TITLE
Subscribe button on cards

### ISSUE THREAD

**Issue by khoomeister** [waffleio/waffle.io#2418]
I was looking at cards on the waffle board and wanted to subscribe to receive notifications.  It was inconvenient to jump to Github and click subscribe there.

**Comment by khoomeister** [comment]
BTW, this is perhaps more useful for non-collaborators.

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
