### ISSUE TITLE
Support columns configuration via dotfile

### ISSUE THREAD

**Issue by sumeetjain** [waffleio/waffle.io#2420]
We'd like to use Waffle for about ~200 projects each year, but one pain point we're exploring solutions to is that we need to manually configure the columns for each project.

For example, our workflow doesn't use a "Backlog", so we'd like the "Ready" section to be our Inbox. And we'd want to remove 'Work Started' from the workflow entirely.

Obviously these are not preferences all users will share; but for any large-scale usage there are likely to be organization-wide standards/conventions.

Something I've seen useful for other projects is a dotfile that lives in the project repo itself. When that file isn't present, Waffle's default settings kick in. But if I wanted to, I might add a **.waffle** to my project:

```
inbox:
  column: Ready
progress:
  columns: [In Progress, Review]
  issues: [New Collaborator PRs]
exclude: [Work Started]
```

Parsing this as YAML should be straightforward, and it might interface well with however Waffle has currently implemented default board settings.

This file would likely be the same across all of our projects. It reduces the burden on Waffle to build some UX for managing columns (besides what already exists), and it's trivially easy for users to add this to all of their repos that need configuration–most probably already have dotfiles for CI, linting, etc.

A challenge would be dealing with changes to this config file after Waffle has already set up the board for a project. E.g. the config might say the inbox column is "Ready", but a user might use the UX to change the inbox back to "Backlog". I don't think it'd be at all inappropriate to ignore the config file entirely after it's processed when the project is added to Waffle for the first time. Changes made via the UX afterwards simply have a higher precedence.

This is related to #2087 in a sense, but I kept it separate since that issue is about syncing milestones/labels (which has many additional complexities not present for this feature).

**Comment by franz-josef-kaiser** [comment]
> Changes made via the UX afterwards simply have a higher precedence

While I could +100 this issue, above is a slight drawback. When I want to standardize a serious number of boards, I'd really like to have the possibility to use the dot file standard first. Copy/pasting and committing can be done in bulk. Clicking through the UI not (that easily). Else removing all settings from all those board would tedious. Alternatively, I'd like to see the possibility to remove all previously made customizations with the click of a button – maybe even in bulk by selecting boards.

One important thought @sumeetjain : A repo might be part of multiple boards. Therefore multiple dot files might be present, each with a different set of columns. What dotfile then "wins" the race?

**Comment by SpainTrain** [comment]
I strongly support this general idea.  Many folks prefer to control settings via project dotfiles for the reasons already mentioned (I would add that also have revision history is another major reason).

As noted, a large point of contention is how to handle conflicting changes made via dotfile and UI.  codecov.io solved this by completely eliminating the UI for configuration and going all in on dotfiles.  I suspect that isn't a reasonable solution here, but it may be reasonable to force a choice of whether a particular board is configured via dotfile or UI.  In this case a board is in UI-configured mode until a `.waffle` config is found, at which point it becomes a dotfile-configured board and the UI is no longer accessible.  If the `.waffle` file is later removed, the UI could perhaps become accessible again.

> One important thought sumeetjain : A repo might be part of multiple boards. Therefore multiple dot files might be present, each with a different set of columns. What dotfile then "wins" the race?

Every board has a "main" repo from which it was first created, right?  Wouldn't this repo be the canonical location for board config?

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
