### ISSUE TITLE
Waffle Takeout Dropping Body From New Tickets

### ISSUE THREAD

**Issue by brycethornton** [waffleio/waffle.io#2422]
We recently upgraded to Waffle Takeout v2.2 and have been seeing our ticket bodies being dropped when adding a new ticket. The title, labels, assignment, and milestone are all saved appropriately.

**Comment by Piefayth** [comment]
We are also seeing this issue on Takeout 2.2. Specifically, when creating an issue in Waffle, the "card description" does not appear in the body of the issue on GHE. It does, however, appear on the card itself.

**Comment by homeyer** [comment]
@brycethornton and @Piefayth, this is fixed in 2.2.1 (available now).
