### ISSUE TITLE
Support to print tickets on the Waffle Board

### ISSUE THREAD

**Issue by ruchim** [waffleio/waffle.io#2427]

**Comment by ruchim** [comment]
It would be helpful to have someone share a hack or perhaps a feature to be able to print the tickets on this board.

**Comment by kellihsf** [comment]
hi @ruchim,

We're already tracking this issue on [#844](https://github.com/waffleio/waffle.io/issues/844), so we'll close this as a duplicate.  I believe another user commented on the already existing issue with a hack. Thanks!
