### ISSUE TITLE
Fix "Cannot read property 'admin' of undefined"

### ISSUE THREAD

**Issue by burtonjc** [waffleio/waffle.io#2434]
See [new relic error](https://rpm.newrelic.com/accounts/783175/applications/7721608/traced_errors/75d289-92af9a2b-e6e5-11e5-9b9f-f8bc12425d50) for more details

**Comment by kellihsf** [comment]
error gone since we don't have more than a day in newrelic... closing this, assuming we'll fix things as we go in the future when we see errors in newrelic.
