### ISSUE TITLE
Create automatic priority in backlog

### ISSUE THREAD

**Issue by jf1978** [waffleio/waffle.io#2435]
We use issues in github to handle our tickets in development, and to prioritize we use different groups of labels (type, urgency, feature area). The different groups have different priority between each other (first check type, then urgency and so on), and within each group, the labels have a priority between each other (type has; bug, task, story). What would "OMG-THATS-SO-COOL" would be to be able to sort the backlog list by the same method. So basically be able to click a button saying "customized sorting" and then set up these rules.

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
