### ISSUE TITLE
Display unread changes on cards

### ISSUE THREAD

**Issue by herrtreas** [waffleio/waffle.io#2444]
Having hundreds of cards on lots of columns makes it pretty much impossible to see what's going on in terms of progress. I'd love to see which cards have been updated (moved, comments, etc) since my last visit. I imagine the card to have a simple indicator like e.g. Unread items in issue lists on GitHub. 

For me this is pretty much the most useful and missing feature..

**Comment by crisbit** [comment]
+1
I too would like to see on the board which issues have unread items by me. I'd use this every time I look on the board after finishing fixing an issue, so I know at a glance where I'm needed next.

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
