### ISSUE TITLE
Columns extremely narrow in Firefox, can't see anything

### ISSUE THREAD

**Issue by LoLei** [waffleio/waffle.io#2447]
I can't really see anything using waffle.io in Firefox, because the columns are really narrow, or at least the text inside is.

Screenshot:
![lolei-sw-ss16 - mozilla firefox_043](https://cloud.githubusercontent.com/assets/9076894/13826345/3978f546-ebb7-11e5-911d-e97d3652d3ba.png)

**This does not happen in Chrome.**

### Specs
OS: Arch Linux 
Kernel: x86_64 Linux 4.4.3-1-ARCH
Firefox version: 44.0.2
GTK Theme: Arc-Dark [GTK2]

**Comment by kellihsf** [comment]
Running Firefox 45 on Ubuntu works fine for us. Can you point us to the distro that you're using?

**Comment by kellihsf** [comment]
hi @LoLei,

We'll be closing this for now. Please let us know if you're still having trouble with this. Thanks!

**Comment by LoLei** [comment]
The distro is noted in the OP, Arch Linux.
