### ISSUE TITLE
Assigned issues dasboard

### ISSUE THREAD

**Issue by brentrobbins** [waffleio/waffle.io#2449]
It would be great if there was a dashboard dedicated to only showing the issues assigned to you. I am trying to get other team members on-board with using waffle, but they find it more useful using github's assigned page (https://github.com/issues/assigned). This is because it's too time consuming for them to go through each waffle project to see what they need to work on.

**Comment by kellihsf** [comment]
hi @brentrobbins,

The workaround we suggest for this is bookmarking a filtered view of the board since the filter saves in the URL (each person would filter by assignee). Then they can just visit that URL and see only the issue assigned to their user.

**Comment by brentrobbins** [comment]
I guess I was more interested in looking for a solution that is integrated with waffle.io

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
