### ISSUE TITLE
Enable Tracking One-Off Issues

### ISSUE THREAD

**Issue by kenperkins** [waffleio/waffle.io#2455]
<aside>Thanks for making waffle; As a dev manager I'm already in love with the visibility of tracking issues across repos. Huge :+1:.</aside>

My team works on a number of various open source projects, sometimes upwards of ~50 projects where we may be contributing a pull request or two. Sometimes these contributions are a significant percentage of the time for a given engineer during a sprint.

In many cases it's a non-starter to grant privileges to Waffle for someone else's repository, in other cases even if I could, I don't want all of the issues from said repository to pollute my board. I know that the workflow currently depends on labels, but *is there a way to make this work for one-off issues* so we can still have visibility into work that we aren't the owners for?

**Comment by homeyer** [comment]
Hey @kenperkins, sorry for the super late reply.

We run into this too, when we make open source contributions for things we depend on. Often we'll first open an issue and PR for the changes on our fork, and add the fork to our board. To do that you have to enable issues on the fork and add it as a source on your board, which is a bit of a headache, but worth it if you want that visibility.

There isn't another way to pull in just one issue from a different repo, or something like that.

Cheers!

**Comment by kellihsf** [comment]
closing this; please let us know if you have any questions. Thanks!
