### ISSUE TITLE
Bulk import of tasks from .csv

### ISSUE THREAD

**Issue by jjsiddall** [waffleio/waffle.io#2456]

**Comment by jjsiddall** [comment]
We are working get our teams/projects over to waffle.io (because it is so simple and so awesome).  Just looking for something that would let us upload a .csv of our current backlog into waffle (because it is so simple and so awesome) :).  Fields - title and description would be more than enough...but if there were others we would use them

**Comment by homeyer** [comment]
Since Waffle's built on GitHub Issues, you can use a tool to import issues from a CSV, like this one: https://github.com/controlgroup/CSV-GitHub-import-export

**Comment by jjsiddall** [comment]
Oh man. I am so dumb. Thank you. 

Jake
