### ISSUE TITLE
Change Repo of existing Issue

### ISSUE THREAD

**Issue by leifg** [waffleio/waffle.io#2463]
My research didn't raise any existing issues or questions on this so I'm opening it here.

In a multi repo project it happens from time to time that an issue is raised for the wrong project. It would be super beneficial if it was possible to change an issue to another repo.

Is this currently possible, if yes. How?

**Comment by kellihsf** [comment]
hi @leifg,

Unfortunately, moving issues into different repos isn't something we support at this time. This issue is already being tracked at [#2044](https://github.com/waffleio/waffle.io/issues/2044) so we'll be closing this one as a duplicate. Thanks!
