### ISSUE TITLE
Add Dennis to the about page

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#2464]
**Acceptance Criteria**
- [x] add Dennis
- [x] remove Nick

**Comment by homeyer** [comment]
![dennis](https://cloud.githubusercontent.com/assets/84629/14068243/59514324-f43a-11e5-9e55-be9aa159ba49.jpg)

**Comment by songawee** [comment]
<img width="1059" alt="screen shot 2016-04-12 at 7 33 55 am" src="https://cloud.githubusercontent.com/assets/434885/14462018/5426fe76-0082-11e6-8267-fb4b23df690f.png">
