### ISSUE TITLE
Actual throughput graph != throughput.svg?

### ISSUE THREAD

**Issue by mcqueary** [waffleio/waffle.io#2465]
Why is [this throughput graph](https://waffle.io/nats-io/roadmap/metrics/throughput) not consistent with this throughput.svg?:

 [![Throughput Graph](https://graphs.waffle.io/nats-io/roadmap/throughput.svg)](https://waffle.io/nats-io/roadmap/metrics)

**Comment by kellihsf** [comment]
hi @mcqueary,

I have included a screenshot below of what I see when I click the link you provided. Can you give me a bit more detail on what you're seeing?

<img width="932" alt="screen shot 2016-04-18 at 1 06 05 pm" src="https://cloud.githubusercontent.com/assets/4775572/14616176/71c9954a-0566-11e6-9b9a-26ba923b4e19.png">

**Comment by kellihsf** [comment]
hi @mcqueary,

We're closing this issue for now. Let us know if you're still having trouble with this or you can open a new  issue on our board. Thanks!
