### ISSUE TITLE
Show branch name when moving to "In Progress"

### ISSUE THREAD

**Issue by martwana** [waffleio/waffle.io#2467]
It would be great if we could see the branch name that was created and pushed that triggers the move to "In Progress".

Say I create a branch for issue #2467 called 2467-add-branch-name and push it, then need to pass the issue to another collaborator, being able to see the branch name in the ui would make passing it over a bit easier.

**Comment by kellihsf** [comment]
hi @martwana,

This issue is already being tracked on [#1889](https://github.com/waffleio/waffle.io/issues/1889), so we'll close this as a duplicate. Thanks!
