### ISSUE TITLE
Single click 'assign to me' on card view

### ISSUE THREAD

**Issue by lloydwatkin** [waffleio/waffle.io#2468]
When I pop open the card view for an issue it would be great to have a single click link to assign an issue to myself.

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
