### ISSUE TITLE
Show Card Details when hovering on a card

### ISSUE THREAD

**Issue by ducwings** [waffleio/waffle.io#2476]
Show Card Details (as an overlay) when hovering on a card.

Moving mouse outside of the overlay should close it.

**Comment by talbotseb** [comment]
:+1:

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
