### ISSUE TITLE
Column API Documentation

### ISSUE THREAD

**Issue by kellihsf** [waffleio/waffle.io#2477]
- [x] describe the column object on the base column age 
- [x] document all column API pages, with example requests and responses

**Comment by homeyer** [comment]
In the column docs it says you must have a done and a backlog column. Can you clarify that you can have only 1 of each of those types, but you can also choose to have neither?

**Comment by homeyer** [comment]
In the Values column of the properties table you use back ticks on some properties but not all, can you add them to all of them?

**Comment by homeyer** [comment]
let's remove the `issues` property, it's legacy and not updated anymore. We'll remove it soon.

**Comment by homeyer** [comment]
Let's remove `issues` from all the example responses too

**Comment by homeyer** [comment]
In `/projects/:id/columns` we say "This is how you update multiple items on a column", can we rephrase to say this is how you update multiple columns at once?

For your "Note" section can you make it a "Warning" and make that word bold? And, as the first sentence say that the list of columns you send will become the set of columns for the project and replace all existing columns, and then keep your current text as an example.

When you say to use the other request to update a single column you can link it, just start typing a `[` and it will prompt you to create a markdown link to another page.

**Comment by homeyer** [comment]
I would remove the json example, the curl example is good enough on the right

**Comment by homeyer** [comment]
For creating a new column, you shouldn't have to pass `_id` (it's ignored if you do) and you need to pass the project, otherwise it won't know which project to create the column for

**Comment by kellihsf** [comment]
I thought that the `_id` was the project id  which would  identify which project the column is created in?

**Comment by homeyer** [comment]
It has to be `project: <project._id>`

**Comment by kellihsf** [comment]
the `id` needs to be named as `project: <project._id>`? 

or is that a different id?

**Comment by homeyer** [comment]
when you create a new column you need a property named `project`, and the value of it is the id of the project you want to create it for

**Comment by kellihsf** [comment]
created a card to disable endpoint for: POST /:owner/:repo/columns

[#2507}(https://github.com/waffleio/waffle.io/issues/2507)

**Comment by homeyer** [comment]
:+1:, let's call this done :)
