### ISSUE TITLE
Option to switch off assignment to an issue when a PR is raised

### ISSUE THREAD

**Issue by adamralph** [waffleio/waffle.io#2479]
It seems that Waffle assigns me to an issue when I raise a PR connected to it. This is often not the case. I usually want to keep the same person assigned to the issue, even if I raise a PR connected to that issue.

Is there a way to turn off this auto-magic? If not, I'd like to get that option added.

**Comment by kellihsf** [comment]
Hey @adamralph, would it be enough if we didn't set the assignee if it was already set? But, still set it if it's empty?

**Comment by adamralph** [comment]
hi @kellihsf 

Ideally, I'd like the option to switch it off, but what you suggest is certainly a step in the right direction. It may well take care of the big side of the 80/20 rule. I'd be happy to work with that as a first step and then re-evaluate.

**Comment by kellihsf** [comment]
hi @adamralph,

Awesome, thanks for the detail! We're actually working on this issue currently. :) 
Feel free to track the issue here [#1697](https://waffle.io/waffleio/waffle.io/cards/54b59d441bb7b90200cb7299)

**Comment by kellihsf** [comment]
closing this one :)
