### ISSUE TITLE
Checkbox to remove org names

### ISSUE THREAD

**Issue by bennovack** [waffleio/waffle.io#2482]
I have a board with lots of repositories all within the same organization; this means that all the names are harder to read since it's all OrgnizationName/repository, OrganizationName/secondRepository, etc. It'd be great to have a checkbox in Sources to automatically hide organization names unless there are two repos with the same name and different org names, in which case of course you'd need that to avoid the conflict.

**Comment by homeyer** [comment]
Hey @bennovack, you can edit the display name for each source to remove the org name. I know it's a bit more work than just a checkbox, but should get you what you want.

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
