### ISSUE TITLE
Throughput graph doesn't show the correct amount of points when filtering by milestone

### ISSUE THREAD

**Issue by kellihsf** [waffleio/waffle.io#2483]
If you look at the throughput with no filters applied, then select all of the milestones and 'Issues with no milestones' you'll see different numbers on each week. 

If you select all of the milestones and 'Issues with no milestone' it should show ALL of the points.

**Comment by songawee** [comment]
This issue has been resolved by the new throughput graph released in WaffleMetrics - http://blog.waffle.io/wafflemetrics/
