### ISSUE TITLE
Is there a way of finding out which Waffle boards a repo is present on?

### ISSUE THREAD

**Issue by adamralph** [waffleio/waffle.io#2487]
The reason I ask, is that for one repo, ~~https://github.com/Particular/docs.particular.net~~ https://github.com/Particular/NServiceBus.AzureStoragePersistence , we have PR's being automatically moved into progress, but we can't find out *which* Waffle board is doing it. We've checked the ones we know about, and neither of those is doing it.

Is there a way to find out which other Waffle boards have that repo as a source?

**Comment by homeyer** [comment]
Hey @adamralph,

The 3 projects with that repo are:
```
Particular/progress-tactical
Particular/progress-strategic
Particular/PlatformDevelopment
```

The only way you could figure that out would be to look at the webhooks for your repo and reverse engineer the urls to figure out which Waffle projects it's connected to. Our API can help you do that, but we haven't opened up our documentation for it quite yet.

**Comment by adamralph** [comment]
@homeyer thanks for the info.

`Particular/PlatformDevelopment` is fine. I can see that, and it's configured as we want.

However, `Particular/progress-tactical` and `Particular/progress-strategic` are deleted GitHub repos, and when I try and navigate to the corresponding Waffle I get, unsurprisingly,

> Is Particular/progress-strategic an organization repo?
Make sure you've granted access to Waffle here.

I guess there is some left over Waffle artifacts from these deleted repos. Could these be deleted? Alternatively, will deleting the webhooks stop those artifacts from interfering with the board? If so, could you tell me which 2 of those 3 webhooks correspond to `Particular/progress-tactical` and `Particular/progress-strategic` and I will delete them.

**Comment by kellihsf** [comment]
We've deleted those two projects, and the webhooks should also be gone as well. Sorry for the delay!

**Comment by adamralph** [comment]
Thanks @kellihsf that solves our immediate problem.

It would be good to have a documented way of finding out which projects reference a given repo, even if it's impossible to access those projects, as in this case, otherwise we'll have to raise a GitHub issue each time and ask you to do this for us.

I guess another fix which presents itself is that Waffle projects are also automatically deleted when a repo is deleted.

**Comment by homeyer** [comment]
Yep, this came from the way we handle deletions. We don't actually know if a repo is deleted or not, all we know is a specific user no longer has access. So, we keep the project around, and remove the user's access to it. We'll think about a better way to handle this situation.

The hard way to figure it out on your own is to hit `https://api.waffle.io/user/projects?access-token=<token>`. You can find an access token by looking at any request the Waffle UI makes to the API from a browser network tab. Then, you'll be able to match the GitHub webhook urls for a repo to projects in Waffle that still exist, and figure out which webhook you should delete.

**Comment by adamralph** [comment]
@homeyer thanks very much for the info. The trick of watching the web request does indeed at least let us figure out the which web hooks correspond to those Waffle projects we know about.

I guess what we still can't do is go the other way. I.e. given a set of web hooks, which projects do they correspond to. Hopefully we won't be in the situation of mystery projects referencing our repos too often in the future, but if we ever are, I guess we'll just have to ping you again and ask you to look them up.

Thanks for all your help on this.
