### ISSUE TITLE
Strange behavior on this PUT request: /projects/:id/columns

### ISSUE THREAD

**Issue by kellihsf** [waffleio/waffle.io#2488]
When making the PUT request, it will update that column, but delete all of the other columns

**Comment by kellihsf** [comment]
Sent the request: PUT projects/:id/columns

Body:
[{"_id": "55cdf1333ff3741000c04649","displayName": "In Progress start", "label": {"url": "https://api.github.com/repos/waffle-maker/waffle-recipe/labels/in%20progress",  "name": "in progress","color": "ededed"}}]

Trying to change the displayName, all columns are deleted except for the 'In Progress' and the display name is updated.

**Comment by marydavis** [comment]
this is accurate - if you only want to update a single column you would use the `/:owner/:repo/columns/:id`endpoint
