### ISSUE TITLE
Done Column shows closed PR requests

### ISSUE THREAD

**Issue by nagavijays** [waffleio/waffle.io#2489]
Done Column shows "Closed" Pull Requests. instead of just github issues. Is this a bug?

**Comment by kellihsf** [comment]
hi @nagavijays,

Yep, you should see both closed pull requests and closed issues in the Done column.

**Comment by kellihsf** [comment]
hi @nagavijays,

We'll be closing this for now. Let us know if you have any questions . Thanks!

**Comment by nagavijays** [comment]
Hi @kellihsf ,
Thanks. I was wondering if there is any way to filter only "Closed" issues and not "Closed" Pull requests. Thanks.

**Comment by kellihsf** [comment]
Yep! So you can click on the filter icon and then choose to view PRs only, PRs & Issues or Issues only. There's no way (at this time) to filter within a column, so when you use the aforementioned filters, it will show all available on the entire board, not just the Done column.
