### ISSUE TITLE
Handles repository removal

### ISSUE THREAD

**Issue by lucasmichot** [waffleio/waffle.io#2491]
A strange behavior can happen in the following use case:
- Create the repo : `acme/repo`
- Enable `acme/repo` in Waffle.io
- Create an issue in Waffle.io with title `First tile`
- Delete the repository `acme/repo` in Gthub
- Re-create the repository `acme/repo` in Gthub

The issue 1 First tile is still in Waffle.io cache and should be cleared.

---

**Solution:**

Remove from Waffle.io cache all issues/PR with `created`  < the `created` field of the least recently created issue/PR

**Comment by homeyer** [comment]
Interesting... the way we have to handle repository deletion is to remove access per-user when you try to access it, because all we know is that you no longer have permission to see it, vs knowing a repo was deleted.

The fix from a user's side is to manually delete the project and re-create it in Waffle.

**Comment by lucasmichot** [comment]
Thx @homeyer this worked for me.

Nevertheless I think this case might happen for other teams 
If api quota is critical, a simple way to handle this situation is when receiving the webhook data :
When a new issue is created (not updated) in github if the id is lower than the latest id in cache, then the cache should be flushed

**Comment by lucasmichot** [comment]
Even simpler via the webhook:
When a new issue/PR is created (not updated) and that its id is 1, then flush the issues/PR cache

**Comment by homeyer** [comment]
Cool, thanks for the ideas. I'm going to leave this issue open so others can find it, although we won't work on it immediately since there's a simple workaround.

Cheers!

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
