### ISSUE TITLE
Client side issue

### ISSUE THREAD

**Issue by AlexandreLogist** [waffleio/waffle.io#2492]
Let your clients add issue's with a

**Comment by kellihsf** [comment]
hey @AlexandreLogist,

It looks like part of your description didn't come through! What are you wanting your clients to add an issue with?

**Comment by AlexandreLogist** [comment]
He,

it would be nice to have a portal where my clients / other department could add issues :-)

Met vriendelijke groet,
Alexandre LogistE-mail: logist.alex@live.be

Date: Mon, 18 Apr 2016 12:02:19 -0700

**Comment by kellihsf** [comment]
If your repo is public, anyone who's logged into Waffle can visit the board and add issues. (They won't be able to take any other actions though like moving cards, adding label, etc..). If your repo is private, you could create a public repo and add it as a source on your main repo which would allow users to view/add only public issues. 

For instance, if you check out our board, you'll notice you can see any of the issues for our 'waffle.io' repository, as well as a few others, like 'takeout', that are public repositories. We also have many private repositories connected to that board as well, all of which are only visible to collaborators of the project. Some open source projects also take this approach where the primary, public repository is a catch all for user requests and public facing roadmap information, and the private repositories added as sources (in Settings->Sources) for that board are reserved for collaborators only.

**Comment by kellihsf** [comment]
hi @AlexandreLogist,

We'll be closing this issue for now. Let us know if you have any questions.. Thanks!
