### ISSUE TITLE
Metrics needs a burndown chart. (for user and for team)

### ISSUE THREAD

**Issue by anthonyskipper** [waffleio/waffle.io#2496]

**Comment by kellihsf** [comment]
hi @anthonyskipper,

We're currently working on a milestone burndown graph now for teams (tracking the issue here: [#1297](https://github.com/waffleio/waffle.io/issues/1297).  No immediate plans for individuals though! :)

**Comment by anthonyskipper** [comment]
If you get a minute check out something like acunote.  They did it really
really well... You need to be able to add a simple points list to any
task...  if you can do that and you have a chart that shows the point total
of what people have signed up for, and what they complete you are golden.

**Comment by kellihsf** [comment]
Cool, thanks for the tip. We'll check it out! :)

**Comment by homeyer** [comment]
closing as a duplicate :)
