### ISSUE TITLE
waffle doesn't show issue reference in commit msg

### ISSUE THREAD

**Issue by guillaume-sticky** [waffleio/waffle.io#2497]
When using an issue reference in a commit message (like #issueNumber ), github shows a message :

added a commit that referenced this issue with the hash of the given commit.

I would like to see it on the waffle issue details

**Comment by kellihsf** [comment]
hi @guillaume-sticky,

This issue is already being tracked at [#1979](https://github.com/waffleio/waffle.io/issues/1979), so we'll be closing this as a duplicate.  Thanks!

**Comment by guillaume-sticky** [comment]
I'm glad  you could answer so fast. Thanks
