### ISSUE TITLE
Add a link to FAQ and intercom popup on landing page for users who haven't signed up/logged in yet

### ISSUE THREAD

**Issue by kellihsf** [waffleio/waffle.io#2499]

**Comment by SteveALee** [comment]
The idea is that anyone not at all familiar with waffle, yet who have been given a link can find out what they need to know.

thanks

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
