### ISSUE TITLE
Time selection for Done column

### ISSUE THREAD

**Issue by hreintke** [waffleio/waffle.io#2501]
The Done column contains the cards closed from the last 7 days. regularly I'd like to see the Done items for a longer period.

Can there be a setting (fixed (in config?) or dynamic (in filter ?) to change the timeframe from Done column ?

**Comment by kellihsf** [comment]
hi @hreintke,

Yep, you're right the Done column empties issues after 7 days of inactivity on the issue. To bring issues back to the board, you can update them from within GitHub (adding a comment, or label). There's no way to change this now, but we're tracking the request to customize the Done column here [#314](https://github.com/waffleio/waffle.io/issues/314). Thanks!
