### ISSUE TITLE
Add git history for repos we published as private modules

### ISSUE THREAD

**Issue by songawee** [waffleio/waffle.io#2503]
To allow for shrinkwrapping our dependencies, we had to use npm packages rather than git dependencies. We've made the following repos private modules so that they could be shrinkwrapped. Hopefully in the future, we can get these changes merged and use the public packages.

The changes to make them private modules are on branch npm in all of those repos.

waffleio/passport-github
waffleio/passport-oauth2
waffleio/node-oauth
waffleio/node-github

**Comment by homeyer** [comment]
@songawee what's the Acceptance Criteria for this? Create branches for these repos named `npm` with the changes we made, or something else?

**Comment by songawee** [comment]
Good call. Code is already on npm branches, but was thinking we would move that to master from npm and re-open prs against upstream using branches?

**Comment by homeyer** [comment]
Thinking about it I don't think we can, a few of the PRs have existing conversations we won't want to lose. Might be stuck with our npm changes on the branches.

**Comment by homeyer** [comment]
This is the one I'm thinking of: https://github.com/ciaranj/node-oauth/pull/248

**Comment by songawee** [comment]
Ok, sure. That makes sense. Just didn't want to forget this in case we needed to do that. I'll go ahead and close this.
