### ISSUE TITLE
waffle-iron seems to not differentiate between 2 forks of the same parent repo

### ISSUE THREAD

**Issue by worace** [waffleio/waffle.io#2504]
I saw some unusual behavior with the waffle Repo Badge PRs today and wanted to document it here to see if what we saw makes sense or is expected.

We use waffle frequently with our students at @turingschool. Students are frequently building projects off of a pre-existing starter template repo that we create to give them some initial structure and configuration for their work.

An example is this repository: https://github.com/turingschool-examples/headcount, which serves as the starting template for their work. Students will frequently fork the starter kit, clone their fork, and work from there. For example:

https://github.com/hectorhuertas/headcount
https://github.com/karinamzalez/headcount

I have not used waffle a ton myself, but it seems that when a user agrees to waffle's prompt to add the waffle badge to their project, waffle forks their repo, makes a commit adding the badge, and sends a PR to the user to get the badge added.

For the 2 repos above, @hectorhuertas had gone through that process in the past (and it worked as expected). However this week, @karinamzalez went through the same procedure, but rather than creating a new fork of her project and sending the Badge PR from there, @waffle-iron seemingly used the existing fork it had of hector's project.

This results in a bunch of other pre-existing changes (from hector's repo) getting bundled in with the supposedly innocuous waffle badge PR. Example: https://github.com/karinamzalez/headcount/pull/1 (that PR has a different name now because the students renamed it when they were confused by the content of all the stuff waffle was trying to send in).

It's a little hard for me to untangle the timeline of what all happened here but I think it was something like this:

Parent Repo A is created
Child Repo B is forked from A
User pushes commits to master on B
User adds waffle integration to B
waffle-iron creates repo C as a fork of B
Waffle sends Badge PR to B from C, which gets merged
----Later-----
Child Repo D is forked from A (D and B are siblings)
User adds waffle integration to C
waffle-iron attempts to re-use existing repo C to send the badge PR to D
this results in any existing changes  already on C getting bundled into the PR to D

Sorry for the lengthy description but I don't know how else to describe what is happening. Would love to know if this is  what ya'll expect to happen in that scenario, or if perhaps we are misunderstanding something.

Our students really love using waffle to organize their projects, and this is the first time we've had any serious issues with it. Seems a little counterintuitive to me that waffle-iron would attempt to recycle its fork of 2 sibling repos, but perhaps there is an explanation.

Thanks again for all your work on the app. Will appreciate any clarification you're able to offer.

**Comment by worace** [comment]
forgot to link the waffle-iron repo -- it's here: https://github.com/waffle-iron/headcount (note that it is forked from hectorhuertas/headcount)

**Comment by worace** [comment]
Ha well joke is on me; looks like karina deleted her fork and re-made it due to some confusion around the stuff they pulled in from waffle-iron; will see if they can reproduce the issue with the new fork

**Comment by worace** [comment]
OK i created another example on my own account demonstrating the same behavior:

made this fork: https://github.com/worace/headcount
added waffle, and received this Badge PR: https://github.com/worace/headcount/pull/1

Note that the Badge PR is coming from this waffle-iron fork: https://github.com/waffle-iron/headcount which is itself forked from hector's repo: https://github.com/hectorhuertas/headcount rather than mine.

Because of this the badge PR somewhat confusingly pulls in a bunch of random commits that had existed on hector's fork but never on mine.

**Comment by homeyer** [comment]
I think it's because @waffle-iron isn't cleaning up it's forks correctly, so it found a different `headcount` fork and used that to issue the PR. Let me clean up the forks and we'll see if that resolves it.

**Comment by homeyer** [comment]
Ok, mind trying it now? @waffle-iron's forks are now cleaned out.

**Comment by worace** [comment]
looks good @homeyer; i closed the existing waffle badge PR, went back to my waffle page, and re-issued it. this one picked up just the one commit as expected: https://github.com/worace/headcount/pull/2

**Comment by worace** [comment]
should this fork: https://github.com/waffle-iron/headcount now get cleaned out?

**Comment by homeyer** [comment]
I think the fork has to exist until the PR is merged, and we don't have a hook listening for that and cleaning up forks right now. So, manual process.
