### ISSUE TITLE
Not able to tag non-team-members

### ISSUE THREAD

**Issue by abhijitkane** [waffleio/waffle.io#2514]
If I'm replying to an issue on Waffle, I can only tag team-members, not other users (including those who opened the issue). I'm able to do this on Github.

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
