### ISSUE TITLE
connect PR to issues from sources which are not connected to my board

### ISSUE THREAD

**Issue by jaypea** [waffleio/waffle.io#2516]
It is not possible to `connect to user/repo#12` from repos which are not added to my boards sources list.
I work in an organization with around 900 repos on github, most teams have their own waffle repos which are just there to organize issues.
For us, it makes sense to organize our tasks and concepts in our waffle repo and the actual implementation takes place in several source code repos. We tried to add all those repos to the waffle sources list in order to link the PRs to the corresponding issues using keywords (connect to, fixes, ...). However this tends to get messy and slows down the interface when there are to many repositories involved.

we would like to be able to use `connect to` to display PRs from unconnected repositories in my waffle board. Would this be possible?

**Comment by kellihsf** [comment]
hi @jaypea,

You are correct, currently, there's no way to `connect to` an issue from a repo which is not added to your source list. We'll leave this open as a feature request in our Ideas column for others to find. Thanks!

**Comment by jaypea** [comment]
Thank you.
As sidenote: `fixes user/otherrepo#123` does close issues already in 'foreign' repositories after merging a PullRequest.

**Comment by jmalloc** [comment]
This would be great, especially if it included the branch-name based correlation, not just the `connect to` syntax.

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
