### ISSUE TITLE
Waffle fresh install wont start.

### ISSUE THREAD

**Issue by mrmikeaz** [waffleio/waffle.io#2523]
Error pulling containers: Image not found

is the error that happens when trying to run waffle after a fresh install. connecting with github enterprise only on ubuntu 14. 

I can verify mongodb is running.

Any ideas on why this is happening?

**Comment by homeyer** [comment]
Hey @mrmikeaz, can you download a support bundle (Support link at the top) and send it to us? takeout@waffle.io. That will help us figure out what's going on.
