### ISSUE TITLE
enable keyboard-only submission in add issue form

### ISSUE THREAD

**Issue by malcomio** [waffleio/waffle.io#2524]
on github, and lots of other sites, forms can be submitted with cmd-enter on mac or ctrl-enter on Windows

would be nice if waffle did the same

**Comment by shieldgenerator7** [comment]
That would be great! This would help with usability!

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
