### ISSUE TITLE
Column sorting

### ISSUE THREAD

**Issue by hreintke** [waffleio/waffle.io#2525]
Is there some information on how the cards are sorted within the columns ?

I would like to sort them on "last commented" so that I can easy follow the discussions going on with the issues/PR's

**Comment by kellihsf** [comment]
hi @hreintke,

When you create a new project, the cards are in the same order as they appear in GitHub. For ranking, you'll want to manually move the cards (drag and drop) in the priority order they should be in. Our intention is that the highest priority items are at the top of the column, but of course you can have them in whatever order suits you best. :)

**Comment by hreintke** [comment]
@kellihsf : 
Does this mean the "sorting" is only manual ? 
If so this is a serious limitation of the usability. I have to go back to github to be able to see on which issues/PR's there were comments/updates.
How am I supposed to keep track of progress/communication is this way ?

**Comment by hreintke** [comment]
From other cards (and experimenting with api.waffleio) I understand there is an api on the waffleio information.
- Can you point me to the information/documentation of that ?
- Is the "location" of a card within a column accessible and update-able from there ?

**Comment by talbotseb** [comment]
Hi @kellihsf 
I back up @hreintke on its demand to be able to sort the issues.

Moreover, we use various repos within the same board, and, above sorting issues by priorities, using the personnalised labels, I'd like to sort them also by repos

I hope you'll give it a thought. And thanks for your work at wafle.io which is really great

**Comment by rilwis** [comment]
+1 for sorting. Github supports sorting for last updated issues, sort by date, etc. We need this to know which issues are updated (have new comments) to track the discussion.

**Comment by g3rd** [comment]
+1 this would be a big timesaver

**Comment by demetriusnunes** [comment]
+1. I would also like to "teach" how issues an be sorted based on labels, because we use labels to define priority and I would like to define which priorities should come on top. Right now, it's a real pain having to manually keep the issues sorted manually.

**Comment by HEskandari** [comment]
+1 this would ease a lot of our backlog grooming pains.

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
