### ISSUE TITLE
Tracking issue lifecycle

### ISSUE THREAD

**Issue by ruchim** [waffleio/waffle.io#2526]
It would be a wonderful feature to some how track how many days each issue has spent in each state (or column) and be able to compare the lifecycle of the issues on a board.

**Comment by kellihsf** [comment]
Hi @ruchim,

Thanks for the request! We're actually already tracking this issue on [#1574](https://waffle.io/waffleio/waffle.io/cards/5460daa0d613f614d44821b5), so we'll close this one as a duplicate. I'll add your feedback and a +1 on the existing issue.  :)
