### ISSUE TITLE
Making notifications persistent

### ISSUE THREAD

**Issue by TheGrandmother** [waffleio/waffle.io#2528]
I would love it if either the notification abr is persistent and doesn't dissapear unless that notification is looked at or dismissed.

Right now it is very easy to miss new events  on cards.

**Comment by TheGrandmother** [comment]
Sorry missed adding it to the  correct column.

**Comment by Slind14** [comment]
Currently its disappearing so quick that there is no chance to even read it. Increasing the duration would make it use able.

**Comment by kellihsf** [comment]
Hi all,

We've fixed this so the notification bar persists longer. Thanks!
