### ISSUE TITLE
Notify users we'll have 45 minutes of downtime

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#2532]
- [x] Send intercom in-app message to active users, notifying them that we'll have 45 minutes of downtime on "2016.05.05 at 03:00 UTC" (9pm MT). Make sure to use that date format, our international users get confused when we use American notation. Mention that they can follow status.waffle.io for updates.

**Comment by homeyer** [comment]
Perfect

**Comment by kellihsf** [comment]
https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/messages/manual/28349351/show

**Comment by homeyer** [comment]
:+1:
