### ISSUE TITLE
Add support for preview when editing a previous comment

### ISSUE THREAD

**Issue by markemeis** [waffleio/waffle.io#2535]
When you add a comment to a card you can view it in preview mode.  When editing a previous comment you don't have the same capability.  Adding support for this would be a nice to have.

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
