### ISSUE TITLE
Integrate Harvest timesheet button

### ISSUE THREAD

**Issue by stefanhar** [waffleio/waffle.io#2536]
To make it easy to track time per issue

**Comment by Willamin** [comment]
If possible, it would be convenient if moving a task to be `in-progress` would auto start a timer with the appropriate description.

**Comment by michaelbaudino** [comment]
@kellihsf Would you mind explaining why you closed this issue?

As stated in [your FAQ](https://help.waffle.io/faq/integrations/when-will-you-guys-integrate-with), I'd like to +1 this Harvest integration and would love to see something like the [Harvest power-up for Trello](https://help.getharvest.com/harvest/integrations/project-management-integrations/trello/#harvest-power-up-for-trello), _i.e._ a "Track time" button on each Waffle card, that would create a Harvest entry or timer with the card name (and ideally a link too).

**Comment by kellihsf** [comment]
hi @michaelbaudino,

We're glad to hear from you! Some context for why you are seeing that issue closed is we only had 2 people in the last two years comment on it. We had cleaned it out as part of our commitment as a team to only keep cards that we are considering or committing to working in the next 6 months. 

By commenting on the card we will take another look at it and how many of our customers are requesting this particular integration, vs. open issue [287](https://github.com/waffleio/waffle.io/issues/287) which is around time tracking functionality from a more general standpoint. 

Any other feedback for our team? Feel free to use this link to communicate your needs to our Customer Advocate: https://goo.gl/forms/QoEO7NQvDFR0qiHU2 (edited)
