### ISSUE TITLE
Make sure you've granted access to Waffle.

### ISSUE THREAD

**Issue by Tree-Hugger** [waffleio/waffle.io#2538]
I've done so in my Git.Hub settings, but still am unable to access Waffle. I instead, continue to receive the message displayed above. 

Thoughts?

**Comment by kellihsf** [comment]
hi @Tree-Hugger,

Can you try to log out of Waffle and log back in again to see if that resolves the issue? Thanks!

**Comment by kellihsf** [comment]
We'll be closing this for now. Let us know if you're still having trouble with this!
