### ISSUE TITLE
Please document private repo access in waffle.io

### ISSUE THREAD

**Issue by dprophet** [waffleio/waffle.io#2539]
I cannot connect waffle.io to a private repo yet the waffle.io has been granted access. Attached is image of all screens.

![waffle_io_error](https://cloud.githubusercontent.com/assets/3594022/15051209/712934d0-12c5-11e6-8565-472ce73f892f.png)

**Comment by kellihsf** [comment]
hi @dprophet,

I just replied to you via email, but just in case you missed it, we were able to get this board created on our end. Can you give your browser a refresh and see if everything looks in order? Thanks!

**Comment by dprophet** [comment]
Now, when I load

https://waffle.io/identity-provider/multi-wallet-coordination

I get these errors constantly spinning icon "Ironing your waffle"and I get the below errors in my chrome console.

https://api.waffle.io/projects/identity-provider/multi-wallet-coordination Failed to load resource: the server responded with a status of 404 (Not Found)
https://api.waffle.io/identity-provider/multi-wallet-coordination/columns Failed to load resource: the server responded with a status of 404 (Not Found)
https://api.waffle.io/user/projects Failed to load resource: the server responded with a status of 401 (Unauthorized)
https://api.waffle.io/identity-provider/multi-wallet-coordination/cards Failed to load resource: the server responded with a status of 404 (Not Found)
https://api.waffle.io/user/projects Failed to load resource: the server responded with a status of 401 (Unauthorized)
2https://api.waffle.io/accounts/5718e3919b1b361300dc0468 Failed to load resource: the server responded with a status of 401 (Unauthorized)

**Comment by burtonjc** [comment]
@dprophet, I was digging into this and noticed something odd that would cause this problem. Waffle uses an `Authentication` header to pass OAuth tokens to our API for authentication. For some reason, your browser is not passing that header (hence all the 401s and 404s). Are you running a chrome add-on that manipulates request headers? If not, you can try clearing your cache and cookies for Waffle and see if that fixes it after logging back in. My hunch would be that a chrome plugin is interfering though.

Let me know neither what happens after trying those two ideas!

**Comment by dprophet** [comment]
I just deleted all of the cookies and still the same problem.

I dont have any Chrome pluggins that would interfere with this. I only use Lastpass pluggin.

**Comment by burtonjc** [comment]
@dprophet, I too use U2F on my GitHub account, so that shouldn't be the problem. The requests we are receiving from your browser still do not have an `Authorization` header. What version of Chrome are you using? Would you mind trying in Firefox or Safari and seeing if you still have this problem?

**Comment by dprophet** [comment]
@burtonjc Chrome Version 50.0.2661.102 m

I just tried in Safari. I got this error, "Unable to create project: Unauthorized"

**Comment by burtonjc** [comment]
Sorry for the delay @dprophet, and for the continuing issues. Is there any chance you are behind a proxy that could be stripping out the headers?

**Comment by dprophet** [comment]
Yes. The problem is our proxy/firewall.

Last week I tried my corporate laptop that connects outside of our proxy's/firewalls and it works. If inside our corporate environment it doesnt work.

@burtonjc This isnt a problem you can solve. :(

**Comment by burtonjc** [comment]
Ok, thanks for letting us know. Sorry it took so long to narrow that down, glad you figured it out though.

I'm going to close this issue out for now. Please feel free to comment here again if there is something we can help out with!
