### ISSUE TITLE
Assignees only visible after issue moved

### ISSUE THREAD

**Issue by richchurcher** [waffleio/waffle.io#2541]
Following the recent server maintenance, when loading a waffle board the assignees are initially visible but are then all set to "not assigned". After an issue is moved, the assignee is displayed and the message appears, "[user] assigned [issue]". However, when the page is refreshed, the assignee persists momentarily and then disappears.

**Comment by richchurcher** [comment]
Unfortunately this breaks filter by assigned user, which is a pretty big use case for us.

**Comment by richchurcher** [comment]
Seems to be resolved now; think it may have actually been a GitHub problem, their issues are now correctly reporting assignee again.

**Comment by kellihsf** [comment]
hi @richchurcher,

Thanks for letting us know about this! We'll keep an eye on it on our end in case it pops up again.

**Comment by kellihsf** [comment]
closing this for now; haven't  received any more reports of this behavior. We'll reopen again if needed.
