### ISSUE TITLE
Sticky tags

### ISSUE THREAD

**Issue by svenfuchs** [waffleio/waffle.io#2545]
I'm not sure if there's another solution for this, of if there's a feature that I'm missing.

We're using two "inbox" columns where one of them is based on the tag `bug`, while the other is the default automatic "new issues" column.

When we move an issue from "Bugs" to our work progress columns ("ready", "in progress", ...) we'd like the `bug` tag to be "sticky", i.e. not removed, and visible when the issue is in any of the progress columns.

**Comment by kellihsf** [comment]
hi @svenfuchs,

When an issue is moved from one column to another, the previous column label will be removed and the new column label will be added. At this time there's not a way for the previous label to remain on the card, so we'll keep this issue open as a feature request. Thanks!

**Comment by luislew** [comment]
:+1:

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
