### ISSUE TITLE
add label based on source

### ISSUE THREAD

**Issue by NathanSweet** [waffleio/waffle.io#2547]
I pull issues into Waffle from multiple public and private repos. The public repos are for different products and allow the public to post issues. When I create an internal issue, I label it for which product it is for. When an issue is created on a public repo, I know which product it is for by which repo it came from, but now I have two ways of filtering for a product's issues: by public product repo and by product label. To fix this I manually add a product label to all public repo issues, but every time this is forgotten, an issue gets lost. I would like a way to add a label based on what repo an issue came from.

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
