### ISSUE TITLE
Ticket was not moved after creating branch

### ISSUE THREAD

**Issue by lucasfeliciano** [waffleio/waffle.io#2553]
After creating a branch with the issue number and push it I received a message from waffle.io team:

> We noticed you recently created a branch in GitHub with an issue number in the name. Did you notice that we moved the issue you referenced in your branch name to ‘in progress’ and assigned it to you?

But the issue was not moved to in progress, it is still on ready :(

**Comment by kellihsf** [comment]
hi @lucasfeliciano,

Sorry for the late reply! Are you still having trouble with this?

**Comment by lucasfeliciano** [comment]
Yeah :(

I think it is because we use feature branches `fix/that-horrible-bug-#132`
So waffle.io think it is a cross repo issue instead of an actual branch of the current issue.

But instead of throw an error it just assume that the issue was moved but it was not .

**Comment by kellihsf** [comment]
Ah yeah, you're exactly right. The naming that you're using will be picked up as a cross repo issue reference. 

You could use all dashes instead of slashes, or you can start the branch name with the issue number followed by a dash.

For more information on this, have a look at our [FAQ page](https://github.com/waffleio/waffle.io/wiki/FAQs#branch-moving).

**Comment by lucasfeliciano** [comment]
Don't you think that is a draw back for waffle.io?

I mean, be unable to use feature branches with lets say `git flow` it is a huge drawback. :(

What if to make reference to cross repo you specify the user like `@anotheruser/repo` instead of `anotheruser/repo` so that will make it clear for waffle.io and it will explicitly saying that is a user causing no confusion

**Comment by lucasfeliciano** [comment]
After reading the FAQ I saw that i can use `feature/#123-my-awesome-feature` which works but even though I like the suggestion of make it explicit when making reference to a cross repo issue using `@` maybe it is something to take in consideration :)

**Comment by kellihsf** [comment]
hi @lucasfeliciano ,

Thanks for the feedback! We'll leave this issue open for others to find. :)

**Comment by codementordev** [comment]
Can it be used with gitflow + cross repo reference? Such as

```
feature/theuser/therepo#1234-my-awesome-feature
```

**Comment by mz026** [comment]
Hi, can it be used with cross repo referencing? Such as

```
feature/theuser/therepo#123-my-awesome-feature
```

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
