### ISSUE TITLE
Drag & Drop child ticket on parent ticket to relate

### ISSUE THREAD

**Issue by that1guy** [waffleio/waffle.io#2554]
To indicate that one ticket is dependent on another ticket it would great if we could drag and drop the child ticket on the parent ticket and they would be nested in one waffle box to indicate relationship.

**Comment by EricTracz** [comment]
@kellihsf Please introduce that. We need that in our lives.

**Comment by jaworskimatt** [comment]
+1 this is the most annoying missing feature of GitHub issues

**Comment by wimpers** [comment]
+1

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
