### ISSUE TITLE
'Add Issue' functionality to be more user friendly

### ISSUE THREAD

**Issue by liatreis** [waffleio/waffle.io#2555]
When clicking the 'Add' button to add a new issue in the 'Add Issue' panel, should trigger the 'Add Issue' panel to close immediately and the newly created issue should be highlighted temporarily to differentiate the newly created issue from others. 

Common user behaviour is to create an issue and then be able to find it easily, to make sure its located correctly or move it to another branch. Having to click the 'Add Issue' button just to clear the panel is annoying, clicking it to add another new issue would make more sense and be more user friendly.

**Comment by adambuczynski** [comment]
+1 for closing the issue panel. It's very annoying that you have to manually close it after having created an issue.

Also, please allow us to specify what column new issues get put in by default.

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
