### ISSUE TITLE
reference committs to branches based on issues

### ISSUE THREAD

**Issue by timburrows** [waffleio/waffle.io#2556]
When you commit to a branch based on a particular issue, it would be nice if it showed up in the comments and link to the commit.

**Comment by tidusjar** [comment]
+1

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
