### ISSUE TITLE
Update FAQ with squash and merge info

### ISSUE THREAD

**Issue by kellihsf** [waffleio/waffle.io#2559]

**Comment by kellihsf** [comment]
https://github.com/waffleio/waffle.io/wiki/FAQs#squash-and-merge

**Comment by burtonjc** [comment]
It actually doesn't matter if there is one or multiple commits on the PR. It is just that the PR title is no longer used as the commit title.

**Comment by kellihsf** [comment]
made changes to reflect that ^. also added in a link to GitHub's squash & merge page
