### ISSUE TITLE
Can you make an integration to support Jira tickets that would translate to issues automatically?

### ISSUE THREAD

**Issue by ChaseBig** [waffleio/waffle.io#2560]

**Comment by kellihsf** [comment]
hi @ChaseBig,

Thanks for the request! We're tracking interest in a Jira integration on  [#1548](https://github.com/waffleio/waffle.io/issues/1548) , so we'll close this as a duplicate. Feel free to leave any comments on the already opened issue. :)

**Comment by ChaseBig** [comment]
Perfect, thanks for the quick response @kellihsf !

**Comment by kellihsf** [comment]
You're welcome!
