### ISSUE TITLE
Custom boards with filtered view

### ISSUE THREAD

**Issue by kevinkuszyk** [waffleio/waffle.io#2564]
We started this conversation on [Twitter](https://twitter.com/kevinkuszyk/status/732224217396183040):

> Hey waffleio, can I make more than one board for a github repro?
> 
> > kevinkuszyk github we only allow one project per primary repository; you can create a dummy board and add that repo as a source :)

But I don't see how to create a new empty board?  It looks like I have to start by linking to an existing repro?

![image](https://cloud.githubusercontent.com/assets/2734580/15466095/cabf5f98-20cf-11e6-9084-a7686c831a84.png)

**Comment by homeyer** [comment]
Hey @kevinkuszyk! Yep, every board starts with a repo. If you need a repo on multiple boards you need to choose a different "primary" repo for a second board, and then add the other repo to it.

For example, https://waffle.io/waffleio/waffle.io has several repos connected to the board our team, and https://waffle.io/waffleio/roadmap also has a lot of the same repos on it.

Does that help?

**Comment by kevinkuszyk** [comment]
Hello!

We're the other way round - we have one repro containing bugs for a supplier to work on, high level tech tasks on our to do list, and general project management stuff.  We'd like to have separate waffle boards for each group of stakeholders (they would be filtered by labels).  

> Yep, every board starts with a repo. If you need a repo on multiple boards you need to choose a different "primary" repo for a second board, and then add the other repo to it.

I just made a new board connected to a different repro, and then added our big one.  It looks like I can't remove / switch the primary repro, so now I see issues from both repros.

I guess in hindsight, separate repros might have been a better way to go.

Can you keep this on your backlog as an enhancement along with #2546 / #1045?

/cc @reddy11

ps. keep up the good work!

**Comment by homeyer** [comment]
Renamed this to "Custom boards with filtered view" to represent the idea behind a board that shows a subset of cards for one or more repos.

We'll have to figure out how to have boards dis-associated from a primary repo. The only reason we haven't so far is to support vanity urls (waffle.io/:owner/:repo), and it's a bit messy to support that and also custom boards without vanity urls. It's a common request though.

**Comment by kevinkuszyk** [comment]
Thanks @homeyer I think you've captured our requirement.

It looks like @kurttheviking and @vkarpov15 have a similar use case in [#2169](https://github.com/waffleio/waffle.io/issues/2169#issuecomment-220168041).

**Comment by vkarpov15** [comment]
Yeah this is exactly my use case. Waffle isn't really useful to me without multiple repos on one board, otherwise I'd just use milestones.

**Comment by vramosp** [comment]
Related to the ability to create a repo with filtered view, in our case (@3scale), we'd like to be able to create a board with selected milestones from different repositories.

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
