### ISSUE TITLE
Remove Waffle Default Labels

### ISSUE THREAD

**Issue by TheCodeDestroyer** [waffleio/waffle.io#2565]
So currently I have my own labels, but when I try to assign labels to a task I can see Waffle labels, which actually get created on GitHub once I close the task the labels disappear on GitHub.
So my question is is there a way to permanently remove Waffle labels for certain project?

**Comment by kellihsf** [comment]
hi @TheCodeDestroyer,

So what you're re referring to are the column labels that are automatically added when an issue is moved into a specific column.  You're not able to permanently remove these, unfortunately. Sorry for the trouble!

**Comment by TheCodeDestroyer** [comment]
It would be awesome if you guys could add an option to remove those, since right now with style of labels I use the Waffle labels actually pollute my label dropdown list.

**Comment by adambuczynski** [comment]
+1

I understand the waffle labels are added so waffle can keep track of what column an issue should be in, but there's no point in showing these labels in the label dropdown list really, so maybe they can be filtered out of there?

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
