### ISSUE TITLE
Redirect {REPO}/issues to {REPO}

### ISSUE THREAD

**Issue by cabloo** [waffleio/waffle.io#2566]
Would be nice if waffle.io/{USER}/{REPO}/issues redirected to waffle.io/{USER}/{REPO} that way on github issues page, you can just replace github.com with waffle.io and the URL works.

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
