### ISSUE TITLE
Clicking on Metrics icon while left hand menu is collapsed expands the menu

### ISSUE THREAD

**Issue by adambuczynski** [waffleio/waffle.io#2567]
Clicking on Metrics icon while left hand menu is collapsed expands the menu for no reason. Then, after I click Return to board, the menu remains expanded and I always have to manually collapse it again.

Can we not have the left hand menu expand automatically? I don't see a point in that. If users like the expanded menu, they can expand it manually. If users like the collapsed menu, they can collapse it manually.

It would be great if the app would just leave the menu state alone however it is according to user preference.

**Comment by marydavis** [comment]
@adambuczynski thanks for letting us know and we agree! we just fixed it :)

**Comment by adambuczynski** [comment]
Cheers, thank you!
