### ISSUE TITLE
No way to edit issue title from the edit issue modal

### ISSUE THREAD

**Issue by adambuczynski** [waffleio/waffle.io#2569]
When you click the comments icon of an issue, you get to edit all aspects of an issue from the resulting modal (e.g. description, labels, assignee) except the title. This is counter intuitive.

Please allow us to edit the title from that screen as well.

**Comment by kellihsf** [comment]
Thanks for the request! We're already tracking that issue on [#801](https://github.com/waffleio/waffle.io/issues/801), so we'll be closing this as a duplicate.

**Comment by adambuczynski** [comment]
Thanks, I'll subscribe there
