### ISSUE TITLE
Skjult profil virker ikke

### ISSUE THREAD

**Issue by bornibyen** [waffleio/waffle.io#2576]
NÅr man vælger et en profil skal være skjult, så bliver den det ikke. Dvs, så kan den stadig ses: http://bornibyen.dk/koebenhavn/users/9161

**Comment by kellihsf** [comment]
hi @bornibyen!

You have reached waffle.io's public board. Were you looking for information on your profile view for http://bornibyen.dk/koebenhavn?

**Comment by kellihsf** [comment]
closing this for now, let us know if there's anything we can help you with!
