### ISSUE TITLE
Add a link to our status page to the FAQ and README

### ISSUE THREAD

**Issue by burtonjc** [waffleio/waffle.io#2577]

**Comment by kellihsf** [comment]
- [ ] FAQ
- [ ] README

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
