### ISSUE TITLE
Attempting to create a new issue results in a 503 error from Waffle (but the issue is still created)

### ISSUE THREAD

**Issue by MakotoTheKnight** [waffleio/waffle.io#2578]
I've been using Waffle successfully for about six months now, and this is the first occurrence of anything like this.

What I've done:

 - Go into my public repository
 - Create a new task
 - Observe that GitHub will create the task
 - Get back a 503 error from Waffle stating that the card cannot be created

If you require the payload I sent across during these requests, please let me know.

**Comment by kellihsf** [comment]
hi @MakotoTheKnight,

I just replied on [#2579](https://waffle.io/waffleio/waffle.io/cards/5748bcee5d96301e000cef5a) too, but just wanted to let you know we've resolved the issue we were having. If you still see this behavior, please let us know! :)
