### ISSUE TITLE
BUG: Tasks and Issues aren't syncing properly

### ISSUE THREAD

**Issue by shieldgenerator7** [waffleio/waffle.io#2579]
It seems that my internet or my browser had a hiccup in which both my Google Calendar and my Waffle.IO project goofed up. My Google Calendar wouldn't create events, and my Waffle.IO project won't sync my tasks/issues correctly.

I created two new tasks in Waffle.IO using the "Add Task" button, which I thought had been created just fine. But then after the hiccup, it displays both of them multiple times in my waffle, but there's only one issue for each one in Github.

Then I tried to create a third task in Waffle.IO, and each time I tried to add it, Waffle.IO gave an error, "Error creating Task" (or something like that). Then I go to Github and see that it's created the issues just fine, and there's three of them (one original and two duplicates. I then closed the two duplicates).

Here is what my Waffle looks like, compared to my GitHub issues page (after multiple refreshes, including restarting my computer):
![image](https://cloud.githubusercontent.com/assets/3438834/15620280/654d10e6-2427-11e6-8317-81b94ca086ef.png)
![image](https://cloud.githubusercontent.com/assets/3438834/15620290/6d1520a2-2427-11e6-85c0-94a71a392780.png)

Note that there's duplicates in the "Inbox" column of the waffle

**Comment by MakotoTheKnight** [comment]
This may be related to some of the things [I've been experiencing](https://github.com/waffleio/waffle.io/issues/2578), and related to the [currently degraded performance](http://status.waffle.io/#) of the site.

**Comment by kellihsf** [comment]
hi @shieldgenerator7,

We are experiencing some performance issues right now and that might be what you are running into. Sorry for the inconvenience! You can follow our [status page](statuspage.waffle.io) for updates.

**Comment by shieldgenerator7** [comment]
@MakotoTheKnight Yes, I believe it is related, altho I don't remember seeing error 503

@kellihsf Yes, I believe that must be what it is. Thanks for keeping us up-to-date and working to maintain this awesome program!  I really appreciate responsive devs!

**Comment by kellihsf** [comment]
@shieldgenerator7,  @MakotoTheKnight

This issue has been resolved! Let us know if you're still experiencing any of this behavior, thanks!

**Comment by shieldgenerator7** [comment]
@kellihsf The issue has been fixed! Thanks!
