### ISSUE TITLE
Pick label functionality inconsistent for add/edit issues

### ISSUE THREAD

**Issue by adambuczynski** [waffleio/waffle.io#2580]
Observe that for editing an issue, I can assign Waffle "column" labels, e.g. "ready", "backlog", etc:

![image](https://cloud.githubusercontent.com/assets/490562/15624911/e50e091c-24e9-11e6-9d4b-8c837b7be7d2.png)

While for adding an issue, where it actually would be more practical, I cannot:

![image](https://cloud.githubusercontent.com/assets/490562/15624919/032cdfd6-24ea-11e6-83f8-50c36b00ef24.png)

Can you please make this consistent so we can immediately assign a new issue to a specific column? My "backlog" column is hidden by default, and every new issue is placed in there, so I have to open it, move the issue, and close it again which is rather annoying and unproductive.

If any, the labels should be removed from the Edit action.

**Comment by Woodya** [comment]
+1, or a separate drop down for "column". either way: ability to assign column when creating the ticket.
