### ISSUE TITLE
Make completed issues accessible

### ISSUE THREAD

**Issue by ddinchev** [waffleio/waffle.io#2581]
Issues in "Done" disappear in a week. Sometime cards contain important information that I would later want to check. It would be nice to have an option to add "Archived" column that is folded by default, instead of having to go to GitHub to check the closed issues.

**Comment by kellihsf** [comment]
hi @ddinchev,

We have an open feature request, [#314](https://beta.replicated.waffle.io/waffleio/waffle.io/cards/574e0016f2ac390900e18893) for customizing the Done column time, would that be helpful to you?

**Comment by homeyer** [comment]
The throughput page shows the last month of completed issues, check it out via the metrics link in your sidebar.
