### ISSUE TITLE
Support for the multiple assignees GitHub feature

### ISSUE THREAD

**Issue by mauroservienti** [waffleio/waffle.io#2585]
Now that GitHub [supports multiple assignees](https://github.com/blog/2178-multiple-assignees-on-issues-and-pull-requests) per issues and PRs it would be nice to have them show up and to have them manageble from the Waffle board.

**Comment by tidusjar** [comment]
:+1: Defiantly.

I've been using Waffle to manage all of my issues, and I have been waiting for something like this to come along. Need to go into Github to manage this now :(

**Comment by burtonjc** [comment]
Must use the `Accept:  application/vnd.github.cerberus-preview` header to see multiple assignees

**Comment by songawee** [comment]
- [ ] make sure that web hooks coming in from github updates assignees collection
- [ ] always pull updated issue from github with the new Accept header
- [ ] if you create a branch that has an issue name in the title, we will move and assign
if there’s not already an assignee and add an assignee to assignees collection

Some improvements to the auto-work tracking:

- [ ] when opening a pr that closes an issue, the user submitting the pr should be added as an assignee on that issue

**Comment by burtonjc** [comment]
This still needs to work in Takeout using potentially out of date GH:E installs. To test that before deploying, we should run the app locally and unset the `Accept` header so GitHub doesn't send us `assignees`.
- [ ] backwards compatibility check

**Comment by burtonjc** [comment]
I created https://github.com/waffleio/waffle.io/issues/2608 to handle the improvements to auto-work tracking once multiple assignees is out.

**Comment by mauroservienti** [comment]
Lovely, thanks
