### ISSUE TITLE
Description gets blown away when creating issue.

### ISSUE THREAD

**Issue by davissp14** [waffleio/waffle.io#2586]
Description doesn't persist when creating an issue, however it does work when editing an existing issue.

**Comment by homeyer** [comment]
@davissp14 are you using waffle.io or an instance of Waffle Takeout?

**Comment by homeyer** [comment]
This bug was fixed in Takeout in 2.2.1: https://github.com/waffleio/waffle.io-takeout/blob/master/releases/2.x.md#waffle-takeout-221, might just need to update your version.

**Comment by davissp14** [comment]
👍  Thank you!
