### ISSUE TITLE
Create a Windows 10 Web App

### ISSUE THREAD

**Issue by kavdev** [waffleio/waffle.io#2587]
Hi all, love the app.

It seems like creating a hosted web app for the Windows 10 ecosystem might be fairly simple. Check it out: https://microsoftedge.github.io/WebAppsDocs/en-US/win10/HWA.htm

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
