### ISSUE TITLE
Mention waffle in page titles

### ISSUE THREAD

**Issue by SirCmpwn** [waffleio/waffle.io#2594]
waffle's "linode/manager" is indistiguishable from GitHub's "linode/manager" in my browser tabs. "linode/manager - waffle" would be better.

**Comment by kellihsf** [comment]
hi @SirCmpwn,

You can change the display name of your repo (Settings->Sources, pencil icon) and it will be displayed on the browser tab as well as on the cards and the drop down. The only thing that won't be changed is the URL. Would that work for you?

**Comment by SirCmpwn** [comment]
I guess that works as a workaround, but this is feedback site-wide rather than a specific concern of my repositories.

**Comment by kellihsf** [comment]
Ah gotcha. I'll leave this in our Ideas column for other users to find! :)

**Comment by marydavis** [comment]
@SirCmpwn we have added "| Waffle.io" to the end of the browser tabs :) Enjoy!

**Comment by SirCmpwn** [comment]
Thanks!
