### ISSUE TITLE
Removed Users Show up in list of Assignees

### ISSUE THREAD

**Issue by AlexMcDuffMiller** [waffleio/waffle.io#2595]
We had a user that was a part of our team, but then the user was removed from the team that gave the user access to the repo. This user still shows up as an assignee in our waffle board even though they are no longer on an authorized team.

**Comment by homeyer** [comment]
Hey Alex, is it still showing up today? Might just be a delayed caching error.

**Comment by AlexMcDuffMiller** [comment]
It's been happening for several weeks. Or did an update just get published?

**Comment by homeyer** [comment]
Ah, ok.

We connect directly to the GitHub API for the assignee list, happy to dig into it a bit more if you tell us which repo it's happening for.

**Comment by kellihsf** [comment]
hi @AlexMcDuffMiller,

We'll be closing this issue for now. Please let us know if we can help you out with this. Thanks!

**Comment by AlexSneedMiller** [comment]
Sorry for not replying. 

This is happening on a GitHub Enterprise repo.
