### ISSUE TITLE
when attempting to create a board for a repo, if the project already exists just send them to the board instead of showing an error that it already exists

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#2597]
When on the dashboard, if you try to create a board for a repo that already exists as a project that you're not a team member on, it will show you a "project already exists error". That's some awesome UX, let's fix it!

**Acceptance Criteria**
- [ ] if a project already exists, just show the board instead of erroring. Probably just try to get the project before attempting to create it, so you're added to the team list appropriately.

**Comment by marydavis** [comment]
we show all projects you have access to now :)
