### ISSUE TITLE
Make assigning users UX consistent

### ISSUE THREAD

**Issue by adambuczynski** [waffleio/waffle.io#2598]
In the overview:

![image](https://cloud.githubusercontent.com/assets/490562/15803150/a619938a-2b23-11e6-856f-8009e7f4132f.png)

Clicking on an avatar brings up the "change collaborator card".

In the issue detail view:

![image](https://cloud.githubusercontent.com/assets/490562/15803153/c94dcb1e-2b23-11e6-9c63-ffc55a5f4264.png)

Clicking on the avatar does nothing and one has to click on the minuscule `edit` link to do the same thing.

Can you please remove the `edit` link, it's inconsistent as this is the only place in all of Waffle that I can see an actual `edit` link being used to edit something. Instead, simply make the avatar (and name) clickable as it is clickable in the overview.

Also, the term "collaborator" is inconsistent when you think about assigning an issue to someone. It says in the edit view "assigned to", so the correct term would be "assignee".

**Comment by marydavis** [comment]
@adambuczynski we just added support for multiple assignees and in the process fixed our inconsistencies for editing assignees :) let us know if you have any other suggestions, we appreciate it!

**Comment by adambuczynski** [comment]
Great to hear, thank you!

**Comment by adambuczynski** [comment]
@marydavis One thing that's still not possible though is that you still can't click on the user's avatar in the list of assignees to bring up the assignees dropdown when viewing an issue.
