### ISSUE TITLE
Support for multiple assignees

### ISSUE THREAD

**Issue by adambuczynski** [waffleio/waffle.io#2599]
Github has recently implemented support to assign multiple people to an issue:

https://github.com/blog/2178-multiple-assignees-on-issues-and-pull-requests

Waffle should probably copy the functionality and allow us to assign multiple assignees to issues as well.

**Comment by kellihsf** [comment]
hey @adambuczynski,

Good news! We're actually working on this now on [#2585](https://github.com/waffleio/waffle.io/issues/2585). We'll close this as a duplicate, so feel free to subscribe to the issue in GitHub to follow its activity. :)

**Comment by adambuczynski** [comment]
Cool thank you :)
