### ISSUE TITLE
Persist column collapse state in URL

### ISSUE THREAD

**Issue by kellihsf** [waffleio/waffle.io#2600]
This would allow users to share URLs to their same board view.

**Comment by Woodya** [comment]
using local storage (in the manner currently implemented) confuses my browser. i have 10-15 tabs open for waffle. each filtered to a particular team member with customized column collapse state appropriate to their role.

cold load my browser is a pita, as all the columns get collapsed incorrectly, also i when i share a view with a team manager, they see the filter through there most recently used collapse state, which is not appropriate to the filtered view i'm sending them, causing them to have to customize the collapse state, which in turn corrupts their local work flow.

using url solves both problems. local state is isolated, links/views can be shared.
to preserve across sessions per the other ticket/use-case, you could simply apply remembered collapse state if there is no collapse-state parameter in the url on page load.

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
