### ISSUE TITLE
Email/Slack as source for feedback

### ISSUE THREAD

**Issue by samhavens** [waffleio/waffle.io#2601]
For example with email, we could have a "send us feedback!" email link, and emails sent to that address could be imported as issues to our waffle. Same with slack, except since it is internal it could be for bugs and/or feedback.

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
