### ISSUE TITLE
Pull size from Zenhub's extension?

### ISSUE THREAD

**Issue by Gabriel-p** [waffleio/waffle.io#2602]
ZenHub's extension has its own size ("Estimate") measure.

Could the size for each issue be pulled from that info?

**Comment by kellihsf** [comment]
hi @Gabriel-p,

We don't have a way to extract size for issues at this time. We plan on releasing our API in the future, so you could use it to get sizes. Thanks!

**Comment by kellihsf** [comment]
Closing this for now, let us know if there's anything else we can answer for you!
