### ISSUE TITLE
Disable debug information

### ISSUE THREAD

**Issue by Crevil** [waffleio/waffle.io#2606]
Increase performance on the website by disabling debug information lige `ng-scope`and `ng-binding` classes on elements.

Read more here: https://docs.angularjs.org/guide/production

It's easily done with the following snippet when running the application in production:

``` javascript
myApp.config(['$compileProvider', function ($compileProvider) {
  $compileProvider.debugInfoEnabled(false);
}]);
```

**Comment by homeyer** [comment]
We're not in a current enough version of angular to use this right now. Angular 2 in the plan though :)

**Comment by Crevil** [comment]
Ah, didn't notice that you were on Angular 1.2.21. 
As a site note, when taking a look on your source, I see that you don't use script bundling either. This will as well decrease loading times as the HTTP transfer overhead is considerable when having many small files. 

Anyways. Just wanted to let you know. Thank you for the great product you're running.

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
