### ISSUE TITLE
Checkbox list remains un-editable

### ISSUE THREAD

**Issue by adambuczynski** [waffleio/waffle.io#2610]
Sometimes, the checkbox list in the description of an issue remains uneditable. E.g. you can't tick or untick the checkboxes, and they appear as disabled.

Not quite sure what the steps to reproduce are, but I've seen it happen a couple of times today.

**Comment by richchurcher** [comment]
I'm seeing this on all our current Waffle.io boards. No checkboxes are currently editable, they are all coming through with the `disabled` attribute set. When viewing the same issue on GitHub, the boxes can be checked and unchecked as normal.

**Comment by adambuczynski** [comment]
Yep, the issue is consistent. Only after refreshing the app completely does
the list become editable again.

**Comment by richchurcher** [comment]
I can't even get them to work after a complete refresh/cache dump.

**Comment by burtonjc** [comment]
This should now work:

- [ ] task lists work
  - [ ] even if they are nested

**Comment by richchurcher** [comment]
Thanks team! Much appreciated :+1:
