### ISSUE TITLE
General Questions

### ISSUE THREAD

**Issue by lars2840** [waffleio/waffle.io#2615]
@homeyer Have you seen the emails Katrina and I (christian larson) have sent you?

**Comment by homeyer** [comment]
Nope, did you send them to andrew@waffle.io?

**Comment by lars2840** [comment]
@homeyer Yep thats the email we have been using (same as when we were originally talking). We've sent about 4-5 to you and Ashley for the past few weeks. Can you try emailing me to see if I receive anything please, thanks.

**Comment by homeyer** [comment]
Just responded to one from June 1st that I missed.

If you email takeout@waffle.io it goes into our prioritized support queue and won't be dropped on the floor 😥.
