### ISSUE TITLE
Pipe/Column description - keep it visible

### ISSUE THREAD

**Issue by Slind14** [waffleio/waffle.io#2616]
The descriptions for reach column/pipeline are great, unfortunately they only show when its empty. Couldn't they always be there at the bottom or shown on hover over the title? Allows for better clarification.

**Comment by alyciapurcell** [comment]
agree with this

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
