### ISSUE TITLE
Sort issues by like (+1) of github issues inorder to order by higher votes.

### ISSUE THREAD

**Issue by nagavijays** [waffleio/waffle.io#2619]
Github doesn't provide users to vote for issues. But it provides Like button (ie. +1). This can be used for voting github issues. 

It would be good if waffle board supports to sort/filter github issues based on the number of votes (i.e likes). This helps to target highly voted issues to develop first.

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
