### ISSUE TITLE
Are external dependencies really needed?

### ISSUE THREAD

**Issue by ramonsmits** [waffleio/waffle.io#2620]
Ghostery reports:

* Google Analytics
* Intercom
* Mixpanel
* New Relic
* Twitter Advertising

Are these really all needed?

**Comment by homeyer** [comment]
Yep!

- GA: we use that to see where we're getting referrals from, so we know who's talking about us (blogs, etc)
- intercom: for in-app conversations
- mixpanel: for acquisition, activation, retention and referral metrics, necessary for us to figure out if we're doing the right thing or not
- new relic: for client side performance monitoring... we're not actively using this right now, so could remove it
- twitter: for some experiments on twitter ads, not active right now
