### ISSUE TITLE
Issues showing up multiple times

### ISSUE THREAD

**Issue by mlafeldt** [waffleio/waffle.io#2621]
I don't know why but some issues show up multiple times.

Example showing 2 duplicates (top and bottom):

![screenshot 2016-06-15 10 28 14](https://cloud.githubusercontent.com/assets/158074/16073035/41f495a8-32e4-11e6-8f7a-2f5e3cf9a734.png)

Even after moving the affected issues to another column, the duplicates are still there.

**Comment by mlafeldt** [comment]
And no, reloading the page does not help. :)

**Comment by kellihsf** [comment]
hi @mlafeldt,

It looks like you have the repo, Jimdo/wonderland-chaos listed twice as a source under your main repo. Can you delete one of the extra repos and see if you still have duplicate issues? Thanks!

**Comment by mlafeldt** [comment]
Yes, that turned out to be the problem. Thank you.

So I guess you improved the UI do avoid duplicating at some point, but forgot to remove existing duplicates?

Also, I noticed that the UI says that a repo does not exist if one tries to add it multiple times, which is a little confusing too.
