### ISSUE TITLE
Order boards by most recently updated

### ISSUE THREAD

**Issue by seancdavis** [waffleio/waffle.io#2622]
GitHub's [orders repos by most recently updated](https://github.com/waffleio). This is nice because it keeps active projects near the top of the list. As more and more boards become inactive it can be beneficial to keep the few active ones near the top of the list.

**Comment by seancdavis** [comment]
I'll add that I do like the filter field being focused when the page loads. Perhaps an alternative to this is highlighting the top entry, so you can type in a couple letters on the name, hit enter, and jump right into the project.

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
