### ISSUE TITLE
waffle iframe with api

### ISSUE THREAD

**Issue by serapath** [waffleio/waffle.io#2631]

**Comment by serapath** [comment]
I'm trying to use waffle embedded via iframe.
This works without problems, but unlike , for example `gitter`, if someone is not signed into github, clicking a button on waffle inside the iframe doesnt work. Would be great to fix that.

In general, a sandboxed iframe (= loads content from a url <iframe src=url>) might be protected pretty well and it would be lovely if it had a `window.postMessage()` based API to interact with it in a controlled way - for example: css theme injected via a postMessage to the waffle iframe :-)

**Comment by serapath** [comment]
**Use Case**:
* read all data in the waffle board (current state) to change something in the parent/surrounding page while the waffle board is embedded as an iframe
* change the `theme` of the waffleboard to adapt (font-family/(background)-color/...) to parent/surrounding page
* add event listeners to elements on the waffle board to read user interaction in order to change the parrent/surrounding page and maybe even replace default behavior, e.g.
  * deactivate opening the github page of an issue
  * make a click anywhere on the card to open the overlay detail view
  * ideally - add a small "pencil icon" to edit the title of a card
* remove the menu bars to the left and top - ideally keeping elements like the "search/filter bar" and sometimes the "add issue button"

**Comment by serapath** [comment]
any news?

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
