### ISSUE TITLE
migrate projects to account for GitHub owner

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#2633]
Projects in Waffle should map to a Waffle account based on the primary repo owner.

**Acceptance Criteria**
- [x] this is a migration, so it works on takeout too
- [x] for each project:
  - [x] if the project's primary repo's owner is not the project's current account, move it to the account.
  - [x] if the account does not exist for the repo owner, create one. 
  - [x] If the owner is an org, set the org flag on the account.

**Comment by songawee** [comment]
This will take about 5 hours to run in production. I didn't see a huge strain on resources when I ran against the prod clone so it seems feasible to run it during business hours.
