### ISSUE TITLE
when a project is created, put it in the primary repo owner's account

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#2634]
**Acceptance Criteria**
- [x] when a project is created, the account is set to the primary repo owner's account
- [x] if that account does not exist, create it, and set the org flag appropriately
- [x] where we handle renames currently, also set the account to the new owner after a rename (creating the account if necessary).

**Comment by burtonjc** [comment]
We will have to figure out a way to keep the org flag in sync because it can change in GitHub
