### ISSUE TITLE
Ability to "pin" projects

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#2642]
Once we show users all the projects they have access to, the list will be rather overwhelming for some.

Give users a way to "pin" their projects to show at top or on a special tab.

**Acceptance Criteria**
- [x] assume existing projects will be pinned before we add users to all projects they have access to
- [x] add to project dropdown
- [x] design UI
- [x] build it!

**Comment by burtonjc** [comment]
Must run https://github.com/waffleio/waffle.io-migrations/pull/13 before toggling on "pinned" projects.
