### ISSUE TITLE
mark existing projects as "pinned"

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#2644]
- [ ] update domain model to denote pinned for a user... somewhere
- [ ] migration to mark existing projects as "pinned"

**Comment by burtonjc** [comment]
### Steps
- [ ] Create Preference model
- [ ] Remove project from `pinnedProjects` preference when a user is removed from that project
- [ ] Create a Preference document for all new users
- [ ] Migrate existing users to have a Preference document
- [ ] API endpoints to `GET`/`PATCH` preferences
- [ ] Client fetches and can update user preferences

### Model Schema:
```coffeescript
user: ObjectId
pinnedProjects: [ObjectIds]
```
