### ISSUE TITLE
夏休みのタスク

### ISSUE THREAD

**Issue by taka-sho** [waffleio/waffle.io#2653]

**Comment by kellihsf** [comment]
Hi @taka-sho,

Is there anything we can help you with?

**Comment by kellihsf** [comment]
We'll be closing this issue for now. Reach out if you need any help! :)

**Comment by kellihsf** [comment]
Also, if you're referring to the checkbox lists not functioning, we're working on a fix for that here:  https://waffle.io/waffleio/waffle.io/cards/575bb4b67d85e21e00f95abc

Thanks!
