### ISSUE TITLE
multi-repo size not in sync/set

### ISSUE THREAD

**Issue by vutran** [waffleio/waffle.io#2656]
**Issue:** When in a multi-repo setup, the size/points is set as compared when viewing as a single-repo.

**Example:**

**Step 1.** I have several single-repo boards (PROJECT-A, PROJECT-B, etc.). I started allocating size/points per card on each board.

**Step 2.** I've created a multi-repo board which includes all my single-repo to allow for a global view of issues across all boards. **Sizes** (or points) are not transferred from the values it was set from Step 1.

**Comment by kellihsf** [comment]
hi @vutran,

Right now sizes on issues won't carry over (labels will though).  Just a tip: we don't recommend having repos added as sources to main projects which are also standalone boards, as it can wreak havoc among the boards. We'd advise you to delete those separate standalone boards, unless they're necessary. :)

**Comment by vutran** [comment]
@kellihsf That makes sense. Will close this since your recommendation has worked.
