### ISSUE TITLE
Checkboxes disappear for closed issues

### ISSUE THREAD

**Issue by adambuczynski** [waffleio/waffle.io#2661]
See:

![image](https://cloud.githubusercontent.com/assets/490562/16355959/ad91417c-3b1c-11e6-8d5e-6036460ea316.png)

Possibly related to https://github.com/waffleio/waffle.io/issues/2610

**Comment by adambuczynski** [comment]
Also happens for non-closed issues. Seems to be related to what was happening with the description disappearing altogether. Now it's just the checkboxes disappearing.

**Comment by seanperkins** [comment]
I am having whole descriptions disappearing when I move a card after editing the issue in Github.
