### ISSUE TITLE
The beginning of the week is not Sunday

### ISSUE THREAD

**Issue by WayneBooth** [waffleio/waffle.io#2662]
The throughput graph counts a week from Sunday to Saturday. Not everyone lives in the US.
User should be able to configure a week to start either Sunday or Monday.

**Comment by kellihsf** [comment]
Hi @WayneBooth,

Touche! We are planning on making some changes to our throughput graph in the near future (including the start of the week). Stay tuned! :)

**Comment by songawee** [comment]
This issue has been resolved by the new throughput graph released in WaffleMetrics - http://blog.waffle.io/wafflemetrics/. In the new graph, you are able to specify what start date you would like. Let us know if you have any other questions or comments.

Thanks!
