### ISSUE TITLE
Build UI for viewing accounts

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#2663]
- [x] AC filled in from #2637

**Comment by marydavis** [comment]
- [ ] add logout icon to sidebar
- [ ] make clicking avatar on sidebar go to account page
- [ ] make clicking avatar on dashboard go to account page
- [ ] maybe add orgs to dashboard to link to org account pages?
- [ ] change url from /account to /:owner - for orgs?
- [ ] create UI to match design

**Comment by homeyer** [comment]
Goal is to be able to release an account page before we have billing.
