### ISSUE TITLE
Appointments repeated in payment report and ALL TIME Revenue Breakdown (payment report)

### ISSUE THREAD

**Issue by bryan-savantcare** [waffleio/waffle.io#2664]
Here is the video : 

https://www.youtube.com/watch?v=LtCSCBJrYcI&feature=youtu.be

**Comment by kellihsf** [comment]
Hi @bryan-savantcare,

You've reached waffle.io's public board! Is there anything we can help you with? (We don't have any type of payment reports/revenue breakdown) :)  Thanks!

**Comment by kellihsf** [comment]
Closing this for now, let us know if you have any questions!
