### ISSUE TITLE
Quoted text is ridiculously large

### ISSUE THREAD

**Issue by adambuczynski** [waffleio/waffle.io#2666]
Why so large? It's just quoted text. It shouldn't be prominent, it should be greyed out even.

![image](https://cloud.githubusercontent.com/assets/490562/16481507/bef89c76-3eff-11e6-965f-8f870487ff73.png)

To produce quoted text, use `>`, e.g.:

> Quoted text

**Comment by songawee** [comment]
Hey @adambuczynski, great catch! Just pushed a fix. Hopefully that looks a bit better ⬆️

> Test

**Comment by adambuczynski** [comment]
@songawee thanks!
