### ISSUE TITLE
Creation of Sublanes

### ISSUE THREAD

**Issue by aladag** [waffleio/waffle.io#2668]
We are working with kanban in our company. We are now working on changing the workflow and noticed that instead of using labels or milestones (in many cases the issues are related somehow - like client request etc - but cannot be grouped under a milestome) we wanted to create sublanes under the lanes. Is that something that you want to put in your roadmap anytime soon?

Thank you to your amazing team!

**Comment by songawee** [comment]
Hey @aladag, thanks for reaching out!

I believe we are currently tracking this feature on this issue - https://github.com/waffleio/waffle.io/issues/1965 and you will be able to follow any updates we have there. Closing this for now, but feel free to add anything on the other issue.

Thank you!
Dennis

**Comment by aladag** [comment]
@songawee thanks a lot for referring me to the request, i am sure this will be a useful feature for a lot of clients
