### ISSUE TITLE
Edit board column

### ISSUE THREAD

**Issue by DaTribe** [waffleio/waffle.io#2670]
After a new board column is created it cannot be edited.

**Comment by kellihsf** [comment]
hi @DaTribe,

You should be able to edit a newly created column, you'll have to do this in the Columns section. What are you unable to edit?

**Comment by DaTribe** [comment]
Hi @kellihsf 

Thanks for coming back to me. I have been MIA for a while hence the late response. Yes, I must have missed the way to get it done. I just checked again and I can edit a column.

Thanks,
