### ISSUE TITLE
Select multiple tags

### ISSUE THREAD

**Issue by mortona42** [waffleio/waffle.io#2671]
In the filter interface, I typed in one of my tags and see the results filtered.  I added another tag, I tried separating with a comma or a tag, neither will filter the results to items with both tags.  Is this possible?

**Comment by kellihsf** [comment]
hi @mortona42,

Currently, it's not possible to type multiple labels in the in the filter box. If you want to filter by multiple labels, you'll just have to select them from the drop down. We'll keep this in our Ideas columns for other users to find, and maybe implement in the future. Thanks!

**Comment by mortona42** [comment]
Oops, I see how to do that now!  Being able to type them in would improve the experience a tad, but glad to know there's a way to do it anyway.

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
