### ISSUE TITLE
`Done` column aggregates closed issues that were **updated** last week

### ISSUE THREAD

**Issue by snird** [waffleio/waffle.io#2673]
As the title says, it considers every closed issue that was **updated** this week.
It means, that even if an issue were closed 5 months ago, if I'll remove a label from it, it will reappear in the `Done` column.

**Comment by homeyer** [comment]
Hey @snird, this is a limitation of the GitHub API. We query GitHub for closed issues that were last updated in the last week, because we can't query on when they were closed.
