### ISSUE TITLE
Past due milestone highlight

### ISSUE THREAD

**Issue by akofman** [waffleio/waffle.io#2674]
Would be nice to indicate from the board whether a milestone is past due. Maybe by highlighting it then add the availability to close it.

Thanks for your work !

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
