### ISSUE TITLE
Fix the `Add Issue` functionality

### ISSUE THREAD

**Issue by 23inhouse** [waffleio/waffle.io#2675]
When adding a new issue, the UI sucks. Tab works but selecting items with arrows does not work. Changing the assigned user and label also sucks. It requires lots of mouse clicks. Then closing these selections is also hard. Finally after adding the new issue, it's hard to make the Add model disappear. I use the add issue feature many times per day. It would be awesome if it could be a bit better.

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
