### ISSUE TITLE
Inline comments is not showing on waffle cards

### ISSUE THREAD

**Issue by rochacbruno** [waffleio/waffle.io#2681]
If a PR has code inline comments (code review comments) that comments is not being showed when we open a card in waffle.io

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
