### ISSUE TITLE
API endpoint for /projects/owner/:owner

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#2684]
**Acceptance Criteria**
- [ ] responds with projects for the `:owner`, correctly limiting results based on your permissions
- [ ] don't show sources in projects, so we can ignore permission checking for sub-sources

**Comment by homeyer** [comment]
Notes from Jacob: Get account, fetch projects where logged in user is in the team/viewers or is public

**Comment by burtonjc** [comment]
Need a query param of `type` that can be `owner`, `member`, or `all`. Default `type` to `owner`. We are going to punt on this until we remove the `/user/projects` endpoint.

**Comment by burtonjc** [comment]
This will have a similar problem to the `/accounts/:owner` endpoint. Going to change it to `/projects/owner/:owner` similar to `/accounts/owner/:owner`.
