### ISSUE TITLE
handle moving account when a repo is transfered

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#2686]
**Acceptance Criteria**
- [ ] where we handle renames currently, also set the account to the new owner after a rename.

**Comment by burtonjc** [comment]
It might so happen that it is moved to an owner that doesn't have a waffle account yet. So we need to handle creating an account if it was transferred to a non-waffle user.

- [ ] Create account for owner if it doesn't exist yet

**Comment by burtonjc** [comment]
After investigating this and #2634 a bit more, we think it makes since to merge these two cards. It is largely the same implementation and will be easier to do it at the same time. Going to move the AC from this issue into #2634 and close this card.
