### ISSUE TITLE
simple annoying issue nothing on "In progress" column

### ISSUE THREAD

**Issue by tzookb** [waffleio/waffle.io#2688]
I open waffle drag an issue to "In progress"

all seems good till now....

I refresh the page,
the issue has the tag of "in progress"
BUT 
it is back on the "backlog" column.....

any ideas?

**Comment by kellihsf** [comment]
hi @tzookb,

Sorry for the late reply, are you still having trouble with this? If so, can you email us at support@waffle.io so we can take a closer look? Thanks!

**Comment by kellihsf** [comment]
We'll close this for now.. please let us know if you need any help!
