### ISSUE TITLE
Testing Waffle.io usage

### ISSUE THREAD

**Issue by stewtopia** [waffleio/waffle.io#2690]
Those who have never seen a living Martian can scarcely imagine the strange horror of its appearance.  The peculiar V-shaped mouth with its pointed upper lip, the absence of brow ridges, the absence of a chin beneath the wedgelike lower lip, the incessant quivering of this mouth, the Gorgon groups of tentacles, the tumultuous breathing of the lungs in a strange atmosphere, the evident heaviness and painfulness of movement due to the greater gravitational energy of the earth--above all, the extraordinary intensity of the immense eyes--were at once vital, intense, inhuman, crippled and monstrous.  There was something fungoid in the oily brown skin, something in the clumsy deliberation of the tedious movements unspeakably nasty.  Even at this first encounter, this first glimpse, I was overcome with disgust and dread. 

Suddenly the monster vanished.  It had toppled over the brim of the cylinder and fallen into the pit, with a thud like the fall of a great mass of leather.  I heard it give a peculiar thick cry, and forthwith another of these creatures appeared darkly in the deep shadow of the aperture. 

I turned and, running madly, made for the first group of trees, perhaps a hundred yards away; but I ran slantingly and stumbling, for I could not avert my face from these things. 

There, among some young pine trees and furze bushes, I stopped, panting, and waited further developments.  The common round the sand pits was dotted with people, standing like myself in a half-fascinated terror, staring at these creatures, or rather at the heaped gravel at the edge of the pit in which they lay.  And then, with a renewed horror, I saw a round, black object bobbing up and down on the edge of the pit.  It was the head of the shopman who had fallen in, but showing as a little black object against the hot western sun.  Now he got his shoulder and knee up, and again he seemed to slip back until only his head was visible.  Suddenly he vanished, and I could have fancied a faint shriek had reached me.  I had a momentary impulse to go back and help him that my fears overruled. 

Everything was then quite invisible, hidden by the deep pit and the heap of sand that the fall of the cylinder had made.  Anyone coming along the road from Chobham or Woking would have been amazed at the sight--a dwindling multitude of perhaps a hundred people or more standing in a great irregular circle, in ditches, behind bushes, behind gates and hedges, saying little to one another and that

**Comment by homeyer** [comment]
![image](https://cloud.githubusercontent.com/assets/84629/16784290/4a9d6768-4845-11e6-850e-26dcafd04258.png)

**Comment by kellihsf** [comment]
hi @stewtopia,

We'll close this issue for now;  let us know if there's anything we can help with! :)
