### ISSUE TITLE
announce project pinning

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#2695]
- [x] screenshot (@marydavis)
- [x] intercom message primed (@homeyer)
- [x] send message over weekend (@burtonjc)
- [x] remove the 'visited' part of the home page text for 'Your Projects' - maybe "All GitHub repositories in which you are a collaborator that a Waffle project has been created will be shown in this list. "

**Comment by marydavis** [comment]
![pin-project](https://cloud.githubusercontent.com/assets/176437/16884149/c86cd262-4a95-11e6-93e3-dcfb220e9ebe.gif)
