### ISSUE TITLE
Increase 'Done' history

### ISSUE THREAD

**Issue by kgiszewski** [waffleio/waffle.io#2698]
Our sprints are >7 days so it'd be nice to see them on Waffle without having to go back to GitHub to see them. Perhaps 14 days if it can't be configured.

**Comment by kellihsf** [comment]
hi @kgiszewski,

We're tracking the feature request for customizing the time on the Done column on [#314](https://waffle.io/waffleio/waffle.io/cards/53440db224ceb40200d90f99), so we'll close this as a duplicate. Thanks!
