### ISSUE TITLE
Labels need explanation and a clean-up

### ISSUE THREAD

**Issue by franz-josef-kaiser** [waffleio/waffle.io#2702]
_Documentation Request_

While everyone will likely understand what labels like `bug` (GitHub default) stand for, not  [all used labels](https://github.com/waffleio/waffle.io/labels) are really clear and easy to follow. Could you please outline (in your [`README.md`](https://github.com/waffleio/waffle.io/blob/61c14ad726ee838a3da2ff9610728c6bbae43e51/README.md)) how exactly your project management works?
#### Acceptance Criteria
- [ ] Add a _Label Cheat Sheet_ `.md`-file in the repo root
- [ ] Clear up labels that have no meaning anymore; Move orphaned issues to other labels – Example: Sprint labels like `iteration*` seem to be abandoned and not in use anymore.
- [ ] Add [contribution guidelines](https://github.com/blog/1184-contributing-guidelines) to make issues better and goals more clear towards reporters and people willing to participate
- [ ] Add descriptions to issues that at least explain the _why_ – see [working agreement](https://github.com/waffleio/waffle.io/blob/master/WORKING-AGREEMENTS.md#work-that-can-be-public-should-be-public) and _"Work that can be public should be public"_
#### Bonus Goals
- [ ] Add issue numbers in the form of `#123` for issues containing the [`blocked`](https://github.com/waffleio/waffle.io/labels/blocked) label so it's clear what the referenced/ blocking issue is

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
