### ISSUE TITLE
Getting Started with Waffle content

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#2707]
When new users first sign up to Waffle, it would be awesome to enable them with a "how to".

- [ ] this could be published to the blog, converted to a PDF or e-book, whatever you think is appropriate
- [ ] can be just how to use waffle, or could also describe best practices (what columns for what types of teams, how/why you should estimate work, continuous delivery with PRs and repo driven development). That might be a bit beyond, so we can start with just how to use waffle effectively.

**Comment by kellihsf** [comment]
getting started guide: http://blog.waffle.io/?page_id=318&preview=true
