### ISSUE TITLE
Add type field on account model

### ISSUE THREAD

**Issue by burtonjc** [waffleio/waffle.io#2709]
#### Acceptance Criteria
- [x] Account model has a `type: String` field that can be `user` or `organization`
- [x] Migration to add `type: 'user'` to all existing accounts

**Comment by songawee** [comment]
Also am removing `billable` field in a separate migration since it is `false` for every account in production and it appears we aren't using it

**Comment by songawee** [comment]
This also removes the virtual `type` field that I believe originally was put in to track billing, but was never used. We've allocated the type field directly to the schema.
