### ISSUE TITLE
Text is selected when dragging a card in Microsoft Edge

### ISSUE THREAD

**Issue by felixfbecker** [waffleio/waffle.io#2710]
When dragging a card across columns in Microsoft Edge, the text you drag over with your cursor is selected.

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
