### ISSUE TITLE
Remove projects that don't have any viewers/team members and delete the associated data

### ISSUE THREAD

**Issue by songawee** [waffleio/waffle.io#2713]
AC:
- [ ] For projects where project.team and project.viewers are empty, delete these projects along with their associated cards, columns, and any other extraneous data

**Comment by burtonjc** [comment]
Need to figure out a way to do this moving forward before we clean up the old data. Don't want to have to clean it up again down the road.

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
