### ISSUE TITLE
Refresh while dragging: card is not refreshed

### ISSUE THREAD

**Issue by GabrielCW** [waffleio/waffle.io#2714]
Small bug I encountered when I started dragging an issue while pressing R for server sync (I don't have the admin hooks in place, so it's fairly common for me).

While I was dragging it, the issue was updated with referenced PRs, but when the dragging stopped and the issue found its new board, this update disappeared and the issue lost trace of its PRs. A simple reload fixed the problem.

I supposed the dragging action keeps a reference of the issue which is used to created the board issue at the end of the dragging event, and that this one isn't updated by the reload.

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
