### ISSUE TITLE
Relative hashtag links to issue comments are broken

### ISSUE THREAD

**Issue by defrank** [waffleio/waffle.io#2721]
Using relative hashtag links will reopen the current card in a new tab.  It won't scroll to the comment or open in Github.  Ideally,  if the relative hashtag link is used, then the comment will be scrolled to in Waffle.io without navigating to Github.

Markdown examples:
- Absolute URL: `[absolute URL](https://github.com/Readz/Readz/issues/8632#issuecomment-223471243)`
- Absolute path: `[absolute path](/Readz/Readz/issues/8632#issuecomment-223471243)`
- Relative URL: `[hashtag only](#issuecomment-223471243)`

The last example is the primary problem.

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
