### ISSUE TITLE
Add columns before Done but after PR is merged

### ISSUE THREAD

**Issue by MiLk** [waffleio/waffle.io#2726]
Currently, as soon as I merge a PR, it's moved into the `Done` column, but I would like to have intermediate columns `To deploy to staging` and `To deploy to production`.

Is it possible to do that?

With the current system, I need to open an issue, connect the PR to the issue, and close the issue when it's in production. But I have no way to know if I have to deploy to staging or production.

The workflow would be:
`backlog` > `ready` > `in progress` > `in review` > `to deploy to staging` > `to deploy to production` > `done`

**Comment by kellihsf** [comment]
hi @MiLk,

We don't support this workflow currently, but we do have a feature request for supporting multiple done columns on [#616](https://waffle.io/waffleio/waffle.io/cards/53440db124ceb40200d90f5d). Would this be helpful to you?

**Comment by MiLk** [comment]
Yes, it would help.

**Comment by kellihsf** [comment]
Great! We'll close this issue as a duplicate, but I'll add your comments to the existing issue, [#616](https://github.com/waffleio/waffle.io/issues/616). You can subscribe to the issue in GitHub or add any additional comments or feedback around your use case to the existing card. Thanks!
