### ISSUE TITLE
"Could not move card" error

### ISSUE THREAD

**Issue by duckinator** [waffleio/waffle.io#2727]
When I try to move a card, I get the error "Could not move card #&lt;card number>."

The debug console reports a 404 error:

```
PUT https://api.waffle.io/cards/57a6f83bc4eb500e0034f027 404 ()
```

![screenshot 74](https://cloud.githubusercontent.com/assets/39698/17467698/12cb1b00-5cef-11e6-8dac-7085c0cde349.png)

**Comment by kellihsf** [comment]
hi @duckinator,

Can you email us at support at waffle.io so we can take a closer look? Thanks!

**Comment by duckinator** [comment]
Done!

**Comment by kellihsf** [comment]
Thanks! Looking now :)

**Comment by duckinator** [comment]
Turns out I moved the repository to an organization, but forgot to give Waffle access to that organization after doing so.
