### ISSUE TITLE
Points on "Add Issue"

### ISSUE THREAD

**Issue by Willamin** [waffleio/waffle.io#2733]
In the "more details" expander of the "add issue" button, it'd be nice to be able to set point value for the issue.

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
