### ISSUE TITLE
Fix Waffle comments overwriting GitHub data with stale data

### ISSUE THREAD

**Issue by songawee** [waffleio/waffle.io#2735]
There is a concurrency issue occurring where:

When a user is making updates to a GitHub comment and another user in Waffle is also making updates to the corresponding card, Waffle overwrites information in GitHub with outdated data. This can also cause a "Content out of date" error in the GitHub UI.

To repro,
Add a task to an issue in GitHub in a comment
Open the corresponding issue in Waffle
Make an edit to the task list in Waffle and hit "update"
Notice in GitHub that the comment has been updated with the data from Waffle

AC:
- Data should be consistent and up to date regardless of whom and on which system updates it

**Comment by songawee** [comment]
See this discussion - https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/5615720067

**Comment by bigplants** [comment]
@songawee 
Hi,
In case of Title, Assignee or Size on a Card has been changed too.
However, I don't know this is same reason or not.

**Comment by seanperkins** [comment]
Same thing happening to me when editing from Github then moving something in Waffle.

**Comment by kellihsf** [comment]
Also occurring on comments, reported in [intercom](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/7838891427)

**Comment by homeyer** [comment]
More steps to reproduce: 
- have two browser windows looking at a waffle board
- in one, edit the description of a card, save and close the modal
- in the other, drag the card. the old description will be set, overwriting the first.

**Comment by jankeesvw** [comment]
I also had this issue, is this linked to #1256?

**Comment by homeyer** [comment]
We've fixed the underlying issue (on May 1st), and haven't received any new support requests related to this. If you continue to experience problems please let us know!
