### ISSUE TITLE
Select repos with arrow keys and enter

### ISSUE THREAD

**Issue by AttilaSATAN** [waffleio/waffle.io#2736]
While adding a new repo to waffle it would be useful if I could just select with arrow keys over filtered repo names on search screen.

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
