### ISSUE TITLE
Show Billing Info

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#2737]
On the account billing tab, display plan information.

Here are some mockups, based on GitHub's interface. There's creative freedom to figure out a better way to represent that "Metrics" is an add-on, vs a paid upgrade. But, since we only have one add-on right now, we can do whatever is simplest for us and easiest to understand for our customers.

Someone who is on our default free tier:
![image](https://cloud.githubusercontent.com/assets/84629/17655566/fae22e1a-626c-11e6-933c-bd6a379f18b2.png)

Someone who has purchased the add-on:
![image](https://cloud.githubusercontent.com/assets/84629/17655552/de43f2de-626c-11e6-928d-737e5cd347e4.png)

**Acceptance Criteria**
- For this work, manually create/update subscriptions from the Stripe UI since this work does not include creating subscriptions
- [x] Fetch plan information from stripe
  - [x] On an account object we’ll need to store info about their stripe identity. Presumably this will be:
    - customerId
    - planId?
    - subscriptionId?
  - We won’t have (and don’t want) customerIds/plans/subscriptions for free users. For these users default to text for the free plan.
    - Some people suggest creating a plan for free users, but that feels like unnecessary overhead.
- [ ] Monthly billing only for now, no pay ahead for a year
- [x] If a user is on the free tier, the button should be “Start metrics 14 day free trial” 
   - starting a trial tracked separately
- [x] If a user is currently in a trial, show “Purchase Metrics”, with language that’s clear your trial will finish before we charge you
    - Button functionality tracked separately
- [x] If a user has trialed and the trial expired, show "Purchase Metrics"
- [ ] Show the coupon button only if they’ve started a trial (we won’t have a Stripe subscription for them, so we won’t have anything to associate the coupon with)
    - Coupon functionality tracked separately
- [ ] Don’t show the billing tab for takeout

**Comment by homeyer** [comment]
If necessary, this includes a server side endpoint for fetching Stripe information if the client side can't fetch it directly. (Do not expose the Stripe secret to the client side)

**Comment by homeyer** [comment]
Show the amount for the plan also on the "Plan" field, so that when you apply coupons it's visible the discount that you have.

**Comment by homeyer** [comment]
the tabs will need to be in the url so we can navigate directly to the billing tab

**Comment by burtonjc** [comment]
4 conditions (from andrew):
1. Haven't started trial yet
2. Actively trialing, have not upgraded
  - Include how long left on trial
2.5 Upgraded durring active trial
  - Same as condition 3, just make sure next bill date is displayed to be the end of the trial
3. Paid
  - Make sure to include when you will be billed next
4. Trial expired

**Comment by burtonjc** [comment]
In the event that we have a user trial and never sign up, or a user who pays us at some point and then cancels the subscription. Do we want to delete their stripe customer? That seems bad because we would lose historical data. I don't want to remove their stripe id from their account either because then if they pay again, we would create a duplicate user. So it seems like we should keep the stripe id once we create it.

**Comment by burtonjc** [comment]
Also need to:

- [ ] account for expired credit cards
