### ISSUE TITLE
Upgrading from Trial to Paid

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#2739]
🎉 If someone likes what they find, they'll need a way to sign up for reals! 🎉 

**Acceptance Criteria**
- You can only upgrade from a trial to paid from the billing page. Technically you could do this from anywhere, but it feels better for organization accounts to know how much you'll pay and why (number of users) before entering payment details.
- Only worry about the individual plan for now, organization plan tracked separately
- [x] Prompt user to enter a payment method, using Stripe’s dialog
- [x] Make sure we won't charge the customer until the trial completes (don't cut the trial short), and make sure we tell the user that too!
- [x] Stripe should handle updating the subscription, and everything on our end should magically work if we’re appropriately depending on the subscription info to show the right thing in the UI.
- [x] mark that a customer is paid in intercom
- [x] track in mixpanel
- [x] be able to link directly to the billing tab (with a query param so we're not reserving `/:owner/billing`). This is necessary for any CTA that tells you to upgrade to continue using metrics.

**Comment by burtonjc** [comment]
WIP on `upgrade-to-paid` branch

**Comment by burtonjc** [comment]
Few different cases:
- [ ] purchasing during a trial (just adding a card)
- [ ] purchasing after a trial ends (`past_due` subscription)
- [ ] purchasing on a `canceled` subscription

**Comment by songawee** [comment]
We are opting to use query params, i.e. `?tab=billing` to hard link to the billing tab. 

Our URLs would have been `:owner/billing` which we typically denote as `:owner/:repo` since GitHub allows users to use repos of name `billing`. 

- [ ] use query params for the different tabs on the account page
