### ISSUE TITLE
Downgrade account

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#2741]
😢 Let's make it easy for customers to downgrade, they're sad enough already.

![image](https://cloud.githubusercontent.com/assets/84629/17655801/8c292fde-626f-11e6-9211-53de6f83ed98.png)

**Acceptance Criteria**
- [ ] Add a section to downgrade to free (or, “remove metrics add-on”) on the Billing tab on the account page
- [ ] Doesn’t refund, just doesn’t renew and downgrades when term ends
- [ ] Update plan details when a subscription is cancelled to show when it will end
- [ ] Stripe subscription we fetch should be enough to display when the subscription expires
- [ ] keep the customer id, so we can one day still show billing history
- [ ] keep payment method for now, if we get customer requests to remove payment info (handled by stripe) we can do that work later

**Comment by songawee** [comment]
- [ ] remove credit card when downgrading
