### ISSUE TITLE
Metrics CTA page

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#2743]
This is the page you see at `/:owner/:repo/metrics` if you haven't started a trial or your trial is expired.

**Acceptance Criteria**
- [x] Design it! Treat it as a landing page for metrics features
- Show the appropriate stuff for:
  - [x] A trial has never been started
  - [x] A trial has already been finished
  - (An in-progress trial will not show this page, nor a paid user)

**Comment by marydavis** [comment]
review changes: 
- [ ] make button bigger
