### ISSUE TITLE
Show "now" on burndown graph

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#2744]
![image](https://cloud.githubusercontent.com/assets/84629/17655930/50380ae8-6271-11e6-811d-34101cff7a21.png)

**Comment by marydavis** [comment]
the graph shows data in realtime, so that is the data as of now, but since it hasn't changed there isn't a data point for it.

**Comment by burtonjc** [comment]
Maybe we should have a label on the x axis that says "Now".

**Comment by homeyer** [comment]
wontfix, until we start hearing from customers. closing for now.
