### ISSUE TITLE
CTA banner on metrics pages during a trial

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#2745]
On every metrics page we should tell people when their trial expires (days left) and give them a button to purchase.

**Acceptance Criteria**
- [x] If a trial is active, on every metrics page (`/:owner/:repo/metrics`, burndown, and throughput) show a banner to add a payment method to keep using metrics after trial end date
- [x] button sends them to the billing tab for their account
- [x] only show banner for admins

**Comment by marydavis** [comment]
[2839](https://github.com/waffleio/waffle.io/issues/2839) needs to be completed before merging
