### ISSUE TITLE
Release Note Generation

### ISSUE THREAD

**Issue by pwelter34** [waffleio/waffle.io#2747]
Consider adding support for release note document generation for a mile stone, aka release.    The feature would create a release note wiki page in the github project in a configurable location.  There are ways to get this by querying, however many standardizations require a snapshot of this information.

The example workflow would be when the release is deployed to production, this would be invoked to gather up a summary of all issues in that release.

At a minimum, a markdown document could be generated to copy where needed.

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
