### ISSUE TITLE
delete account for org accounts

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#2748]
**Acceptance Criteria**
- [ ] change the url from `DELETE` `/account` to `DELETE` to `/account/:id`. The endpoint is currently in the app. For the sake of other billing routes, we may want to leave the endpoint in the app, unless billing routes (like downgrading) will be in the API.
- [ ] check permissions to make sure the user is an admin of the account, so it works for org accounts and individual accounts. The middleware will probably be re-used for billing routes, FYI.

**Comment by marydavis** [comment]
currently using `/orgs/#{owner}/memberships/#{username}` to check org membership client side

**Comment by burtonjc** [comment]
+1 for leaving it in the app. feels weird to allow a third party integrator to delete peoples accounts.
