### ISSUE TITLE
Show notifications

### ISSUE THREAD

**Issue by joelworsham** [waffleio/waffle.io#2750]
Currently, I have to go back to GitHub to view my notifications for things like new comments on issues, PR's, etc. It would be wonderful if this was somehow baked in to Waffle (no pun intended!).

**Comment by kellihsf** [comment]
hi @joelworsham ,

We have a feature request for notification history on [#1199](https://waffle.io/waffleio/waffle.io/cards/53c564cb7953d2fd0f726d66). Is this what you'd like to see?

**Comment by joelworsham** [comment]
I believe so, but this seems to imply there is a notification system already in existence? I am not aware of this... where are notifications displayed in Waffle?

**Comment by kellihsf** [comment]
Yep, just the blue notification banner that come across the top of the screen when an action occurs. 

ex: 'kellihsf commented on #10'

**Comment by joelworsham** [comment]
Oh okay. Yes, so the issue you mentioned would be what I'm looking for. THat would be perfect!
