### ISSUE TITLE
embeddable milestone burndown

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#2751]
e.g., https://graphs.waffle.io/projects/52e041cfe045b8ac35fe4620/burndown.svg?milestone=Account%20Visibility

**Comment by songawee** [comment]
Would be good to also validate whether we should use JSDOM instead of phantom. I have some ideas around this.

**Comment by AnaMSteele** [comment]
We are closing this issue as it is not part of our short term roadmap.
