### ISSUE TITLE
add the first source to the projects/:owner endpoint

### ISSUE THREAD

**Issue by marydavis** [waffleio/waffle.io#2754]
this is so we can tell if the repo is public/private and whether it has a display name

**Comment by homeyer** [comment]
details:
- For the account page, we show a list of projects (filtering out private projects if you don't have permission to see them).
- Right now we don't list the project using it's display name, nor show it's public/private status. 

AC: 
- [ ] `projects/:owner` endpoint should include the first source, if a user has permission to see it
- [ ] UI should use that source to display the project using the display name and show if it's public/private.
