### ISSUE TITLE
Hide issues from board with special label

### ISSUE THREAD

**Issue by cannikin** [waffleio/waffle.io#2755]
Occasionally we have Issues that aren't really development tasks to be sized and assigned and worked on. It would be AWESOME if it was possible to hide an Issue from the waffle board completely. 

I figured the easiest way to do this would be with a special label. If labeled with "hide" or maybe "no board" or maybe "invisible" then just exclude it from display on waffle.io. Taa-daa!

**Comment by kandros** [comment]
any progress on that ?

**Comment by nicksloan** [comment]
Our team would also love this! We use our issues for a few tasks that don't fit into the workflow. An improvement to @cannikin's proposal would be to let the user define a list of labels that should exclude an issue from boards, since there may be a variety of items  that a team wants to exclude, but which need to be distinguishable easily amongst themselves as well.

**Comment by jpike88** [comment]
This is SO easy to implement! Come on guys, my backlog should be just that, a backlog, not a trash pile of all open issues!

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208

**Comment by jpike88** [comment]
Thanks for cementing my decision to use Zube instead.

**Comment by fernandocalsa** [comment]
Do you have this feature in mind? This would increment our productivity with Waffle :D

**Comment by fernandocalsa** [comment]
This could be easy to achieve if the label filter would have a new button, `select all`, then we should remove the label that we want to hide, and that's it.
![screen shot 2018-04-17 at 13 36 30](https://user-images.githubusercontent.com/6080414/38869990-5f79ec92-4244-11e8-9b56-6758b0318080.png)
