### ISSUE TITLE
Ability to move a task to a different board.

### ISSUE THREAD

**Issue by ebdrup** [waffleio/waffle.io#2758]
It could be done by clicking the repo name on the task card.
It's ok if it's implemented by closing the old task, maybe adding Moved to:xxx/yyy to the title) and creating a new one.

I've messed up several times putting tasks on the wrong repo. Moving things is a hassel.

**Comment by ebdrup** [comment]
I meant different `repo` in the title

**Comment by kellihsf** [comment]
hi @ebdrup,

Thanks for the request! We're already tracking this request on [#2044](https://github.com/waffleio/waffle.io/issues/2044), so we'll close this as a duplicate.  (You can change the title of the card from the board view, just click on the title and the text box will appear. :) )
