### ISSUE TITLE
FEATURE REQUEST: Board-style screen for Milestones

### ISSUE THREAD

**Issue by joehanna** [waffleio/waffle.io#2763]
I would like to manage milestone assignments on issues using a drag-n-drop interface like the Board-View.  Editing individual issues is slow and cumbersome.

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
