### ISSUE TITLE
throughput graph filtering

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#2764]
**Acceptance Criteria**
- [x] filter server side
- [x] start date
- [x] timebox unit (day, week, month, year)
- [x] timebox size (1-12, or a text field)
- [x] label exclusion (api supports inclusion too if we want)
- [x] milestone
- [x] source

Jacob says to use the scope callback pattern.

**Comment by marydavis** [comment]
- [ ] change purple  color to dark blue
