### ISSUE TITLE
Assignee search for real names

### ISSUE THREAD

**Issue by plusjeff** [waffleio/waffle.io#2767]
In GitHub, users can add a "Name" to their profile (i.e. "Jane Smith"). When adding assignees in GitHub, one can search by the person name in addition to their GitHub user ID. This is helpful since it's easier to remember teammates real names rather than their GitHub user IDs.

Waffle only allows the assignee search to be by GitHub user ID. Please allow the search to work for real names.

P.S. This would also be helpful for @mentions.

**Comment by kellihsf** [comment]
hi @plusjeff,

Thanks for the request! We're already tracking this request on [#1730](https://github.com/waffleio/waffle.io/issues/1730), so we'll close this as a duplicate. :)
