### ISSUE TITLE
@username autocomplete should work under "Add Issue" just like it does in tickets.

### ISSUE THREAD

**Issue by mustmodify** [waffleio/waffle.io#2768]
Waffle will autocomplete usernames after an @ for open tickets; it would be nice if that worked in the "Add Issue" screen as well.

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
