### ISSUE TITLE
Free text note on cards

### ISSUE THREAD

**Issue by roll** [waffleio/waffle.io#2774]
Because this - https://github.com/waffleio/waffle.io/issues/1830 - looks like a dead-end could you please just add a small free-text box for notes on every card (e.g. near to github link)? Just small input stored at waffle side.

We badly need some ability to estimate cards in days after migration from Trello with scrum plugin but just can't do it with Fibonacci numbers. Special labels for it is ugly and writing to issue titles will mess it on github..

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
