### ISSUE TITLE
Custom Domain names

### ISSUE THREAD

**Issue by agentlewis** [waffleio/waffle.io#2775]
Currently we use a fairly hacky process of using a ruby app. Would be great if this was a core feature - like gitbook. eg 
[http://handbook.enspiral.com](http://handbook.enspiral.com)
our waffle one
[http://improvements.enspiral.com](http://improvements.enspiral.com) which just redirects.

**Edit:** updated links and also want to add that I just had to setup another of these for another group and used [https://www.301redirect.it](https://www.301redirect.it) instead of a ruby app. 

Please make it a native feature!!!

**Comment by Disane87** [comment]
+1

**Comment by kgab0r** [comment]
+1

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
