### ISSUE TITLE
Checkboxes disappearing, whole text disappearing, etc.

### ISSUE THREAD

**Issue by adambuczynski** [waffleio/waffle.io#2776]
I am getting increasingly frustrated with the description text disappearing from issues when I open them. It requires me to close the issue and reopen it again, or in some cases to refresh the page in order to get to see the text.

In addition, checkboxes are also still frequently disappearing when you open the issue, and likewise requires you to reopen the issue to see/use them.

This is as you can imagine super annoying and it wastes a lot of time. Can you please look into these issues, as you've have more open and closed around this disappearance:

https://github.com/waffleio/waffle.io/issues/2609
https://github.com/waffleio/waffle.io/issues/2661

Can you please investigate and prevent text and checkboxes from disappearing? It's making Waffle unusable for us.

It seems to me like a binding or caching issue.

**Comment by seanperkins** [comment]
Still happening to me regularly.

**Comment by adambuczynski** [comment]
Yes, it's intermittent, but I still occasionally have things disappearing form issues.

**Comment by adambuczynski** [comment]
This is not an idea... it's a bug...

Anyway, I've grown weary of the amount of outstanding issues that are slowing down our team on a day by day basis and decided to move to Zenhub instead. At least they offer the whole suite *for free* for small teams, which includes velocity charts and burn down charts.

If I may suggest, you should first fix the bugs in your software and deal with the outstanding basic feature requests (which have been around for as long as we've been using Waffle), *before* you start removing features people rely on and hiding them behind a pay wall.
