### ISSUE TITLE
Use github "project" instead of "label" for waffle columns

### ISSUE THREAD

**Issue by dsyer** [waffleio/waffle.io#2784]
Github repos can now have "projects" which it has been suggested buy github.com could be used as tracker statuses: https://youtu.be/C6MGKHkNtxU. Seems like waffle could do this and stop polluting labels?

**Comment by tonytonyjan** [comment]
why not just use github project, i wonder

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
