### ISSUE TITLE
Label/column for code review status

### ISSUE THREAD

**Issue by brettlangdon** [waffleio/waffle.io#2787]
Would be awesome to have labels for code review statuses like "request changes" and "approved".

We sort of do this now, we have an "approved for merge" label, but we have to manually apply this label to PRs that we approve.

Some context around how we have our board structured, we have the following columns:
- Backlog
- Ready
- In Progress
  - Work started
- Ready for review
  - New collaborator PR
- Approved
- Done

When a PR is moved into the "Approved" column, then it is ready to be merged/deployed. This way we can easily see from our board which PRs still need to be reviewed, and which are ready to be released.

So, ideally for us, we would like to be able to auto-assign/move approved PRs into the "Approved" column when they are approved in GitHub. We could have something similar for "Request changes" status as well.

**Comment by colmdoyle** [comment]
:+1:

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
