### ISSUE TITLE
500 error when attempting to add size estimates for cards

### ISSUE THREAD

**Issue by MakotoTheKnight** [waffleio/waffle.io#2788]
I'm observing some 500 errors this morning (local time) when attempting to add size estimates for cards.

Error:

 > 2016-09-19 08:44:04.756 api.waffle.io/cards/57cefc61aabdd7f4017a88e6:1 PUT https://api.waffle.io/cards/57cefc61aabdd7f4017a88e6 500 ()

To reproduce:

 - Attempt to add a size estimate to a card.
 - Observe that the error message "unable to add size to card XXX" appears above.
 - Observe that the console reports a 500 error.

**Comment by kellihsf** [comment]
Hi @MakotoTheKnight,

We were experiencing some issues this morning due to GitHub's increased error rates. Things are looking good on our end, although a bit slow due to GitHub's API response time being degraded. Are you still having trouble with this?

**Comment by MakotoTheKnight** [comment]
It seems like things have indeed smoothed out since earlier today, which likely means that GitHub was having the issues more than Waffle.  Thanks for looking into this!

**Comment by kellihsf** [comment]
You're welcome! :)
