### ISSUE TITLE
Memory leak in Chrome

### ISSUE THREAD

**Issue by bmunkholm** [waffleio/waffle.io#2790]
When my Mac was hovering on my table due to excessive fan use, I checked the Activity Monitor and noticed one Google Chrome Process that used +5 GB memory - killed it and saw that it was waffle.io. Not sure if this is a Chrome leak or Waffle.io leak, but none of my other trillion tabs has the same memory usage, so I assume it's yours.

**Comment by songawee** [comment]
Hey @bmunkholm, can you please provide the Chrome version you are using so we can debug from there on the memory leak? Does it also occur in other browsers (if you have tried)?

**Comment by bmunkholm** [comment]
Sure - it's Version 52.0.2743.116 (64-bit).
I didn't try it in other browsers for a long while.
It's also sort of hard to monitor as you can't see which tab is which
process - unless you kill it...

**Comment by Frizi** [comment]
@bmunkholm you can use chrome's own "task manager", accessible on the context menu of chrome's header. It gives you usage statistics per tab/extension, all properly labeled.

**Comment by bmunkholm** [comment]
Ahh, nice - I will keep an eye on it.

**Comment by burtonjc** [comment]
Has this behavior persisted for you, @bmunkholm?

**Comment by bmunkholm** [comment]
Not noticeably. It's around 278MB now.

**Comment by homeyer** [comment]
After doing some intense organization type work on our board (1k issues), memory usage doubled. Unfortunately that makes sense; as you scroll a column we render cards below the fold, and don't clean up those cards as you scroll back up. The UI becomes noticeably slower at this point, but a refresh fixes it.

Long term, moving to Angular 2 should improve some of this. From what I can tell, there isn't a detectable leak beyond the loading of more cards over time.

![image](https://cloud.githubusercontent.com/assets/84629/23000342/618bb066-f39d-11e6-8882-b67306e35ae3.png)
