### ISSUE TITLE
Improve wording of FAQ 'Automatically Move Issues "In Progress"' section

### ISSUE THREAD

**Issue by chipit24** [waffleio/waffle.io#2791]
Under the section, [Automatically Move Issues "In Progress"](https://github.com/waffleio/waffle.io/wiki/FAQs#automatically-move-issues-in-progress) in the [FAQs](https://github.com/waffleio/waffle.io/wiki/FAQs), you have the following wording:

> We move an issue into "In Progress" if you put the issue number at the beginning of the branch name with a '-' or '_' behind it [...]

The wording is ambiguous and makes it unclear whether the '-' or '_' should go before the issue number, or before the branch name.

The example (`123-fix-bug`) makes clear what you mean, but I think the wording should be improved.

**Comment by kellihsf** [comment]
hi @chipit24,

Thanks for bringing this to our attention! I have updated the wording here and included more example branch names.
