### ISSUE TITLE
Select issues that are unassigned or assigned to a specific person

### ISSUE THREAD

**Issue by retog** [waffleio/waffle.io#2793]
I'm typically interested in issues that are either unassigned or assigned to me. I used to be able to select them all, now I have to switch between them.

**Comment by kellihsf** [comment]
hi @retog,

This filtering has changed recently when the multiple assignee feature was implemented. We're tracking the request to support OR again when filtering by assignee. This is being tracked on [#2654](https://github.com/waffleio/waffle.io/issues/2654), so we'll close this as a duplicate. Thanks!
