### ISSUE TITLE
Allow source filtering by label

### ISSUE THREAD

**Issue by LynnMcRae** [waffleio/waffle.io#2801]
We have several projects we manage in waffle that cross multiple code bases -- generally a primary code base and others, like general infrastructure services, only selectively. If we configure waffle to include all the sub-projects as sources, we inherit the full backlog of tickets from each of them. We would like to include into our composite waffle board only relevant tickets from sources based on some controllable criteria, like label, on a source-by-source basis.  This would reduce the backlog on a typical such project from hundreds, with 90% noise, to the relevant handful of tickets.

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
