### ISSUE TITLE
Allow adding a non-owned repository to a board

### ISSUE THREAD

**Issue by javiplx** [waffleio/waffle.io#2804]
From what I'm able to found, I can only add repositories owned by me or by an organization I belong to. It would be glad to allow adding (by full name, no searching is required) other public repos, that will be useful to track forked repositories.
In my case, I'm setting up a board for a Jenkins plugin with my own repo and the Jenkins organization one. But I would like to add issues from another repo which is the original one from the other two get forked, and to where users still open issues from time to time despite of the fact that development is not done there for two years now.

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
