### ISSUE TITLE
Issue_template.md is not applied

### ISSUE THREAD

**Issue by Disane87** [waffleio/waffle.io#2805]
I've added an issue template to guide the users through adding a "proper" issue. Unfortunatly your application is not using this issue template 😞 . Is there any chance to get that working?

**Comment by kellihsf** [comment]
hi @Disane87,

Unfortunately, we don't support the GitHub templates yet. 😕   
We're already tracking that issue on [#2398](https://waffle.io/waffleio/waffle.io/cards/56c521d69837d4320074c2c0). Feel free to add any comments or support to the card!

**Comment by Disane87** [comment]
Thanks in advance and sorry for not searching this issue already :)

**Comment by kellihsf** [comment]
You're welcome and no worries! 😀
