### ISSUE TITLE
Handle commas in milestone names

### ISSUE THREAD

**Issue by kellihsf** [waffleio/waffle.io#2806]
If you have commas in your milestone name, then filter by the milestone and refresh the board, the milestone filter is not saved in the URL.

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
