### ISSUE TITLE
Add PRs to milestone of connected issue

### ISSUE THREAD

**Issue by sschmid** [waffleio/waffle.io#2808]
Q:

> PR that close issues are nicely grouped together. Do you think it makes sense to automatically set the milestone for those PR based on the linked issue? I'm currently automating changelog and releases. I use git flow and PR for every fix / feature to close issues. I'd like to generate a changelog based on milestone contents

A: (from @kellihsf)

> It sounds like you're wanting your PRs to automatically be added to a 'release' milestone that the connected issue is set to so you can generate your changelog by everything in that milestone. Unfortunately, Waffle doesn't have anything in place to do this right now. That is an interesting idea though, feel free to open an issue on our board for this if you like. :)

**Comment by SpainTrain** [comment]
We noticed this was not happening the other day.  It makes it more difficult for us to tell how complete milestones are, and to historically understand how much work a particular milestone involved.

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
