### ISSUE TITLE
ability to create/managing label & milestone in github

### ISSUE THREAD

**Issue by opinipm** [waffleio/waffle.io#2811]

**Comment by jouni** [comment]
Seems like a duplicate of #2087

**Comment by kellihsf** [comment]
Hi @opinipm,

Thanks for the request! Would you mind taking a look at issues  [#909](https://waffle.io/waffleio/waffle.io/cards/5363e987ebef97b1f959af6b) and [#2087](https://waffle.io/waffleio/waffle.io/cards/55f1e46816606e3900971454) to see if they describe what you're looking for?

**Comment by opinipm** [comment]
Hi @kellihsf @jouni 

thank you for the info, yes its duplicated with #2087 and #909 , sorry for my mistake :D 
kr,
oppm
