### ISSUE TITLE
[spike] Should we be in Heroku

### ISSUE THREAD

**Issue by burtonjc** [waffleio/waffle.io#2812]
Questions to answer:

- [ ] Where would we go if not heroku?
- [ ] Cost of hosting heroku vs other solution?
- [ ] Ability for any person to manage it (anti-single point of failure)?
- [ ] Migration path?
- [ ] Flexibility to support the future of Waffle?
- [ ] CI/CD?

**Comment by burtonjc** [comment]
Timebox to 3 days, revisit if we need more time.

**Comment by jtslear** [comment]
Regarding a migration path, 

This shall mostly be completed via a DNS change.  Each microservice appears to use it's own DNS entry.  Such that we can potentially migrate one app at a time.  Validate the app works appropriately, followed by proceeding with a DNS change to "flip the switch."  

Flipping may take some time (DNS propagation), so it might be kinda nice if there was a way in New Relic to know which apps were taking traffic, whether it be the heroku infra compared to the new infra.

During the period of a migration, I'd suggest a freeze on deployments for the affected apps until we deem a migration successful.  But leave the heroku instance running; just in case we need to roll back.  Otherwise we'd need to ensure the deployment process can handle both heroku and the new infra.  The CI/CD pipeline will be tremendously important here.

I'm not necessarily worried about an outage due to flipping the switch here cuz we'll have the ability to validate that the app is working prior to the flip. 

cc @marydavis @burtonjc Input for this particular bullet point is encouraged and welcomed.

**Comment by jtslear** [comment]
Heroku is currently configured to use a total of 100GB of RAM; I have no idea how to calculate CPU core usage.....  Top cost of JUST heroku is $3800/monthly.

This includes minor apps that aren't necessarily related to waffle, including the geckoboard proxy, hackshop, and wafflebot (not the auto-work-tracking bugger).

**Comment by jtslear** [comment]
MOAR NOTES:
Let's talk about products that are similar to heroku that we probably don't want to use:
  - Deis - The workflow is very similar to heroku.  Push your code, they build and deploy it
  - Apps Code - The workflow is very similar to heroku.  Push your code, they build and deploy it.  It does look, however, they may be more open and flexible with regards to the exposed technology.
  - Dokku - This guys is not enterprisey at all.  Great for local PaaS?
I mention not using the above as there's a desire to utilize the docker tool for running our application.  The above do not meet these criteria.  There's also a desire to separate the compiled component of our applications to the deployment step.  AppsCode comes the closests based on documentation, but still fails when it comes to infrastructure.  We must bring our own.  They do not go into details about how that infra is managed

Let's talk about products that are similar to heroku that we may want to try out:
  - AWS - They have a bunch of services that we could try out and see if it'll fit our desired workflow 
    - Code Deploy - DOCUMENTATION OVERLOAD
    - ElasticBeanStalk
    - ECS
  - Google - Again they have a bunch of services we could try out
    - AppEngine - note that app engine supports nodejs in a beta release right now...
    - Container Engine
      - Runs kubernetes under the hood
      - which means if we create docker containers, it'll run them
      - parts of it are not necessarily refined, so CI/CD will be important in managing this 
setup
  - Both google and aws have many many OTHER services that we'd be able to potentially take advantage of, and both would offer the ability to grow into their infrastructure if we find that one of these solutions doesn't work out so well.  For one example, if we decide that running the api service in containers is not feasible, we'll still have the flexibility to spin up just a plain ole server, and plop the app on it.  And both options provide options on top of that!
  - IBM Bluemix
    - They also have various products, but documentation is kinda light, would probably need to try it out to really figure it out

Other noteworthy items:
- Openshift Dedicated
  - I like openshift, but this is hella expensive
- Docker Datacenter
  - This looks intriguing, but there are some downfalls
    - This is hella expensive
    - requires us to bring our own infrastructure.  It is fully managed though
- StackPoint
  - this is a solution that manages kubernetes for you, I don't see any benefit to using this service over google compute engine, unless we didn't want to use google, then MAYBE
  - documentation is light, so we don't really know what the permissions model is and what access they have to our stuff, nor control of versioning and upgrades of kubernetes
- Pivitol; Cloud Foundry- i can't seem to get the damn email to sign up for this service so I can't even check it out
- Techtonic 
   - created by CoreOS - fully managed infrastructure running kubernetes
   - documentation for setup is cumbersome
   - we would still need to pay the infrastructure costs + the cost of using their service, which is kinda pricey
- Openshift Online
  - This is just like heroku, and currently is using the old version which not any better than heroku
  - Their dev preview brings in the version using kubernetes under the covers, but they won't have a beta release for paying customers until next year.

**Comment by marydavis** [comment]
would it be beneficial to instead of switching an app over entirely, to route a % of traffic over to it and then increase that % until fully converted? So it sounds like either AWS or Google are the ones we want to give a try?

**Comment by jtslear** [comment]
@marydavis completely agree here.  The problem though, is how to do this.  Right now the only thing sitting in front of the application is CloudFlare.  The only potential load balancing we'd be able to accomplish is via DNS without some other major infrastructure change.  If we go this route, we could leverage DNS round-robin, which will put roughly 50% of requests on different infrastructures.  But that is not guaranteed.

UNLESS there's something that can be done inside of the application to send requests to specific end points.  Example if waffle.io-app can route too `something-else.api.waffle.io`.  (I guess that is more controlled in the front end not really the app isn't it?)

**Comment by jtslear** [comment]
So, if we were to migrate our current dyno's and transfer those into individual instances in aws, a very rough calculation puts us around $1400/monthly.  If we were to use google, I would imagine it's about the same as these two companies are decently competitive.

This goes beyond a savings, but one must remember this is a one-to-one comparison.  If we want any sort of redundancy, double that amount.  With redundancy in place we'd add an ELB per application.  I'm predicting 8 of those things, which adds another $144/monthly, plus a variable cost of $.008/GB of traffic for each ELB.  Google has a different pricing model, which makes this slightly less expensive.

On cost alone, we are already back up to approximately $3k.  There's probably room for improvement as I'm taking a mix of nano instances for small apps and using potentially oversized instances for the larger apps, but we could probably optimize our usage of the fleet by using more smaller instances for example.

**Comment by jtslear** [comment]
If we decide to choose a cloud provider such as google or aws, we could leverage their container orchestration products.  This would allow us to lessen our cost by allowing their product manage both the docker containers running, and potentially autoscale as necessary.  This will also allow us to use slightly larger instances while over provisioning the containers on the available instances.  This model would assume more than one application is running per node.  We could potentially deploy a fleet of t2.larges, and scale those as necessary.  
Note that AWS does not have built in scaling with kubernetes, but does with ECS.  ECS does not cost any extra; while google charges a minor amount per cluster pending on the amount of nodes you have (free up to 5 nodes, then 15 pennies per hour)
Google's solution has built in scaling of the nodes capability.
Note that we could potentially install kubernetes in AWS but we'd have to manage the master nodes that run the service ourselves, and those instances will cost us a bit of money, luckily they can be relatively small.

Keep in mind that with the above configuration, we are introducing a new service which starts to get into pinch point of the skillset available on team to manage this service.  These are a set of services that are not a part of the overall waffle ecosystem, but rather what waffle runs on, and it would be detrimental to have an outage of a service to negatively effect waffle.

**Comment by jtslear** [comment]
Whatever solution we choose, CI/CD will probably be the most important.  

I would imagine a world where to help with troubleshooting issues with underlying services, the wafflechatbot is outfit with helpers to assist with various things.  That may include deploying infrastructure, diagnosing service problems, and potentially handling deploys.

Codeship support arbitrary commands to perform deploys, we can grab the ssh key off of him and add him to servers, or we can plop down scripts that can do custom work for us.  These custom scripts could be small bash scripts, or we can rock out a configuration management tool to assist us on that front if needed.

**Comment by marydavis** [comment]
this is such awesome info, thanks! really like the idea of a wafflechatbot - would be super cool. are you leaning towards using Google because they have the built in scaling with kubernetes?

**Comment by jtslear** [comment]
I think the autoscaling is cool, supposedly they are building it for AWS.  I would more so lean on AWS at this point, cuz there are features we could potentially leverage that have been "in production" much longer than google has.  I would lean on google cuz they manage a portion of the kubernetes infrastructure for us.  It's a give and take here....

Regarding auto scale, I'm not sure how often we'll actually use it.  We'll always keep  two "things" running the application for redundancy.  Is there a service that is so heavily used that we'd need more than two?  Looking at throughput on new relic, it really doesn't look like load changes but so much to warrant the need for auto scaling.

**Comment by burtonjc** [comment]
This is awesome @jtslear. Totally agree with the give and take between AWS and Google. I'd say I am leaning toward Google _if we go anywhere_. As far as a migration path, would it be possible to:

1. Stand up new infrastructure (could be one app at a time).
1. Still direct 100% of traffic to heroku, but simultaneously send every request to the new instance.
1. Respond with whatever heroku responded with.
1. Monitor and tune the new instance (which is under 100% load) until it outperforms heroku.
1. Flip the switch to point at only the new instance.

You mentioned in standup that this probably would not be enough benefit for us to justify the cost. Can you expand on that a bit more?

**Comment by jtslear** [comment]
The challenge with the migration path you mention, is that there isn't anything sitting in front of heroku that allows us to split traffic or duplicate traffic.  Cloudflare doesn't appear to have this capability.  The only thing I've found thus far is a webpack by heroku, but it appears to assume a ruby based application.  Another situation with duplicating traffic to a second instance, is that depending on the request, we can do damage to the content stored in waffle or github.  I imagine when someone comments on a card for example, duplicating that to two different api instances would then cause that comment to show up twice.

If we wanted to try to do that, we'd need a modified version of the application deployed to avoid duplicate information population, as well as some infrastructure in front of heroku.  I can always spin up an instance and AWS or google that simply proxies traffic to either instance, but now we are adding extra hops and potentially slowing down the application.  For testing this probably isn't a terrible idea, but I'd shy away from running this against production.  Also note I've never dupped the traffic before, so that would be interesting..............

**Comment by jtslear** [comment]
Regarding your question on costs, see my above post where I do math.  If we do a one-to-one relationship and ensure redundancy, the costs kinda equal out.  

If we do something such as a container orchestration tool, whether it'd be ECS or kubernetes, I can see where costs can be brought down.  But it's difficult to judge how many nodes we would place into a cluster.  If we base it strictly off of memory allocation (above I guessed at 100GB), and using google as an example, we can spread all apps on three nodes, each with 30GB of RAM, which will cost around $600/monthly.  Massive cost savings if we implement a kubernetes cluster here where we can overprovision our instances, but remember that adds a layer to the infrastructure we didn't have to previously manage.

**Comment by ErikAGriffin** [comment]
Another thing to think about, today the Heroku API is down and thus our (and I'm guessing all) waffle boards are unavailable.  Can't fix the issue because you can't log in.

That's not to say other hosting providers would not have similar issues, but I think it is worth noting.
