### ISSUE TITLE
Wafflebot shouldn't assign issue to user when using Github's squash/rebase buttons

### ISSUE THREAD

**Issue by zbjornson** [waffleio/waffle.io#2813]
If you use Github's "squash and merge" or "rebase" buttons, the author on the commit changes. Consequently, wafflebot assigns those issues to whoever did the merge. Github's authorship change might be difficult to work around, but we don't want this behavior.

**Comment by SpainTrain** [comment]
In addition to assigning the PR, wafflebot also will erroneously move the PR to a different column.  This issue causes us a ton of issue column moving and manual reassignment daily.

**Comment by zbjornson** [comment]
Nope, wafflebot no longer assigns issues to the person who clicks "rebase" or "squash," thanks!
