### ISSUE TITLE
Issues doents load on board

### ISSUE THREAD

**Issue by viniciusss** [waffleio/waffle.io#2814]
Hi, i did the migration from Jira to Github Issues. For this i use de "import/issues" API.

I imported 2550 issues.

- 292 open
- 2258 closed

My waffle board is movessimonetti/webpdv

**Comment by kellihsf** [comment]
Hi @viniciusss,

Is this a newly created board? If it's an older board that hasn't been viewed in a while, Waffle is probably having trouble syncing. The easiest fix for this would be to delete the project and recreate it. Note that you will lose size and ranking, and you'll need to recreate the columns. If this is a new board, can you either send us an in-app message (click the ? in the sidebar) or email us at support at waffle.io so we can have a closer look? Thanks!

**Comment by viniciusss** [comment]
@kellihsf i send the message... is a new board.

**Comment by kellihsf** [comment]
Thanks, looking now!

**Comment by kellihsf** [comment]
discussed over email
