### ISSUE TITLE
Account overview tab should show appropriate billing info

### ISSUE THREAD

**Issue by burtonjc** [waffleio/waffle.io#2816]
AC:
- For an account you are an admin of:
  - [x] Shows if you are on free plan
  - [x] Shows if you are trialing
  - [x] Shows if you are trialing but have upgraded
  - [x] Shows if you are on a paid plan
  - [x] Shows if payment is expired
- For accounts you are not an admin on
  - [x] Maintain current behavior: does not show the overview tab

**Comment by marydavis** [comment]
we don't show the account overview page at all if you are not an admin - did we want to change this?

**Comment by songawee** [comment]
as I'm working on the Org plans, would it make sense to also show quantity (all subs have default quantity 1) when the account is an org?

**Comment by marydavis** [comment]
i was expecting to show the monthly amount and the next payment date - so for an org it would show like $25 month (plus applicable taxes) - i think we had talked about having a 'collaborators' tab showing the people you are paying for

**Comment by songawee** [comment]
ok cool, that makes sense. Right on, I'm still wrapping my head around the `collaborators` tab. I feel like it would be super useful, but hard to calculate since we would have to page all of the members and pull out the necessary ones. And, the criteria for what GitHub constitutes could change and we would be out of date.

**Comment by marydavis** [comment]
agreed, can just show the number of users with a link to the github org page :)

**Comment by burtonjc** [comment]
@marydavis you are correct, I updated the AC.
