### ISSUE TITLE
update throughput api endpoint

### ISSUE THREAD

**Issue by marydavis** [waffleio/waffle.io#2819]
AC:
- [x] filter exclusion labels by 'unlabeled'
- [x] filter labels by 'unlabeled'
- [x] filter milestones by 'none'

**Comment by burtonjc** [comment]
Would be awesome to deflakify the milestone and throughput tests as a part of this. Dennis already started on the [de_flakify_integration_specs branch](https://github.com/waffleio/waffle.io-api/compare/de_flakify_integration_specs).
