### ISSUE TITLE
Expected time taken for a Project/Issue to be accomplished

### ISSUE THREAD

**Issue by Jammizzle** [waffleio/waffle.io#2820]
A small date/time area that'll prompt the user for an estimated time they believe the task will take to complete. 

This is different from the Due Date feature request as a task may have a deadline for next week, but could only take a few hours to complete. This'll allow our company, and probably many others to manage their time a little more effectively, I'm not sure if this has already been mentioned so my apologies if it has

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
