### ISSUE TITLE
Mixed content blocked over HTTPS

### ISSUE THREAD

**Issue by Crevil** [waffleio/waffle.io#2822]
When loading Waffle.io over HTTPS Chrome blocks non-secure content from `http://static.ads-twitter.com/oct.js`.

The complete message in the developer console is:
```
Mixed Content: The page at 'https://waffle.io/racketometer/thesis' was loaded over HTTPS, but requested an insecure script 'http://static.ads-twitter.com/oct.js'. 
This request has been blocked; the content must be served over HTTPS.
```

This further results in an error when using the Twitter object `twttr`:
```
Uncaught ReferenceError: twttr is not defined
    at https://waffle.io/racketometer/thesis:47:268
```

The Twitter script is [available through HTTPS](https://static.ads-twitter.com/oct.js) so this can be resolved by just changing the protocol.

**Comment by songawee** [comment]
Great catch @Crevil! 

Just started seeing this as well. I have updated the URL. Thanks for reaching out and let us know if you have any other issues.

Cheers!
