### ISSUE TITLE
Additional state between Inbox and Progress

### ISSUE THREAD

**Issue by WanderingMatt** [waffleio/waffle.io#2823]
Our team considers "Backlog" to be any issue that has not been assigned to a Milestone. In Waffle though, the Backlog includes anything that doesn't have a custom column label set. During our evaluation, we're using an additional column (with label) called To Do. This works, but still requires us to label/drag every issue after we've already decided to work on it by assigning it to a Milestone.

It would be awesome to have something in between the Inbox and Progress columns that automatically displays issues that have a set milestone. Perhaps call it something like "To Do" or "Queued for Work". Essentially, a column that holds issues that we know we're going to work on, haven't started working on yet, but don't want to have to sift through the Backlog to find when we want to move them to In Progress.

**Comment by burtonjc** [comment]
This is interesting. What about making columns more configurable so that you can specify a number of conditions. Label could be one, but you could also specify a specific milestone or something like an `any` clause. So an issue with `any` milestone, or `any` label.

**Comment by WanderingMatt** [comment]
If it was smart enough to filter out issues with other column labels, that would work. We could reconfigure our current **To Do** column to show all issues with `any` milestone.

Probably makes this idea a bit more useful to other teams with slightly different workflows as well.

**Comment by Cakelicious** [comment]
+1

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
