### ISSUE TITLE
Cannot uncollapse columns in IE 11.

### ISSUE THREAD

**Issue by lamanning** [waffleio/waffle.io#2825]
Collapsed all columns . . . well, because i could. Can't uncollapse them. How do i get them back??? Need solution quickly.

**Comment by kellihsf** [comment]
Hi @lamanning,

I just replied to you through in our in-app messenger. We'll take a look at this now and see what's causing this issue. Other users have reported this happening on IE as well [#2366](https://waffle.io/waffleio/waffle.io/cards/56a8fb566a037a14005193da), but we haven't seen it happen recently.

**Comment by lamanning** [comment]
Holy guacamole (<<please excuse strong language . . .)! You fixed it! THIS IS GREAT!!!!
