### ISSUE TITLE
[spike] Lambda inner workings

### ISSUE THREAD

**Issue by burtonjc** [waffleio/waffle.io#2826]
### Questions
1. Can we connect to the DB from a Lambda function?
1. Can we call out to GitHub?
1. Can we configure various environments (production, development, ...)?
1. Can we detect failures?
1. How should we handle failures assuming we can detect them?
1. Can we instrument the function? NewRelic? Loggly?
1. CI/CD with Lambda Functions?

**Comment by jtslear** [comment]
https://github.com/waffleio/waffle-spike

**Comment by homeyer** [comment]
What's the next step for the sync work? Is anything broken down into issues yet? I don't see anything in [the milestone](https://github.com/waffleio/waffle.io/milestone/104), just want to make sure I'm not missing anything
