### ISSUE TITLE
Ability to save/restore filters

### ISSUE THREAD

**Issue by samdeane** [waffleio/waffle.io#2828]
A small feature request for you.

I typically use one of three views, which boil down to:

- show me (allthethings)
- show me my stuff, plus stuff that I might pick up to review
- search for a specific term

The filtering system allows me to do the second one (although it's a bit of a hack*). Invariably I use a text search for the third one, not a label search, even if searching for labels!

However, it's a pain having to set the "my stuff" filter, which I have to do whenever I want to "my stuff", and it's a pain having to clear it to take a quick look at the global picture. It's even more of a pain when I want to do a quick text search across the whole issue database, but I forget to clear the "my stuff" filter :). 

This is especially true since the UI responds quite slowly for our repo, which is big.

It would be fantastic to be able to set up some filters/views and switch between them quickly. I could then pre-bake a "my stuff" view and go back to it quickly.

**Comment by samdeane** [comment]
* the reason this is a hack is that I generally search for things assigned to me + assigned to nobody.

What this filter effectively does is show me anything assigned to me in *any* column, plus anything that has a PR attached to it (since we don't assign PRs to people).

In practise, this happens to be what I want to see, since I'm looking for either the state of my own issues, or things from other people in the "To Review" column that I should pick up.

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
