### ISSUE TITLE
Is automatic work tracking across forks supported?

### ISSUE THREAD

**Issue by nrip-monotype** [waffleio/waffle.io#2829]
We have one main project, and each developer works on their own forks. But we want to track all issues on main repo.

How can automatic work tracking work on such scenario? How to create branch such that issue of original repository is referenced?

**Comment by homeyer** [comment]
Hi @nrip-monotype! It can work, but you have to add all the forks to your board, and then reference issues with a full path, like `owner/repo#number` instead of just `number`.

**Comment by nrip-monotype** [comment]
@homeyer ,

Yes it works when I name my branch as `owner/repo#number`. 

Thanks.
