### ISSUE TITLE
Logging to measure impact of new sync process

### ISSUE THREAD

**Issue by burtonjc** [waffleio/waffle.io#2831]
AC:
- [x] determine what to measure in our current service stack and what to log to measure it
- [x] determine what to log in new sync functions
- [x] make those logs meaningful in loggly (graphs?, alerts?, ...)

**Comment by jtslear** [comment]
My current logging mechanism for waffle.io-sync will ensure we can graph numbers by converting the report values to numbers.  Our current logging process we have the ability to take the request duration and graph that.  I've got an open ticket with loggly to be able to assist with groking logs as right now, it appears to be difficult to filter by specified URL's.

**Comment by jtslear** [comment]
Our request queueing time is kinda high.  It accounts for nearly half the amount of time a request is being processed.  I'm not sure how to measure this, but it'd be cool to keep an eye on this, and see if this decreases as we place functions into lambda.

**Comment by jtslear** [comment]
It'd be nice to have a log per function in our current existing code that captures a similar report that aws lambda provides, memory use, time spent processing, name of the function.  Would upgrading our new relic account provide these details though?

**Comment by jtslear** [comment]
I think it would be good to validate that loggly is being sent logs in a manner that does not impact the performance view of the user.  Based on transaction logs, time spent taking care of logging is chewing up a lot of unnecessary time.

**Comment by jtslear** [comment]
We could also potentially ship what I'm already sending to loggly to new relic as well to enable a single place to look at metric data:
https://docs.newrelic.com/docs/insights/new-relic-insights/custom-events/insert-custom-events-insights-api

**Comment by jtslear** [comment]
Having all of this could be helpful: https://blog.newrelic.com/2016/09/15/nodejs-custom-metrics-analysis/

**Comment by jtslear** [comment]
Unless we move out of coffeescript, it's probably impossible to be able to rely on the metric data provided by our application.  New relic relies on the naming of functions to apply data too, and coffeescript purposely hides the ability to create named functions.  Therefore everything in new relic shows up as `anonymous`

**Comment by jtslear** [comment]
we are unable to add the cpu metric i'd like to cuz we are running node version less than 6.

we are unable to add the gc collector metric as that relies on some external library.  

we have memory being graphed which is nifty :-)

**Comment by jtslear** [comment]
> determine what to measure in our current service stack and what to log to measure it

Currently adding metrics for the following: 
* Memory use of nodejs
  * includes the dyno
  * includes the pid
* Function time elapsed
  * contains the name of the function run
  * contains the name of the project ID

Graphing memory can be beneficial for various reasons including troubleshooting and planning.

Graphing the time spent on a function in each transaction, with the added ability to query for slow projects, and even track projects that grow; we can watch their performance over time.

Also, already available to us, is the graphing of time spent in each route.  But with New Relic Essentials, we are able to see transaction traces.  Which is tremendously beneficial at seeing specific slowness in the application and pin point slow transactions.

**Comment by jtslear** [comment]
> determine what to log in new sync functions

I'd like to repeat the above and log the following into new relic:
* name of function
* time spent on the function
* if it's possible to gather the memory use from lambda, toss that in there as well
* Also log the project ID

Please see the above note about the recommended way from NewRelic regarding how to get the data from lambda into Insights

**Comment by jtslear** [comment]
> make those logs meaningful in loggly (graphs?, alerts?, ...)

I've got example graphs here: 
https://insights.newrelic.com/accounts/1479581/dashboards/222794

No alerts are configured.  I think we'd need to discuss as a team, when to fire an alert, or watch a failure to see what to actually alert on.
