### ISSUE TITLE
Move issues across repositories

### ISSUE THREAD

**Issue by jthi3rry** [waffleio/waffle.io#2836]
With the rise in popularity of the micro-services architecture, the number of repositories managed by organisations blow up, and the different stakeholders can find it difficult to know what repository to create an issue against when a project is composed of multiple repositories. When an issue is created against the wrong repository, this involves a lot of manual work to rectify.

Since actually moving issues is not possible within Github, Waffle would be the perfect place to add a “Move Issue” action and allow the selection of a different repository.

The results of the action could include:

1. Creating a new, identical issue on the selected repository.
2. Adding a Wafflebot or user comment to the old issue, referencing the new issue: “Moved to [ url of new issue]” (this will also create a back reference from the new issue within Github).
3. Adding the `duplicate` label to the old issue.
4. Closing the old issue.

**Comment by wimpers** [comment]
+1 We now rely on https://github-issue-mover.appspot.com/ tpo move issues but doing it from Waffle would be a plus.

**Comment by wimpers** [comment]
Btw duplicates https://github.com/waffleio/waffle.io/issues/1226

**Comment by wimpers** [comment]
And duplicates https://github.com/waffleio/waffle.io/issues/2044

**Comment by wimpers** [comment]
Another duplicate https://github.com/waffleio/waffle.io/issues/1729

**Comment by jthi3rry** [comment]
duplicate, https://github.com/waffleio/waffle.io/issues/2044 seems to be the main one.
