### ISSUE TITLE
Do not render empty page at the metrics url if the account does not exist

### ISSUE THREAD

**Issue by burtonjc** [waffleio/waffle.io#2839]

**Comment by burtonjc** [comment]
Turns out there are a couple problems here. This is with the feature toggle on:

1. For a public repo that doesn't have a project, you are able to navigate to the new throughput and burndown pages, but they error when fetching the data (no project id) and show an empty graph.
  - Instead show the CTA page with an action to "Create the project"?
  - If there is no account, should we show an action to "Sign up"?
1. For a private repo that does not have a project, you get a blank white page with no errors when navigating to the metrics page.
  - same options as above?

**Comment by marydavis** [comment]
what did we do before with the throughput?

**Comment by marydavis** [comment]
can we just fix it for when the toggle is off for now?

**Comment by burtonjc** [comment]
Also, per @homeyer, it would be awesome if the marketing pricing page could give you a way to start a trial such that you auth with github (login or signup), start a trial, and get redirected to the dashboard.

Seems like a good stretch goal or post launch item.

**Comment by burtonjc** [comment]
PR open to fix the legacy throughput in the mean time.
