### ISSUE TITLE
start trial from pricing page

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#2842]
AC:
 - from the (new) pricing page there will be buttons to "start trial"
-  that button should log you in, and start a trial, and then land you on the dashboard (not the metrics page, because you don't have any projects)

**Comment by burtonjc** [comment]
We decided to punt on this because:
1. We need to invest in more on-boarding work before this makes since
2. It would only work for personal accounts because you cannot "Sign up" as an org
Seems like it might even hurt us more than help us at this point.
