### ISSUE TITLE
unwaffled repos should see the metrics CTA page at :owner/:repo/metrics

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#2843]
AC:
- [ ] when metrics is toggled on, unwaffled repos should see the metrics CTA page at :owner/:repo/metrics with a CTA to signup
- [ ] after login/signup, it should take them back to the CTA page, where they can then start a trial

**Comment by burtonjc** [comment]
It needs to not be painful, but we shooting for MVP here.
