### ISSUE TITLE
ability to create same issue across multiple repos?

### ISSUE THREAD

**Issue by winkumar** [waffleio/waffle.io#2846]
This is helpful to maintain with multiple repo issue management.

**Comment by kellihsf** [comment]
Hi @winkumar,

Are you wanting to create the same issue across multiple repos?

**Comment by winkumar** [comment]
Hi @kellihsf 
Yes i looking to manage project issue in single place is it possible. ex : i have two repo called back-end and front-end ,any requirement is came i want create issue with two different repo in two times. this is main problem to maintain project level issue.

**Comment by kellihsf** [comment]
Ok, thanks for the reply! Would you be open to changing the title of the issue to something like 'ability to create same issue across multiple repos'? That way, it would be easier for others to find. :)

**Comment by deckard86** [comment]
This feature (or similar solution) would be great
