### ISSUE TITLE
Allow filtering on closed milestones

### ISSUE THREAD

**Issue by wimpers** [waffleio/waffle.io#2847]
When a milestone is closed in GitHub, it will be removed from the filter in Waffle. So unfortunately, you're not able to filter by that milestone once it's closed.

For making Release notes it would be handy to filter on  a closed milestone. Our Waffle board spans across 15+ repos and a single view on all closed tickets would be handy.

This ticket should be tackled with https://github.com/waffleio/waffle.io/issues/2728  and relates to  https://github.com/waffleio/waffle.io/issues/2747

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
