### ISSUE TITLE
Move cards from the detail modal

### ISSUE THREAD

**Issue by songawee** [waffleio/waffle.io#2849]
As a user, I would like to be able to move cards between columns from within the detail modal so that I do not need to manually drag and drop cards to change columns.

AC:
  - [ ] update the card's column if a card's column labels have been updated with requiring a browser refresh

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
