### ISSUE TITLE
Hide board from Your Boards

### ISSUE THREAD

**Issue by twitherington** [waffleio/waffle.io#2851]
If you no longer want to see a previously visited board in "Your Boards", there doesn't appear to be a way to remove a board from that view.

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
