### ISSUE TITLE
add help documentation for card #2853

### ISSUE THREAD

**Issue by marydavis** [waffleio/waffle.io#2854]
https://waffle.io/waffleio/waffle.io/cards/582f520d6bc8470a01b16d05

**Comment by kellihsf** [comment]
https://github.com/waffleio/waffle.io/issues/2853

**Comment by kellihsf** [comment]
https://wafflehelp.zendesk.com/knowledge/articles/235672607/en-us?brand_id=1653167

**Comment by marydavis** [comment]
added some comments, thanks!
