### ISSUE TITLE
track individual metrics on throughput and burndown

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#2856]
Add ability to filter by individuals on the throughput graph.

This feature isn't hard to implement, but is contentious as to whether it's a "good thing" to support or not. So far, Waffle has enabled team level metrics to encourage collaboration; does it really matter who opened the Pull Request, when it's a team effort to review it, and it's a team goal to hit iteration commitments?

This feature is something we'll continue to consider, but aren't scheduling yet.

**Comment by kellihsf** [comment]
Tracking on [#1327](https://github.com/waffleio/waffle.io/issues/1327)
