### ISSUE TITLE
Coupon not re-applied to past_due sub upon re-activation

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#2859]
Steps to repro:

- start a trial
- add coupon
- expire trial
- get to past due (attempt to pay outstanding invoice)
- update card info
- coupon has been removed

**Comment by burtonjc** [comment]
I think we are going to have to change our paradigm of how we handle past due subs. Currently we cancel and create a new sub. We will instead need to update the existing sub (set `trial_end` to `now`) and then handle whatever we need to handle for the invoices.

**Comment by homeyer** [comment]
manually fix if it happens
