### ISSUE TITLE
Cancelled state appears to be borken (yes borken).

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#2861]
![image](https://cloud.githubusercontent.com/assets/84629/20652063/caf91976-b4af-11e6-862d-4a51149c8499.png)

Maybe we show "Purchase Metrics" button?

Updating the card info on a cancelled subscription seems to show the right thing tho

**Comment by songawee** [comment]
Not borken after all. Looks like the card wasn't deleted while testing and this condition caused the issue. In production, we delete the card in addition to cancelling the subscription.
