### ISSUE TITLE
navigate to organization account page

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#2862]
Currently there's no way to get to an org account page.

@marydavis, you mentioned there's an existing design somewhere for how this would work. I couldn't find an issue for it, can you link to it?

**Comment by marydavis** [comment]
https://waffleio.slack.com/files/mary/F1N0LKSD7/rough_draft_of_account_page.jpg

**Comment by marydavis** [comment]
new idea: add link next to project dropdown and on dashboard project list and move this to another card
