### ISSUE TITLE
Downgrading during a trial results in a past_due subscription

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#2863]
Steps to repro:
- start a trial
- purchase metrics
- downgrade
- expire trial (new invoice is generated)
- pay invoice (fails since no CC)
- subscription now in past due state (should be in cancelled)

**Comment by burtonjc** [comment]
I think this is not actually an issue, the downgrade sets the `cancel_at_period_end` flag but then the expire trial script unsets it. Let's still verify though.

**Comment by burtonjc** [comment]
confirmed, it works as expected.
