### ISSUE TITLE
Better reporting to show progress

### ISSUE THREAD

**Issue by dwowens** [waffleio/waffle.io#2865]
When looking at the throughput graph... I'd love a view that includes open issues and NEW issues as well. So we can see progress being made toward "done" and also see new issues being added moving us away from done.   At the moment we can only see the rate at which issues are closed... but that doesn't give us a sense of how much is left and how many new issues were added.  We tend to manage our work toward a single milestone and its associated issues.

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
