### ISSUE TITLE
track when an account is deleted in intercom

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#2883]
when a user deletes an account we don't accurately track it as a canceled sub.

AC:
- [ ] track in intercom
  - [ ] cancelled (`Intercom.trackEvent "canceled #{subName} subscription"`)
  - [ ] deleted account
 - [ ] track in mixpanel (`TrackService.track "canceled #{subName} subscription"`)

**Comment by burtonjc** [comment]
I feel like we shouldn't have the subname in the event name. You can't build any sort of funnel if the event names aren't the same. Also, I feel like it should be "canceled account", not "subscription". Thoughts?
