### ISSUE TITLE
Columns apply milestones too

### ISSUE THREAD

**Issue by AmirSavand** [waffleio/waffle.io#2891]
Just like the "In Progress" column that applies in progress label, columns need the ability to apply milestones too.

**Comment by leeogrady** [comment]
+1

**Comment by Alir3z4** [comment]
+1

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
