### ISSUE TITLE
Select file from file choose to initiate image upload

### ISSUE THREAD

**Issue by burtonjc** [waffleio/waffle.io#2901]
AC:
- [ ] button somewhere to open file browser
- [ ] on file selected, post to asset upload endpoint
- [ ] on asset endpoint response, upload to according to response body

**Comment by marydavis** [comment]
![upload.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/53724c88ebef97b1f959cc15/125516c66e82c728ace21e0d46fd84962c8387ebc3abaf51ab57f5973d047d317c56a67b24d4e02eba122f540d571fff425d0911f8ff8b2bb4aa2e32db025fb28c341521842f1bbeba8415be05b3278e4c83bfbb8a4ac5ee2f68.png)
