### ISSUE TITLE
Configure S3 bucket

### ISSUE THREAD

**Issue by burtonjc** [waffleio/waffle.io#2904]
This [heroku article](https://devcenter.heroku.com/articles/s3-upload-node#s3-setup) is helpful.

AC:
- [ ] S3 bucket named something like `waffle-direct-uploads`
- [ ] public read permissions for anyone
- [ ] must authenticate to upload
- [ ] CORS enabled from the waffle.io client

**Comment by songawee** [comment]
caching?

**Comment by jtslear** [comment]
>  must authenticate to upload

I disagree with public reads.  This may enable someone to brute force names and read uploads for private repos.

> caching?

Cache-Control should be set when the file is initially uploaded to S3. http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#putObject-property

**Comment by homeyer** [comment]
GitHub's uploads are public read, but the filenames aren't the same. For example, uploading a gif named `excited.gif` becomes https://cloud.githubusercontent.com/assets/84629/24480515/08028864-14a2-11e7-82c2-477a5e82858f.gif.

Let's do something like that.

**Comment by jtslear** [comment]
* S3 buckets are configured PER environment.
* Each bucket has it's own dedicated user, therefore a set of credentials PER environment
* Uploads should go to s3://<bucket-name>/uploads/ in order for them to be served by the cloudfront configuration
