### ISSUE TITLE
Display reviewers on pull requests, closes #3133

### ISSUE THREAD

**Issue by swallez** [waffleio/waffle.io#2907]
Github [recently added review requests](https://github.com/blog/2291-introducing-review-requests) on pull requests. On Waffle, only assignees are displayed.

Displaying reviewers on PRs seems like a mandatory feature!

**Comment by pickledgator** [comment]
this would be helpful. right now if you use github's recommendation to make the assignee the person assigned to the original issue, the reviewers don't get task notifications within waffle.

**Comment by nsidhaye** [comment]
It will be really useful to have reviewer. Actually assigning PR as well as review is somewhat dual task. In our internal github repo as well as open source repo we always select reviewer for PR not assingee. I will really love to see reviewer (at least only for display purpose)

**Comment by kellihsf** [comment]
Hi all,

We've just released this new feature! You can now see reviewers (and assignees) on pull requests. This new feature is a paid add on for private repos (free for open source). Let us know what you think! 😀
