### ISSUE TITLE
Metrics: Add total count at the top of each bar

### ISSUE THREAD

**Issue by kellihsf** [waffleio/waffle.io#2908]
Previous throughput graph would show the total number of issues/points at the top of each bar.

Would be nice to have this again to easily see the total.

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
