### ISSUE TITLE
Column sorting

### ISSUE THREAD

**Issue by kellihsf** [waffleio/waffle.io#2910]
Would like to sort columns by:

- size
- fifo
- a to z
- delivery date 
- countdown

**Comment by akatov** [comment]
Ideally one would want column sort order to be configurable.
I'd want to pick which of the above I would want to use for sort order and in which priority (e.g. delivery date ascending, then size descending).

In addition to this, it'd be nice to be able to sort by labels.
This could be either a total order defined upfront.  e.g. ("bug" > "enhancement" > "idea"), or an order implied by a "number" part of a label, e.g. "Impact: 1" < "Impact: 2" < "Impact: 10" etc. where I'd be free to define "Impact: 11" when I need it without having to do anything else.

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
