### ISSUE TITLE
Allow columns with Label1 AND Label2

### ISSUE THREAD

**Issue by EmilStenstrom** [waffleio/waffle.io#2911]
We have a tag called "Translations" that means the feature has to go through an additional step before being able to ship. I would like it if I could put all the "Shipit" features in one column, and all the "Shipit AND Translations" in another. 

This means that one card could match multiple columns. I suggest you resolve that my simply giving precedence to the column furthest to the right (closest to done).

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
