### ISSUE TITLE
track work in repos you don't own

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#2914]
https://twitter.com/bostonaholic/status/810878553789120512

Example: I contribute to open source, and would love to see the progress of PRs I contribute. I'm not a collaborator on the team, so can't add the repo to my board (and I only want to see my work, not everything in their repo).

**Comment by jasonkarns** [comment]
Exactly what I want!

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
