### ISSUE TITLE
Nano Degree not in "enrollments" in Android app

### ISSUE THREAD

**Issue by lethargicpanda** [waffleio/waffle.io#2918]
The Self-Driving Car Nano degree isn't showing up in the enrollments section in the Android app.

**Comment by kellihsf** [comment]
hi @lethargicpanda,

You've reached the waffle.io public board! Not sure if you were trying to contact us or not, but the self-driving car sounds pretty rad! :)

**Comment by lethargicpanda** [comment]
Lol :D sorry... wrong board!
