### ISSUE TITLE
investigate CORS errors on Safari Technology Preview

### ISSUE THREAD

**Issue by kellihsf** [waffleio/waffle.io#2923]

**Comment by elia** [comment]
The affected release is `Release 20 (Safari 10.1, WebKit 12603.1.16)` in case you feel it's a bug in safari TP and want to submit a bug report to https://bugreport.apple.com

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
