### ISSUE TITLE
Add Browser performance timings

### ISSUE THREAD

**Issue by songawee** [waffleio/waffle.io#2924]
Let's use some form of timing, i.e. - https://www.html5rocks.com/en/tutorials/webperformance/usertiming/

AC:
- [ ] Capture the following metrics at the minimum
  - [ ] measure the time for JS in the <head> (these load synchronously)
  - [ ] measure the time for CSS in the <head>
  - [ ] make a mark for 'board loaded'

Extra Credit (EC):
- [ ] make a mark for loading the detail modal (may require using WebPageTest scripting API- https://sites.google.com/a/webpagetest.org/docs/using-webpagetest/scripting)

**Comment by homeyer** [comment]
This would be so sweet... good enough is probably tracking this in a dev environment, but seeing it across geo regions, and then being able to tie it to specific customers would be the holy grail.

**Comment by marydavis** [comment]
making note of these metrics internally to use for performance, thanks!
