### ISSUE TITLE
Remove blocking vendor scripts from critical rendering path

### ISSUE THREAD

**Issue by songawee** [waffleio/waffle.io#2925]
There are third-party scripts we use for different pieces of functionality in the app. Would be great to move twitter, mixpanel, etc. to bottom of <body> so we can un-block our critical rendering path and download our essential assets.

AC: 
- [ ] WebPageTest run showing these requests aren't blocking

**Comment by songawee** [comment]
![screen shot 2017-01-03 at 3 27 21 pm](https://cloud.githubusercontent.com/assets/434885/21625589/93737730-d1c9-11e6-9a8d-79cf4afcec1c.png)

**Comment by homeyer** [comment]
Pretty sure we've done all we can on this... mixpanel has to be at the top, and twitter is gone

**Comment by burtonjc** [comment]
Agreed! Closing it.
