### ISSUE TITLE
Metrics: ability to export to csv/xls

### ISSUE THREAD

**Issue by kellihsf** [waffleio/waffle.io#2927]
from [intercom convo](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/7379792407)

- use it to create different charts if needed i.e. line-graphs etc etc. 
- also like to export data from 2 Waffle boards and compare the 2 way interaction between projects (which share resources)

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
