### ISSUE TITLE
connect waffle to slack in project settings

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#2928]
- [ ] add back the integrations section of project settings
- [ ] have a section for slack (no other sections right now, but maybe in the future!)
- [x] "Add to slack" button to start oauth flow: https://api.slack.com/docs/slack-button
- [x] oauth flow prompts to select a channel, and requests permissions to be able to post in the channel (no bot permissions or whatnot yet)
- [x] save off the slack token somewhere, tied to the project
- [ ] settings in waffle show that slack is connected
- [ ] hide integrations section for takeout

**Comment by songawee** [comment]
- [ ] be able to delete integrations
- [ ] only project admins can view/delete integrations
