### ISSUE TITLE
post in slack when a card is moved

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#2931]
When a card is moved to a new column (either by a manual drag and drop, updating a label in github, or an auto work action) the event should appear in a slack channel.

Bonus: If we implement this in wafflebot we could get slack events for GH Project auto-moves too! If we do this, we'll have to have messaging in the project settings to tell people they need wafflebot installed if they don't already.

**Comment by homeyer** [comment]
For reference, here's what one of our competitors does: https://docs.google.com/presentation/d/177WxdiZFD1FUhS1UNC4Xp55XCSXCuR7YYlINdgErdt8/edit#slide=id.g1bc9123685_0_0

**Comment by djbrooke** [comment]
Thanks for implementing this!

**Comment by burtonjc** [comment]
Here is what we are thinking for the slack messages:
<img width="609" alt="screen shot 2017-02-02 at 2 25 48 pm" src="https://cloud.githubusercontent.com/assets/443084/22569149/a53d6ee8-e953-11e6-9238-eae8105e74ba.png">
