### ISSUE TITLE
SPIKE: Investigate New Relic Browser

### ISSUE THREAD

**Issue by songawee** [waffleio/waffle.io#2933]
Let's add some timings to track in New Relic and evaluate the features the service provides

AC:
- [ ] hook up New Relic to the client application
- [ ] add custom metrics (User Timing API) around page load and board loaded
- [ ] investigate connecting Browser APM with server APM
- [ ] investigate looking at traces and creating trace views

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
