### ISSUE TITLE
move wafflebot icon to settings once it's installed on an account

### ISSUE THREAD

**Issue by kellihsf** [waffleio/waffle.io#2937]
Currently, if you have WaffleBot installed on your account, you'll still see the WaffleBot icon in the sidebar

closes #3267

**Comment by marydavis** [comment]
and change icon to new waffllebot font icon

**Comment by homeyer** [comment]
AC:
- [ ] if wafflebot integration is installed for the account, don't show it in the sidebar and instead show it in the settings.
- [ ] somewhere in settings say that wafflebot is installed. Link to the integration page in github (where we already link to). 
- [ ] (optional) show a help link to explain what it is
