### ISSUE TITLE
design PR info on cards

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#2941]
What does it look like in the final state, and how can we incrementally deliver it?

- [x] review state (what all do we need for that? requesting reviewers, reviewed, etc)
- [x] build state
- [x] merge state
- [ ] branch name
- [ ] anything else?

**Comment by jtslear** [comment]
I don't think having the name of the branch on cards is useful.  The links send us directly to the PR anyways.

**Comment by marydavis** [comment]
also, what do you want to be able to do from it too, assign reviewer? etc?

**Comment by burtonjc** [comment]
Biggest things for me are:
- reviewers (as opposed to assignees)
- status (open|closed|merged)
- review status (review needed, approved, changes requested, changes have happened since last review)
- build status (pending, pass, fail)

Pie in the sky would also have deployment status.
