### ISSUE TITLE
Assigned reviewers on card

### ISSUE THREAD

**Issue by rochacbruno** [waffleio/waffle.io#2944]
Cards could show assigned reviewers

**Comment by pickledgator** [comment]
this would be helpful. right now if you use github's recommendation to make the assignee the person assigned to the original issue, the reviewers don't get task notifications within waffle.

**Comment by pickledgator** [comment]
Also, related to #2907

**Comment by phyrog** [comment]
It would also be nice to be able to move cards into columns based on the review status (e.g. positive review given -> move to column "Approved").

**Comment by georgewfraser** [comment]
It would be nice if when I filtered on "assignee" = myself it would also show PRs where I am a reviewer.

**Comment by kellihsf** [comment]
Hi all,

You can now see reviewers (and assignees) on pull requests with our new feature! This is a new paid feature for private repos (free for open source). You can purchase Waffle through GitHub Marketplace: https://github.com/marketplace/waffle

This isn't implemented for auto-work tracking yet, but we'd love to hear your ideas around this. Feel free to open a new issue with any thoughts!
