### ISSUE TITLE
Zendesk integration

### ISSUE THREAD

**Issue by kellihsf** [waffleio/waffle.io#2946]
integrate Zendesk's articles in Waffle to create a workflow or a todo's list to better manage our help center.

Any update in Zendesk's article could be automatically updated within Waffle's boards.

**Comment by Workshop2** [comment]
This would really help us, why was it closed @kellihsf

**Comment by kellihsf** [comment]
Hi @Workshop2,

We're glad to hear from you! Some context for why you are seeing that issue closed is we didn't have anyone in the year it was open comment on it. 

We had cleaned it out as part of our commitment as a team to only keep cards that we are considering or committing to working in the next 6 months: [more about this on our blog](https://blog.waffle.io/managing-large-backlogs-48db59425208). By commenting on the card now we will take another look at it and how many of our customers are requesting this particular integration, vs. some of the other integrations we are seeing voted.

We are seeing over 200 for some of the others open on the board right now. Any other feedback for our team? Feel free to use this link to communicate your needs to our Customer Advocate: https://goo.gl/forms/QoEO7NQvDFR0qiHU2 . Thanks!

**Comment by Workshop2** [comment]
Thanks @kellihsf. We are really interested in waffle, however, to move off of Jira we need zendesk integration as we work very closely with our support team.

I'm not sure filling out that form would be of use to you as we haven't tried waffle yet.
