### ISSUE TITLE
⏳ onboarding videos, cut #1 📽

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#2947]
To be embedded in an intercom message that you receive when you first navigate to burndown. Or maybe in a dialog when you first navigate there (more work).

AC:
- [ ] a short (1 min?) video showing you how to use burndown and what value you get from it.

**Comment by homeyer** [comment]
Something like this would be magical https://player.vimeo.com/video/153702377

**Comment by homeyer** [comment]
or something simpler: https://vimeo.com/204206449

**Comment by marydavis** [comment]
maybe we can get the soundtrack from the waffle video to use for our help videos :)
