### ISSUE TITLE
document linked issues

### ISSUE THREAD

**Issue by kellihsf** [waffleio/waffle.io#2948]

**Comment by kellihsf** [comment]
https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/educate/articles/419094/show

https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/educate/articles/419132/show

**Comment by marydavis** [comment]
so may want to add to docs that if you connect and issue with connected issues/prs you no longer see those because the issue attaches

**Comment by kellihsf** [comment]
good idea, i think i'll add an image too. one of the issue by it's self and another of it nested beneath another issue. I'll wait til the PR icon is removed though. :)
