### ISSUE TITLE
remove PR icon on a linked issue

### ISSUE THREAD

**Issue by kellihsf** [waffleio/waffle.io#2949]

**Comment by kellihsf** [comment]
![screen shot 2017-01-17 at 10 27 36 am](https://cloud.githubusercontent.com/assets/4775572/22031937/9c06fdaa-dc9f-11e6-923f-7b5e95becbb9.png)

Currently, linked issues will have a PR icon on them, although they are not PRs. PR icon should be removed or changed to indicate it's an issue.

**Comment by czyoshida-naoko** [comment]
PR icon's on/off is useful to track a progress of issues, so please change to another icon rather than just remove it and let an icon show its status (open or close) as PR icon.

**Comment by marydavis** [comment]
@czyoshida-naoko agreed, we didn't remove the PR icon from connected pull requests, we now show the issue icon for connected issues instead of the PR icon :)

**Comment by czyoshida-naoko** [comment]
thanks a lot :)
