### ISSUE TITLE
Add the ability to create per repository filter on dashboard

### ISSUE THREAD

**Issue by JeremyAshton-shopify** [waffleio/waffle.io#2951]
It would be beneficial to include the ability to apply different filters based on which repository the data comes from.

i.e. show all unassigned issues for repo x and all issues assigned to me on repo y.

thanks

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
