### ISSUE TITLE
allow filtering on non-tags (like review requirements)

### ISSUE THREAD

**Issue by SwartzCr** [waffleio/waffle.io#2962]
Github allows teams to require Pull Requests to be reviewed before they're able to be merged: https://help.github.com/articles/about-pull-request-reviews/
it would be nice if I could filter on this - the same way that I would with a tag - and have unreviewed PRs auto-populate a column

**Comment by homeyer** [comment]
Now that Waffle shows PR review status on cards, we'd recommend having PRs auto-move to a "review" column, and then you can see in realtime what the review state is.
