### ISSUE TITLE
Move collapse column button to left of headline

### ISSUE THREAD

**Issue by timmybird** [waffleio/waffle.io#2964]
It would be nice if the collapse column button, the double arrows, could be moved to the left side of the column headline. By doing that the button would remain in the same position no matter if the column is expanded or collapsed.

**Comment by marydavis** [comment]
love that suggestion, thanks - will do!

**Comment by Alisuehobbs** [comment]
@timmybird Moved the collapse button. Check it out!

**Comment by timmybird** [comment]
Sorry for late response. Awesome  stuff!!
