### ISSUE TITLE
For some repos, the column label is not removed when issues are closed

### ISSUE THREAD

**Issue by adamralph** [waffleio/waffle.io#2976]
E.g. https://waffle.io/Particular/Collaboration

For (perhaps all of) the other boards under the Particular organisation, the column label is removed when an issue is closed, but not so for https://waffle.io/Particular/Collaboration. Would you be able to find out why this is the case?

**Comment by homeyer** [comment]
Hey @adamralph! Looks like there isn't a webhook configured for that project, so we're not listening for the events to clean up labels.

I flipped the toggle on the project to prompt you to install the webhook the next time you refresh your board.

**Comment by adamralph** [comment]
Thanks @homeyer!

I refreshed the board, added the webhook, moved an issue into an "in progress" column, and then closed the issue in GitHub. Waffle removed the "in progress" label. Thanks again!

**Comment by homeyer** [comment]
👍

**Comment by homeyer** [comment]
Any chance someone at Particular would be up for a customer development interview? We're talking with teams to understand how we can best help them and inform where we go next. If so... https://calendly.com/andrew-waffle/30-minutes

**Comment by adamralph** [comment]
@homeyer sure, I've just scheduled a time with you.

**Comment by adamralph** [comment]
@homeyer this is the blog post I mentioned https://particular.net/blog/an-organization-deconstructed

It's older than I thought, but more to come on the subject.
