### ISSUE TITLE
List "referenced issue" on side menu of issue detail, below milestone section

### ISSUE THREAD

**Issue by takayukioda** [waffleio/waffle.io#2981]
In current waffle.io, there is no easy way to check issue relations other than using `connects` keyword and make issues dangle, but sometimes, I just want issues to be related, but not dangling way.

Since GitHub provides an api to get the list of timeline including "issue has been referenced" from list issue timeline api (https://developer.github.com/v3/issues/timeline/#list-events-for-an-issue),  having a list of "referenced issues" on right side menu, below milestone, won't be too hard I hope. 

It looks similar to #803 or #1979, but their request was about commit message reference, and mine is about cross-reference of issue, so I made as new request.

Thanks!

closes #1996

**Comment by thel0r4x** [comment]
we went to use codetree on top of github.  get issue relationships and dependencies.  

we set up a new repo for "features" (epics and stories) and also reference those issues as parents.

display options nice and report makes codetree with github a good, lightweight project and product management tool for our dev and pm orgs.

**Comment by AnaMSteele** [comment]
We will be addressing this request via #771 Please upvote and comment there.
