### ISSUE TITLE
Showing `member` / `contributor` tag on a comment header, like GitHub does

### ISSUE THREAD

**Issue by takayukioda** [waffleio/waffle.io#2982]
Well, since waffle.io is made more for internal use, it might be not needed, but I thought it would be lovely to see which is the member / contributor's comment and which is not.

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
