### ISSUE TITLE
Committing branch with / in title, and ticket #, does not move ticket to in progress

### ISSUE THREAD

**Issue by andrewhl** [waffleio/waffle.io#2983]
If I have a branch called: bug/some-bug#123, and I push it to master, it will not activate the ticket. The same branch called bug-some-bug#123 WILL activate it however. Cool feature, but not quite properly implemented. Slashes are valid in branch names.

**Comment by homeyer** [comment]
Unfortunately this pattern is used for cross repo matching, :owner/:repo#number. We can't assume bug/some-bug isn't a repo (our token might not have access to know if it is or isn't), so we can't ignore it and associate to just the number in the same repo.
