### ISSUE TITLE
Add keyword for size

### ISSUE THREAD

**Issue by oferh** [waffleio/waffle.io#2984]
Add a keyword that can be used to set the card size from issue description.
this will allow to see the issue size when opening the issue in github

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
