### ISSUE TITLE
Use github filters everywhere

### ISSUE THREAD

**Issue by bjhartin** [waffleio/waffle.io#3000]
child #3651

### The Problem

Many open waffle.io issues are of the flavor 'allow me to filter based on XXX' or 'allow me to use XXX in filters'.  I think this means that users need more control to define what their boards and columns mean to them.  The label-only and 'is:closed' approach isn't flexible enough.

Rather than adding each specific feature capability, could you support columns that are defined by arbitrary github filters like:

>'Done' is defined as "is:closed label:reviewed label:deployed"

### Filter-Based Columns

When dragging a card into a column with a complex filter, waffle.io probably can't easily *force* the card to fit the filter.  However, I would be happy with a warning, in exchange for this flexibility.  For example:

>You can't drag issue 380 into the 'In Active Review' column because the filter is 'is:open label:being-reviewed commenter:joe-reviewer').  This card will appear in this column when it meets these criteria.

Perhaps the columns could be two types: traditional label-only columns and filter-based columns.

### Board Filters

I'd also like to be able to express board-level filters, e.g. 'team:my-team' and save the board with that definition.  Currently we copy the URL after adding the filter.

**Comment by AnaMSteele** [comment]
@bjhartin We are validating what it would look like to better serve different needs when viewing a board. Feels like your initial request is targeting at solving that issue. I know its been a long time, but is this still a friction point for you and would you be willing to jump on a short call and share more context with our team? If yes will you email me at support@waffle.io and we can set up a time to talk. Thank you.

**Comment by AnaMSteele** [comment]
Closing since this issue has not gathered enough feedback from Waffle users for us to prioritize over other work at this time, and we will not plan on addressing this in our near term roadmap.
