### ISSUE TITLE
show tool tip for expanding sidebar

### ISSUE THREAD

**Issue by kellihsf** [waffleio/waffle.io#3003]
A lot of users (especially new) aren't aware of how to open the sidebar. Having a tool tip over the arrow to expand would be helpful.

**Comment by marydavis** [comment]
what if we start it expanded for new users?

**Comment by kellihsf** [comment]
Yeah, I like that idea. Would we have something that explains how to collapse it? Otherwise, it might seem like that's the normal view.

**Comment by marydavis** [comment]
makes sense, we can add a tooltip either way :)

**Comment by marydavis** [comment]
another question, do they find the arrow okay? or does it blend in too much?

**Comment by kellihsf** [comment]
I think it blends some, but usually when I describe it (small arrow above your avatar) they find it.
