### ISSUE TITLE
custom column behavior

### ISSUE THREAD

**Issue by jazzdragon** [waffleio/waffle.io#3005]
Hi,
We're currently evaluating waffle, to see if we can use it effectively in our organization.
We have a bit of a different workflow: Ready -> in progress -> PR -> in dev -> done.
Can we attach behaviors to the columns?
For example, when opening a PR on an issue, I want the ticket to move from `in progress` to `PR`, and when merged I'd like it to go to `in dev`.

Thanks!

**Comment by homeyer** [comment]
Hey @jazzdragon! You can configure Waffle to do the first step, moving an issue to `PR` when a pull request is opened, by configuring your columns in the project settings. More details here: https://help.waffle.io/faq/waffle-workflow/can-i-move-issues-across-columns-automatically-using-pull-requests

When PRs are merged Waffle will either leave the issue where it is if you use our "connects to" keywords (see the link above), or we'll move the PR and related issue to "Done" if you use the "fixes" keywords. Unfortunately we don't support moving issues to any other column when a PR is merged.

**Comment by jazzdragon** [comment]
Thanks for the quick reply.
Are you planning to make it more personalized so it's not moved to "Done" without exception, when using "fixes"? for us, done means deployed to production...

**Comment by homeyer** [comment]
Each team handles production deploys a bit differently, so we're planning on implementing this feature to support a few different patterns: https://github.com/waffleio/waffle.io/issues/616

Your team could then have multiple columns tracking closed issues, as they go through the review and deployment cycle. Would that work for you?

**Comment by jazzdragon** [comment]
Perfect, thanks

**Comment by homeyer** [comment]
Awesome. Closing this for now, feel free to reopen or create a new issue with other questions.
