### ISSUE TITLE
show last viewed milestone in burndown graph

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#3006]
It's a bad experience to have to select a milestone every time you go to the burndown page.

Instead, let's (AC):
- [ ] remember last viewed milestone, load that when coming back to the page (local storage)
- [ ] if no last viewed, default to the most recently updated milestone

**Comment by AnaMSteele** [comment]
aggregating this request into our overall tracking of metrics related requests on #1327, and closing this issue. Please add further comments and upvotes there. Thank you.
