### ISSUE TITLE
FYP

### ISSUE THREAD

**Issue by ShaunLim123** [waffleio/waffle.io#3012]
User Registration does not work properly. Password hashing problems.

Login problems - wrong email and password although typed correctly.

Validating file upload does not show error if file size is not of .jpg, .png or image format or file size is too big.

GridViews do not have delete options, only adding and edit options.

Lack of validation.

Password strength/alphanumeric capital small letter

Progress:

Revamped the User Interface of Signup and Login. Applied Material Design which makes it cleaner, lighter, slicker and more consistent across the board.
Revamped the User Interface. UI is now Material Design and is cleaner, lighter, slicker and more consistent across the board.
Added in list of top 10 items running out and top 10 most popular items.
Added pie chart.
Added alphabetical searching for gridviews.
Added average food and service ratings for feedback.
Added manage customers.
Generally fixed user registration and login problems by changing the hash to Encryption/Decryption for now. Encrypt the password to check against the encrypted password when logging in and encrypt typed password during registration.

Under progress:
Activating, deactivating promotions.
User roles for login and logout and CMS.
Password hashing.
More features for gridviews.
Polish up file upload and improve validation.

**Comment by kellihsf** [comment]
hi @ShaunLim123!

You've reached our public board. :) Let us know if you have any questions or anything we can help with!
