### ISSUE TITLE
Hiring a Duo Blog Part 2

### ISSUE THREAD

**Issue by meganespeland** [waffleio/waffle.io#3020]
https://docs.google.com/document/d/1F5FS3TOHoOkR9D6_qPS8RLiCmnfE4p-797Q_SDX9Wn8/edit

**Comment by kellihsf** [comment]
up on the blog as a draft: http://blog.waffle.io/wp-admin/post.php?post=583&action=edit

**Comment by BAMason** [comment]
I don’t think I have access to Wordpress and didn’t see a global login in 1password.  Is there another way to view this?

**Comment by kellihsf** [comment]
^added Beth & Ali to blog as admins

**Comment by kellihsf** [comment]
Going live on wednesday 3/22
