### ISSUE TITLE
turn on proxy

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#3021]
- [ ] testing on staging2 is done

- [x] write instructions for removing proxy (if something doesn't work) in the ops channel. These should be accurate until we remove the marketing content from the app.

- [x] make sure latest syrup is on master and up on syrup.netlify.com
- [x] make sure proxy is up!

- [ ] ~~test these steps on staging 1?~~

- [ ] flip DNS!

**Comment by jtslear** [comment]
i'd like to disagree with testing on staging1 for the time being.  If we ever need to roll back, having one staging environment that is still representative of what prod should look like would be beneficial.

**Comment by homeyer** [comment]
Fine by me
