### ISSUE TITLE
when filtered by a milestone on the board, show a link to view the milestone's burndown in the header

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#3024]

**Comment by marydavis** [comment]
figured something simple like this, and then hide on mobile sizes:
<img width="1218" alt="screen shot 2017-03-23 at 11 01 13 am" src="https://cloud.githubusercontent.com/assets/176437/24253969/1586ff36-0fb8-11e7-8d39-487819e8047f.png">

**Comment by BAMason** [comment]
How do we want this to work if they have multiple milestones selected in the filter?
 * Pick a milestone and just show that one chart (say the first one in the list)?
 * Open multiple tabs to show each of the selected burndowns?
 * Ask them which one they want to see?
 * Other?

**Comment by marydavis** [comment]
hmmm...good question!

**Comment by marydavis** [comment]
i like option 2 personally

**Comment by homeyer** [comment]
I like showing both too!
