### ISSUE TITLE
Invalid Email Exception

### ISSUE THREAD

**Issue by twillms07** [waffleio/waffle.io#3031]
If an invalid email is entered an exception occurs. Should report send back invalid message and capture exception.

[info] javax.mail.internet.AddressException: Domain contains dot-dot in string ``twillms07@gmail..com''
[info] 	at javax.mail.internet.InternetAddress.checkAddress(InternetAddress.java:1326)
[info] 	at javax.mail.internet.InternetAddress.parse(InternetAddress.java:1116)
[info] 	at javax.mail.internet.InternetAddress.parse(InternetAddress.java:655)
[info] 	at javax.mail.internet.InternetAddress.<init>(InternetAddress.java:115)
[info] 	at co.piiq.personas.server.util.mail.package$.addr(package.scala:17)
[info] 	at co.piiq.personas.server.service.EmailService$class.sendEmail(EmailService.scala:17)
[info] 	at co.piiq.personas.server.boot.Server$.sendEmail(Server.scala:15)
[info] 	at co.piiq.personas.server.service.DefaultSecurityComponent$class.co$piiq$personas$server$service$DefaultSecurityComponent$$sendEmail(SecurityService.scala:264)
[info] 	at co.piiq.personas.server.service.DefaultSecurityComponent$DefaultSecurityService$$anonfun$authenticateVerifyRequest$1.apply(SecurityService.scala:88)
[info] 	at co.piiq.personas.server.service.DefaultSecurityComponent$DefaultSecurityService$$anonfun$authenticateVerifyRequest$1.apply(SecurityService.scala:87)
[info] 	at scala.util.Success$$anonfun$map$1.apply(Try.scala:237)
[info] 	at scala.util.Try$.apply(Try.scala:192)
[info] 	at scala.util.Success.map(Try.scala:237)
[info] 	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237)
[info] 	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237)
[info] 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
[info] 	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
[info] 	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91)
[info] 	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
[info] 	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
[info] 	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
[info] 	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90)
[info] 	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
[info] 	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:409)
[info] 	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
[info] 	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
[info] 	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
[info] 	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

**Comment by kellihsf** [comment]
hi @twillms07,

You've reached the waffle.io public board! Let us know if we can help with anything. :)
