### ISSUE TITLE
Open new github Issue with branch name keyword

### ISSUE THREAD

**Issue by tcldr** [waffleio/waffle.io#3034]
Problem: As a developer, often it is necessary to fix a quick bug that has yet to be added to the backlog.

Creating a new issue on github or waffle creates friction for the developer – this often results in issues not being tracked.

Currently it is necessary to create a new issue in waffle or github, and then open up a matching branch to work on the fix.

Remove the need for the developer to open an issue within github or waffle prior to commencing work.

Solution: When a developer pushes a new branch prefixed with a keyword, a new github issue should be created and assigned to the branch pusher.

This gives visibility of the issue/fix to the rest of the team and makes work easier to track.

Example:
1. Developer finds button with incorrect colour
2. Developer creates new branch with keyword 'fix', to work on issue and pushes to github. i.e fix-incorrect-button-colour-on-homepage.
3. Waffle detects new branch and creates github issue titled 'Fix incorrect button colour on homepage'. Assigns it the the branch creator, and assigns it the label 'bug'.
4. Workflow continues as usual

**Comment by homeyer** [comment]
If you create a PR from your branch Waffle will automatically show that on your board. You can even use [hub](https://github.com/github/hub) to do it from your command line:

```
git push origin HEAD:fix-incorrect-button-colour-on-homepage
git checkout fix-incorrect-button-colour-on-homepage
hub pull-request
```

**Comment by homeyer** [comment]
Closing this, in favor of always making changes with pull requests so it's visible in Waffle. You can use [Protected Branches](https://help.github.com/articles/about-protected-branches/) to make sure every change is visible.
