### ISSUE TITLE
Sync estimates in different boards

### ISSUE THREAD

**Issue by superkhau** [waffleio/waffle.io#3038]
Say I have two boards, board1 and board2. Assuming there is an issue that exists on both boards (say issue1). When I update an estimate for an issue1 in board2, I want the same estimate to be reflected in for issue1 on board1.

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
