### ISSUE TITLE
feature - show another issue card if in the same board

### ISSUE THREAD

**Issue by mika666** [waffleio/waffle.io#3039]
apologies if this has come up before

when clicking a referenced ticket from a waffle card, there is a redirect to github. it would be good if a card, provided it's in the same board, was opened straight away without going to github.

a quick and dirty example of behavior I am after:
in firefox go to: https://waffle.io/waffleio/waffle.io/cards/57fd2ff37135330e00b5cf4d, an appropriate card will be opened when waffle loads
imagine you clicked a link of a referenced issue - execute the following in the dev console:
```
history.pushState(null, '', 'https://waffle.io/waffleio/waffle.io/cards/53da94ec82b317f7d9ad35e9'); history.go(-1);
history.go(1);
```
a new card should be opened on the top of a previous one

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
