### ISSUE TITLE
Provide a "slim" option for the Slack integration to reduce noise

### ISSUE THREAD

**Issue by BAMason** [waffleio/waffle.io#3040]
From [this](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/8938232813) conversation:
*  Remove some of the extraneous card details when posting to Slack 
*  Ex: Send only brief one liners to slack along the lines of "Card #348 migrate to S3 moved to In Progress by <user>."

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208

**Comment by ilyapoz** [comment]
Very unfortunate because as I stated, slack notifications as they're now just a non-feature to me, had to turn them off, but I'm really missing out on the ability to easily let my team know that some issue is moved to "In progress" etc.

**Comment by homeyer** [comment]
@ilyapoz we keep waffle's slack notifications in a separate channel, so it doesn't interfere with conversations. Would that help your team?
