### ISSUE TITLE
feature - display progress tracking info in a ticket

### ISSUE THREAD

**Issue by mika666** [waffleio/waffle.io#3043]
apologies if it has been mentioned before.

in github issue, there is an option to add 'progress tracking checkboxes' that are then displayed on an issue list:
a DoD example
- [x] subtask 1
- [ ] subask 2
- [ ] subtask 3

continued in a comment...

**Comment by mika666** [comment]
initially the issue looks like this on a list
![image](https://cloud.githubusercontent.com/assets/712528/24286232/7bc0c4b4-1074-11e7-97d7-a8ab8589a0dd.png)

As you start toggling the checkboxes, it updates:
![image](https://cloud.githubusercontent.com/assets/712528/24286256/a0c64194-1074-11e7-863d-50ab8252aa1d.png)

It would be awesome to have such a display visible somewhere on a card.

**Comment by kellihsf** [comment]
Hi @mika666,

Thanks for the request! We actually do have an existing issue open for this already, so we'll close this as a duplicate. Feel free to check out [#2459](https://github.com/waffleio/waffle.io/issues/2459) and leave any additional info on the issue if you'd like! :)
