### ISSUE TITLE
feature - plugin subsystem

### ISSUE THREAD

**Issue by mika666** [waffleio/waffle.io#3044]
A plugin subsystem, even at a basic level in a form of an injectable js please.
Having a nice clientside API unifying adding gui elements or monitoring ticket changes and such would be awesome.
Not that it's not hackable now, but it would feel way better if accessed through an official apis

**Comment by homeyer** [comment]
what type of plugins do you envision adding?

**Comment by mika666** [comment]
I have been thinking about some of the following:
* adding a btn that allows for customising filters and simplifies restoring the defined filters
* 'precompose' / 'postcompose' - fired when rendering a card, so it is possible to add some xtra info to a card such as issue progress, time worked on an issue and such; a card could have an extra placeholder(s) to inject some html into
* same for the issue content

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
