### ISSUE TITLE
Authorization Bearer token is not invalidating after Logout and after github user revoke the access to waffleio app

### ISSUE THREAD

**Issue by kotireddyaluri** [waffleio/waffle.io#3048]
Authorization Bearer token is not invalidating after Logout and after github user revoke the access to waffleio app

Steps to Reproduce:
----------------------
Prerequisite: setup a burp proxy to the browser to see waffle.io requests and responses

1. access https://staging2.waffle.io and login as github OAuth
2. You will see waffle.io loads the repositories etc
3. Observe the waffle.io api request with authorization bearer token like below
4. make a note on bearer token
5. Now logout from the waffle.io
6. Go to github.com--authorized apps then revoke the waffle.io app access.
7. Repeat the below waffle.io api request with the above bearer token
8. Observe still bearer token is still valid and getting user information.

---------------------------------------------------------
Request:
----------
GET /user HTTP/1.1
Host: waffleio-api-staging2.herokuapp.com
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0
Accept: application/json, text/plain, */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Referer: https://staging2.waffle.io/kotiredXXX/private
Authorization: Bearer rHGlRX297ramEMCXXXXXXXXXXXXXG1QtglgDX0eDyL
Origin: https://staging2.waffle.io
Connection: close

Response:
-----------
{"_id":"58d4eb00cda4e700113efcd2","account":"58d4eb00cda4e700113efcd4","__v":13,"credentials":[{"accessToken":"rHGlRX297ramEXXXXXXXXXX1QtglgDX0eDyL","provider":"589874ee1ed9a21742eb1d8f","scope":"*","_id":"58d4eb00cda4e700113efcd7"},{"accessToken":"58a5b63c3f3a9668XXXXXXXab80da40c49","provider":"589873109XXXXdcd2363","scope":"read:org,repo,user:email","_id":"58d8fe1ed9041b0011650852"}],"github":{"login":"kotireddyaluri","email":"kotiredXXX@XXXmail.com","name":"Koti Reddy Aluri","avatar_url":"https://avatars3.githubusercontent.com/u/4362114?v=3"}}

---------------------------------------------------------

Fix:
----
Bearer token should be invalidated after logout/revoke the access and it should atleast invalidated after certain idle timeout.

Tested in https://staging2.waffle.io

**Comment by kotireddyaluri** [comment]
Retested the issue and it is not reproducible now.

Thanks,
Koti

**Comment by homeyer** [comment]
🍻
