### ISSUE TITLE
Issues do not merge with Pull Requests if retrospectively added

### ISSUE THREAD

**Issue by barrymcgee** [waffleio/waffle.io#3049]
Sometimes I forget to add 'Fixes #1' to a Pull Request so the issue and the related PR are not linked on my Waffle board.

When I then edit the PR to link the issue - Waffle still doesn't seem to pick up that they are now linked?

**Comment by kellihsf** [comment]
hi @barrymcgee,

Hmm, this should work! You may need to refresh the board and wait a few seconds to see the immediate change. Also, can you confirm that the 'fixes #1' is in the PR description or title?

**Comment by barrymcgee** [comment]
Ah - the issue was I was writing `Fixes #1, #2, #3` instead of `Fixes #1, Fixes #2, Fixes #3`

Got it now - thanks for your help.

**Comment by kellihsf** [comment]
Nice, anytime! :)
