### ISSUE TITLE
Adding labels/assignies in github does not reflect in waffle card

### ISSUE THREAD

**Issue by ashatp** [waffleio/waffle.io#3054]
I edited an issue in github and added comments, assigned and labeled. This was not reflected in waffle card after refreshing and moreover, moving the card in waffle caused the change in github to be overwritten. ( assignees & labels got removed and comments intact)

**Comment by kellihsf** [comment]
hi @ashatp!

We've had similar reports.. does this sound like what you're running into? 
https://github.com/waffleio/waffle.io/issues/1256

**Comment by kellihsf** [comment]
we'll close this one for now, let us know if you see this behavior again!
