### ISSUE TITLE
Flowdock integration --support for notification of changes to cards

### ISSUE THREAD

**Issue by superstructor** [waffleio/waffle.io#306]
E.g CircleCI and TravisCI Pro both support this via a Flowdock token. It would be awesome if moving or updating cards in waffle.io would publish change summaries to the flow on Flowdock.com.

**Comment by AntonioO** [comment]
:+1:

**Comment by armilam** [comment]
:+1:
Like @6twenty said, we already have github notify flowdock, but having waffle do it instead would be very nice.

**Comment by ashumz** [comment]
[+1](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/828641878)

**Comment by psiniemi** [comment]
+1

**Comment by mspangdal** [comment]
+1

**Comment by Ivogler** [comment]
+1

**Comment by gottfrois** [comment]
+1

**Comment by kmscode** [comment]
👍

**Comment by alisondavis17** [comment]
+1

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
