### ISSUE TITLE
NOT on Labels filter

### ISSUE THREAD

**Issue by superkhau** [waffleio/waffle.io#3064]
We have our repos/boards split out, but some repos are shared between boards. We need a way to filter our our issues on our board via something like: Filter `NOT team-* label`, so I don't have to add `team-*` to all our issues (thousands).

**Comment by kellihsf** [comment]
hi @superkhau!

Thanks for the request! This issue already exists on [#1799](https://github.com/waffleio/waffle.io/issues/1799), so we'll close this one as a duplicate. Feel free to add any additional info on the existing issue. :)
