### ISSUE TITLE
Sync issues order with Github milestone order

### ISSUE THREAD

**Issue by ewiner** [waffleio/waffle.io#3065]
Github changed their Milestone page a few months ago so it could be reordered by drag-and-drop, just like a list on Waffle.io.

It would be great to be able to sync the ordering of issues between Waffle.io (with a Milestone filter applied) and the Github Milestone page - whether that's a one-way sync or bidirectional.

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208

**Comment by dwijnand** [comment]
This would be wonderful. I'm currently debating with my team which ordering to honour, whether it should be the ordering on the milestone page in GitHub, or the ordering of issues in our Waffle board.

@homeyer what can be done to re-open this? Thanks.
