### ISSUE TITLE
Define columns using milestones and assignees rather than labels

### ISSUE THREAD

**Issue by georgewfraser** [waffleio/waffle.io#3074]
We'd like the ability to define columns like so:

Backlog: no milestone or assignee
Next Up: has milestone
In Progress: has assignee
Done: closed

What we would need is something like your "Work Started" / "New Collaborator PRs" rules:

<img width="239" alt="screen shot 2017-04-17 at 1 57 51 pm" src="https://cloud.githubusercontent.com/assets/1369240/25104668/1465ff68-2376-11e7-8274-7fb8c7662f84.png">

We need rules like these, except for "has assignee" and "has milestone".

**Comment by kellihsf** [comment]
hi @georgewfraser,

Thanks for the request! We'll move this over to Ideas for other to find and discuss. :)

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
