### ISSUE TITLE
scope patch requests (1256)

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#3079]

**Comment by burtonjc** [comment]
Required work:
1. __API__
    - new endpoint for card `PATCH`s
1. __APP__
    - new method in the card service to do a PATCH request (do not use `$resource` ... ever)
    - everywhere that uses the `card.$update` method will need to be changed to use  the new service `PATCH` method
        - directives/board/assignees-dropdown-menu
        - directives/board/board.coffee
        - directives/board/card.coffee
        - directives/board/detail-modal.coffee
        - directives/board/label-dropdown-menu.coffee
        - directives/board/milestone-dropdown-menu.coffee
        - directives/board/owner-dropdown-menu.coffee
        - directives/board/size-dropdown-menu.coffee
