### ISSUE TITLE
Suggestion: allow filter by "Reviewer request"

### ISSUE THREAD

**Issue by mfn** [waffleio/waffle.io#3084]
Currently it's only possible to filter for PR assigned to someone but not to filter only for PR which have requested review from a particular user.

**Comment by kellihsf** [comment]
hi @mfn,

Thanks for the request! We'll move this to our Ideas column for others to find and add their support. 😊

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208

**Comment by mfn** [comment]
If properly used by Github, the reviewer feature is a killer feature and not being able to simply filter for it in waffle is real bummer.
