### ISSUE TITLE
Request: Add a Keyup Delay to the Page Filter's Search Model

### ISSUE THREAD

**Issue by a12k** [waffleio/waffle.io#3085]
On larger boards (maybe smaller boards too) when using the "Filter Board" box, it filters pretty slow. Additionally, it also seems to be calling the angular search model on every keyup rather than giving the user a delay to make sure typing is done, or maybe the delay is really short. It seems like it would work more smoothly with a longer delay between keyups before calling the filter, maybe 200ms. Right now it hangs on every single keystroke. If I paste in my search term rather than typing, it behaves as expected. i.e. calling the search model once and filtering the board, which is a little slow, but happens once versus once for every keystroke.

**Comment by homeyer** [comment]
Hey @a12k!

The debounce for the board filter is set to 350ms right now. Do you notice a typing lag for every keystroke when typing quickly?
