### ISSUE TITLE
Figure out WaffleBot errors 💩

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#3087]
- [x] lots of `isGrandfathered` errors
- [x] wafflebot seems to be on vacation, is there anything else going on?

**Comment by homeyer** [comment]
while you're searching for where wafflebot goes on his vacations, can you ask him about this one too? https://github.com/waffleio/waffle.io/issues/3073

**Comment by BAMason** [comment]
Still waiting on GH to flag old installations to prompt them to update permissions
https://githubplatform.slack.com/archives/G2644G9KM/p1493818042799776
