### ISSUE TITLE
Add automatic label assignment

### ISSUE THREAD

**Issue by Nashet** [waffleio/waffle.io#3088]
Add some prefixes for each label, like "-" for bug, ">" for enhancement, etc..

Now, then user writes in card title "- Something" waffle will remove "-" prefix but add bug label. And so on.  User should be able to change standard prefixes \ add his own.

That would save user form routine work to assign labels. That's the only thing I dislike in Waffle.

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
