### ISSUE TITLE
Add Salesforce Integration. 

### ISSUE THREAD

**Issue by jsanch** [waffleio/waffle.io#3093]
An issue could be a task associated to an opportunity

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
