### ISSUE TITLE
issues that were deleted from github cannot be moved

### ISSUE THREAD

**Issue by guyzmo** [waffleio/waffle.io#3099]
for some reasons issues some issues put on my repository disappeared, and now I got cards I cannot remove in my backlog column, over at https://waffle.io/guyzmo/git-repo try accessing or moving the guyzmo/git-repo#130 or guyzmo/git-repo#135 cards ☺

Can you just remove them, please?

**Comment by kellihsf** [comment]
Hi @guyzmo,

We've removed those cards from your board. You may need to refresh the board for the changes to be picked up. Let us know if you run into anything else. Thanks!
