### ISSUE TITLE
Create a wider array of badges - connect to #3288

### ISSUE THREAD

**Issue by AdamBCo** [waffleio/waffle.io#31]
I think a wider array of badges would be useful, perhaps showing more than just the number of "ready" issues; I would ideally like to show both the backlog and the ready issues at the same time.

**Comment by Alisuehobbs** [comment]
Great news! We've updated our badge to be customizable with all columns. Check out our help doc for instructions on how to get the new badge and let us know what you think!

https://help.waffle.io/faq/github-badge/where-can-i-find-the-code-for-my-github-readme-badge
