### ISSUE TITLE
Add 1s delay to wafflebot to test race condition for fetching resource

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#3102]
When WaffleBot goes on vacation, it's sometimes not his fault. 

Wafflebot receives a PR opened event, and then goes and tries to fetch the PR with a valid token. Sometimes the `GET` request will 404.

A hypothesis is that the resource isn't available on all GitHub API nodes when we're making the request - we're too fast!

To verify, let's add a 1 second delay before handling webhooks in wafflebot.

If we see the number of 404s reduced, reach out to GitHub's platform team in slack to start a conversation about it.

**Comment by BAMason** [comment]
<img width="1680" alt="pre_delay" src="https://cloud.githubusercontent.com/assets/17367713/25931767/86153a54-35cb-11e7-8467-cdfd0e496eef.png">

**Comment by BAMason** [comment]
![post-delay](https://cloud.githubusercontent.com/assets/17367713/26205589/6c1eb3e4-3b9f-11e7-9823-9e5e15ed5933.png)
