### ISSUE TITLE
how should we let grandfathered, non-paid accounts know about upgraded PR status?

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#3104]
- [x] they need to upgrade before they can use it
- [x] is there a call to action or a way to tease that more functionality exists?
- [x] don't take away existing

**Comment by marydavis** [comment]
https://docs.google.com/a/waffle.io/document/d/1YVorp6oSIe1XiIm5NU6usqnSKb9M5cbonhm_fMm1-7A/edit?usp=sharing
