### ISSUE TITLE
CircleCI Case Study

### ISSUE THREAD

**Issue by meganespeland** [waffleio/waffle.io#3106]
Fill out this Google doc to complete a case study for CircleCI on how Waffle uses it and why we love it. 

https://docs.google.com/a/waffle.io/document/d/1w-6Q1-5gyU2Zq-z0NJV0rZu2mp7gnYVlHNGVNTBZ8EU/edit?usp=sharing

**Comment by jtslear** [comment]
I think it would be a good idea to get another person on this too.   My answers are very light... I would imagine they would want a little more substance.

**Comment by meganespeland** [comment]
I'll help elaborate and expand upon your answers and then have another dev
give it a review and opportunity to add more. Sound good?

**Comment by songawee** [comment]
@meganespeland I added a bit. John's answers were great.
