### ISSUE TITLE
Improve issue view for code blocks

### ISSUE THREAD

**Issue by Dids** [waffleio/waffle.io#3110]
When viewing issues on GitHub which have code blocks, especially if they have long lines (think stack traces, for instance), GitHub neatly shows these in a horizontally scrolling view. In addition to that, GitHub's issue view is also quite wide.

On waffle.io, everything is word wrapped, even code blocks, making it very hard to read (sometimes obscure) text. The waffle.io issue popup is also quite thin, compared to GitHub's issue view.

Ideally I'd love to see the popup size being adjustable (maybe save the size preference across repo/account/local storage too?), as well as not word wrapping code blocks, but using a horizontally scrolling view instead.

This is one of the only reasons I still have to switch between GitHub and waffle.io, so I'm hoping this gets some love as soon as possible.

**Comment by AnaMSteele** [comment]
@Dids is this still an issue, or is Waffle using GH's version of markdown in comments solve this problem?
