### ISSUE TITLE
Done column card order?

### ISSUE THREAD

**Issue by Nashet** [waffleio/waffle.io#3115]
What is idea behind card order in Done column? It looks random. Can it be closing date order?

**Comment by kellihsf** [comment]
hi @Nashet,

They should normally appear in the order they were closed(newest go to the top) but it looks like we have a bug. 😕   Thanks for the tip!

**Comment by Nashet** [comment]
That's my tracker with bugged done column: https://waffle.io/Nashet/EconomicSimulation
Usually I close issues in Desktop Github by closes #number

**Comment by Nashet** [comment]
Hi @kellihsf, is this fix included in official release? If yes, than it's still bugged for me.

**Comment by kellihsf** [comment]
Hi @Nashet,

Oops, look like this hasn't been resolved completely. Re-opening to have the dev team look at. 👍

**Comment by Nashet** [comment]
Hi, @Alisuehobbs.
I recently closed ticket and bot pushed it at bottom of Done column, again. Re-ironing waffle won't help. 
Repo: https://waffle.io/Nashet/EconomicSimulation card: #237
