### ISSUE TITLE
Font resources could not be loaded

### ISSUE THREAD

**Issue by Gebon** [waffleio/waffle.io#3116]

**Comment by Gebon** [comment]
![default](https://cloud.githubusercontent.com/assets/5419623/26043632/18ebf8d8-3958-11e7-82d1-4e147a5e66d0.PNG)

**Comment by Gebon** [comment]
Their URLs is smth like `https://waffle.io/urfu-2016/undefined/resources/d6cd4777dc581913c8b247b8bd44e02b.otf`

**Comment by homeyer** [comment]
Thanks @Gebon, looking at it right now!

**Comment by homeyer** [comment]
fixed! We're looking into the root cause.

**Comment by Gebon** [comment]
Thank you! Now it looks much better)
