### ISSUE TITLE
Issue and PR lifecycle

### ISSUE THREAD

**Issue by Gebon** [waffleio/waffle.io#3118]
When an issue with linked PR is moved from Needs Review to In Progress, the PR's label is not updated. Is it desired behaviour?

**Comment by kellihsf** [comment]
hi @Gebon,

Yes, that is the expected behavior today. We have an open request on our board, [#1622](https://github.com/waffleio/waffle.io/issues/1622) for updating the PR label when associated to an issue. We'll close this one out as a duplicate, thanks!
