### ISSUE TITLE
show team analytics / metrics - cumulative flow diagram, velocity (see also #1327)

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#312]

**Comment by ashumz** [comment]
[+1](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/703279334) 

"My team would love to see the whole team Throughput on projects and/or all of an individual's contributions given a set of time (weekly/monthly)"

**Comment by ashumz** [comment]
also see #1327

**Comment by ashumz** [comment]
from @erichexter: 
"It would be awesome to have a cumulative flow diagram for items as they work thru the columns of the kanban board.  I would imagine you would be able to calculated the times from the add/remove label history on each issue.

![image](https://cloud.githubusercontent.com/assets/114692/5939273/f764609e-a6c7-11e4-8efd-1aba3d6f70d3.png)

I was looking for a way to pull this together, and while it seems possible, its not trivial, so having this as part of waffle.io would be a pretty compelling feature."

**Comment by erichexter** [comment]
I was able to put a cfd together parsing the Issue Events then grouping the labels we use for columns, in our waffle board.

![image](https://cloud.githubusercontent.com/assets/114692/6122367/f291ece0-b0b7-11e4-855a-c1e33546aade.png)

**Comment by kwiens** [comment]
+1

**Comment by erichexter** [comment]
I created an app to produce a CFD for anyone who is interested, its as basic as you can get, but go to the site, login and select the repo you would like to analyze the issues for. https://githubissuereports.azurewebsites.net/

**Comment by aslakhellesoy** [comment]
@erichexter I'd love to try it out for one of my open source projects, but I'm reluctant to give the app access to my private repos.

Could you make two auth options - one for public scope and one for private+public ?

**Comment by erichexter** [comment]
Yes i can work they that, I implemented the private access because I am
using this for our work repository.

On Monday, March 23, 2015, Aslak Hellesøy <notifications@github.com> wrote:

> @erichexter <https://github.com/erichexter> I'd love to try it out for
> one of my open source projects, but I'm reluctant to give the app access to
> my private repos.
>
> Could you make two auth options - one for public scope and one for
> private+public ?
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/waffleio/waffle.io/issues/312#issuecomment-85035961>.
>


-- 
Eric Hexter

blog | http://Hex.LosTechies.com
info | http://www.linkedin.com/in/erichexter

**Comment by marleypetro** [comment]
+1

**Comment by kwiens** [comment]
+1

**Comment by O-Zone** [comment]
:+1:

**Comment by ThomasBurleson** [comment]
@erichexter - I would love to try you GihubIssueReport tool, but it **requires** access to private repositories. This is acceptable for me... Any workarounds ?

**Comment by blakewest** [comment]
:+1:

**Comment by nilswloka** [comment]
+1, together with WIP limits, this would eliminate my need for other task tracking tools

**Comment by wk001** [comment]
👍

**Comment by andrebrov** [comment]
+1

**Comment by kellihsf** [comment]
+1  [from intercom convo](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/7820211431), this link has a lot of good info: http://open.bekk.no/cumulative-flow-diagrams-with-google-spreadsheets

**Comment by dmine4** [comment]
+1

**Comment by djbrooke** [comment]
+1

**Comment by AnaMSteele** [comment]
We officially moved all tracking for this request to #1327. Please see transcription of comments from this tracking there now. Please feel free to continue to comment there and upvote to help our team prioritize this work. Thank you.
