### ISSUE TITLE
Access token for waffle public API

### ISSUE THREAD

**Issue by cactail** [waffleio/waffle.io#3125]
Hi, I'm developing a little program to manage my waffle projects from a file. I need an access token to use this [api](http://docs.waffle.io/v1.0/docs). How can I get it?

**Comment by cactail** [comment]
![captura de pantalla de 2017-05-16 14-40-52](https://cloud.githubusercontent.com/assets/6946058/26120202/516158ea-3a46-11e7-973b-c048e7452c73.png)
This is what I see in the docs. Nothing about authentication.

**Comment by kellihsf** [comment]
hi @cactail,

Our API is live in production, we just have a bit of work left to do around documentation and giving users the ability to create their own tokens. We don't have an ETA of when this will be released yet, which is why it's not considered ready for public/testing usage.

**Comment by cactail** [comment]
Ok. I will wait for it. ty

**Comment by trooney-nudge** [comment]
Looking forward to this. It's surprising to find a documented API, but no way to authenticate against it.

**Comment by dmjio** [comment]
Any updates on this?

**Comment by marcos-scalabrin-tereos** [comment]
Hello, any news on the API Auth?

**Comment by jvanderhoof** [comment]
Any new update?  We're trying to standardize columns across our projects, and access to the API would really help us do this.
