### ISSUE TITLE
assign issue to yourself when you drag it to in progress

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#313]

**Comment by Auruss** [comment]
+1

**Comment by robertjd** [comment]
+1 this is a standard kanban feature.

**Comment by qswinson** [comment]
+1

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
