### ISSUE TITLE
PR status styling changes

### ISSUE THREAD

**Issue by marydavis** [waffleio/waffle.io#3130]
- [x] remove extra padding when no statuses are in list
- [x] fix tooltip being cutoff
- [x] add color for in progress, not fallback to gray
- [x] make bar taller for easier clicking/hovering (or at least least the area)
- [x] add small space between statuses, so know if there is more than 1

**Comment by BAMason** [comment]
can we make the bar a smidge wider to facilitate easier clicking/hovering?
