### ISSUE TITLE
Integration badge style does not match defaults

### ISSUE THREAD

**Issue by orome** [waffleio/waffle.io#3134]
The integration badge is not sized or styled to match other badges (e.g. from shields.io) and I don't see a way to control its appearance.

See, for example, https://github.com/orome/crypto-enigma-py/blob/develop/README.rst.

**Comment by marydavis** [comment]
@orome here is how to use shields.io for the Waffle badge :)  https://help.waffle.io/faq/github-badge/do-you-have-any-other-badge-options-besides-the-custom-waffle-one

**Comment by orome** [comment]
@marydavis That doesn't seem to provide full control over color (e.g., `colorB` sees to be ignored). Is there a way to control that?

**Comment by marydavis** [comment]
@orome currently there is not a way to overwrite `colorB`, it uses the label color.
