### ISSUE TITLE
Implement the script to asynchronously synchronize marketplace accounts

### ISSUE THREAD

**Issue by burtonjc** [waffleio/waffle.io#3135]

**Comment by songawee** [comment]
We need to account for dropped hooks regarding Waffle accounts and GitHub accounts.

AC:
- [ ] Free -> Paid
  - [ ]  subscriptionEndDate = 2517
  - [ ] trialEndDate = existing || now 
  - [ ] marketplacePlan = paid plan ('Personal' || 'Organization')

- [ ] Paid -> Free
  - [ ] subscriptionEndDate = now
  - [ ] trialEndDate = existing || now 
  - [ ] marketplacePlan = 'Free'

- [ ] Personal -> Organization
  - [ ] subscriptionEndDate = 2517 (should already be set)
  - [ ] trialEndDate = existing || now
  - [ ] marketplacePlan = 'Organization'

- [ ] Cancelled Accounts (accounts not found in GitHub)
  - [ ] subscriptionEndDate = now
  - [ ] trialEndDate = existing || now
  - [ ] marketplacePlan = no change

- [ ] Extra GitHub Accounts
These are accounts we find that have a marketplacePlan, but do not have an associated Waffle account
- [ ] create new Waffle account if account does not exist
- [ ] update existing waffle account with marketplace plan

**Comment by burtonjc** [comment]
Other conditions that we may or may not need to care about right now:
- [ ] unset `cancelAt` if a customer re-subscribes
- [ ] do we mean to be setting `subscriptionEndDate` when canceling a free plan?
- [ ] when switching plans do not set `cancelAt`

**Comment by songawee** [comment]
Free plans do not get a subscriptionEndDate nor trialEndDate
