### ISSUE TITLE
A changelog page or use of our blog (with specific category tag) for updates [biz]

### ISSUE THREAD

**Issue by marydavis** [waffleio/waffle.io#3141]
maybe use: https://headwayapp.co/ (changelog app)

**Comment by homeyer** [comment]
We talked about copying how slack does it: in-app badge thingamajig for new features, linking out to blog posts, which I think can all be covered by https://github.com/waffleio/waffle.io/issues/3143.

**Comment by marydavis** [comment]
the app above includes the in app piece which would make this super easy

**Comment by homeyer** [comment]
Cool, added that note!

**Comment by marydavis** [comment]
this card was more a biz card for setting the app up

**Comment by marydavis** [comment]
idea is use the changelog for small blurbs and such and if more is needed can link to blog post or help articles

**Comment by marydavis** [comment]
i think you are right, this would require time to upkeep and maybe we should just focus on blog posting more and just add a link to the blog

**Comment by homeyer** [comment]
👍  I like the idea of focusing on fewer brand assets :).

I'll close this for now, we can always reopen if headwayapp is the easiest thing to use for the in-product portion.
