### ISSUE TITLE
Not all labels accessible - connects to #3029

### ISSUE THREAD

**Issue by retog** [waffleio/waffle.io#3145]
When having a lot of labels selection some of them is tricky. I can only move the slider of the labels within the visible area. And I cannot use the outer slider as clicking on it makes the label menu disappear which in turn makes the outer slider obsolete.

![image](https://cloud.githubusercontent.com/assets/110756/26361084/268aa4d4-3fda-11e7-869f-6a216642f0c9.png)

**Comment by homeyer** [comment]
Fix deployed! 🍻
