### ISSUE TITLE
Badges show issue count only from the main repository, not all source repositories

### ISSUE THREAD

**Issue by MikkCZ** [waffleio/waffle.io#3154]
STR:
1) Create a Waffle project.
2) Add some tickets to ready/progress.
3) The number on the badge corresponds.
4) Add new sources to the Waffle project.
5) Move some of their tickets to ready/progress.
6) The badge still shows the number of the issues according to the first repository instead of all that are in the project.

**Comment by kellihsf** [comment]
hi @MikkCZ, 

Thanks for opening this issue! We're actually  tracking this on [#2019](https://github.com/waffleio/waffle.io/issues/2019), so we'll close this one as a duplicate. Feel free to leave any comments or support directly to the already opened issue. 😀
