### ISSUE TITLE
Custom names for badges do not render dead space at the ends correctly

### ISSUE THREAD

**Issue by itsthejoker** [waffleio/waffle.io#3155]
First off, I'm sorry for filing this, but it is a legitimate (very minor) bug. We were playing renaming the badge and discovered that for long names, the empty space at either end of the badge does not render correctly.

Standard badge: 
https://badge.waffle.io/itsthejoker/TranscribersOfReddit.png?label=ready&title=Ready
This renders and looks fine.

Unstandard badge:
https://badge.waffle.io/itsthejoker/TranscribersOfReddit.png?label=ready&title=What+the+fuck+did+you+just+fucking+say+about+me%2C+you+little+bitch?+I%27ll+have+you+know+I+graduated+top+of+my+class+in+the+Navy+Seals%2C+and+I%27ve+been+involved+in+numerous+secret+raids+on+Al-Quaeda%2C+and+I+have+over+300+confirmed+kills%2E+I+am+trained+in+gorilla+warfare+and+I%27m+the+top+sniper+in+the+entire+US+armed+forces%2E+You+are+nothing+to+me+but+just+another+target%2E+I+will+wipe+you+the+fuck+out+with+precision+the+likes+of+which+has+never+been+seen+before+on+this+Earth%2C+mark+my+fucking+words%2E+You+think+you+can+get+away+with+saying+that+shit+to+me+over+the+Internet?+Think+again%2C+fucker%2E+As+we+speak+I+am+contacting+my+secret+network+of+spies+across+the+USA+and+your+IP+is+being+traced+right+now+so+you+better+prepare+for+the+storm%2C+maggot%2E+The+storm+that+wipes+out+the+pathetic+little+thing+you+call+your+life%2E+You%27re+fucking+dead%2C+kid%2E+I+can+be+anywhere%2C+anytime%2C+and+I+can+kill+you+in+over+seven+hundred+ways%2C+and+that%27s+just+with+my+bare+hands%2E+Not+only+am+I+extensively+trained+in+unarmed+combat%2C+but+I+have+access+to+the+entire+arsenal+of+the+United+States+Marine+Corps+and+I+will+use+it+to+its+full+extent+to+wipe+your+miserable+ass+off+the+face+of+the+continent%2C+you+little+shit%2E+If+only+you+could+have+known+what+unholy+retribution+your+little+%22clever%22+comment+was+about+to+bring+down+upon+you%2C+maybe+you+would+have+held+your+fucking+tongue%2E+But+you+couldn%27t%2C+you+didn%27t%2C+and+now+you%27re+paying+the+price%2C+you+goddamn+idiot%2E+I+will+shit+fury+all+over+you+and+you+will+drown+in+it%2E+You%27re+fucking+dead%2C+kiddo%2E

You'll see that there is a large amount of extra space at both ends. This is easy to replicate with any large amount of text.

**Comment by marydavis** [comment]
@itsthejoker fortunately you can use the shields version of our badge which handles long names better and has more styling options, check out this article for more: https://help.waffle.io/faq/github-badge/do-you-have-any-other-badge-options-besides-the-custom-waffle-one
