### ISSUE TITLE
URGENT BUG: issue with new image uploader

### ISSUE THREAD

**Issue by joshrosenheck** [waffleio/waffle.io#3157]
It costs money

**Comment by kellihsf** [comment]
![cat.gif](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/56241220b728ed1d0009af87/125516c66e82c728ace21e0d46eb958e61cec1bb8ee7bb4ca954ea913b047d317a56f97a24dcb570e81628505c5e4caf53444d04bea6d37ef5f22e7a985909b8d1695e27906811a8bdd017ee52b925dd1a81b0be8a5e8d.gif)
