### ISSUE TITLE
What onboarding experiences do you like?

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#3160]
- [ ] share products and @kellihsf can take some screenshots or videos of their onboarding experience
- [ ] or, grab your own screenshots and put them on this issue!

**Comment by kellihsf** [comment]
Intercom: https://docs.intercom.com/recorded-intercom-demos/create-and-share-help-content

**Comment by marydavis** [comment]
![Screen Shot 2017-06-15 at 11.06.01 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/53724c88ebef97b1f959cc15/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b77256455f66b7191a379ee0c2b57415f4fbc30254d58eeb9cb74fce36f34985619e8d3385f70c76e47f9b8861aed09eb73884ad3e3b88c4ec0fa2137a5dad11b61435c52dcbd4f3fb29a49c259f242e64856ad1a3666e0723e6e0a.png)

**Comment by marydavis** [comment]
![Screen Shot 2017-06-15 at 11.07.16 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/53724c88ebef97b1f959cc15/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b77256455f66b7191a379ee0c2b56415e48bc30254d58eeb9cb74fce36f34985619e8d3385f70c76e47f9b8861aed09eb73884ad3e3b88c4ec0fa2137a5dad11b61435c52dcbd4f3fb29a49c259f242e64856ad1a3465e37e346e0a.png)

**Comment by Alisuehobbs** [comment]
I actually thought LinkedIn's onboarding was super helpful. They had a status circle showing how complete your profile was and only showed you one question at a time, so it wasn't overwhelming. I can't seem to find it now, though.

**Comment by burtonjc** [comment]
I don't have any products to point out apart from what was already listed; however, I really like the idea of a progress indicator. It could include steps like:
1. Create a project
1. Select repos (which I wonder if we should actually call them "repositories" instead of "sources" <- probably why some people never realize we have multi-repo support)
1. Configure columns
1. Install WaffleBot
1. Invite team members
1. tweet? (bonus point? maybe for swag?)
1. anything else I am missing?

**Comment by marydavis** [comment]
if it is public, maybe add the badge to their repo?

**Comment by homeyer** [comment]
I would love to get rid of the badge banner in exchange for an onboarding step :)

**Comment by homeyer** [comment]
Pretty sure we're on the same page as to an approach to improve onboarding, but I found this post  a good foundation I agree with: https://ux.useronboard.com/bulletproof-user-onboarding-f34ee03f655f

On that note, UserOnboard does breakdowns of popular sites. They're fun to click through, might find some hidden gems: http://www.useronboard.com/onboarding-teardowns/

**Comment by homeyer** [comment]
@kellihsf this is a cool idea for where to inject a video: http://www.useronboard.com/how-invision-onboards-new-users/?slide=35

**Comment by BAMason** [comment]
Haven't had a chance to look at all of these yet, but some recommendations from asking around on what folks enjoyed (some I think are mobile, but still good):
* Mural
* Headspace
* Asana Rebel
* Spotify
* Haiku Deck

**Comment by homeyer** [comment]
I also enjoyed HeyTaco's onboarding, i'll record it real quick

**Comment by kellihsf** [comment]
All of the above comments are moved to this google doc: 

https://docs.google.com/document/d/1ren95_yjGVnrYvuG8-ljzxMcjNZQeAbDph-tXw4UCbw/edit
