### ISSUE TITLE
Issues with multiple assignees on a single issue ticket

### ISSUE THREAD

**Issue by anyren** [waffleio/waffle.io#3161]
Github allows you to assign multiple people to an issue. I've noticed waffle will unassign all but one when an issue changes state (i.e. from backlog -> in progress). It also doesn't display multiple users. Would it be possible to:

* Fix the issue where waffle unassigns users on state change
* Display all users assigned to an issue in waffle

fixes waffleio/waffle.io-takeout#201

**Comment by homeyer** [comment]
Hey @anyren!

We're tracking multiple assignee support for takeout on this issue: https://github.com/waffleio/waffle.io-takeout/issues/201

Mind me asking what version of GitHub Enterprise you're on? We're considering only supporting 2.10 for our next release, which would also include build status and pull request reviewer support.

**Comment by anyren** [comment]
Hi @homeyer! Looks like we're planning to be at 2.10 or higher by the end of the month. I think we may currently be at 2.8.7.

**Comment by homeyer** [comment]
Great - I'm connecting this issue to the other one, so you'll be notified when it ships.

**Comment by homeyer** [comment]
The latest version of Waffle Takeout supports multiple assignees! Minimum GitHub Enterprise requirement is 2.7, so you should be good to go.
