### ISSUE TITLE
what do we want to learn from SustainOSS?

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#3164]

**Comment by burtonjc** [comment]
Reason we are going:
> We love open source. We ourselves are not an open source product; however, we do have an open backlog/workflow and collaborate with our community to figure out what to work on. Because of that, we do experience some similar pains in how to organize and prioritize work.
> In addition to that, we use open source, we are passionate about helping open source in whatever way we can. We are going primarily just to listen. We want to know what problems maintainers are facing and figure out how we can help.

What we want to learn:
> What problems are open source maintainers facing? How can we help?
> How do open source maintainers work with their community to build and share roadmaps? Are you happy with this or are their pains that need to be solved?
