### ISSUE TITLE
if wafflebot is installed for a source, ignore those events in hooks

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#3165]
AC:
- [x] teach hooks to know if wafflebot is ~~active for a source,~~ installed for an account and ignore webhooks if so
  - [x] issue closed
  - [x] branch create
  - [x] pr opened, reopened, closed
- [x] remove logic for ignoring waffle orgs with the feature toggle

**Comment by homeyer** [comment]
after this is deployed, go ahead and increase wafflebot's delay from 1s to 2s, so we get fewer 404s. Gotta wait til this is done so we don't also have to increase hooks.

**Comment by DanieleSassoli** [comment]
Hi, 
I was having an issue with wafflebot as it wasn't moving tickets from "to do" to "in progress" when I pushed a branch referencing the issue number in one of the repos of my organisation.
I came across this thread and, although I don't clearly understand what you mean with "if wafflebot is installed for a source", I thought of removing wafflebot from my personal account. This seems to have fixed the issue and now when I push branches or merge PRs in my org, wafflebot picks up the events correctly, but it means I can't use it on my personal repos. 

Is this something you guys are aware of?

**Comment by kellihsf** [comment]
Hi @DanieleSassoli,

On this issue, the wording "source" refers to a connected repo on a multi-repo board. (We no longer use this wording to avoid confusion!)

Webhooks are responsible for all real-time events. If you created a card in GitHub, or added a label to a card, basically anything that happens in GitHub you need webhooks to send that over to Waffle in real-time. If you don't enable webhooks, you'll have to refresh your Waffle board each time an action is taken in GitHub.

WaffleBot is responsible for showing the "wafflebot" user is taking those actions. So if you didn't enable webhooks, you'd still see "wafflebot moved card #1", but you'd have to refresh your board every time for those actions to take place.

**Comment by DanieleSassoli** [comment]
thanks @kellihsf, the issue I was seeing was that the webhook was sending the event to waffle but got this as a response "{"code":202,"message":"Wafflebot is installed. Ignoring create:branch event."} ".
When I disabled waffle from my personal account then it started working and moving over the cards as expected. (Before it wouldn't move the cards at all, not even after refreshing.)

**Comment by BAMason** [comment]
@DanieleSassoli, this is actually as expected!  That message is intended to let us know we're keeping webhooks and wafflebot from trying to duplicate actions.

Wafflebot should be handling the movement of your cards and managing assignees, while webhooks handle realtime events like label, title, description changes, relationships, etc.  Without Wafflebot, you won't see in the github histories where we've made those movements on your behalf.  As Kelli mentioned, where it would normally say `Wafflebot added/removed assignees or labels` it will now just look like a member of your team performed those actions and can cause some confusion.

We'd love to help troubleshoot the issue with Wafflebot. Please click the '?' icon in the lower left corner of Waffle to open up a support ticket so we can get some more detailed information.
