### ISSUE TITLE
hide/collapse/fold columns

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#317]
- [x] determine how we want to handle filtering - do we show the counts of issues in the collapsed column if it matches a filter? Ignore to start with.
- [x] don't worry about not rendering cards in the column, first iteration can just be styling changes. We can optimize for performance later.
- [x] persist collapsed columns in local storage

**Comment by agibson22** [comment]
[hiding the backlog request](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/705853759)

**Comment by kwiens** [comment]
+1

**Comment by niklaspolke** [comment]
+1

**Comment by qualityshepherd** [comment]
+1

**Comment by ashumz** [comment]
+2 from #1873

**Comment by chmac** [comment]
:+1: huboard does this really well

**Comment by Rarst** [comment]
+1

**Comment by Petervw** [comment]
+1

**Comment by frosforever** [comment]
:+1:

**Comment by ehausen** [comment]
+1

**Comment by samdeane** [comment]
:+1: on this

**Comment by Glenndejaeger** [comment]
:+1:

**Comment by JimmyKuruvilla** [comment]
+1

**Comment by suriyanto** [comment]
:+1:

**Comment by vtemian** [comment]
:+1:

**Comment by ashumz** [comment]
Hi all, 

This is now live on your Waffle boards :) Check it out and let us know what you think! The columns will collapse and open based on your personal settings (rather than for all team members.) 

Cheers, 

Ashley

**Comment by kdeloach** [comment]
Thanks! :clap:

**Comment by HelaG** [comment]
Nice feature 
But I collapsed (all) my columns and now I can't open them back :( 
I tried deleting all my cookies but still, can't reopen them
(I'm on an old version of firefox  31.3...)

**Comment by marydavis** [comment]
Hi @HelaG - sorry the new collapsible columns do not support that version of firefox :( The collapsible column is saved in local storage, which you can get to and delete using the browser's dev tools. If you need additional help, just click on the '?' in the sidebar in Waffle and we can walk you through it.

**Comment by HelaG** [comment]
Done thx!

**Comment by ri0t** [comment]
For reference: http://stackoverflow.com/questions/6084099/how-to-view-delete-local-storage-in-firefox#6130392

**Comment by lamanning** [comment]
howdy. i also collapsed all columns and need to get them back. not using firefox; i'm on ie 11.
