### ISSUE TITLE
Design project creation on-boarding options

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#3170]
- [x] Use #3160 as input
- [x] Iterate on how we could improve the project creation flow with mockups

Purpose is to help our users find value faster. Faster might mean more steps to help them discover what they need, so they're enabled to use Waffle more effectively after finishing.

First pass we can choose to only handle it from the dashboard, instead of also creating a project from the board.

**Comment by marydavis** [comment]
https://docs.google.com/document/d/10Xb9kGtvBQDBg8ujondVHPqUji9ekboNQJcqtcPeAyk/edit
