### ISSUE TITLE
Upgrade to node@latest

### ISSUE THREAD

**Issue by burtonjc** [waffleio/waffle.io#3173]
fixes #3171

AC:
  - [ ] set dev engine to node@8
  - [ ] verify it all works

Do this in all the things:
  - [ ] app
  - [ ] api
  - [ ] hooks
  - [ ] wafflebot
  - [ ] models
  - [ ] helpers
  - [ ] env
  - [ ] slackify
  - [ ] infrastructure
  - [ ] functions

**Comment by homeyer** [comment]
We've started this work, need to check-in to see how much we want to move forward.
