### ISSUE TITLE
How to grant access to an organisation?

### ISSUE THREAD

**Issue by nikitavoloboev** [waffleio/waffle.io#3176]
I found [this](https://help.waffle.io/faq/creating-project-boards-in-waffle/how-can-i-add-my-organizations-repo-to-waffle).

But I don't see anywhere how I can actually get access to the organisation so I can see all of the repositories and their issues within Waffle.io.

Thank you for any help.

**Comment by nikitavoloboev** [comment]
Oh I figured it out. :)

**Comment by homeyer** [comment]
👍🏼
