### ISSUE TITLE
Is it possible to set default columns?

### ISSUE THREAD

**Issue by nikitavoloboev** [waffleio/waffle.io#3177]
For example I want to remove 'Ready' column completely so all repos I integrate with Waffle will only have Backlog, In progress and Complete as default columns.

Can I do that?

**Comment by homeyer** [comment]
Not yet! We're exploring ideas around this though, by letting you choose to copy a different board's configuration when creating a new one.

Have you considered putting all of your repos on a single board?

**Comment by nikitavoloboev** [comment]
How can I do that?

I am new to Waffle

**Comment by homeyer** [comment]
Welcome to Waffle! You can configure your board via the gear in the left menu and add more repos to your board from there: https://help.waffle.io/faq/creating-project-boards-in-waffle/how-do-i-add-multiple-repositories-to-a-single-board

**Comment by nikitavoloboev** [comment]
That's pretty awesome.

Can I change the name of this board somehow? I want to create a board to attach all my repos to it and call it 'GitHub' or something similar.

**Comment by nikitavoloboev** [comment]
I figured that out too. :)

**Comment by nikitavoloboev** [comment]
Btw is there a hotkey available to activate this? 

![2017-06-22 at 18 05](https://user-images.githubusercontent.com/6391776/27444082-7dce3abe-5775-11e7-80ea-ce6cce6ba671.png)

**Comment by homeyer** [comment]
No hotkey for it :). Awesome dark theme!
