### ISSUE TITLE
Highlight filtered icon on the board when filtered

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#3185]
- [ ] color the filter icon when filters are applied, same as we do on the milestone burndown page.

**Comment by harkenn** [comment]
The URL does change pretty dramatically since filters are handled over GET data. With "Filtering" over on the right hand side I'm not sure it'll be terribly visible anyways. Still, probably an easy enhancement to brightly colorize the "filter" icon in the top-right.

**Comment by marydavis** [comment]
the filter icon is colored when filtered on the metrics page, maybe that is a good place to start?

**Comment by homeyer** [comment]
awesome, easy first step. Updating the title to reflect that.
