### ISSUE TITLE
fix why subscriptionEndDate isn't updating on subscription updated event from stripe

### ISSUE THREAD

**Issue by marydavis** [waffleio/waffle.io#3193]

**Comment by homeyer** [comment]
Stripe waits an hour between when someone purchases and when an invoice is paid.

A user experienced purchasing waffle, but waffle did not show it was purchased.

We have a webhook for invoice created that should set `subscriptionEndDate`. Verify the webhook is working (in staging so we can use fake CCs) and that a user who purchases immediately sees it as purchased in Waffle.

**Comment by homeyer** [comment]
make sure to push the latest hooks to staging.

**Comment by marydavis** [comment]
the situation as i understand it is - 
customer starts a trial
customer pays for plan
trial expires
the `subscription.updated` sends a hook that we should update the `subscriptionEndDate`
stripe charges customer (an hour or so later)
we receive hook that payment succeeded and we update `subscriptionEndDate`

The issue is we need to make sure that when the trial expires that the  `subscription.updated` event is being received and we are updating the `subscriptionEndDate` with the correct date
