### ISSUE TITLE
Actions are being shown taken by a user not by WaffleBot - connects to #3165

### ISSUE THREAD

**Issue by flatcap** [waffleio/waffle.io#3194]
I've commented on this before, in the closed issue: #2840 
But it's still happening.

1. I created an organisation
2. I added lots of users
3. Added Waffle

Yesterday, a non-member created a pull-request: neomutt/neomutt#661
It was "auto-tagged" as "status:backlog" (from my Waffle settings), but **not** by WaffleBot, but by user "ThomasAdam" (the first user that I added to the organisaion).

It happened again a few minutes ago: PR neomutt/neomutt#662

**Comment by homeyer** [comment]
Thanks @flatcap, we have #3165 prioritized that will disable our legacy automated workflow actions when wafflebot is installed. Should land in the next week or so.
