### ISSUE TITLE
remove Home side panel

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#3196]
It's rather distracting right now, and doesn't give you the right information at the right time:

![image](https://user-images.githubusercontent.com/84629/27888978-8ec69fba-61a6-11e7-9f46-e4cc123152f5.png)

There's a number of things we could do in that same spot instead, but an easy first step is to just remove it entirely if it's more distracting than helpful. 

AC:
- [x] remove sidebar

**Comment by marydavis** [comment]
Add keyboard shortcuts, connected keywords, etc to help menu?

**Comment by marydavis** [comment]
requires #3189 to be done first

**Comment by homeyer** [comment]
Yup, #3189 is at the top of Planned. "Help menu" - I don't have a picture in my head for what that would look like, have an example of a product that does that you like?

**Comment by marydavis** [comment]
we already have a help menu, might just be nice to add a keywords to the shortcuts menu and add a link to that in the help menu

**Comment by homeyer** [comment]
At the bottom of the help menu could we link to the help docs on whatever topics we think are most important? Start with keyboard shortcuts, keywords?

**Comment by marydavis** [comment]
we currently link to `ask a question` and `help center` - was thinking of just putting the keyboard shortcut icon on there somewhere which would open that up and maybe add keywords to that

**Comment by homeyer** [comment]
oh, gotcha. cool!

**Comment by marydavis** [comment]
will need to find a way to still show a button to upgrade to private permissions as it gets on average 25 clicks a day from the user panel

**Comment by marydavis** [comment]
maybe just a button at the top right :)

**Comment by marydavis** [comment]
and maybe add to sidebar when we move the other stuff under account
