### ISSUE TITLE
"Pick a Repo" in Angular

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#3199]

**Comment by marydavis** [comment]
Might be nice to initially sort by User's account, with the option to choose account by dropdown or show all accounts - (also could load user account projects first then continue to load the rest in the background lowering the initial wait time), also save last selected

![Screen Shot 2017-07-11 at 5.18.08 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/53724c88ebef97b1f959cc15/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b77246455f26b7191a37df113234f5f575ecc3c4a4356bcbbd671f3e57862804e0eef846d5b75956b44acbc874db750e9238e19d0b2ba884cd2f42f67b6d5db1063474f4dcbed5727a39841c95cff42e94d5da4163266ee702431.png)

**Comment by burtonjc** [comment]
Blocking for now. We need to finish https://github.com/waffleio/waffle.io/issues/3215 before doing this guy.
