### ISSUE TITLE
Add multiple issues at once

### ISSUE THREAD

**Issue by resistdesign** [waffleio/waffle.io#3209]
Like this:
![issue-concept-fast](https://user-images.githubusercontent.com/356375/28197455-073cdf34-6825-11e7-830f-e5d845355027.gif)

**Comment by homeyer** [comment]
The add issue dialog supports hitting `Enter` after typing a title for rapid issue creation:

![add issue](http://g.recordit.co/85E02UpJqu.gif)

Are you doing epic breakdown activities, where the list changes a bunch before you want to persist it as an issue? What's your use-case for wanting to do it this way vs one at a time?

**Comment by resistdesign** [comment]
Looking for bulk entry.

**Comment by AnaMSteele** [comment]
tracking a single issue for all bulk issue action requests here #3629. closing this in favor of tracking all the requests in aggregate. please comment and upvote on this issue there.
