### ISSUE TITLE
Design new card detail view

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#3212]
Consider the requests in this milestone: https://waffle.io/waffleio/waffle.io?milestone=%F0%9F%8D%84%20Card%20Detail%20View

AC:
- [x] full screen optional
- [x] mobile friendly
- [x] ability to see the board at the same time (details as a sidebar, a la AZ?)

**Comment by marydavis** [comment]
convo starts: https://waffleio.slack.com/archives/C0P4DLWQY/p1510254704000568

**Comment by marydavis** [comment]
created cards #3324 and #3323 and ideally would add #801
