### ISSUE TITLE
WaffleBot isn't moving issues when referenced in branch names

### ISSUE THREAD

**Issue by kellihsf** [waffleio/waffle.io#3219]

**Comment by sfitts** [comment]
Not sure if this is related, but it also has stopped moving cards into "needs review" when a PR is created that references the issue (the PR gets "stacked" with the issue, but they don't move).

**Comment by kellihsf** [comment]
Hi @sfitts, yes this is related if you're using the "close" keywords to automatically move cards when the PR is merged. The "connect" keywords will not move the PR + issue when the PR is merged.
