### ISSUE TITLE
Allow creating a card without an issue nor repository

### ISSUE THREAD

**Issue by johnnywell** [waffleio/waffle.io#3220]
Here at @Snowmanlabs we are using @waffleio to manage multi repository boards and It would be great if we could create a card, then after defining which repository suits it better turn this card into an issue on that repository.

Currently, we use a repository to allow our customers to create cards that will be later replicated on another repository after further validation of scope and priority.

But, since we are a company with multiple clients and projects it will soon get out of control.

**Comment by harkenn** [comment]
The desired functionality of this would also be accomplished by providing a means in waffle.io to change the repository of an issue (behind the scenes you would actually be closing the old issue and creating a new issue in the new repository). We at @2020IP run into this frequently as issues are either mistakenly created in the wrong repository or - more likely - an issue thought to be in one place is found to actually be a defect in some other place.

Doing this would obviously have caveats. There would be no way to replicate comment ownership or anything like that. When creating the new issue, you might collect all the previous comments and boil them down into a single, author-amended comment?

Alternatively you could simply cover all the bases by saying "duplicating everything is too hard, we'll close the old, create the new (maintaining only the original issue's text) and link them together using GitHub's cross-repo linking pattern.

**Comment by AnaMSteele** [comment]
We are moving towards having other connections appearing on a Waffle board. For example a card showing work to be done from another system aside from GH. We are still researching what this means. Likely we will not arrive at having a card in Waffle that has no connection to any other tool. We are open to your perspective, but at this point we are closing this card as it's not in our near term roadmap.
