### ISSUE TITLE
Clearing milestone changes clears issue text display

### ISSUE THREAD

**Issue by harkenn** [waffleio/waffle.io#3223]
The change doesn't actually persist, if you close the card and re-open it the issue text is still there.

![5463ae7a-ef27-413d-b582-2f8aeed4f963](https://user-images.githubusercontent.com/231052/28828545-af49ac1e-7696-11e7-8fb9-7d806803fdf2.gif)

**Comment by marydavis** [comment]
@harkenn should be fixed now :) thanks for reporting it!
