### ISSUE TITLE
How to delete all Waffle.io webhooks 

### ISSUE THREAD

**Issue by nikitavoloboev** [waffleio/waffle.io#3225]
Unfortunately I had to move away from Waffle.io to use another service however I want to completely remove Waffle.io integration. I deleted it from my authorised apps however each of my repositories still has Waffle.io webhook : 

![2017-08-04 at 03 41](https://user-images.githubusercontent.com/6391776/28950752-c5c810ac-78c6-11e7-9274-1b97963c58e6.png)
 

Is it possible to remove all of them. Going to each repository and removing each webook manually is super annoying.

Thank you for any help.

**Comment by homeyer** [comment]
If you delete the projects in Waffle we'll remove the webhook. Since you already unauthorized Waffle that won't work, you'll need to manually remove each, sorry!
