### ISSUE TITLE
performance issues introduced with angular upgrade

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#3237]

**Comment by homeyer** [comment]
I'm not able to repro it on a board without many cards, but on a board with a lot-o cards it's super obvious.

**Comment by homeyer** [comment]
A suggestion:
- Figure out how to measure the # digest cycles, or whatever other metric makes more sense for AngularJS performance, or general browser performance.
- Go back in time (git checkout) and see if we introduced something recently that made this worse.

**Comment by homeyer** [comment]
feels like the add issue title field is lagging too, so maybe not specific to the detail modal.

**Comment by lamille** [comment]
https://stackoverflow.com/questions/23066422/how-do-i-measure-the-performance-of-my-angularjs-apps-digest-cycle
