### ISSUE TITLE
Allow multiple filter criteria of a single type

### ISSUE THREAD

**Issue by diemer** [waffleio/waffle.io#3239]
It would be wonderful if I could sort cards by multiple criteria of a single type, for example: I can look at all cards that are both unassigned *and* assigned to me so I can see all upcoming possible work in a single view.

**Comment by kellihsf** [comment]
hi @diemer,

We're tracking filtering by OR on issue [#1440](https://waffle.io/waffleio/waffle.io/cards/54208c21d613f614d446694a). We'll close this one as a duplicate, but feel free to upvote on the other issue. :)
