### ISSUE TITLE
Hide organisation name

### ISSUE THREAD

**Issue by umarniz** [waffleio/waffle.io#3240]
We have a over 20 character organisation name and it gets super annoying to have that everywhere in all repos, project boards and issues.

Can you introduce an option to hide it?

**Comment by homeyer** [comment]
You can customize the display name for repositories in your project settings!

Click the pencil icon to edit it: 
![image](https://user-images.githubusercontent.com/84629/29178448-d7f90c94-7dae-11e7-8e8f-44ab03ea35c5.png)
