### ISSUE TITLE
Drag-and-drop into a collapsed column

### ISSUE THREAD

**Issue by kylegach** [waffleio/waffle.io#3263]
I keep the right-most column collapsed 90% of the time. It would be rad if I could drag-and-drop from another column into that one when it is collapsed, to avoid having to expand it first.

**Comment by kellihsf** [comment]
Hi @kylegach,

We haven't seen any activity on this card since it was opened from the rest of the Waffle user base. We are closing it for now as we prioritize and work on other more highly requested features/integrations. 

PS: wanna join us for a week and get this done? 😜

**Comment by kylegach** [comment]
Ha. Thanks for the offer, but if no one else has requested it, I'd hate to add complexity just for my benefit.
