### ISSUE TITLE
⚡️ highlight wafflebot if reinstall required

### ISSUE THREAD

**Issue by BAMason** [waffleio/waffle.io#3267]
AC:
- associate an installation to an account, so the board UI can know whether wafflebot is installed or not
- based on the date when GitHub changed permissions (see https://github.com/waffleio/waffle.io-app/blob/master/scripts/find-old-wafflebots.js), make the lightning bolt red, and change the CTA in the popover to be about upgrading.
- if wafflebot is installed and happy, don't show the wafflebot icon. Add a section under general in settings to say that waffle bot is installed.

**Comment by marydavis** [comment]
was thinking something like this would be better than making the icon red:
![Screen Shot 2017-09-12 at 10.51.01 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/53724c88ebef97b1f959cc15/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b772a6455f16b7191a379ef0c2e50415f4fbc30254d58eeb9cb74fce36f34985619e8d3385f70c76e47f9b8861aed09eb73884ad3e3b88c4ec0fa2137a5dad11b61435c52dcbd4f3fb29843c259f34be44f57a31b3f66e471356e0a.png)
