### ISSUE TITLE
Esc key is not excluded from key pressed events

### ISSUE THREAD

**Issue by burnhamrobertp** [waffleio/waffle.io#3274]
You can see this behavior pretty much anywhere in waffle. Tab around between stuff and hit the `esc` key and if you're on an element capable of interaction, that interaction will be triggered. The escape key should not be bound to the same behaviors as non-escape keys. The keycode of esc (27) should be excluded from these interactions. Esc should absolutely still close the modal!

**Comment by marydavis** [comment]
@burnhamrobertp thanks for opening an issue, just want to make sure i understand the problem :) currently, if you press esc in an input it will de-focus or if you have a dropdown open it will close - are those the things you would not expect to happen? if that is not what you are referencing can you give me an example? thanks!

**Comment by burnhamrobertp** [comment]
The modal behavior is normal. I do not see the same behavior when focussed on certain inputs

When applying a lable, for example, you an click on "labels" and search for a label. Then hit "enter" to select the top most filtered label and apply it. The focus is still on the input but `esc` won't do anything. If you hit "tab" then your focus is now on the next gear and hitting `esc` only causes its menu (milestones) to open up

**Comment by marydavis** [comment]
@burnhamrobertp thanks for the detailed response, it helped us find the problem. Should be fixed soon :)
