### ISSUE TITLE
make board work with closed columns

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#3280]
Add a column in the db, after the done column, set to `isClosed` and with a label.

AC:
- [x] cards are closed when dragged into it
- [x] cards are assigned the label when dragged into it
- [x] closed cards are still auto moved to Done, not to the labelled column
- [x] archives isClosed columns independently
- [x] addNew column select drop down removes all isClosed columns

**Comment by marydavis** [comment]
when did this AC change, archiving is on #3276

**Comment by BAMason** [comment]
when andrew and I added it.  didn't think it would impact you since we assumed you were only touching setting pages.
