### ISSUE TITLE
scope how multiple done columns will work

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#3281]
- how do we want this to work ourselves?
- what are users asking for? look at card with 70+ comments
- consider different column targets based on what type of "done" it is: "closing" goes to done done, "merging" goes somewhere else, etc.
- what about merging into a non-default branch?

**Comment by marydavis** [comment]
https://docs.google.com/document/d/1vuegSfchnV2cdPrFFJ7WyAsqZGh4LbrInSHUJBXiQTM/edit
