### ISSUE TITLE
Move issues in bulk from one milestone to the next

### ISSUE THREAD

**Issue by tiendatiowa** [waffleio/waffle.io#3282]
At the end of a milestone, I'd like to move all of the pending issues to the next milestone, and moving one by one is very time consuming (when you have 100+ items to move). It'd be extremely helpful if I can select multiple cards and move them all to the next milestone.

**Comment by piedup** [comment]
We're considering moving to waffle and this would really be helpful.

**Comment by AnaMSteele** [comment]
tracking a single issue for all bulk issue action requests here #3629. closing this in favor of tracking all the requests in aggregate. please comment and upvote on the new issue to help us prioritize.
