### ISSUE TITLE
remove badge banner - move to share popover

### ISSUE THREAD

**Issue by marydavis** [waffleio/waffle.io#3284]
- [x] Remove badge banner
- [x] Move badge pull request to share popover
- [ ] ~~Show notification dot if not opened share popover in 3 days~~
- [ ] ~~Hide dot after opening per project not user, don’t show again~~
(see #3298 for the notification work)

see dot images here: https://docs.google.com/document/d/1cbbQPN7lkl2FQayBth0wLxLg2xRuZrXefoeWuVnt1Xk/edit

**Comment by homeyer** [comment]
use a user preference, with the project in the name so it's per project, to remember if the share popover is opened.

**Comment by marydavis** [comment]
Maybe something like this? Then have the badge and then text and button for sending pull request. maybe text or tooltip that can copy badge from settings page?

![Screen Shot 2017-09-18 at 3.18.17 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/53724c88ebef97b1f959cc15/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b772a6455fb6b7191a37bf113234f5e585ecc3c4a4356bcbbd671f3e57862804e0eef846d5b75956b44acbc874db750e9238e19d0b2ba884cd2f42f67b6d5db1063474f4dcbed5727a19e41c95df64ee64b56a4133465e6712431.png)
