### ISSUE TITLE
fix current badge

### ISSUE THREAD

**Issue by marydavis** [waffleio/waffle.io#3285]
- [x] right side default color #FFA700
- [x] ~default to 'to do' label for now~ : in progress instead
- [x] fix styling to match shields
- [x] Update general settings badge instructions
- [x] ~update help docs~ created a card
- [x] make sure existing badges don't break (default of "Ready" label)

**Comment by homeyer** [comment]
make it look like this, but with only the one column 
![image](https://user-images.githubusercontent.com/84629/30554373-8f928bac-9c61-11e7-80ec-d63067b566ce.png)
