### ISSUE TITLE
Windows 10 Chrome struggling with detail modal

### ISSUE THREAD

**Issue by Alisuehobbs** [waffleio/waffle.io#3289]
![image](https://user-images.githubusercontent.com/20324499/30562023-53d37fae-9c7a-11e7-9a4f-ea151422c3fb.png)

**Comment by Alisuehobbs** [comment]
https://waffle.io/rualark/MGen/cards/59bd8b102f2d0600d987c8d8

**Comment by marydavis** [comment]
haven't seen this issue arise since opened, will re-open if issue resurfaces
