### ISSUE TITLE
update help docs for new badge styles

### ISSUE THREAD

**Issue by marydavis** [waffleio/waffle.io#3294]

**Comment by Alisuehobbs** [comment]
badges will now only use params after `?label` or `?column`. in other words, title is no longer used

**Comment by kellihsf** [comment]
https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/educate/articles/122282/edit

**Comment by kellihsf** [comment]
https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/educate/articles/122282/show

https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/educate/articles/1246594/show
