### ISSUE TITLE
Milestone value is not properly encoded

### ISSUE THREAD

**Issue by haynar** [waffleio/waffle.io#3297]
Milestone values are not properly URL-encoded. Looks like you're using `encodeURI` method instead of `encodeURIComponent`.

So as a result the milestone value `Week of Sep 18, 2017` becomes `Week%20of%20Sep%2018,%202017` (note that `,` is not encoded) which makes the page interpret those incorrectly when refreshed so it is converted to `none,none` as no matching milestones found.

Instead you probably should be using `encodeURIComponent` method, which would return `Week%20of%20Sep%2018%2C%202017` so it can be safely used in the URL as a parameter.

**Comment by haynar** [comment]
@homeyer is there any chance this issue can be addressed sometime soon? 

It is really annoying and in fact it prevents sharing/bookmarking links that contain specific milestone values like in the example above.

**Comment by marydavis** [comment]
@haynar working on it now, will let you know as soon as it is fixed :)

**Comment by haynar** [comment]
@marydavis thanks a lot for looking into this. Looking forward to get this fixed :)

**Comment by marydavis** [comment]
@haynar unfortunately it wasn't as simple as originally thought but should be all good now :)

**Comment by haynar** [comment]
@marydavis thanks, I can confirm that it is now fixed.
