### ISSUE TITLE
notify new projects of badge after a few days

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#3298]
wait until #3288 is done

Let's just send an intercom message, 3 days after a project is created to suggest adding the badge.

Not doing all this:
- [ ] dot on share icon after 3 days: https://docs.google.com/document/d/1cbbQPN7lkl2FQayBth0wLxLg2xRuZrXefoeWuVnt1Xk/edit
- [ ] remove dot after they click it, based on a user preference tied to the project
- [ ] send auto intercom in-app message at the same time to tie them together

**Comment by marydavis** [comment]
so only intercom, not email is that right? also, do we have other messages they are getting too, just want to make sure we aren't overloading ppl with messages.

**Comment by kellihsf** [comment]
correct, only in intercom. we updated the messages recently, so right now there aren't any messages going out when a users first creates a board.

**Comment by kellihsf** [comment]
draft: https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/engage/messages/auto/149228818
