### ISSUE TITLE
fix LabelDropdownMenu closes label menu when close button is clicked in Phantomjs

### ISSUE THREAD

**Issue by Alisuehobbs** [waffleio/waffle.io#3299]
`LabelDropdownMenu closes label menu when close button is clicked`test works in Chrome, but not Phantomjs

**Comment by BAMason** [comment]
test broke with [this commit](https://github.com/waffleio/waffle.io-app/commit/fd49a7af314f69a1542f141aa5543fb619ee1b79) and error `undefined is not an object (evaluating 'context.createDocumentFragment')` at line 85
