### ISSUE TITLE
🏗 Epics

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#3316]
Organize work under a common Epic issue!

Why epics, when we have milestones? Teams often use milestones for timeboxed activities, like sprints or planned releases/launches. 
GitHub's ability to organize work is limited by only allowing an issue to belong to one milestone. Epics will enable teams to group work in a more flexible way.

child of https://rally1.rallydev.com/#/28451149440d/detail/portfolioitem/feature/210195034624

**Comment by openbaringen** [comment]
Just wanted to add my 2 cents to this. Epics is much needed, but I believe they should be separate from a specific code project. Implementing stories might also make sense. Because sometimes you have a story that is implemented in 2 code bases.

**Comment by freeformz** [comment]
Whatever is done here, it needs to be able to span multiple repositories to be useful to us. We use milestones like Epics at this point since they span repositories and Waffle will auto-create them for us if they don't exist in the repo.

**Comment by PLaRoche** [comment]
Suggestions on Epic implementation:

**Comment by PLaRoche** [comment]
@homeyer as someone who is actively looking at other tools, I noticed this just went to in prog.....  Can you share a sense of timeline ?

**Comment by homeyer** [comment]
@PLaRoche this month!

**Comment by PLaRoche** [comment]
@homeyer OH YES!

Can you share any early "this is what it will look like" details???? So excite

**Comment by homeyer** [comment]
Here's an early mockup:

![image](https://user-images.githubusercontent.com/84629/35688803-41f37e54-072f-11e8-8cf2-36baaae6ba9b.png)

The icons and text have changed since then, but the spirit is the same!

**Comment by uerceg** [comment]
@homeyer That month has passed. :) Any updates on ETA for this feature? Cheers!

**Comment by homeyer** [comment]
Hit a few hiccups, but we're still focused on this and shipping soon!

**Comment by fernandocalsa** [comment]
@homeyer in that screenshot I see that issue `#198` is part of the Epic `#438` but also that is blocked by `#233`. Is this `block by` part of #1996?

**Comment by AnaMSteele** [comment]
@PLaRoche and @uerceg  we are starting the beta testing this week. Any interest in getting an early look at it in return for doing a feedback session with our team live?

**Comment by fernandocalsa** [comment]
We are always keen to test this kind of things, we usually have issues where this feature would be helpful

**Comment by AnaMSteele** [comment]
@fernandocalsa I will find and message you from within Waffle and we can get you set up as a beta tester

**Comment by bulldetektor** [comment]
@AnaMSteele Yes, we'd like to test i out :)

**Comment by AnaMSteele** [comment]
@bulldetektor mind messaging me directly at ana@waffle.io with the name of your project in Waffle? we can talk through logistics and see if you can make the feedback session for beta testers scheduled for next Tuesday morning.

**Comment by AnaMSteele** [comment]
Oh and yes! cross-repo references are a part of epics in Waffle

**Comment by kellihsf** [comment]
hi @luisherranz,

You'll need to use the wording: "parent of username/repo#12" within the issue's title or description. Also, the other repo must be connected on the same board. 

Read more here: [Waffle Help Docs](https://help.waffle.io/epics/can-i-have-issues-from-other-repos-in-my-epic) or email us at support@waffle.io to chat!

**Comment by luisherranz** [comment]
Awesome, thank you! @kellihsf

**Comment by andybergon** [comment]
When will this be available for Waffle Takeout? :)

**Comment by AnaMSteele** [comment]
Hi @andybergon our team has this work planned. We will be launching Epics in Takeout in a couple weeks, so we can include some of the enhancements we have already heard requested by other users.

**Comment by homeyer** [comment]
Tracking shipping Epics to Takeout here: https://github.com/waffleio/waffle.io-takeout/issues/259
