### ISSUE TITLE
Make Slack integration auto-link to Waffle cards

### ISSUE THREAD

**Issue by alastairs** [waffleio/waffle.io#3317]
I have no idea if this is possible, but it would be fantastic if typed references like "#472" could be auto-converted to a link to the appropriate Waffle card on our board, ideally with the card preview attached ot the message too.

child of #3652

**Comment by homeyer** [comment]
Oh cool. We can unfurl waffle urls right now, but not generic github id references. If #123 referenced multiple issues across your org's repos, would it be ok to unfurl both?

**Comment by alastairs** [comment]
Ideally, I think it would:

- unfurl an open issue in repo A over a closed one in repo B
- prompt to choose in case of ‘conflict’

There are probably other heuristics that could be applied too.

**Comment by AnaMSteele** [comment]
Closing this issue, as we track aggregated requests around improvements to our slack integration on #3353.
