### ISSUE TITLE
Unable to get account info

### ISSUE THREAD

**Issue by gmangesh77** [waffleio/waffle.io#3326]
I am unable to create project, even if I have granted permission of github account. It keeps on loading when I try to create project from the existing repo.

Also when I click on Profile menu option then it show below error:
Unable to get account info for gmangesh77.

Thanks,
Mangesh

**Comment by kellihsf** [comment]
hi @gmangesh77,

Can you let us know the name of the repo you're trying to create a project for? Feel free to reply here on the issue, email us at support@waffle.io, or click the ? icon on your board to chat with us.

Thanks!

**Comment by gmangesh77** [comment]
Our test repo is here:
https://github.com/FireBrickGroup/oak-import-job

**Comment by kellihsf** [comment]
We see that you do have the correct access to that repo on our end. Do you see the board on your Dashboard? To get to your Dashboard, click the waffle icon in the top left corner. Here, you should see all repos you have access to that boards have been created for.

**Comment by gmangesh77** [comment]
I don't see any board on my dashboard. It says loading projects and shows nothing. 
Regards, Mangesh 


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Kelli Stone <notifications@github.com> Date: 11/17/17  10:31 PM  (GMT+05:30) To: "waffleio/waffle.io" <waffle.io@noreply.github.com> Cc: Mangesh <mangesh@signitysolutions.com>, Mention <mention@noreply.github.com> Subject: Re: [waffleio/waffle.io] Unable to get account info (#3326) 
We see that you do have the correct access to that repo on our end. Do you see the board on your Dashboard? To get to your Dashboard, click the waffle icon in the top left corner. Here, you should see all repos you have access to that boards have been created for.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/waffleio/waffle.io","title":"waffleio/waffle.io","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/waffleio/waffle.io"}},"updates":{"snippets":[{"icon":"PERSON","message":"@kellihsf in #3326: We see that you do have the correct access to that repo on our end. Do you see the board on your Dashboard? To get to your Dashboard, click the waffle icon in the top left corner. Here, you should see all repos you have access to that boards have been created for."}],"action":{"name":"View Issue","url":"https://github.com/waffleio/waffle.io/issues/3326#issuecomment-345301852"}}}

**Comment by kellihsf** [comment]
Do you see any errors in the dev console when trying to load Waffle?

Also, what happens when you go here?:  waffle.io/FireBrickGroup/oak-import-job

**Comment by gmangesh77** [comment]
It's working fine now. 
Thanks, Mangesh 


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Kelli Stone <notifications@github.com> Date: 11/21/17  10:30 PM  (GMT+05:30) To: "waffleio/waffle.io" <waffle.io@noreply.github.com> Cc: Mangesh <mangesh@signitysolutions.com>, Mention <mention@noreply.github.com> Subject: Re: [waffleio/waffle.io] Unable to get account info (#3326) 
Do you see any errors in the dev console when trying to load Waffle?
Also, what happens when you go here?:  waffle.io/FireBrickGroup/oak-import-job

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/waffleio/waffle.io","title":"waffleio/waffle.io","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/waffleio/waffle.io"}},"updates":{"snippets":[{"icon":"PERSON","message":"@kellihsf in #3326: Do you see any errors in the dev console when trying to load Waffle?\n\nAlso, what happens when you go here?:  waffle.io/FireBrickGroup/oak-import-job"}],"action":{"name":"View Issue","url":"https://github.com/waffleio/waffle.io/issues/3326#issuecomment-346092308"}}}

**Comment by kellihsf** [comment]
Great, thanks for letting me know!
