### ISSUE TITLE
I can't add a repo to waffle bot

### ISSUE THREAD

**Issue by freeformz** [waffleio/waffle.io#3327]
We have a lot of repos in our organization. One is named "x". We install wafflebot via "Only select repositories" and I can't seem to add the "x" repository or "orgname/x". Github's matching only returns 10 suggestions to pick from and apparently there are > 10 other repos with the letter "x" in them. I realize that this maybe a github issue, but it happens when using their ui to install Wafflebot on a subset of repos.

**Comment by kellihsf** [comment]
hi @freeformz,

This is an issue on GitHub's side. We recommend that you contact them to see if they're able to resolve this: ![GitHub contact here](https://github.com/contact). Thanks!
