### ISSUE TITLE
Allow repos to have default label filter

### ISSUE THREAD

**Issue by freeformz** [waffleio/waffle.io#3328]
child #3651
We work on multiples shared code bases as well as ones that we alone work on.

I need to *always* apply a label filter to our board to see the issues that are relevant to us.

This is a PITA.

I'd like to be able to associate a default label filter to a repo for a given board. This would have two effects.

1. When viewing the board, issues from that repo will have this filter automatically applied to them (in addition to any filters applied to the board). This will just make our teams day to day life easier.
2. When opening issues against that repo, via our waffle board, the labels in the filter should be automatically applied to the new issue.

**Comment by AnaMSteele** [comment]
@freeformz we are tracking a larger body of filtering work. We have saved filters as a feature request #3575 that we feel would likely address the use case you are describing as well. Mind taking a look at that card and adding your thoughts there? We will close this card in favor of tracking this body of work related to epic #3651. Thank you.
