### ISSUE TITLE
"User Assigned" Event -> move from "backlog" to "next"

### ISSUE THREAD

**Issue by the-vampiire** [waffleio/waffle.io#3329]
Our team replaced "backlog" with "unassigned" and "next" to "assigned" where the following column ("in progress") signifies a branch / commit associated with the milestone has been pushed.

New Functionality:
- event listener for "on assign" github issue event
- moves the "unassigned" card to "assigned"
Into Current Functionality:
- "assigned" card moves to "in progress" when a branch / commit is pushed
- "in progress" moves to "in review" during PR review
- "in review" moves to "completed / done" when the PR is merged or closed 

Workflow View:
![Uploading Screen Shot 2017-11-18 at 11.33.32 PM.png…]()

**Comment by AnaMSteele** [comment]
Duplicate. Closing this card, please upvote #1876. Thank you!
