### ISSUE TITLE
create blog post for move to top/move to bottom shortcuts

### ISSUE THREAD

**Issue by kellihsf** [waffleio/waffle.io#3335]

**Comment by kellihsf** [comment]
draft: https://medium.com/p/e092d29987ad/edit

**Comment by marydavis** [comment]
haha, i love the "its a drag" comment :)

**Comment by homeyer** [comment]
looks good! If you want, spell out numbers under ten #grammarpolice https://www.grammarly.com/blog/when-to-spell-out-numbers/
