### ISSUE TITLE
Internal Server Error when fetching cards

### ISSUE THREAD

**Issue by sangaline** [waffleio/waffle.io#3338]
The XHR call to `https://api.waffle.io/sangaline/{{project-name}}/cards` has been consistently returning a 500 server error for the last few days. The UI displays the following error

![image](https://user-images.githubusercontent.com/8236564/33565800-1f748876-d8ec-11e7-8e59-ad978b088f3f.png)

and the cards aren't populated.

**Comment by homeyer** [comment]
@sangaline oh no! Which project are you loading it for?

**Comment by sangaline** [comment]
The project is `evandre-docs`.

**Comment by homeyer** [comment]
Looking into it, thanks!

**Comment by kellihsf** [comment]
@sangaline We've made an update on your account, can you try loading your board again?

**Comment by sangaline** [comment]
It works again, thanks!
