### ISSUE TITLE
blog post about emojis in column names

### ISSUE THREAD

**Issue by kellihsf** [waffleio/waffle.io#3339]

**Comment by kellihsf** [comment]
https://medium.com/p/afcc51e05653/edit

**Comment by homeyer** [comment]
`Control + Command + Space bar` is a mac thing, not Chrome :)

**Comment by kellihsf** [comment]
lol I was mid-changing it when you commented!

**Comment by homeyer** [comment]
looks good to me! we can 🎁 deliver all the posts tomorrow, want to save this one for when things get slow?

**Comment by kellihsf** [comment]
👍

**Comment by BenjAzko** [comment]
Not working on Windows/Chrome ... "Command" key doesn't exists on windows,.. and "CTRL + WINDOWS + SPACE" doesn't work.
