### ISSUE TITLE
Support renaming GitHub repositories

### ISSUE THREAD

**Issue by cbeams** [waffleio/waffle.io#334]
Repro:

1. create a repo 'foo'
1. set up waffle issue tracking for that repo, e.g. https://waffle.io/ghuser/foo
1. add a custom column called "Ideas"
1. rename "foo" via the GH interface to "bar"
1. refresh https://waffle.io/ghuser/foo, notice 'not found' message
1. set up waffle issue tracking for newly-renamed "bar" repo, e.g. https://waffle.io/ghuser/bar
1. notice that the custom "Ideas" column is now gone.

Workaround:

Re-add custom columns etc. At least any labels created before the rename will persist, so it's not too hard to sync everything back up, but not pleasant, either.

**Comment by ashumz** [comment]
[+1](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/712332030)

**Comment by adamralph** [comment]
:+1: Having to recreate the Waffle board after renaming a GitHub repo is a real pain...

**Comment by moezubair** [comment]
+1

**Comment by edweip3** [comment]
just tested this. and it seem to pickup renames now.  can someone else confirm?

**Comment by homeyer** [comment]
Yep, it landed a few weeks ago with https://github.com/waffleio/waffle.io/issues/2014. We didn't catch that we had multiple issues tracking it. Closing this one now! :)
