### ISSUE TITLE
Add days of the week to the milestone board. Also, have an option for not showing weekends on there as well.

### ISSUE THREAD

**Issue by pbullion** [waffleio/waffle.io#3347]

**Comment by schwern** [comment]
👍 Particularly the option to ignore weekends (or any days of the week, or particular dates for holidays). Assuming we work weekends makes the glide path too shallow on a 2 week sprint.

**Comment by AnaMSteele** [comment]
We are closing this card in favor of tracking all the request for updates to metrics and tracking in Waffle on this [card](https://waffle.io/waffleio/waffle.io/cards/53f27af882b317f7d9adafa2).
