### ISSUE TITLE
Pseudo adding repo... Read Only Repo

### ISSUE THREAD

**Issue by shadowcodex** [waffleio/waffle.io#3348]
So my understanding is this. In order to attach/connect a PR to an issue card on a waffle board both the repo with the issue card and the repo with the PR have to be added to the waffle board.

However I don't want users being able to open issues on the extra repo's from waffle. I'd like to add a read only repo to the waffleboard. So it can do the following things.

- See's PR and Information on repo
- Allows for comment on PR
- Does not import issues
- Does not allow issue creation

Is this possible atm?

**Comment by homeyer** [comment]
Some of this works by setting up GitHub permissions, e.g. someone with pull only permissions on a repo can't move cards around. But, they would still be able to open issues.

But true read-only: no, not yet. 

Is this for a private repo, where you want stakeholders to be able to see but not touch? Or keeping an eye on an open source repo your team depends on but doesn't contribute to?

**Comment by shadowcodex** [comment]
This is for a repo that will go public eventually. We already had an issue
with people putting something private on a public repo issue because they
clicked create issue on the wrong repo in waffle interface. I want to
prevent the opportunity for those kinds of errors by disallowing issue
create through waffle interface for certain repos.

**Comment by homeyer** [comment]
Would a warning in the "add issue" menu help, when you're creating a new issue in a public repo on a board that has private repos too?

**Comment by shadowcodex** [comment]
Maybe. It would have to be really obvious 😂. A board defaults to the repo
it is setup against first right?

My thought was a switch in settings that would allow you to turn off or on
issue creation per repo. Imo that’s more elegant.

A warning is nice too, but it should have a switch in settings to turn on
that warning and have it off by default.

**Comment by AnaMSteele** [comment]
@shadowcodex this is an interesting use case. This request hasn't seen any activity from the rest of the Waffle user base, so we are closing for now as we don't see if happening within our short term roadmap.
