### ISSUE TITLE
make improbability drive board a good demo environment

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#3366]

**Comment by homeyer** [comment]
https://waffle.io/waffleio/infinite-improbability-drive

**Comment by burtonjc** [comment]
The one deployment on that board is a fun name, but I don't think I would understand what it is. It would be nice if it was a more expected deployment name (ex. "testing", "staging", "production"). I don't think, as a new user, I would know that waffle supported deployments by looking at that board.

**Comment by burtonjc** [comment]
Could be nice to have some sizes also.
