### ISSUE TITLE
Fix pusher configuration in staging environments

### ISSUE THREAD

**Issue by burtonjc** [waffleio/waffle.io#3373]
Currently, staging3 uses the dev pusher app. Either, we should make sure all the staging environments are using the staging pusher app, or we should delete the staging pusher app and use the dev app for all the staging environments.

AC:
- [x] pusher apps are consistent across waffle staging environments.

**Comment by jtslear** [comment]
Fixed staging3 to use the existing waffle.io-staging pusher application.  Deleted the waffle.io-staging2 application as it was not utilized.  I restarted all pods in staging3 to pick up the new configuration.  Replaced the secret in kubernetes as well as 1password.
