### ISSUE TITLE
bar-stripes css animation gobbles CPU

### ISSUE THREAD

**Issue by RShergold** [waffleio/waffle.io#3374]
For some reason the bar-stripes css animation at `.status-bar .pending:after` kills my cpu

[animation.mp4.zip](https://github.com/waffleio/waffle.io/files/1682761/animation.mp4.zip)

Using Chrome 63.0.3239.132  on a Mac

**Comment by marydavis** [comment]
we also need to account for status bars that don't finish and are stuck at pending
