### ISSUE TITLE
UI is not updating when assigning a new milestone to a card from within Waffle

### ISSUE THREAD

**Issue by burtonjc** [waffleio/waffle.io#3386]

**Comment by shadowcodex** [comment]
yeah this is pretty hard to keep track of things when you are updating items from last sprint to be added to the new sprint (such as like 45 commitments that were not met)

**Comment by adamzolyak** [comment]
@burtonjc @shadowcodex I just tested the following cases.  Both results in the milestone being updated on the card on my Waffle board in real-time.  

1. Open existing issue, create new milestone, close card, view card on board with milestone assigned
2. Open existing issue, assign existing milestone, close card, view card on board with milestone assigned

Can you try to repro and if you can - provide more info?
