### ISSUE TITLE
Project templates (pre-defined work flow/columns)

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#339]
Requested by @highvoltage

Templates for creating issues with predefined content, or something else? Can you give us an example?

**Comment by ginfuru** [comment]
:+1:  It would be nice to have pre-defined issues along with the pre-defined boards.

**Comment by mc706** [comment]
+1

**Comment by laughedelic** [comment]
+1

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
