### ISSUE TITLE
Filter shortcuts for assignees, labels, and milestones

### ISSUE THREAD

**Issue by scottmmjackson** [waffleio/waffle.io#3391]
As a team that makes heavy use of these features, it helps a lot if I can filter a label (or, more rarely, assignee or milestone) with the same short keystroke as I'd use the search filter.

It might also help to have a keybinding for clearing those filters. Suggestion below (uppercase for clarity, shift not implied):

`L+/` - open label filter search box
`L+X` - clear label filter
`A+/` - open assignee filter search box
`A+X` - clear assignee filter
`M+/` - open milestone filter search box
`M+X` - clear milestone filter

Another thing to think about would be "completing the look" and adding keybindings for the rest of the features:

`x+x` - expand connected PRs
`p+p` - PRs only
`p+i` - PRs & Issues
`i+i` - issues only

**Comment by AnaMSteele** [comment]
We actually think this is a great idea, but since we haven't seen a lot of activity or upvotes on this card we are going to go ahead and close it. We are open to revisiting this if we see more traction or requests, but at this point we don't see it on the short term roadmap, and wanted to be transparent.

**Comment by scottmmjackson** [comment]
Wait, how does one upvote a card?

**Comment by kellihsf** [comment]
<img width="324" alt="screen shot 2018-08-24 at 1 37 42 pm" src="https://user-images.githubusercontent.com/4775572/44604367-ebf45900-a7a2-11e8-94e9-f221ef89ac75.png">


If you look in the top right corner of a comment on an issue in GitHub, you'll see that option ^ unless it already has a reaction you'll see this in the bottom left corner of the comment:

<img width="154" alt="screen shot 2018-08-24 at 1 38 51 pm" src="https://user-images.githubusercontent.com/4775572/44604420-13e3bc80-a7a3-11e8-8dc6-02fc421df648.png">

**Comment by scottmmjackson** [comment]
I see; it wasn't clear to me until it was brought up that reactions were meaningful.

Last question: Is there any kind of entrypoint for userscript keybindings to be created? Any place to shim that would give us access to waffle's redux store as well? That way we could do these modifications ourselves.

**Comment by AnaMSteele** [comment]
Hi @scottmmjackson at this point, the answer is unfortunately no to your last question. We are however looking at some other work that may improve filtering usability. More to come on that as we work on validating across the Waffle user base.
