### ISSUE TITLE
Add Ana to about page

### ISSUE THREAD

**Issue by kellihsf** [waffleio/waffle.io#3397]

**Comment by homeyer** [comment]
![image](https://user-images.githubusercontent.com/84629/36677273-bc021be6-1adb-11e8-9259-f9417a4c7f1e.png)

**Comment by homeyer** [comment]
![ana](https://user-images.githubusercontent.com/84629/36911848-190f1c7a-1e02-11e8-8862-a86561bf48f5.png)
