### ISSUE TITLE
Render emojis in labels

### ISSUE THREAD

**Issue by adamralph** [waffleio/waffle.io#3401]
[GitHub now supports emojis in labels](https://github.com/blog/2505-label-improvements-emoji-descriptions-and-more). 🎉 However, Waffle doesn't render them. 😢 That means that if I use them, I end up with a load of `:{emoji}:` in the labels in Waffle. 🤢 It would be ultra-awesome if Waffle rendered the emojis in label names. 🙏

**Comment by kellihsf** [comment]
confirmed that emojis in labels are not displaying in Windows, works on Mac

**Comment by adamzolyak** [comment]
Awesome!  One of the DevWeek NYC hackathon teams was running into this challenge.
