### ISSUE TITLE
migration/script to build parent/child relationships for existing cards

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#3403]
have a technical discussion about how to do this
child of waffleio/waffle.io#3316

**Comment by homeyer** [comment]
also need to clean up relationships after duplicate sources are removed

**Comment by homeyer** [comment]
what about deleting the syncedAt on sources? 😅

**Comment by BAMason** [comment]
After the technical discussion, we'll try the following solution:
1. Remove all existing relationships
2. Go project by project and
  a. Remove `lastSyncedAt` for `enabled` sources that don't have a `migrated` flag
  b. Add `migrated` flag to those
  c. Get credentials for user on this project with both GitHub & API tokens
  d. Hit the API `GET .../cards` endpoint to initiate the Sync process
3. Remove the `migrated` flag from all sources
