### ISSUE TITLE
filter by epics - requires #3463

### ISSUE THREAD

**Issue by marydavis** [waffleio/waffle.io#3409]
questions : 
is this a board filter where:
   show all epic cards only
   exclude all epic cards
or a toggle
or a filter that shows list of epic card titles like milestones

child of #3460

**Comment by Surgo** [comment]
Please support EPIC only here.

![screenshot 2018-04-19 18 53 18](https://user-images.githubusercontent.com/31176/38989806-024c3ec8-4413-11e8-9137-11322b874e82.png)

**Comment by kellihsf** [comment]
https://docs.google.com/document/d/1f0SNt8R2kZrD7lmI61-1_UvklEMolT8pM2qzTKptnY8/edit
