### ISSUE TITLE
investigate why cards are not staying in correct columns in "Closed" section

### ISSUE THREAD

**Issue by kellihsf** [waffleio/waffle.io#3410]
to reproduce: 

you have a few columns in the "closed" section that all have column labels, then the actual Done column is on the far right with no column label. If you try to drag an issue to one of the first columns, it will not stay there but will go to the "Done" column.

**Comment by homeyer** [comment]
oh weebee 
![image](https://user-images.githubusercontent.com/84629/37118820-b5d8ec98-2212-11e8-86bd-888ef591319b.png)
