### ISSUE TITLE
link to 'how to' on GH:E tab when adding sources goes to 404

### ISSUE THREAD

**Issue by marydavis** [waffleio/waffle.io#3418]
should the tab be removed, or reference takeout, or fix the article

**Comment by kellihsf** [comment]
this is the help doc it was linked to: https://help.waffle.io/waffle-takeout/github-enterprise-support-saas

it was moved back to a draft (I don't remember why), but I made the article live again for the time being

**Comment by marydavis** [comment]
that was the right one :)
