### ISSUE TITLE
suggest a "Deployed" column in board setup

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#3427]
- [x] add "Deployed" to advanced template, or a new template
- [x] in column body (like the done column) link to help docs to set up deploy columns
- [x] update help docs for deploy columns (@kellihsf copy from blog into doc)
- [x] make sure still CSS responsive

**Comment by homeyer** [comment]
add to advanced template, and if you have wrapping issues, consider removing an existing column

**Comment by kellihsf** [comment]
help doc draft: https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/articles/articles/1853904/show

^code is not pretty yet
