### ISSUE TITLE
Moving and pointing child issues of epics

### ISSUE THREAD

**Issue by awead** [waffleio/waffle.io#3431]
We're able to group tickets as children of epics, thanks to #3390.
<img width="243" alt="waffle" src="https://user-images.githubusercontent.com/312085/38505983-96b90d0a-3be6-11e8-9e5d-79cbe7e42b40.png">
However, the points for each child ticket isn't getting added up in the Ready column. Additionally, we don't seem to be able to move the child ticket out to In Progress. Is there a workflow pattern I'm missing here, or was this feature meant to be used in a different way?

**Comment by AnaMSteele** [comment]
@awead sounds great! I am the Waffle customer advocate here at Waffle, and coordinating beta testers. 

Mind e-mailing me at ana@waffle.io and I will get things moving on our side to get you access to the beta.
