### ISSUE TITLE
Time Zones and the Burndown Graph

### ISSUE THREAD

**Issue by schwern** [waffleio/waffle.io#3434]
Hi,

The Burndown Graph appears to be using UTC for the current time. It's 9:30pm April 11th here in Portland, Oregon, but the Burndown Graph shows well into April 12th.

We have people in US Pacific, US Central, and Central European Time, but we use US Eastern as a common time zone. We work odd hours. Having the burndown chart count what is done in a day too early is something I can account for, but it is inconvenient.

A setting for the project time zone would solve this for us.

Thank you.

**Comment by AnaMSteele** [comment]
We are tracking all graph requests in aggregate on #1327. Feel free to continue to comment and upvote this request there. Thank you.
