### ISSUE TITLE
Fix multiple js errors in console

### ISSUE THREAD

**Issue by nerrad** [waffleio/waffle.io#3443]
I noticed today that a pull request card (with an attached issue) didn't automatically move to the "done" column when it was merged and closed in github.  I don't know if its related but when I open the console after loading our waffle.io board that there's these errors:

![console screenshot](https://www.evernote.com/l/AANaNI8jVR5CaIqprVrOdycCPimjrQbqj4sB/image.png)

I'm happy to drill down further in the console if needed.

**Comment by homeyer** [comment]
Hey @nerrad, thanks! Would you mind sending us a note at support@waffle.io with your board URL? (or post it here if you're ok with that).

**Comment by nerrad** [comment]
https://waffle.io/eventespresso/event-espresso-core

**Comment by nerrad** [comment]
We're still evaluating the product.

**Comment by homeyer** [comment]
Root cause: there's a PR without a commit, so our handling of the graphql response in multiple places (e.g., `pullRequest.commits.nodes[0]`) fails because we assume a PR always has a commit.

Not sure how to reproduce that scenario, but it's still fixable.

**Comment by homeyer** [comment]
@nerrad we've deployed a fix for this issue, thanks for letting us know about it!
