### ISSUE TITLE
Hover to show details in metrics Burndown: Show date & count on hover. Show actual/ideal difference. Throughput: show actual number on bar on hover

### ISSUE THREAD

**Issue by schwern** [waffleio/waffle.io#3454]
Right now I have to eyeball how far off the glide path we are. Not a big deal, but it's extra work. "It looks like we're at about 22 or 23, and the glide path is at about 18 or 19..."

If on-hover we're told the date and count, for both the actual and ideal, that would be helpful.

Even better would be to also show the difference between the actual and the ideal both for the current datetime and where the mouse is hovering.

Thank you.

**Comment by kellihsf** [comment]
hi @schwern, 

Thanks for the request! Moving this to our Ideas column for others to +1 or comment on.

**Comment by Workshop2** [comment]
+1 for this feature

**Comment by AnaMSteele** [comment]
Moving these requests and comments to #1327 where we are tracking all metric enhancement requests. Please comment and upvote there to help our team prioritize. Thank you.
