### ISSUE TITLE
update marketing pages to include Epics & Dependencies

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#3456]
- [x] pricing page
- [x] in-app CTAs
- [x] features page
- [x] in-app account plans

requires #1996

**Comment by adamzolyak** [comment]
I'm also interested in a few other updates on the feature page (re https://waffleio.slack.com/archives/C08B8GY20/p1524585399000328).  Let's chat if you pull this card.

**Comment by adamzolyak** [comment]
related to https://github.com/waffleio/waffle.io-biz/issues/1429 (for cutsheets)

**Comment by marydavis** [comment]
should also add deployments while we are at it too :)

**Comment by adamzolyak** [comment]
Indeed.  We should prob add a help article for deployments, even if it mostly just links back to the blog post.

**Comment by marydavis** [comment]
requires #1996

**Comment by adamzolyak** [comment]
@AnaMSteele volunteered to help get content together today for a quick update for epics, dependencies, and deployments.  Adam will create another card for further A/B testing of feature page.  Adam can help on Tues if it's still outstanding.

**Comment by AnaMSteele** [comment]
Epics to organize your work
Easily create epic parent issues and track overall progress of children. 

Dependency tracking 
Visualize what items are blocking your work on both pull requests and issues. See those blockers update as work is moved to done. 

Track code into deployment
See what happens to work after code is complete with deployment badges.
