### ISSUE TITLE
Single sign-on (SSO) not required

### ISSUE THREAD

**Issue by beoliver** [waffleio/waffle.io#3468]
It is possible to view all issues related to repository that requires [Single sign-on](https://help.github.com/articles/about-authentication-with-saml-single-sign-on/) (SSO) without logging in via SSO. 

The git hub [page](https://help.github.com/articles/about-authentication-with-saml-single-sign-on/) on this states that 
> Note: Outside collaborators aren't required to have an external (SAML) identity to access an organization that uses SAML SSO.

So I am guessing that this means that by default this is expected behaviour? 

Is there any way to enforce SSO on waffle.io?

**Comment by homeyer** [comment]
Waffle respects GitHub's permission model and we rely on OAuth for authentication, so if a user can see issues in GitHub they'll be able to see them in Waffle as well.
