### ISSUE TITLE
ability to add Column before 'Inbox'

### ISSUE THREAD

**Issue by opinipm** [waffleio/waffle.io#3469]
we need to create a column that will be used for organizing a list of Big Epics, ideally the position will be on the Left of the board (like what Jira did) , but right now i cant create any column before 'Inbox' column :-?

**Comment by kellihsf** [comment]
hi @opinipm,

That's correct; Waffle doesn't allow columns before the Inbox section. You can however, move the Inbox column to the right, then add a different column it its old place.

**Comment by opinipm** [comment]
Hi @kellihsf  , how about if the option for "open issue without column label" setting is in the filter label on each columns, so user can be more flexible to arrange their columns  :D

**Comment by AnaMSteele** [comment]
See #1153 and #924.

**Comment by DayuGVM** [comment]
@AnaMSteele , yap i think that will solve this issue, its all about planning management

**Comment by AnaMSteele** [comment]
Awesome! We are consolidating those 2 cards and their combined comments together to help track this grouping of requested functionality overall. We are going to close this issue and moved its comments over as well and would appreciate upvotes and further comments on the consolidated planning/backlog management card which is #1153. Thanks!
