### ISSUE TITLE
MS Edge Small Window Unable to Login

### ISSUE THREAD

**Issue by jtslear** [waffleio/waffle.io#3470]
On MS Edge, with smaller screens (the font size is NOT adjusted, the zoom level is NOT adjusted) you literally cannot login.  The Enterprise link is on top of Login, and Login cannot be clicked.

**Comment by jtslear** [comment]
![MSEdge - Win10 [Running] 20180426.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/53adcd5c7953d2fd0f7215bc/125516c66e82c728ace21e0d46c5a7bf278586e9c2a9884aaa0ca0d41274327d270dad2c4dc5b178ee1a2b555d595cb053181d1ba6acda6fb4bc2e7588090be9d03e0921c63914feb0d34cbc04ec758f4987b6ae965e82b96371b8d6d6056b5c17129bfe5a3fa19c49cc5ff34de5445dac103071ab.png)

**Comment by homeyer** [comment]
why are you using edge

**Comment by AnaMSteele** [comment]
Closing as this issue as there has been no user requests for this to be prioritized and addressed. Thank you.

**Comment by kellihsf** [comment]
![burn.gif](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/56241220b728ed1d0009af87/125516c66e82c728ace21e0d46ea81882dc0cfeb9ffbb049a15ee4d6730472212c54f77a7383e678eb1779590e0c4da9170d5b42fef99b37b4f46d2ede0356b49b381d66cc2f10abb2831abc02b322884a81b1bf824bd2a5.gif)
