### ISSUE TITLE
Agile Central Integration - Feature/Waffle Epic Synching

### ISSUE THREAD

**Issue by schaveyt** [waffleio/waffle.io#3471]
(Value Score: 9 out of 10 for POs and Scrum Master)

With the assumption that portfolio management is completely done in rally via feature, program epics and portfolio epics (per Scaled Agile)...and the devs remain in Waffle and GitHub...a way will be needed to "synch" rally features to waffle epics. The scenario we we're thinking of was:

1. __Project Startup__: The POs establish a new project and create an anticipated 30 rally features that are known to be implemented during development. Now.. somehow/someway... tell waffle : synch to this Rally "project"...Waffle then scans that project _and all child projects_ for features and creates them in waffle Boom..done..We now hold release planning to flesh out 3 of the features with waffle user stories and estimates.

1. __Adapting to change__: during execution the POs discover that 4 of the features (not the ones fleshed out during planning) need to be removed and 2 new ones are added. The POs go into Rally and delete the 4 features and add the 2 new ones. Waffle, either via human invocation or automatically, synchs the featurea again and deletes/adds the corresponding waffles epics.

Repeat step 2. A waffle epic containing stories should not be deleted but maybe tagged somehow as "rally orphan" badge or something.

**Comment by homeyer** [comment]
We've thought about this also from the angle of teams that do story breakdown in Rally, say during a big room planning event across teams. A Rally feature could be chosen, and duplicated into an epic in Waffle, and all the children would become issues as well.

Would data need to stay in sync, if either of the copies changed? E.g., someone edits the feature in Rally, should it update the description in Waffle? 

We could make the actual feature visible on the Waffle board too, as a card that would not exist as an issue.

**Comment by schaveyt** [comment]
The "big room" is exactly how we approach our release planning day ^_^.
Right. If Waffle we're in place for us, then the team would never see
Rally...just a bunch of waffle epics that the POs have prepped on the
"Release Backlog".

I would assume that no data of a rally feature is stored in waffle..that
way the "truth" is in Rally.

Synching would be in essence be a "bulk" action for product owners to
maintain that "child of" relationship you've already implemented. :-)


Hmm. Having the Rally Feature visible as a card is interesting..I just
wonder if it would start to clutter the board.

I suppose it would be a straightforward way to quickly determine "which
waffle epic is associated with Rally Feature F23595".

...just wonder about that clutter effect...you know best of course (rock).

..by the way...pass along to your execs that we appreciated the individual
team you and Anna gave to out team and you deliver a great demo.

We will be intenally evangelizing here too but for an internal pilot...will
likely take 8 to 10 months knowing our IT overlords :-)

...in the meantime..feel free to bounce idea with us as you see fit.

Kind regards,
Schavey

**Comment by AnaMSteele** [comment]
@schaveyt We appreciate the insights here. We are working to validate the overall approach of this integration and if you are willing we will plan to be in touch to interview you in more detail in the coming weeks. Closing this issue for now as we are tracking this body of work separately during our validation efforts.

**Comment by schaveyt** [comment]
Thanks for the update. I look forward to you next chat. 😊
