### ISSUE TITLE
Epics sometimes become undefined

### ISSUE THREAD

**Issue by jtslear** [waffleio/waffle.io#3475]

**Comment by jtslear** [comment]
![waffle.io | Waffle.io 20180430.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/53adcd5c7953d2fd0f7215bc/125516c66e82c728ace21e0d46ff959c258e86e786e6ff5fe46af1922f4a223d200be37920d4bb78eb112b43434d0eee1e020a17b8eb8339a3b469708e5d58bb846d5b71943540ffbb8749ea05bc228b5d99a4fedb1294b7607caddecd5d340c071883fe5837a59942cf5ff642e04450b65e.png)

**Comment by marydavis** [comment]
this is an external contribution reference

**Comment by homeyer** [comment]
@jtslear any javascript errors when you see it?

**Comment by marydavis** [comment]
may have been caused by the feature toggle change over?

**Comment by jtslear** [comment]
Negative.  After doing a refresh with the dev console open, it started to work just fine.  Prior to the dev tools being open, even a refresh would show the same result above.  I have dev tools configured to Disable Cache.

**Comment by homeyer** [comment]
I haven't seen this - if it occurs again @jtslear please reopen!
