### ISSUE TITLE
performance spike (part 1): Confirm the current bottlenecks are what we think they are.

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#3476]
- [ ] what metric is most important to improve?
  - initial board load? 
  - focus on boards with lots of cards, or focus on boards with lots of repos?

**Comment by burtonjc** [comment]
Just had a pre-spike meeting to [fill out some details](https://docs.google.com/document/d/1yNsbkmnmN5EQJAYDCDXUclTonIumkClQT0DjqyvFMU4/edit?usp=sharing) on what we want to accomplish. We came up with two separate spikes:
1. Confirm the current bottlenecks are what we think they are.
1. We believe GraphQL would be a big help in the two major, known bottlenecks. See if we could implement (in a reasonable amount of time) a GraphQL endpoint to get projects, columns, and paged cards.

I am going to change this issue to be the first spike, and create a second one for the second spike.

**Comment by burtonjc** [comment]
After our pre-spike meeting we decided to focus on board load time and the ability to load large boards. Given that, we decided to break this into two spikes:

1. (This issue) is to confirm that we know the current bottlenecks in loading a board.
1. (https://github.com/waffleio/waffle.io/issues/3481) Given that the results of the first spike confirm that we know the bottlenecks, we believe GraphQL is the right way to alleviate the problem. See if we can implement it in a reasonable amount of time.

See our [meeting notes](https://docs.google.com/document/d/1yNsbkmnmN5EQJAYDCDXUclTonIumkClQT0DjqyvFMU4/edit) for more context.

**Comment by burtonjc** [comment]
## Spike Results
### Observations
1. Takes 11 -12 seconds to load https://waffle.io/waffleio/waffle.io
    - Only takes 800ms to fully draw the board once cards are loaded.
    - Over half of our load time is spent waiting for the network requests.
1. Webpage test: https://www.webpagetest.org/result/180511_TS_4c6f20e32c679b0765d4125320840e66/
1. From the client's perspective the biggest holdups are the requests for cards, columns, and project in that order; however, cards/columns are parallel so we are bound by cards on that one. Also, project must be fetched before anything renders at all.
1. There might also be a chance to optimize our vendor files
1. For the project, cards, columns requests, the biggest offender is the auth checking and we do it on all three requests.
1. on the project GET request, we are using a non-indexed query
1. We spend several hundred milliseconds on initial board load checking the users credentials.
1. The plurality (~30%) of server side cycles are spent by Express and the way it uses the node http module.

### Recommendations
1. Use an indexed query to get project on `GET /projects/:owner/:repo`
1. Reduce the auth checks (`checkReadAccessToProject`)
    - We could cache permissions, that feels like too much work for our timeframe
    - In GraphQL, we could have column/card resolvers underneath a project resolver, then the project resolver would be the only one to do the auth checking.
1. Optimize vendor loading.
    - Try moving all the independent script tags in the `app-head.jade` and `head.jade` to be a part of the `vendor.bundle.js`
    - we are using `es6-promise` for our a Promise polyfill and it gets loaded on its own. This should be in our polyfills bundle and probably use the `core-js` one instead.
1. Rework how we check credentials so we can get rid of a few hundred milliseconds on initial board load. Maybe even handle it client side somehow?
