### ISSUE TITLE
Progress bar and other indications of epic parent child relationship not displaying

### ISSUE THREAD

**Issue by jbrownkramer** [waffleio/waffle.io#3479]
I'm running Chrome 65.0.3325.181 on Windows 10.  I've tried clear the cache and hard reloading the page, turning off extensions and clearing the cache and hard reloading the page.  I've also tried removing the milestones, organizing by parent instead of child, and changing in which fields I'm indicating the parent child relationship.

![image](https://user-images.githubusercontent.com/4051645/39479304-7ed7b45c-4d2a-11e8-8bf2-0813e52acc03.png)

![image](https://user-images.githubusercontent.com/4051645/39479522-226ebbec-4d2b-11e8-8fe3-5abc84807bb8.png)

**Comment by kellihsf** [comment]
hi @jbrownkramer,

Your organization is on a legacy free plan in Waffle, and the new epics feature is only being enabled for the current paid plans in Waffle. Check out our help doc here for more info: [Waffle Help Doc](https://help.waffle.io/faq/why-dont-i-see-new-features-on-my-waffle-board). Email us at support@waffle.io with any questions!
