### ISSUE TITLE
Unable to switch between labels with different casing

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#3488]
If, in one repo the label `bug` exists and in another repo `Bug` exists, you cannot switch between them. 

Presumably Waffle fails to create an additional label with different casing of the same name, because the GitHub API does not support multiple casings of the same name.

Solution: Manually update labels in GitHub to not have different casing across projects.

Ideal solution: Waffle label management to make this process easier.

**Comment by AnaMSteele** [comment]
Can we validate how often this comes us in our user base?
