### ISSUE TITLE
New Waffle.io doesn't load in Safari

### ISSUE THREAD

**Issue by sfiquet** [waffleio/waffle.io#3489]
I did a whole project with Waffle.io open in Safari. But now it doesn't load anymore. Whether you're on the landing page or a project page, the page is just blank. There are errors in the console. I would have added a screenshot but I can't do it in the Waffle card.

**Comment by sfiquet** [comment]
Here's the screenshot:
![screen shot 2018-05-10 at 08 44 12](https://user-images.githubusercontent.com/4646869/39858734-63329d3c-542f-11e8-9024-eca0eb0960c7.png)

**Comment by kellihsf** [comment]
hi @sfiquet,

Can you try loading Waffle in an incognito window?

**Comment by sfiquet** [comment]
Hi @kellihsf 

It works fine in private mode.

**Comment by kellihsf** [comment]
Cool, thanks for confirming. Can you also try clearing cache & cookies?

**Comment by kellihsf** [comment]
@sfiquet, this issue should be resolved. Let us know if you're still having trouble!
