### ISSUE TITLE
Pro tips while you're ironing your waffle!

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#3491]
While a board is loading suggest pro tips!

Like slack:

![image](https://user-images.githubusercontent.com/84629/39937315-93e37b30-550c-11e8-8de6-25f3ff9eb76c.png)

- [ ] waffle logo at the top
- [x] randomize the pro tip that we show. Collect 10 protips from the team, each should be less than 140 characters
- [ ] spinner at the bottom, or make the waffle logo at the top drip syrup!

**Comment by marydavis** [comment]
so excited we are doing this, same thing a lot of my fave video games do which is awesome :)

**Comment by kellihsf** [comment]
pro tip ideas: https://docs.google.com/document/d/19bNIMj0kpkiM0LxYbyHBWO-KXVUKxQZV1gf0r1pNVhw/edit

**Comment by JuKu** [comment]
@homeyer @kellihsf Is there a opportunity to see all pro tips in a list somewhere (without pressing F5 10 times :D )?

**Comment by kellihsf** [comment]
hi @JuKu, 

We have a help article with all of the pro tips listed! https://help.waffle.io/faq/waffle-pro-tips

**Comment by JuKu** [comment]
@kellihsf nice!
Thanks! :D
