### ISSUE TITLE
Investigate how we can fix client side caching

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#3494]
Blue/green deploys?

**Comment by jtslear** [comment]
I disagree with blue/green deploys fixing the problem.

If a user still hasn't lazy loaded a file, and the switch happens, they'll ask for the file that is not compatible with the module they already have cached on their system.

I think the move to add hashes back into our files would solve half the problem.  The problem this will introduce is very similar (4 hours after the deploy).  After a deployment is complete, some hash of a file may not be available to be lazy loaded.  To solve this, I would like to suggest, if feasible, to up the time cloudflare caches files.

Currently set at 4 hours, we can max it out to 1 year.  Previously we couldn't do this for X reason that I cannot recall.  However, if we are adding hashes to all files, I don't see why this wouldn't work.  Even though the requested resource may no longer be available at our application, cloudflare would still intervene and served the cached object.  If this works, we don't even need to introduce a CDN.

The only remaining issue I see in this situation, is a situation where a user in a region never had loaded all resources.  Example, If we have one user in Italy, and they never lazy loaded a file, the region of cloudflare that serves Italy may not have all files available for caching.  That user would be presented with the white screen of death until a hard refresh to get the latest version of all the things.

If we can't increase the time cloudflare caches, I think our only solution would be to go back to a CDN.  The deployment process would need to upload to the CDN before deploying the application.  Haproxy would need to have his modifications added back to serve the static content.

**Comment by homeyer** [comment]
We're switching back to using the bundle hashes in the file names. If you have app.123.js, when you need to lazy load a module it will ask for 0.app.123.js instead of the newer 0.app.456.js.

I agree with the cloudflare cache time - 1 year would be great. If we can't do that, let's move to a CDN.

We still need green/blue if we don't do a CDN. If you do a deploy, and a client loads the index page which tells the browser to load app.234.js, and the request hits an old pod that doesn't have app.234.js, the user gets a crappy experience. Every time we do a deploy we'll potentially give users this experience, across the app. 

If we use a CDN we don't need green/blue, but then we have to figure out prod vs takeout.

**Comment by jtslear** [comment]
Cache can be bumped to 1 year, I'll proceed to do such.

I've created a calendar invite such that we can sit down and have a lengthy chat about what else we need to move forward and remove pain and suffering from end user experiences.
