### ISSUE TITLE
Extend trial period by inviting team members

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#3496]
Waffle's more useful when you invite your team. Let's incentivize expanding your team by extending the trial end date by a week for every team member that joins via the share link.

- the `/join` link on boards extends your trial
- change banner to be "5 days remaining on your trial! <Invite> your team to extend your trial!", open the share modal where they can copy the link
- change the modal text, but only if you're on a trial
- limit to 5, if it's easy

**Comment by homeyer** [comment]
also we can put it on the trial banner! quick way to promote it

**Comment by adamzolyak** [comment]
might be helpful to create a sense of urgency - "5 days remaining!  earn more days (linked)!"

**Comment by adamzolyak** [comment]
https://www.prodpad.com/ does a really good job of earning more trial days.  sign up for a trial and check it out.

**Comment by homeyer** [comment]
we can change the trial email messages to encourage them to share their join link

**Comment by Alisuehobbs** [comment]
If a team member joins your project through the join link, we'll add some amount of time to your trail. Each time this happens,  we'll track it on the account by and only allow up to 5 extensions.
