### ISSUE TITLE
Angular injector fails and page is not rendered

### ISSUE THREAD

**Issue by matiasgarcia** [waffleio/waffle.io#3497]
It has happened to me, more than once, that the application stops working. This is the error I get:

![image.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59ee3eeb4db56a0013907aed/125516c66e82c728ace21e0d46e1999b2487c1e5cdf9ad4cae58f3806b1c65267b01f37f2186e52def162e03570e1daf440e0a40fafb8939baa47e21d40854b088270a36d43703adbf881eba03bc23894a84b6b48f4ec0fa70.png)

Normally, I can fix this by cleaning up the cache.

**Comment by homeyer** [comment]
I think we've resolved this by changing our caching strategy. If it happens again please shout!
