### ISSUE TITLE
if a "close" keyword is used in the PR title AND a different "close" keyword is used in the description, the connection won't be picked up

### ISSUE THREAD

**Issue by kellihsf** [waffleio/waffle.io#3501]
to repro:

1. use a "close" keyword in a PR title
2. use a different "close" in the description 
3. PR will not be connected to issue
4. when PR is merged, it will move the issue

ex: fix in PR title and resolves in PR description

**Comment by danielBingham** [comment]
Yeah, this specific case was a PR titled after its branch ``feature/so-and-so-fix``.  It's probably not terribly uncommon to title branches or PRs using the word "fix" with out necessarily intending to use it as the keyword.  We have PR templates that include "Resolves #nnnn" in the first line of the description and we just use that to do the linking, and as a result, I'd completely forgotten that "fixes" was a linkage keyword.   

It might make sense to note when a keyword doesn't successfully resolve to a connection in the title, and double check the description for fallback keywords.  

Just my 2 cents!
