### ISSUE TITLE
angular error when card moves

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#3503]
![image](https://user-images.githubusercontent.com/84629/40145880-bdea3d70-5920-11e8-9b04-97e55a5037bd.png)

**Comment by homeyer** [comment]
when a PR changes columns for an auto work tracking action.

**Comment by burtonjc** [comment]
I _think_ this happens when a PR card receives a status event after moving columns. Might have to manually unsubscribe from the status query on destroy.
