### ISSUE TITLE
Create a cheat sheet for waffle shortcuts

### ISSUE THREAD

**Issue by chrismclarke** [waffleio/waffle.io#3512]
I had a quick look around and can't tell if this might already exist, but if not a cheat sheet would be really handy to provide quick reference to things like epics, dependencies and changing issue status. They're mostly documented well in help sections, but would be nice to have in a single place

**Comment by adamzolyak** [comment]
Hi @chrismclarke!  Thanks for the idea!  Is there any other info that would be helpful (maybe things that were hard to discover or remember how to use)?  

I've been working on a draft of a Waffle Automation Cheatsheet.  I'll share in a few days and would love your feedback.

**Comment by chrismclarke** [comment]
Automation cheat sheet sounds like a great inclusion. If also including non waffle-specific features then use of keywords for things like [closing issues](https://help.github.com/articles/closing-issues-using-keywords/), [referencing specific issues or commits](https://help.github.com/articles/autolinked-references-and-urls/), notifying specific users (via @), adding hyperlinks, or even some basic markdown [cheatsheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) references could all be useful. Happy to feedback.

**Comment by adamzolyak** [comment]
this card  doesn't include experiments to distribute the cheatsheet, just the creation of it.

**Comment by adamzolyak** [comment]
Draft cheatsheet

[waffle_cheatsheet_june2018_b_v2.pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5457b48ff284760200e70666/125516c66e82c728ace21e0d46ff959c258e86968ce1ba42b04ef8912c5218793c0aa67920d4bb17bd7d6d534d435cec03070511afbd9b21b4b33e258a580abe87385f70c36f19fdeb811ae954be26894f97aaaec81d9ebc6278bec1da0d2c14171980f55c30a29149cb5dfe4be94f50a1017b.pdf)

**Comment by adamzolyak** [comment]
@chrismclarke ^ link to draft cheatsheet.  Would appreciate your feedback - is this what you expected, what's missing, what did you learn, what did you want to learn but didn't?

**Comment by chrismclarke** [comment]
I never knew about 'connects'! I really like the overall design, what is there is very clear. If you were to include more I would suggest epics and dependencies for helping manage inter-relationships between issues in addition to the board and status (particularly as the first screenshot on page 1 shows  and example of require/required). As an additional minor note I see there is a link to help.waffle.io at the bottom (which I think is a really handy resource), although I wonder if this should be made more prominent by adding a hyperlink or using color/underline (the exclamation mark also makes it harder to copy-paste into the browser as pasting with the exclamation will not navigate directly). Glad to see it coming together so nicely though, will definitely share with my own team when ready!

**Comment by adamzolyak** [comment]
[waffle_cheatsheet_june2018_b_v3.pdf](https://github.com/waffleio/waffle.io/files/2077405/waffle_cheatsheet_june2018_b_v3.pdf)

@chrismclarke great feedback.  see an updated version w/ a command cheatsheet.  any other feedback?

**Comment by chrismclarke** [comment]
I like it! thanks for all the effort you've put in.

**Comment by adamzolyak** [comment]
Posted at:

https://help.waffle.io/automatic-work-tracking/the-waffle-automation-cheatsheet

https://blog.waffle.io/introducing-the-waffle-io-automation-cheatsheet-47b78a243d3f

**Comment by adamzolyak** [comment]
Thanks for your help @chrismclarke!  Feel free to keep the feedback coming - about this or other things.  We love helping our users!

**Comment by aronatkins** [comment]
@adamzolyak Could we get more parts of the quick reference included in the `?` help that is available in the UI? Right now it contains the keyboard shortcuts but only indicates a subset of the supported keyword. It's missing information about dependencies (requirements and parent/child).

**Comment by adamzolyak** [comment]
Good suggestion!  Created #3580.  @aronatkins would it be helpful to have a basic example for epics and dependencies and then have links to more info?  Or what info would you be looking for?
