### ISSUE TITLE
Telegram Bot

### ISSUE THREAD

**Issue by JuKu** [waffleio/waffle.io#3519]
Currently waffle.io only supports Slack Bot.
Is there also a telegram bot planned?

**Comment by kellihsf** [comment]
hi @Juku, 

No plans for this, but we'll keep the issue open in our Ideas column for others to find and 👍.

**Comment by AnaMSteele** [comment]
Hi @juku we haven't seen any activity on this card since you opened it 3 months ago from the rest of the Waffle user based. We are closing it for now as we prioritize and work on other more highly requested features/integrations. Thank you.

**Comment by JuKu** [comment]
@AnaMSteele That's a pity, but thanks for that information!
