### ISSUE TITLE
Time tracking

### ISSUE THREAD

**Issue by JuKu** [waffleio/waffle.io#3520]
It will be a nice feature, if waffle.io supports time tracking for issues.

**Comment by kellihsf** [comment]
Hi @JuKu, 

We have heard of some people using [toggl](https://toggl.com/) with Waffle. I haven't tried this yet so I can't personally recommend it, but it may be something worth checking out!

**Comment by JuKu** [comment]
@kellihsf Thanks for your answer!
I will try this.
