### ISSUE TITLE
Pull Request Functionality

### ISSUE THREAD

**Issue by kmoore134** [waffleio/waffle.io#3524]
Right now when we treat PRs as a ticket, it's somewhat cumbersome to have to open the PR in github to review the changes and merge it. Would be nice if this could all be done via the Waffle interface directly.

**Comment by homeyer** [comment]
Woah that would be awesome! I don't think we'll be able to keep up with GitHub's progress though, reproducing what they have in the core UI would be pretty difficult for us.
