### ISSUE TITLE
One board for more than one repositories

### ISSUE THREAD

**Issue by JuKu** [waffleio/waffle.io#3527]
Hi,

Is it possible to use one board for more than one repositories?

**Comment by kellihsf** [comment]
Hey @JuKu,

Yep!  You can connect as many repos as you'd like to a single board in Waffle to create a multi-repo board, which will give you an overview of all of your issues across multiple repos. You can do this with a personal account or an organization. 

To create a multi repo board, you'll open the gray sidebar (arrow above your avatar) and go to Project Settings->Repositories. Click the green GitHub icon and select which repos you'd like to add to that project. More info here: [Waffle Help Docs](https://help.waffle.io/faq/creating-project-boards-in-waffle/how-do-i-add-multiple-repositories-to-a-single-board)

**Comment by JuKu** [comment]
@kellihsf Very nice!
Thanks!
