### ISSUE TITLE
Badge is inconsistent with board ticket count

### ISSUE THREAD

**Issue by ericyliu** [waffleio/waffle.io#3528]
<img width="1402" alt="screen shot 2018-05-31 at 2 19 11 am" src="https://user-images.githubusercontent.com/8580080/40765089-41e24484-6479-11e8-84dd-75e0bcc51561.png">
<img width="409" alt="screen shot 2018-05-31 at 2 19 05 am" src="https://user-images.githubusercontent.com/8580080/40765090-41f59bec-6479-11e8-9a61-4720b1b731fa.png">

The badge is including any PRs attached to the tickets in its count.

**Comment by kellihsf** [comment]
hi @ericyliu,

Would you mind sending us details on which repo this is occurring on to support@waffle.io? Thanks! :)

**Comment by kellihsf** [comment]
hi @ericyliu, 

Just following up here. After confirming with the dev team, this is indeed how the badges are intended to work. Each PR that's attached to an issue, will contribute to that column's total issue count.
