### ISSUE TITLE
Keyboard Shortcut for Clear All Filters

### ISSUE THREAD

**Issue by adamzolyak** [waffleio/waffle.io#3530]
With the addition of Epics and Dependencies in Waffle, I am frequently clicking on cards to filter by epic, by dependencies, etc.  It would be a timesaver to have a way to quickly clear the filters such as a keyboard shortcut to clear all filters.  Currently, clearing all filters requires 3x clicks - clicking filter, clicking clear all, clicking close.

child of #3651

**Comment by AnaMSteele** [comment]
Moving to research, feels like a jobs to be done question for a planner/manager of a team.

**Comment by marydavis** [comment]
haha @adamzolyak, i ran into this same annoyance recently - so created a PR :)
