### ISSUE TITLE
Card count on Load Board event in Mixpanel

### ISSUE THREAD

**Issue by adamzolyak** [waffleio/waffle.io#3532]
we want to know how many new users view an empty board as their first experience SO THAT we can determine the best activation strategy for new users

AC
- record number of issues + pull requests on board as a property on the Load Board event in Mixpanel

**Comment by marydavis** [comment]
this looks to already be tracked under the event `loaded board` with `numberOfCards`

**Comment by adamzolyak** [comment]
From 5/7 - 6/5, 2018, 1285 unique users loaded a board within 30 minutes of a new user signup.  of these, 340 of these users saw 0 cards when loading the board - roughly 25%.  478 of the total users saw between 1-5 cards.
