### ISSUE TITLE
Set target for burndown/burnup arbitrarily

### ISSUE THREAD

**Issue by DanieleSassoli** [waffleio/waffle.io#3535]
It would be nice to set a target score for our sprint without having to specify a milestone(we work on multiple milestone, setting a milestone per sprint doesn't really work for us) and see the burn-up/burn-down towards that score.

**Comment by AnaMSteele** [comment]
We are tracking all metric/report updates on #1327. Moving this request there, feel free to comment up-vote there. Thank you.
