### ISSUE TITLE
Restore deleted webhook

### ISSUE THREAD

**Issue by freakinruben** [waffleio/waffle.io#3536]
I noticed a lot `422` errors in the webhooks section of github. I tried to solve it by deleting the webhook, assuming that waffle would request a new webhook. However, I can't find the option to recreate the webhook from waffle..

**Comment by tifthedog** [comment]
hi @ freakinruben,

Can you let us know the name of the board this was on? We can reset the banner for you on our end. Feel free to email us at support@waffle.io, if you prefer. :)

**Comment by kellihsf** [comment]
hey @freakinruben,

The above comment is indeed accurate! Just our friendly mascot, Tif helping out! 😆
