### ISSUE TITLE
Dive Into Waffle Automation - CTA button w/ cheatsheet link (step 1)

### ISSUE THREAD

**Issue by adamzolyak** [waffleio/waffle.io#3544]
Add a link to the Waffle Automation Cheatsheet on the WaffleBot tile on the feature page SO THAT users can more easily learn about the specifics of how Waffle automation works.  Part 2 will be a dedicated automation landing page (not part of this card).

**Hypothesis**
Based on usertestin.com research w/ 4x devs and 2x project managers, most of these participant's #1 value prop was Waffle's automation / WaffleBot.  However, some of them wanted to learn more about specifics or thought it was too good to be true.  After these participants viewed the Waffle Automation Cheatsheet, they better understood the details of customizing and using automation in Waffle.  By providing more information about Waffle's automation, more users will signup and become better activated.

**Goals**
* increase signups by 2% in this user group
* increase activation of automation by 2% in this user group

**Comment by AnaMSteele** [comment]
card captured on biz board, closing duplicate
