### ISSUE TITLE
Bark Garage Video above the fold on landing page (removed from Feature page)

### ISSUE THREAD

**Issue by adamzolyak** [waffleio/waffle.io#3547]
Move the Bark Garage video from the feature page to the landing page SO THAT users can more easily learn about Waffle.io above the fold on the landing page.  Suggest A/B testing w/ Google Optimize.  

**Hypothesis**
80% of new visitors bounce (only view 1 page) and only 5% sign up.  Based on usertestin.com research w/ 4x devs and 2x project managers, most users don't know about Waffle's core value props - automation, multiple repos, real time updates - from the landing page.  By providing more information about Waffle's core value props on the landing page above the fold, more users will signup and less will bounce.

**Goals**
* increase signups by 2%
* decrease bounce (viewed 1 page) by 5%

child of https://rally1.rallydev.com/#/28451149440d/detail/portfolioitem/feature/210195034624

**Comment by AnaMSteele** [comment]
blocked by Google Optimize thing
