### ISSUE TITLE
add multiple sources from GH and GH:E at the same time

### ISSUE THREAD

**Issue by BAMason** [waffleio/waffle.io#3558]
Currently you can only add multiple repos from GH or GH:E (not both) when creating a project.  Let's add all the things at once.

**Comment by kellihsf** [comment]
Can we see how many of our customers have a mixture of GH and GH:E repos to see how relevant this is?

**Comment by kellihsf** [comment]
Haven't seen any upvotes/activity on this from the rest of the user base, closing for now.
