### ISSUE TITLE
API: 429 Too Many Requests

### ISSUE THREAD

**Issue by chris48s** [waffleio/waffle.io#3559]
Hi. We are using the Waffle API for our badge on http://shields.io/
Recently we have started to see failures due to hitting a rate limit. It looks like we are being limited based on user agent. For example, I can reproduce on my local machine:

```
$ curl -I "https://api.waffle.io/ritwickdey/vscode-live-server/cards"
HTTP/1.1 200 OK

$ curl -I -A "Shields.io" "https://api.waffle.io/ritwickdey/vscode-live-server/cards"
HTTP/1.1 429 Too Many Requests
```

I've had a look at [the docs](https://docs.waffle.io/v1.0/docs) and I've been unable to find information on what the rate limits are and what actions we can take to stay under them:
* Do we need to get an API key?
* If so how? https://docs.waffle.io/docs/authentication has no info

Could someone give us some info on this - thanks.

**Comment by homeyer** [comment]
Hey @chris48s! Instead of using the card endpoint can you use the column endpoint, like this? `https://api.waffle.io/ritwickdey/vscode-live-server/columns?with=count`

We recently switched over to GitHub's graphql api for our server side permission checks and we've been hitting new rate limits for some requests, and we've blocked some external requests while we figure out how to improve it.

We can open a PR too in shields if that would help!

**Comment by chris48s** [comment]
Hi. Thanks for responding. Happy to switch to a different endpoint and the less verbose output from `/columns` is probably preferable, but the `/columns?with=count` endpoint doesn't seem to be returning the correct totals.

If we continue to work with https://waffle.io/ritwickdey/vscode-live-server as an example, at the time I'm writing this if I hit https://waffle.io/ritwickdey/vscode-live-server the totals at the top of the columns are:

```
Issue		18
In progress	 2
Question	29
Help Wanted	 6
Need More Info	 5
Bug		 5
Can't Help	 1
Closed		46
Production	14
```

but if I call https://api.waffle.io/ritwickdey/vscode-live-server/columns?with=count it is returning [cut down]:

```json
[
  {
    "displayName": "Issue",
    "count": 19
  },
  {
    "columnDescriptionHeader": "In Progress",
    "count": 2
  },
  {
    "displayName": "Question",
    "count": 10
  },
  {
    "displayName": "Help Wanted",
    "count": 4
  },
  {
    "displayName": "Need More Info",
    "count": 6
  },
  {
    "displayName": "Bug",
    "count": 2
  },
  {
    "displayName": "Can't Help",
    "count": 1
  },
  {
    "displayName": "Closed",
    "count": 71
  },
  {
    "displayName": "Production",
    "count": 14
  }
]
```

It doesn't appear to be specific to this example. I won't post the whole output verbatim again, but if you compare the totals on https://waffle.io/waffleio/waffle.io to the counts from https://api.waffle.io/waffleio/waffle.io/columns?with=count some of the counts/totals are different there too. The code we had parsing the `/cards` endpoint was giving us numbers that match the totals displayed in the front-end.

Cheers

**Comment by chris48s** [comment]
OK. Thanks for updating that. I started looking at updating our code to use the `/columns` endpoint, but we seem to hit the same rate limit again very quickly on that endpoint:

```
$ curl -I "https://api.waffle.io/waffleio/waffle.io/columns?with=count"
HTTP/1.1 200 OK

$ curl -I -A "Shields.io" "https://api.waffle.io/waffleio/waffle.io/columns?with=count"
HTTP/1.1 429 Too Many Requests
```

**Comment by homeyer** [comment]
Oof, sorry about that. Just shipped a fix, all good now for `curl -I -A "Shields.io" "https://api.waffle.io/waffleio/waffle.io/columns?with=count"`

**Comment by chris48s** [comment]
Thanks. I'll close this now. We'll keep an eye on it once https://github.com/badges/shields/pull/1745 lands. :+1:
