### ISSUE TITLE
[BUG] wafflebot always assign my PR to me

### ISSUE THREAD

**Issue by cychiuae** [waffleio/waffle.io#3563]
Can wafflebot stop assigning my PR to me? Why would I review my PR?

**Comment by BAMason** [comment]
We use the assignee to help identify the person owning the PR and show specific reviewers or commenters as those actions happen as well!  Take a look at this [article](https://help.waffle.io/pr-statuses-and-reviewers/pull-request-reviewers) for more detail.
![pr_reviews](https://user-images.githubusercontent.com/17367713/41297725-084c9190-6e1d-11e8-88e8-f58fa230f557.png)

**Comment by pijemcolu** [comment]
I would like to reopen this.

Waffle bot assigns all existing PRs to anyone who commits into the PR. 

Very often the case is that PRs are in review and then during the review process, small fixes are made to the PR which re-assigns all current committers to the PR. After a short while this becomes annoying as anyone who makes any small tweak to the PR gets assigned, will most likely not work on the task anymore, yet according to the waffle board, the person is assigned to the review, therefore no one picks it up.

I would suggest two possible workflows:
- the ability to disable automatic assignment made by waffle bot
- disable assignment by waffle bot to existing PRs
- if automatic assignment functionality should persist, then it would make sense that the PR is at least moved back to the in progress column, as the assignment means that someone is currently actively working on the issue.

**Comment by adamzolyak** [comment]
RE
> if automatic assignment functionality should persist, then it would make sense that the PR is at least moved back to the in progress column, as the assignment means that someone is currently actively working on the issue.

Many teams that use Waffle have separate In Progress and Reviewing columns.  Cards in In Progress aren't ready for PR review yet.  Cards in Reviewing are ready for review, and changes may occur as part of the review.  For an example, see the Waffle team's board https://waffle.io/waffleio/waffle.io.  I wondering if this approach might be helpful for you and your team?  If not, I'd love to have more detail about why it's not ideal.

**Comment by pijemcolu** [comment]
@adamzolyak

I guess we have a slightly different process where assignment equals in progress OR 'will take a look in the near future', the reason for that would be that we work more in a kanban style, where we pull tasks and it doesn't really matter who picks the task, tasks are not assigned to developers, but they pick tasks. We do have separate 'in progress' and 'review' column. We don't have an 'Actively reviewing' column. Let me explain columns we have and the process we follow.

In general a task would pass through these columns:
Inbox -> Estimation/Maturing/Discussion -> In progress -> Review -> Reopened/Done

At any point the only columns where it makes sense to have an assignee is 'In progress' or 'Review' as these are the processes we see as lengthy. In general an issue would be created for every PR, so we would have a PR stacked to the issue.

At times some PRs get small fixes made by other developers either as part of the review or 'in progress' process. These are small fixes and by no way a git commit means that the committer has taken over a task or will continue actively working or reviewing it. 

The automatic assignment by wafflebot however makes it seem as such - committer to the PR taking active charge of reviewing or actively working on the task.
- This creates confusion as to who's working on the task.
- Makes other developers think that someone is actively taking care of the task, while he only committed/helped with a small problem.
- Forces the developer providing help to un-assign himself after every small commit into any PR.

**Comment by adamzolyak** [comment]
Thank you for the additional detail!  Totally makes sense.  This could also become more common with the recent release of GitHub Suggested Changes.  We'll keep this in the backlog and consider it for the future.  

I'm going to remove bug from the title as it's working as expected although it doesn't git your team's use case.
