### ISSUE TITLE
Bug: when user has access to a repo, the project does not show automatically

### ISSUE THREAD

**Issue by RickCardoso** [waffleio/waffle.io#3565]
**Description**
If a user has access to a certain repo that has a waffle.io project, the project does not appear automatically. Only when the user accesses the waffle project by link, it appears.

**Expected behaviour**
Because the user already has access to the main repo, it's expected that it will appear to him without previous access.

**Reason**
On a big company with several repos, projects and products, it's much easier, candid and transparent to tell people to checkout a project then to have to send each person a link to it.

**Screenshots**
![image](https://user-images.githubusercontent.com/15681333/41310510-15796916-6e58-11e8-8b39-d291e566884f.png)
Before accessing through the URL

![image](https://user-images.githubusercontent.com/15681333/41310554-32ea4d30-6e58-11e8-900d-5aafabf6b9a6.png)
After accessing through the URL

**Comment by homeyer** [comment]
Hey @RickCardoso,

We just added a button to sync project membership to auto-add you to projects you have access to. You can find it at the top of your dashboard: 
![image](https://user-images.githubusercontent.com/84629/41310840-eb2a39aa-6e3f-11e8-9a3b-1552742ca168.png)

We do our best to add you automatically to projects when your account is created too, but sometimes we miss events so now you can click the button to make sure you see everything you should!

**Comment by RickCardoso** [comment]
Amazing, thanks! I'll test later!
