### ISSUE TITLE
Upgrade all services to Circle 2.0 by August 31st

### ISSUE THREAD

**Issue by burtonjc** [waffleio/waffle.io#3567]
![Capture.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5370e138ebef97b1f959c719/125516c66e82c728ace21e0d46cb958a379791accda5fd53b652fa912a5265296b51f12e20d1b22bb9472b555a0d46fd125b5a12a9fd8f29a6a42062c80d55b98e30063e937f03a6aa8316b500bf22824f85b5b8894dc7e93d37aa.PNG)

**Comment by jtslear** [comment]
The only remaining projects that we mildly care about:
* domain
* replicated
* takeout-startup
* takeout-management
* env
* graphs
