### ISSUE TITLE
Unable to configure Waffle Bot

### ISSUE THREAD

**Issue by GMishx** [waffleio/waffle.io#3568]
Hello there,
I have installed Waffle bot on my GitHub repo but whenever I visit waffle bot settings here: https://waffle.io/GMishx/fossology/settings/wafflebot , it shows that I have not installed WaffleBot from GitHub.
![image](https://user-images.githubusercontent.com/18077542/41498061-5a27bac8-7181-11e8-8db5-46fd336b392f.png)

1.  When I click on the **Configure WaffleBot** button, I am taken to https://github.com/apps/wafflebot
    ![image](https://user-images.githubusercontent.com/18077542/41498066-7df7c02e-7181-11e8-8714-271f29530a26.png)
1.  Which has a configure button which redirects me to https://github.com/apps/wafflebot/installations/new from where I choose my repository and land here:
    ![screenshot-2018-6-16 build software better together](https://user-images.githubusercontent.com/18077542/41498078-d2c5d0f0-7181-11e8-9b58-a29f3375297c.png)
  -  As you can see, I have given all the access to it for my repo. But when I come back to waffle.io and click on WaffleBot, I receive this message:
    ![image](https://user-images.githubusercontent.com/18077542/41498089-ffe3fa4e-7181-11e8-84d1-1bb0ae785a82.png)

Is there a solution for this? As the WaffleBot is working on my repo and assigning labels and people but I am unable to change its behavior.

**Comment by kellihsf** [comment]
Hi @GMishx,

Can you try to uninstall and re-install WaffleBot? I have included a link below to our help docs with instruction on how to do this.

[Waffle Help Center](https://help.waffle.io/wafflebot-basics/how-do-i-update-my-wafflebot-installation)

**Comment by GMishx** [comment]
Hello @kellihsf,

Thanks for the reply. I followed the steps as per the docs and reinstalled WaffleBot on my GitHub but after doing so, I can not see WaffleBot in my waffle.io

**Comment by kellihsf** [comment]
Hi @GMishx,

So it looks like WaffleBot was successfully installed on your account, good news! Once WaffleBot has been installed, you'll no longer see the lightning icon in your sidebar indicating that it's been installed. Are you not seeing WaffleBot taking actions on your board/GitHub? Ex: "wafflebot added the `in progress` label"

**Comment by GMishx** [comment]
Hi @kellihsf ,

Yes it is working and taking actions on GitHub. But it is assigning a PR to the person who opened it. Can I change this behavior or stop it from assigning entirely?

**Comment by kellihsf** [comment]
Ok, great! So that is the expected behavior: WaffleBot will assign the PR to the user who opened it. We use the assignee to help identify the person owning the PR and show specific reviewers or commenters as those actions happen as well!  Take a look at this article for more info: [Waffle Help Docs](https://help.waffle.io/pr-statuses-and-reviewers/pull-request-reviewers)
