### ISSUE TITLE
Issue/User deleted in GitHub remians as empty card in Waffle

### ISSUE THREAD

**Issue by bbrks** [waffleio/waffle.io#3574]
We had an issue filed, I think by a spammer on GitHub. The user and any associated issues have since been deleted, however Waffle has retained this issue in our board.

Is there a way to force this issue to disappear or delete from Waffle? We are unable to interact with this empty card in Waffle.

Screenshot of Waffle board showing deleted issue:
![screen shot 2018-06-27 at 11 09 48](https://user-images.githubusercontent.com/1525809/41967889-a6525a94-79fa-11e8-8b61-caf2cf689992.png)

Screenshot of user raising the issue:
![screen shot 2018-06-26 at 18 08 40](https://user-images.githubusercontent.com/1525809/41967909-b84e52f2-79fa-11e8-802d-ca9184918996.png)

Issue in question (returns 404):
https://github.com/couchbase/sync_gateway/issues/3654

User (now deleted) who raised the issue (returns 404):
https://github.com/Wongkako

**Comment by kellihsf** [comment]
hi @bbrks,

We've deleted this card for you on our end. Let us know if anything else comes up!
