### ISSUE TITLE
Easily add and distinguish tasks vs bugs

### ISSUE THREAD

**Issue by mkwu** [waffleio/waffle.io#3576]
here's a feature request. Would love to be able to easily distinguish issues as a task or a bug. very error prone and cumbersome trying to use labels within github to differentiate. feels like this is something that would be easy to layer in from your end especially if i get the team all using waffle for issue entry.

i was thinking of from the add issue dialog, that you can explicitly designate an issue as a bug and along with that require a priority (p0,p1,p2,p3? seems common enough vernacular these days) where the bug and priority are then simply added as labels, and while at it i do wonder if you can leverage labels even more by also labeling all non bug issues tasks, and maybe even epics with the epic label? I know this may eat into how different orgs would use labels, but at least as I think about how our development team here evolves and trying to see if we can make github issues work instead of going to something like JIRA or Asana would be great, and Waffle so far seems to be really close to doing the trick!

**Comment by AnaMSteele** [comment]
Hi @mkwu feels like this feature request relates to labels being hard to use, and maybe adding lots of issues at the same time. Mind sharing some of the specific use cases that makes this come up for you and your team to help us better understand it?

**Comment by mkwu** [comment]
Most Issue tracking systems allow you to distinguish the difference between
different issues (eg: JIRA, Pivotal Tracker) where you can classify what
kind of issue we are dealing with, we prioritize and think of the scope of
feature requests and bugs differently, and if we are using Waffle.io as a
primary mode of  managing issues in Github, then forcing people to choose
would help a lot make sure we are tracking things correctly

**Comment by AnaMSteele** [comment]
Hi @mkwu, so if I understand the use case correctly, this would be a forcing function to get folks entering new issues into GH (or your Waffle board) to choice a  work type (bug, feature request, etc.) that would allow you to filter your board and triage those categories as appropriate. We usually see this accomplished by leveraging GH labels when entering a new issue. What am I missing that would function differently then just applying the correct label? 

Would it be forcing someone entering a new issue to choose the appropriate label? 

In your use case, who typically enters new issues? 

Thanks again for being willing to explore this further and help our team understand your use case more clearly.

**Comment by AnaMSteele** [comment]
@mkwu we are consolidating your request into how does Waffle better serve users during the planning stages of work, which we are tracking in aggregate on #1153. Does this feel at a high level from bucketing this functionality correct to you? Let us know if that doesn't sound/feel right and we will adjust. If that is all good, feel free to further comment and upvote this request and others about how Waffle can better serve planning needs on #1153. Thank you.
