### ISSUE TITLE
Add a description in the detail modal is confusing with out the text box

### ISSUE THREAD

**Issue by kellihsf** [waffleio/waffle.io#3579]

**Comment by kellihsf** [comment]
The "Add a description" was previously a text box like the comments. It's easy to miss where the description belongs.

**Comment by AnaMSteele** [comment]
Next step validate mock ups originally created for #3461 on making epics more discoverable with customers. 

Possible intermediary step would be day effort to add new text including "Add Keywords Here" 

@kellihsf what's the volume in the support Q like around this issue? Deserves an intermediary step while we validate a more thought out solution?

**Comment by kellihsf** [comment]
@AnaMSteele this doesn't come up very often, can be moved to Ideas if needed.
