### ISSUE TITLE
DT25DT68018

### ISSUE THREAD

**Issue by Caohuynhgithub2018** [waffleio/waffle.io#3605]
88888

**Comment by Caohuynhgithub2018** [comment]
99999

**Comment by marydavis** [comment]
Hi @Caohuynhgithub2018,

Glad to see you are giving Waffle a try, let me know if you have any questions along the way :) 

Here is quick guide on setting up a project of your own:
https://help.waffle.io/getting-started/how-to-get-started-using-waffle

Hope you enjoy!
