### ISSUE TITLE
Periodic duplicate notifications in Slack

### ISSUE THREAD

**Issue by adamzolyak** [waffleio/waffle.io#3609]
We're currently seeing issues with the slack integration duplicating events that are magically resolved when we restart the kubernetes pod.

depends on waffleio/waffle.io-slackify#45

**Comment by adamzolyak** [comment]
This will be resolved by https://github.com/waffleio/waffle.io-slackify/issues/45 (private repo).  This issue is for public tracking.

**Comment by BAMason** [comment]
Haven't seen any duplicates in a while.  Will reopen if they pop back up again.
