### ISSUE TITLE
Where is the source code ? 

### ISSUE THREAD

**Issue by domainoverflow** [waffleio/waffle.io#3619]
Hi, according to the website the free version is open source but I do not see any source code here. 
What am I missing or you are no longer open source ? thanks for your time.

**Comment by kellihsf** [comment]
Hi @domainoverflow,

Sorry for any confusion here! When you see "free for open source" in Waffle, that's in reference to our [pricing plans](https://waffle.io/pricing). Any users or organizations that are using public repos (open source) in GitHub can use Waffle at no charge, and others who use private repos will need to be on a paid plan. Waffle.io itself is not open source. 😀
