### ISSUE TITLE
Issues deleted on GitHub cannot be removed from the Waffle board

### ISSUE THREAD

**Issue by pvdlg** [waffleio/waffle.io#3622]
The issue `https://github.com/semantic-release/semantic-release/issues/808` has somehow been deleted by GitHub. Not sure how it happened...the user account that opened it doesn't exists on GitHub anymore. Maybe it got deleted when the user deleted their account...

It's still present in the board https://waffle.io/semantic-release/semantic-release and cannot be deleted or archived.

Is there a way to get rid of it?

**Comment by kellihsf** [comment]
Hi @pvdlg,

We've deleted this issue for you on our end. If anything else comes up, let us know! :)

**Comment by pvdlg** [comment]
Awesome! Thanks a lot!
Maybe an issue should be added to the backlog to handle this case automatically?
