### ISSUE TITLE
Cannot add a "Deployed" column to existing board

### ISSUE THREAD

**Issue by pvdlg** [waffleio/waffle.io#3623]
When creating a new project and selecting the "Advanced" board it contains a "Deployed" column to which issue will be moved once deployed (based on GitHub deployment API).

However, if this column is removed it cannot be re-created.
Similarly, if one initially created the basic board, the "Deployed" column cannot be created.

**Comment by kellihsf** [comment]
Hi @pvdlg,

You are able to add a Deployed column (or any column!) to your board. Are you getting an error when trying to add the column?

**Comment by pvdlg** [comment]
When creating a new column it appeared on the "Progress" area (the large one in the middle).
I didn't realized the new column could be moved outside the "Progress" area into the "Closed" area.

So there is no issues :-)
