### ISSUE TITLE
Free text form input option for size/estimate value

### ISSUE THREAD

**Issue by katewardin** [waffleio/waffle.io#3640]
It would be nice to have the option of free form text input for the size/estimate value on a Waffle card. Sometimes, we use 'SMorL` or time (2 days, 1 week, 1 quarter, etc).

**Comment by AnaMSteele** [comment]
We are tracking a card in our backlog to move to more flexible sizing, moving away from fibonacci sequence, so that a team can decide is a 1=S, 3=M, for example. Would that be an acceptable work around for your teams needs? If yes mind adding your vote to #1830? Thank you!
