### ISSUE TITLE
Show linked issues on Waffle cards

### ISSUE THREAD

**Issue by katewardin** [waffleio/waffle.io#3641]
We often use linked issues to track 'sub tasks' for larger epics.  In the Github UI, you can see the linked issues with their status (`open` or `closed`) .  It would be nice to see this status detail in the Waffle cards as well.

Github view: 

![screen shot 2018-08-10 at 8 18 38 am](https://user-images.githubusercontent.com/15126604/43959937-0c6f2292-9c76-11e8-9c45-20d3e212e021.png)

Waffle request:

![screen shot 2018-08-10 at 8 21 44 am](https://user-images.githubusercontent.com/15126604/43960070-7551028a-9c76-11e8-995f-65af91b27fc5.png)

**Comment by AnaMSteele** [comment]
Hi @katewardin check out #3464, is this what you are asking for in your request? If so, want to add comments there and upvote it? Thanks!

**Comment by AnaMSteele** [comment]
@katewardin, let us know what you think about the comment above^, and we will go ahead and close this issue as a duplicate and track your comment in aggregate there. Thank you.

**Comment by katewardin** [comment]
It looks like the other issue was closed, but yeah it looks like that is what we're looking for.  which issue should I upvote?

**Comment by kellihsf** [comment]
@katewardin, oops our mistake! We have re-opened issue #3464 for upvoting. 👍
