### ISSUE TITLE
See time an issue was in a specific column

### ISSUE THREAD

**Issue by cgeissen** [waffleio/waffle.io#3642]
Several teams here would like to report on the time that a specific issue was in a column so that we can measure things like how long was an item blocked (one of our columns aka Git labels), in review etc. We are using Waffle as a Kanban board and several teams have mentioned that this would be useful for them.

**Comment by kellihsf** [comment]
We're already tracking cycle time on [#1574](https://waffle.io/waffleio/waffle.io/cards/5460daa0d613f614d44821b5) so we'll close this as a duplicate. Thanks! :)
