### ISSUE TITLE
Iterate on the design of the WIP limit editor in column settings

### ISSUE THREAD

**Issue by burtonjc** [waffleio/waffle.io#3649]
- [x] create mockups for feedback in design channel
- [x] start implementing chosen design (chose the toggle version)
- [x] confirm design in channel before opening PR (put on staging)
- [ ] make sure to have help docs updated
- [x] add tracking to all right things - check with biz on what to measure

See https://waffleio.slack.com/archives/C0P4DLWQY/p1534185166000333 for more info.

**Comment by marydavis** [comment]
did we get feedback on these designs yet? were they included in the wip limit interviews?

**Comment by burtonjc** [comment]
I know people commented on confusion how to clear/edit WIP limits. I don't believe we showed them the new design though.
