### ISSUE TITLE
label search should not be case sensitive

### ISSUE THREAD

**Issue by scottmmjackson** [waffleio/waffle.io#3653]
For example, for `waffleio/waffle.io`, type `C` to begin `customer requested`. 

Actual:

No results show.

Expected:

All results containing `c` or `C` should show.

**Comment by kellihsf** [comment]
Hi @scottmmjackson,

Thanks for bringing this to our attention. Notes on how to reproduce:

1. Open the filter on the board
2. Select "Labels" on the drop down
3. Try searching for `Customer` vs `customer`
4. Expected to see "customer requested" but instead nothing shows up
![Screen Shot 2018-08-24 at 10.23.17 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/56241220b728ed1d0009af87/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b772b6456f76b7191a379ef0c2952415e49bc30254d58eeb9cb74fce36f34985619e8d3385f70c76e47f9b8861aed09eb73884ad3e3b88c4ec0fa2137a5dad11b61435c52dcbd4f3fb2984cc259f348e44c57a31a3464ee7e3f6e0a.png)

**Comment by scottmmjackson** [comment]
Note that the label search on a card is case-insensitive:

![screen shot 2018-09-05 at 12 29 20 pm](https://user-images.githubusercontent.com/1735264/45107398-79bb3700-b107-11e8-8a55-3e41507268b5.png)

**Comment by scottmmjackson** [comment]
Is this supposed to be fixed in the current live version? Or will there be a deployment soon?

**Comment by scottmmjackson** [comment]
Aha, thanks wafflebot. Verified it works on my end. Thank you for addressing this! 🎉
