### ISSUE TITLE
archiving backed by GH issue data

### ISSUE THREAD

**Issue by aronatkins** [waffleio/waffle.io#3655]
Issue archiving should be backed by GitHub issue data; this allows for management of issues outside of the waffle.io UI.

As noted in #3654, there is no option to archive filtered issues. If issues were marked with an "archived" label, for example, we could work-around #3654 by performing filter-based bulk management in the GitHub UI.

Having an "archived" label would also permit searching by this label in the GitHub UI.

**Comment by aronatkins** [comment]
Performance issues like #3502 and #3186 make it more likely that users will want to fall-back to the GH UI for certain operations.

**Comment by AnaMSteele** [comment]
Howdy @aronatkins we think that bulk archiving by a filter is a solid way to tackle buckle issue changes. We are tracking all bulk action work on card #3629 and have moved your excellent comments over for tracking in aggregate. We are closing this issue, but please feel free to add additional context and upvote on the grouped issue. Thank you!
