### ISSUE TITLE
Label Color is not Consistent

### ISSUE THREAD

**Issue by JTonda** [waffleio/waffle.io#3663]
I created a label in my github project and selected a color for it.  In Waffle, when I add the label to issues, it is only the correct color for some issues while other issues show the same label in a different color.  This makes it confusing to the eye to know what issues have the same labels on them.

**Comment by JTonda** [comment]
Hi @kellihsf,

I think it is actually displaying an incorrect color because when I click on the issue to read the description, the label shows as the correct color when it's expanded.  It's only when it's in the board view that it is inconsistent.

**Comment by JTonda** [comment]
I moved the issues around to different columns and now they have refreshed to the correct color.  I had refreshed the entire page, however, multiple times before this without any change.  I'm not sure why the column move would trigger the correct color to show vs a full page refresh.  Perhaps this is because I changed the label color after already tagging issues with the label.

**Comment by marydavis** [comment]
Hi @JTonda,

Thanks for the extra info, sounds like it was because of the color change before selecting the labels. We cache labels to help with loading times which is why it didn’t update right away. We normally catch when labels are added but it looks like we didn’t catch the color change.
