### ISSUE TITLE
Add a "Need review", "Change requested" and "Reviewed"  actions

### ISSUE THREAD

**Issue by pvdlg** [waffleio/waffle.io#3666]
GitHub allows to request review from a collaborator on a PR. That would be nice to have actions  that would move PRs in a certain column based on review requests:
- Need review: Triggers if a PR has at least one non-fulfilled review request
- Change requested: Triggers if a PR has at least one review request with change requested
- Reviewed: Trigger if a PR has at least one review request and all are fulfilled

This would work like this:
1. Request a collaborator to review => Trigger "Need review" action
2. Collaborator request changes => Trigger "Change requested" action
3. Changes are made and collaborator approve them => Trigger "Reviewed" action
4. Request another collaborator to review => Trigger "Need review" action (go back to need review as 1 review request is approved but not the second one)
5. Second collaborator approve the changes => Trigger "Reviewed" action

**Comment by AnaMSteele** [comment]
@pvdlg What is the use case for these requests? Is it to help notify the team of pending work that has been handed off?

**Comment by pvdlg** [comment]
That would help teams to identify more easily:
- Need review => The work that is blocked waiting for a review (help to avoid situation where completed PRs pile up because they don't get reviewed)
- Reviewed  => The work that is ready to merge (so when one decide to make a release they can easily see the list of PR that are ready and reviewed and could be included in the release)
- Change requested => The work that can be ignored until the collaborator make the requested changes

**Comment by AnaMSteele** [comment]
Currently these statuses are visually represented on the board, not by moving the PR to a different column, but by the color of the circle around the reviewer on the card. Yellow for waiting for review, reviewed and approved is green, and change requested in red. 

Check out https://help.waffle.io/pr-statuses-and-reviewers/pull-request-reviewers-on-cards

Does this meet the use case you are thinking of?

**Comment by AnaMSteele** [comment]
Thanks for the context on your request. We don't have anything planned in the short term that would allow for a column move triggered by what state a review is in, but we are keeping it in mind as we think of how to better address hand-offs within teams. Thank you for sharing your use case.

**Comment by adamzolyak** [comment]
Hi @pvdlg.  Check out https://probot.github.io/.  You'd be able to automate most of your use cases fairly easily.  I'd be happy to pair with you on it to get you started!
