### ISSUE TITLE
support "or" filtering on labels

### ISSUE THREAD

**Issue by aharbick** [waffleio/waffle.io#3667]
I organized our labels around some categories like "priority", "component", "process", etc.  This is a good article that has a similar setup: https://robinpowered.com/blog/best-practice-system-for-organizing-and-tagging-github-issues/

As far as I can tell there is no way to in the existing filter UI to say:

> label=component1 OR label=component2

**Comment by kellihsf** [comment]
Hi @aharbick, 

We're tracking the feature request for OR filters on [#1440](https://waffle.io/waffleio/waffle.io/cards/54208c21d613f614d446694a). We'll move your comments over to that issue and close this one as a duplicate. Thanks! :)
