### ISSUE TITLE
Cross-repo dependencies fail on refresh

### ISSUE THREAD

**Issue by Kyle-Woodworth** [waffleio/waffle.io#3670]
Hi,

Per this: https://help.waffle.io/dependencies/can-i-have-issues-from-other-repositories-in-my-dependency

I added a cross-repo dependency from one waffle board to another.  It worked, displaying the appropriate status in the issue in the other waffle board; however, upon refreshing the board in which the dependency is not written in, it disappears and no reference exists except for in the issue the dependency is declared in.

**Comment by kellihsf** [comment]
Hi @Kyle-Woodworth,

What you're seeing is the expected behavior. Because both boards aren't connected on the other board, we won't show that dependency.
