### ISSUE TITLE
Unable to open card from URL link

### ISSUE THREAD

**Issue by kellihsf** [waffleio/waffle.io#3672]
example: https://waffle.io/waffleio/waffle.io/cards/5b844675e02b58001d39da90

If you click the link, it will take you to the board but won't open the card

**Comment by BAMason** [comment]
![Screen Shot 2018-09-06 at 15.25.48.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5ab2c6ef09345f0011eaa189/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b772a6454f56b7191a379ea0c2954415b46be5d4a1f06a3a3dc78e2a436628f5e5eedd56c0c22933d15a9ea8a4eec02bf76de4b83b4bc9850d2aa6c7bb3d4d216744b470a83ed5f35aa984ecb5ef44de84f50ad133162f43b.png)

**Comment by kellihsf** [comment]
reported in [intercom](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/inbox/unassigned/conversations/18381149548)
