### ISSUE TITLE
configure wafflebot to ignore pull requests OR link the PR to the originating issue

### ISSUE THREAD

**Issue by aharbick** [waffleio/waffle.io#3677]
For planning purposes we use issues.  Development creates a feature branch, does work, and creates a PR.  So far so good.

The trouble is that Wafflebot only manages the state of PRs putting them into "Code Review", "Ready to Release", etc. and since it doesn't manage the state of the linked issue you end up with confusing status of our board where you have a PR that is "Ready to Release" with the matching issue still in "Code Review" or "Acceptance".  So we have to do manual work to sync up the state thus making the value of the helping hand from wafflebot less useful.

TBH, I'm not really sure of the value of seeing the PR on the board anyhow.  In our case with 4-6 issues in progress at once and potentially at least that many matching PRs our board looks way more complicated than it needs to (so I often filter PRs which further compounds the synced state problem because I don't see the problem)

I would propose a few ideas:

1.  Make it possible to configure Waffelbot so that it ignores PRs
2.  Have Wafflebot be smart and when it moves the status of PRs have it also move the corresponding issue.
3.  Similar to how you can link an issue to an Epic with the "child or XXX" DSL... maybe you can do something similar with PRs?  So that an issue and it's matching PRs shows up as attached to the card/issue.

**Comment by adamzolyak** [comment]
@aharbick have you tried connecting Issues to PRs using [closing](https://help.waffle.io/faq/waffle-workflow/use-github-closing-keywords-to-connect-prs-to-issues) or connecting keywords?

**Comment by aharbick** [comment]
Oooohhhh!  I didn't know about that.  I think that might make the rest of this idea irrelevant.  Thanks for the tip (and cheatsheet)!
