### ISSUE TITLE
out of place element?

### ISSUE THREAD

**Issue by GeorgiosP** [waffleio/waffle.io#3712]
https://cl.ly/19d3177bcbcc

when you scroll up there seems to be an element sitting at the top of the page it does not cause issues  just seems to be out of place. 😄

**Comment by AnaMSteele** [comment]
Hi @GeorgiosP thanks for sending this our way. It is a known issue and since it doesn't take anything away from the user's view we haven't prioritized it into our near term roadmap to fix. We are going to close this issue for now since we are aware! Thanks again for sending the feedback our way.
