### ISSUE TITLE
Karate to review

### ISSUE THREAD

**Issue by ngouldman** [waffleio/waffle.io#3716]

**Comment by ngouldman** [comment]
App-Api: review and update tests
Football-api: review and update tests(get pl clips media items)
Editorial-api: keep tabs on tara's branch
Interactive-selector-api: in progress

**Comment by kellihsf** [comment]
![karategif](https://user-images.githubusercontent.com/4775572/48274609-ef41cd00-e400-11e8-9642-1cc515d53d73.gif)
