### ISSUE TITLE
Identify status checks for providers who have restricted 3rd party access

### ISSUE THREAD

**Issue by BAMason** [waffleio/waffle.io#3742]
Currently there are some providers (ex: CircleCI, WIP check) who have restricted 3rd party access.  This means Waffle cannot display these items and results in the following GraphQL error:
```
GraphQL error: Although you appear to have the correct authorization credentials,
the `<name>` organization has enabled OAuth App access restrictions, meaning that data
access to third-parties is limited. For more information on these restrictions, including
how to whitelist this app, visit
https://help.github.com/articles/restricting-access-to-your-organization-s-data/
```

We need to find a way to preemptively identify these checks and show an impartial status (neither passing, failing, nor in progress) so we aren't blocking other checks, but aren't presenting inaccurate data either.

**Comment by Alisuehobbs** [comment]
Resolved https://github.com/waffleio/waffle.io-app/pull/2179
