### ISSUE TITLE
Github's beta : transfer issue does not work

### ISSUE THREAD

**Issue by sriv** [waffleio/waffle.io#3760]
https://github.com/getgauge/gauge-vscode/issues/315 was transferred to https://github.com/getgauge/gauge/issues/1280 using github's transfer issue feature.

Github redirects to the new target. Waffle recognizes the new issue.

Problem: waffle.io/getgauge/gauge shows "315" as a card in "In progress" lane, and I am unable to move it.

Note that on opening the card, waffle is able to honour the redirect and open the new issue.

**Comment by sriv** [comment]
Thanks for the tip on "Delete Card", @marydavis  - I did not know that before.

I also understand the limitation from waffle's side on this feature. Am happy for this issue to be closed unless you think otherwise.

Cheers!

**Comment by marydavis** [comment]
Glad it worked and thanks for your understanding :)
