### ISSUE TITLE
If a ticket has been deleted in github, it should disappear from my waffle

### ISSUE THREAD

**Issue by bess** [waffleio/waffle.io#3827]
Github has a new beta feature: delete issue. But when I delete an issue github leaves a placeholder object in its place. In waffle, this results in a card that cannot be moved or edited.

**Comment by marydavis** [comment]
Hi @bess - unfortunately since it is a beta feature it doesn't always work seamlessly on our end yet. When this happens, you can manually delete the Waffle card. Here are the instructions: https://help.waffle.io/faq/general-support/can-i-delete-cards-from-my-waffle-board
