### ISSUE TITLE
Quick-clear of all filters

### ISSUE THREAD

**Issue by llmartinll** [waffleio/waffle.io#3828]
'clear all filter' button on the home-bar. ('reset board')

Why? (UX)
- Less clicks for a often-used action
- When you click f.e. on a 'Required by #xxxx" and it filters anything related to that issue it is very counter-intuitive / cumbersome to either re-click the 'required by' link, or to press the filter icon and click 'clear all'

**Comment by marydavis** [comment]
I've got good news @llmartinll - we have a keyboard shortcut for that :) Pressing `shift + f` will clear all filters.
