### ISSUE TITLE
Filter issues when clicking on the bookmark icon of parent issues

### ISSUE THREAD

**Issue by janaagaard75** [waffleio/waffle.io#3829]
Right now it is possible to filter issues on the Waffle board by clicking on the outline bookmark icon that child issues get.

I would like to also be able to do the same when clicking on the filled out bookmark icon that parent issues get.

**Comment by marydavis** [comment]
Hi @janaagaard75 - you can get the same filter by clicking on the progress bar of the parent epic issue :) We chose not to make it the icon because it is so close to the clickable number which doesn't give it a lot of separate click area.

**Comment by janaagaard75** [comment]
Oh! Thanks for the tip. 👍
