### ISSUE TITLE
Milestones are created only for one repo of project

### ISSUE THREAD

**Issue by maptuhec** [waffleio/waffle.io#3830]
When you have a project with one or more repos attached and creating a new milestone, the milestone is created only for one of the repos, and not all of them which I find strange. It should create the milestones for all of the repos/cards in one board

**Comment by marydavis** [comment]
Hi @maptuhec - we don't automatically create the milestone across all connected repos, but we do add it to the milestone dropdown for all cards across all repos. If you select that milestone from the dropdown on a card in a repo that doesn't have it, it will then be created in that repo :)

**Comment by maptuhec** [comment]
Hey @marydavis, actually if for example, I have created a milestone for repo 1, and try to add this to a card, in the same board, for repo 2, there is an error saying "unable to set milestone" or something, and I should go manually create the milestone for repo 2
