### ISSUE TITLE
Two things on Poetic Learning landing page

### ISSUE THREAD

**Issue by ameliatheo** [waffleio/waffle.io#3845]
Poetic Learning landing page:
1. The quotes in the top right corner are old and we want to update them -- but we can't see where they are changed on the back end. 

2. The sections at page bottom ('For Teachers' etc.) also need changing and we can't find where to access this on the back end.

Please advise if this is something I can do myself. 

https://redroomcompany.org/education/

**Comment by marydavis** [comment]
@ameliatheo I think this was accidentally created on our Waffle.io board.
