### ISSUE TITLE
Issue Linkings

### ISSUE THREAD

**Issue by AdamBCo** [waffleio/waffle.io#43]
ooks good so far, but it's missing one critical feature - issue linking. Often times, someone opens an issue (#50), and someone else fixes in (#54) and then the two issues are linked via github (and closed at the same time).

If you look here: http://www.waffle.io/acrmp/chefspec #158 fixes #118, but there's no indication of that on the board. It would be nice to see them nested in some way.

**Comment by pnpritchard** [comment]
+1

**Comment by kellihsf** [comment]
We now support linking one issue to another! Check out our [FAQ page](https://help.waffle.io/faq/waffle-workflow/can-i-link-two-issues-together) on how this works.
