### ISSUE TITLE
Be able to estimate issues with story points

### ISSUE THREAD

**Issue by aaronrenner** [waffleio/waffle.io#436]

**Comment by agibson22** [comment]
[+1](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/665040321)

**Comment by agibson22** [comment]
[+1](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/676553626)

**Comment by agibson22** [comment]
[+1](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/684523017

**Comment by marydavis** [comment]
We just released the ability to add size estimates to cards behind a feature toggle so we can fine tune it before a full release. We chose to only use Fibonacci numbers 1-100. If you would like to give it a try, just send us a message within Waffle (by clicking the ? in the sidebar) to let us know and we will turn it on for you. Your team members will not see the size functionality unless we also toggle on the feature for them as well. We would appreciate the feedback, thanks!

**Comment by marydavis** [comment]
we just added the option to toggle on size estimates for an entire project if you would rather that instead of per user :)

**Comment by joostdevries** [comment]
@marydavis sent you an e-mail on your GH address with a small feedback point.

**Comment by miraculixx** [comment]
I very much like this feature. Is there a way to back-propagate the size estimate to github? It would be great to have the story size as labels (e.g. size-1, size-3, etc.).

**Comment by mpgerlek** [comment]
Adding sizing was a great idea - but...

(1) Not everyone uses Fibonacci numbers. Any chance of supporting T-shirt sizing?

(2) +1 to the idea of pushing the data back to github as labels

**Comment by marydavis** [comment]
@mpgerlek - we have issues created for both of these requests :) #1753 for adding t-shirt sizes and #1720 for creating GitHub labels from the sizes.

**Comment by robcaw** [comment]
+1 @miraculixx

**Comment by johnmurphy01** [comment]
This is great! But how are the hours burned? For instance, if I have a story that's 8 points and we say a typical development day is 6 hours. The developer finishes most of the story on day 1 but can't actually close the issue until day 2. The burndown will indicate that no work was done on day 1 when in actuality, the majority of the work was done.

**Comment by justinmcmichael** [comment]
+1 for story points. We are currently using zenhub, which is far too expensive for such a simple feature.

@johnmurphy01 in general actual time isn't an issue. The story points as a measure of perceived difficulty tend to average out over time. In your case, you would notice that what should have been a simple task took longer than expected, so as a manager you would know who to ask, and ensure that a comment is made on the issue in question. In terms of the milestone itself, it should not make a difference. The person who worked on that task can likely start working on another task in the meantime.

**Comment by johnmurphy01** [comment]
@justinmcmichael sure, time measurement isn't necessarily critical in Agile processes. But I've not ever been involved in one where the general "hours to story points" measurement wasn't at least approximated.

Ideally for the way I track Agile projects, I would be nice to have a place where developers can burn their hours against each issue/task. If this feature was available, it would be clear to see via a burndown chart exactly how much work was done the previous day and then compare the "estimated" story point to hours ratio and then determine whether a developer took on too much or not enough.

**Comment by Alinutzav** [comment]
+1
