### ISSUE TITLE
CI/CD integration

### ISSUE THREAD

**Issue by ashumz** [waffleio/waffle.io#494]
- [ ] show build status on PRs (also tracked [here](https://github.com/waffleio/waffle.io/issues/746))
- [ ] move cards based on deployment events (have a column track deploys to staging, etc)

Support multiple CI/CD systems by integrating with GitHub's status API. Include:
- TravisCI
- Codeship
- CircleCI

**Comment by KalleDK** [comment]
+1

**Comment by burtonjc** [comment]
:+1: [from intercom](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/696153314)

**Comment by agibson22** [comment]
[+1](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/697866476)

**Comment by CodeMan99** [comment]
:+1: Additionally a really cool sub-feature could be triggering a build when a certain label is added.

**Comment by ashumz** [comment]
+1 from @luan-cestari

**Comment by arpunk** [comment]
:+1:

**Comment by aaronmallen** [comment]
:+1:

**Comment by byannoni** [comment]
:+1:

**Comment by bbirch** [comment]
:+1:

**Comment by p404** [comment]
:+1:

**Comment by Kmaschta** [comment]
:+1:

**Comment by keynmol** [comment]
:+1:

**Comment by ruuts** [comment]
:+1: support for semaphore would be nice.

What you can also do without the need of building integrations with CI services:

![bookingexperts-website 2015-09-11 13-17-17](https://cloud.githubusercontent.com/assets/468526/9813635/97ec47ae-5887-11e5-9fa2-82b70d20cb20.png)

Since our CI deploys the "staging" branch to our "staging server" (same for master) we have an indication of where the issue is.

**Comment by Hiroyou** [comment]
:+1:

**Comment by ignatiusreza** [comment]
:+1:

**Comment by pvcarrera** [comment]
:+1:

**Comment by P8H** [comment]
+1

**Comment by rubbish** [comment]
:+1: for this. Even if it's a little green/red light next to the PR description, it'd be very useful.

**Comment by sabbyanandan** [comment]
:thumbsup:

**Comment by GaelVaroquaux** [comment]
:+1:

**Comment by sibson** [comment]
+1

**Comment by forivall** [comment]
:+1:

**Comment by laughedelic** [comment]
:+1:

**Comment by dogeared** [comment]
:thumbsup:

**Comment by aaronmallen** [comment]
+1

**Comment by ro-savage** [comment]
+1

**Comment by forivall** [comment]
I think we can switch to using comment reactions now. (Too bad they haven't been added to the mobile interface yet)

**Comment by kenmellem** [comment]
+1

**Comment by LuisBurgos** [comment]
+1

**Comment by daneov** [comment]
👍

**Comment by homeyer** [comment]
Shipped!
