### ISSUE TITLE
make going to an issue on GitHub more intuitive - clicking modal header is hard to find

### ISSUE THREAD

**Issue by marydavis** [waffleio/waffle.io#582]
Expose that you can 'command + click' on the issue number or comment icon from the board to open the issue in GitHub in a new tab.

**Comment by Gouthamve** [comment]
+1

**Comment by ashumz** [comment]
[internal conversation](https://www.flowdock.com/app/rally-software/rudder/threads/4-50aRdVQlB1OaRIY8po2rZTDw2)
