### ISSUE TITLE
update issues in column when column label is changed

### ISSUE THREAD

**Issue by marydavis** [waffleio/waffle.io#593]
the current behavior is if you change a label name for a column, the label does not change in GitHub. All issues move from that column to the backlog as a result. You can rename the column back to its original name, but you will lose all ranking.

**Comment by ashumz** [comment]
a customer ran into this issue and lost all of their ranking [here](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/694910715)
