### ISSUE TITLE
support multiple done columns, so users can track work after an issue has been closed/is code complete

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#616]
Our users want to close issues when they're "code complete", which makes sense especially for Pull Requests. After being closed, you should be able to have columns after "done" like "released", or "toggled on for x". 

AC:
- [ ] toggled so we can beta before releasing to the wild
- [ ] allow multiple columns to represent closed issues
- [ ] rename "Complete" section in column editor to "Done", and add a new section for closed columns called "Code Complete" Columns in this section are for closed issues, and columns need labels.
- [ ] The right-most column, in the "Done" section, still auto archives after 30 days. Update the column editor to say this. It's allowable to delete this column (as it is today). The right-most column does not have a label (like the left-most column).
- [ ] draggable pills for collaborator pr start and such can't be assigned to closed columns
- [ ] board works with closed columns

**Comment by burtonjc** [comment]
:+1: [from intercom](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/696132943)

**Comment by agibson22** [comment]
[+1](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/696853506)

**Comment by burtonjc** [comment]
:+1:  [from intercom](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/jacob@waffle.io/conversations/699004964)

**Comment by daniel-garcia** [comment]
+1

**Comment by rbg** [comment]
+1

**Comment by daniel-garcia** [comment]
This issue is 11 months old. Any estimate of when/if this will be done?

**Comment by drewwells** [comment]
:+1:

**Comment by wli** [comment]
+1

**Comment by ashumz** [comment]
[+1](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/757490289)

"My reason for asking is that I have a "Demo" column. A card should be able to be in the demo state even if the pull request has been merged. Currently I can't find a way to move the card out of the "Done" column and into that column after the pull request has been merged."

**Comment by ashumz** [comment]
@daniel-garcia we are focused right now on shipping an on-prem version of Waffle, but are still organizing and reviewing the feedback we're receiving for this request. The most helpful thing you (or anyone following this issue!) can do to help us define this work and get it moved along sooner than later would be to define your use case, so when the time comes for us to pull this work, we'll have as much information to solve as many of your problems around this as possible. 

Thanks for checking in with us! We're working hard to continually improve Waffle for you all. 

Ashley

**Comment by daniel-garcia** [comment]
Our use case:

We want to define a workflow with the following states:
```
new -> backlog -> in progress -> fixed -> verified
^                            ^   ^               ^
+------------ open ----------+   +--- closed ----+
```

Developers need to be able to use the "fix #XXX" grammar in their commit messages. QA then picks up fixed tickets and verifies them.

**Comment by ashumz** [comment]
+1 for the purpose of having one closed column for all merged PR's and one closed column for closed PR's. +1 request for the purpose of having a "closed - won't fix" column, in addition to a regular Done column.

**Comment by jakehow** [comment]
@ashumz this is a blocking issue for us as well.  There should just be a setting on the column (show closed issues), the use case shouldn't really matter that much.

Our states in our kanban workflow are Backlog -> Design -> Code -> Review -> Sandbox -> Production

Issues and PRs in Sandbox and Production are both 'closed' from GitHub's perspective, but still need to be visible on our board.

**Comment by penne12** [comment]
+1 

Also, @ashumz, I love the won't fix idea

**Comment by nditada** [comment]
+1 same issue here, we have a verification step by the QA team before we move things to production. I added the lane and went all happy to start using waffle when I realized it doesn't work. Bloking issue for us, a real pity.

**Comment by MattiSG** [comment]
+1

[Our process](https://github.com/sgmap/mes-aides-ui/blob/master/CONTRIBUTING.md#processus) includes “deployment” and “communication” before a task is done, even though it is “code complete” and thus closable as an issue.

The current setup means there's either duplication in all columns that close, or that the issue has to stay open, adding a lot of noise for devs.

Unless there's a roadmap on this issue, this is probably a no-go for Waffle  :(  Technically, it seems to be only about keeping the “track tags” logic even when the “closes issue” trigger is on.

**Comment by aaronmallen** [comment]
:+1: we have a column "Closed (Broken)" which gives a tag `wontfix` it would be nice if the logic flowed like:

```
if issue.closed? & issue.has_label?
  if issue.label == column.label
     column.where(issue.label == column.label)
  else
    close_column
else
  closed_column
```

**Comment by SimonCropp** [comment]
please add this feature

**Comment by mbulkeley** [comment]
+1

**Comment by stepthom** [comment]
+1

**Comment by jtgrenz** [comment]
We could also use this. We have a usecase where we review submissions and need two close columns to apply labels. Our last step for closing is to move a card into "Launched" or "Rejected" if the review failed and we wish to scrap it. Right now we can move to a rejected column and add a tag but keep the issue open, or we can close it and add no label.  Throws off our stats unless we manually add a label before moving it.

**Comment by bcardiff** [comment]
+1 having a more that one column for done make sense. If labels are allowed together with "close issue", a column with done and without label should list only closed issue without any label issues in the others close enabled columns.

**Comment by kefirchik** [comment]
:+1: This can be easily used for roadmaps

**Comment by mrucevic** [comment]
+1

**Comment by waj** [comment]
+1

**Comment by nditada** [comment]
@ashumz We also have the same use case as @daniel-garcia, we need a few columns for QA steps to track already closed issues. This is not only a blocker for us, but also none of your competitors seems to get it either. I've checked huboard, zenhub, over.io and codetree.com. You'd have a great differentiator if you were the first to implement this ;-)

**Comment by nekron** [comment]
+1

**Comment by pmallol** [comment]
+1

**Comment by wplu** [comment]
+1

**Comment by lherich** [comment]
+1

**Comment by liddellj** [comment]
:+1:

I'd love to see this as well. In my case - I'd like to basically rename the existing 'Done' column to something like 'Pending Deployment' or 'For Review' - so that I can track the workflow of promoting a feature from our staging environment (which is automatically deployed to), to our production environment.

**Comment by jwhitehorn** [comment]
I originally expressed my interest in this over a year ago. However, due to not being able to properly track the difference between things being done from a development perspective, versus done from a QA perspective, I'm sorry to say, but I've entirely stopped using Waffle.

**Comment by nekron** [comment]
@jwhitehorn May I ask what are you using right now? I see no other competitor, nor paid nor free, that supports this functionality.

**Comment by jakehow** [comment]
This just got merged in huboard, but not sure if it solves the problem -> https://github.com/huboard/huboard-web/pull/102

**Comment by burtonjc** [comment]
:+1: [from intercom](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/1294938405)

**Comment by johnsonryan** [comment]
Just ran into this as our team started using Waffle.io, we have added "Staging" and "Production" columns after the Done column. We can't currently track changes after an issues has been closed or moved into the Done column. Because it will reopen the issue.

**Comment by sandieq** [comment]
+1 - would like to be able to look at items that are closed more than a week, in particular since we use our sprint numbers as Milestones, it would be great to be able to pull back in all the closed items from a given sprint. Thanks.

**Comment by MakotoTheKnight** [comment]
:+1: - I'd love to see this implemented.

We're using Waffle and we've recently had to incorporate an extra branch to help with our workflow, one that represents a "on staging" state for the code.

Not being able to have this does slow us down a bit given that we want to use [a bastardized version of] Git Flow, and it'd be nice to know what state our work is in.  I feel like having this feature in place would be very beneficial.

**Comment by shadowbq** [comment]
for staging and release (+1)

**Comment by kapkema** [comment]
:+1:  would love to have staging and release to the right of done.

**Comment by suriyanto** [comment]
:+1:

**Comment by trestletech** [comment]
Yes, please!

**Comment by gappleto97** [comment]
+1. I'd love to have a column for failed or rejected ideas. Marking them as done feels dishonest.

**Comment by burtonjc** [comment]
:+1: [from intercom](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/5195174735)

**Comment by virtser** [comment]
+1

**Comment by srjefe** [comment]
+1

**Comment by kellihsf** [comment]
from issue [#2726](https://github.com/waffleio/waffle.io/issues/2726):

'Currently, as soon as I merge a PR, it's moved into the `Done` column, but I would like to have intermediate columns `To deploy to staging` and `To deploy to production`.

Is it possible to do that?

With the current system, I need to open an issue, connect the PR to the issue, and close the issue when it's in production. But I have no way to know if I have to deploy to staging or production.

The workflow would be:
`backlog` > `ready` > `in progress` > `in review` > `to deploy to staging` > `to deploy to production` >` done`'

**Comment by GilGald** [comment]
+1

**Comment by robtassl** [comment]
👍

**Comment by robtassl** [comment]
In our dev process, we create feature and bug fix branches as our working branches and then create pull requests to our staging branch for code review, once its been approved, then it's merged into our staging branch and deployed to our staging server, where it is reviewed by our sales team, and then finally merged into master once approved by our sales team. Being able to tie specific branches to specific board columns would really improve this product, and allow for much more versatility. This way I could have a code review column, that contains issues that are in pull requests for my staging branch, I could have a demo column that contains issues that have been merged into my staging branch, and then finally, the live/demo column, for issues that have been closed/merged into master.

Is there a timeline for when to expect a feature like this? My team is current looking to change our project management application, but this is a pretty key feature for us.

If this isn't a feature you plan on adding anytime soon, are you accepting pull requests? My team might consider contributing if it would help get this feature out sooner.

**Comment by kevinroche** [comment]
+1

**Comment by corleygr** [comment]
+1

**Comment by GeoffreyPlitt** [comment]
+1 Needed badly, we're doing a weird work-around right now.

**Comment by chrowe** [comment]
Our current process keeps the issue open until it is deployed to production and tested there. This means that we can not use Waffle Metrics in any meaningful way since all issues tend to get closed together after live QA.

The ideal fix for this would be to add one of the little things like you have for "Work Started"
![screen shot 2017-02-22 at 3 52 41 pm](https://cloud.githubusercontent.com/assets/240115/23231769/04144202-f917-11e6-9d7c-bd3db3eebb46.png)
that marked when an issue was considered done by metrics. It could be independent of when an issue was actually closed in Github.

**Comment by bjhartin** [comment]
+1 This is sorely needed.  'Done' ends up including all kinds of closed things which are not for my team, since I can't specify a filter on 'Done'.

**Comment by MichielLeyman** [comment]
I too would love me some more done columns :)

**Comment by homeyer** [comment]
⛵️ Shipped! https://blog.waffle.io/tracking-work-after-done-6a94594f0be7

Head over to your board settings to create columns in the "Closed" section to track issues after they're closed.

![image](https://user-images.githubusercontent.com/84629/33673653-9e35a210-da6a-11e7-9e82-0d20ff0fa018.png)
