### ISSUE TITLE
be able to edit column descriptions

### ISSUE THREAD

**Issue by burtonjc** [waffleio/waffle.io#626]
Be able to customize text, ie: Ready's text of "Place issues in this column when they are ready to be worked on."

**Comment by ashumz** [comment]
[+1](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/all/conversations/625209566)

**Comment by ashumz** [comment]
[+1](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/724406191)

**Comment by jpirkey** [comment]
+1

**Comment by CodeMan99** [comment]
:+1:

**Comment by conklinbd** [comment]
+1

**Comment by SteveALee** [comment]
+1
I just noticed with another column set a backlog the backlog column still says all open issues go here.  Automatically updating that is a second issue I guess
