### ISSUE TITLE
support badges for closed issues - connects to #3288

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#631]

**Comment by zbeekman** [comment]
:+1:

**Comment by chevdor** [comment]
:+1:

**Comment by Alisuehobbs** [comment]
Great news! We've updated our badge to be customizable with all columns. Check out our help doc for instructions on how to get the new badge and let us know what you think!

https://help.waffle.io/faq/github-badge/where-can-i-find-the-code-for-my-github-readme-badge
