### ISSUE TITLE
add issue - with details option so the description, milestone, and/or labels populate when the card is created

### ISSUE THREAD

**Issue by ashumz** [waffleio/waffle.io#694]
requested by neovim also because when you submit an issue, subscribers get an email - but if you do this via Waffle, the email does not have all of the relevant details yet because the description has not yet been filled in.

**Comment by burtonjc** [comment]
[+1](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/681393797)

**Comment by AntoineInsa** [comment]
+1

**Comment by ZCJ** [comment]
+1

**Comment by mohierf** [comment]
+1

**Comment by kwiens** [comment]
+1

**Comment by ashumz** [comment]
Quick update on the completion of this: #1553 (Add issue with labels) is in progress now which completes the scope of work for this epic. If you'd still like to follow "Add issue with assignee", please subscribe to issue #1554 in the backlog. 

Thanks! 

Ashley
