### ISSUE TITLE
ability to add new labels in Waffle

### ISSUE THREAD

**Issue by ashumz** [waffleio/waffle.io#695]
fixes #3029

**Comment by cweber** [comment]
+1

**Comment by roll** [comment]
:+1: for new issue with a label as much needed and pretty simple to implement

Just one move to add a card with right milestone and labels to the right column. Now it's about 5 moves.

**Comment by AndyWendt** [comment]
:+1:  This would be pretty nice to be able to add issues from the create issue dialog

**Comment by andrewvt** [comment]
+1 - this is one of the few things I always have to jump over to github to accomplish.  Would really improve my workflow to do this all within waffle.

**Comment by colinurbs** [comment]
+1

**Comment by gbrand802** [comment]
+1

**Comment by lhavel** [comment]
+1

**Comment by tansaku** [comment]
+1

**Comment by lightstrike** [comment]
+1

**Comment by qswinson** [comment]
+1

**Comment by RumbleFrog** [comment]
+1

**Comment by homeyer** [comment]
From the card detail view you can now create labels! 🎉
You can also pick labels from other repos on a multi-repo board.

![image](http://g.recordit.co/iknVdDiCKT.gif)
