### ISSUE TITLE
build status on pull requests

### ISSUE THREAD

**Issue by joshrtay** [waffleio/waffle.io#746]

**Comment by homeyer** [comment]
This depends on #1562. Once that's there, should be fairly trivial to show more PR info on PR cards and slivers.

**Comment by ashumz** [comment]
[+1](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/andrew@waffle.io/conversations/709881620) for showing more information on PR's (ie: branch name, and linking to the branch itself)

**Comment by ryansch** [comment]
:+1:

**Comment by davidmiller** [comment]
+1 for showing build status !

**Comment by hughsaunders** [comment]
I'd like to see build status for all PRs connected to an issue.

**Comment by Jwata** [comment]
+1
I also would like to see review status for all PRs.
related to #2787.

**Comment by kellihsf** [comment]
Hi all!

We now show build status on PRs! Read more about it on [our blog](https://blog.waffle.io/image-upload-build-status-and-pull-request-reviewers-oh-my-a61c25015e3f). 😀
