### ISSUE TITLE
Document/expose Waffle "Best Practices"

### ISSUE THREAD

**Issue by ashumz** [waffleio/waffle.io#761]
This would be a great way to tell teams what behavior to expect on their boards, how they can best handle pull requests and how they move across the board, etc. Maybe also some info around using milestones and multirepo. Not sure the best place to do this - maybe a blog post and then link to Intercom in initial onboarding message

**Comment by therobhayes** [comment]
+1  would really enjoy this - or even having some example boards that you can copy into your org to help you get up and running in the 'correct' way, before you find out what works best for your team.
