### ISSUE TITLE
"comment and close" an issue from the card detail modal

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#828]

**Comment by jasonkarns** [comment]
:thumbsup: We have a board where having a 'Done' column doesn't make sense. We don't need to keep cards visible once they've been closed, so the done column exists only for the purpose of having a means to close the ticket. If we could close the ticket from the modal (or other) then we could remove the 'Done' column from our board entirely.

**Comment by kintso** [comment]
:+1:

**Comment by pjf** [comment]
+1 from me as well. We have so many columns that the 'done' column is often off-screen.

**Comment by tophersimon** [comment]
+1

**Comment by tobalsgithub** [comment]
+1 Our "Done" column is off the screen. Would really appreciate a close button.

**Comment by zspencer** [comment]
Also want a close button :)

**Comment by antoineazar** [comment]
:+1:

**Comment by homeyer** [comment]
shipped!

**Comment by pjf** [comment]
@homeyer : Hooray! Thank you!
