### ISSUE TITLE
better handling and/or prevention of badge pull request errors when default branch != master

### ISSUE THREAD

**Issue by ashumz** [waffleio/waffle.io#842]
in our pull request handler, we assume there is a base of 'master' for our badge PR to be merged into, but this is not always the case.  similarly, if the default branch is set to anything besides master, our pull request will fail because the head is set to be 'waffle-iron:master' which will not be the case if a default branch other than master is set.

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
