### ISSUE TITLE
cards created while filtered by milestone don't show up until you clear the milestone filter

### ISSUE THREAD

**Issue by burtonjc** [waffleio/waffle.io#849]
This is just a bad UX. Some options we could explore:
1. showing the card and then having it fade away
2. assign the card to the current milestone selection (what if multiple milestones are selected?)

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
