### ISSUE TITLE
Condensed, compact board view (aka a list view of cards)

### ISSUE THREAD

**Issue by agibson22** [waffleio/waffle.io#885]

**Comment by ivarpruijn** [comment]
+1

Especially on the tablet that we use during standup this would, with a team of about 10 people, this would help a lot to see all the issues in one view.

**Comment by AnaMSteele** [comment]
We think this issue has been addressed with the UI changes we have implemented since this issue was first opened. If you disagree, please leave a comment so we can see this arrive back on the board for consideration.
