### ISSUE TITLE
scrollbars displayed over pop up windows

### ISSUE THREAD

**Issue by Nashev** [waffleio/waffle.io#886]
On Android Chrome

![screenshots_2014-04-30-09-33-37](https://cloud.githubusercontent.com/assets/190140/2838061/c650ae06-d029-11e3-8a00-57887b1fd6c7.png)

**Comment by globexdesigns** [comment]
Happens for me as well on Windows 7, Chrome 42.0.2311.152

**Comment by kellihsf** [comment]
[customer reported](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/1689741411) same behavior

**Comment by rikai** [comment]
Can also confirm on the latest chrome stable:
![yep](https://sc-cdn.scaleengine.net/i/545270a999aa38c43002ab1f32b60687.png)

**Comment by kellihsf** [comment]
another user reported via [intercom](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/1841049916)

**Comment by rikai** [comment]
This still isn't completely fixed, here's an example:
![example of issue](https://sc-cdn.scaleengine.net/i/5e7b4d9525de79ced3d61951f43b5c9e.png)

**Comment by rikai** [comment]
Can this please be reopened with the issue stated above still existing?

**Comment by homeyer** [comment]
@rikai, which browser and version?

**Comment by rikai** [comment]
Latest chrome stable version.

**Comment by marydavis** [comment]
sorry @rikai - having trouble replicating, which OS are you using?

**Comment by rikai** [comment]
Windows 7

**Comment by rikai** [comment]
Easiest way to reproduce this from what i'm seeing is to give the second column a bunch of stuff to give it a scrollbar and then to click the add issue dropdown button at the top. The scrollbar will overlap that dropdown.
