### ISSUE TITLE
link multiple repositories to view separatelly

### ISSUE THREAD

**Issue by Nashev** [waffleio/waffle.io#887]
I have linked my own project - that's good
I can see and update waffleio/waffle.io repository by direct link and this good too.
But I can't swich between them by combobox at the top of waffle's page, because there are only my project even if I look at https://waffle.io/waffleio/waffle.io page!

I try to setup additional repos at page https://waffle.io/nashev/multipult/settings/sources, but it is about combined view of additional repos for my own repo.

Please add abiluty to add any projects to that combobox and swich to them without any combining!

**Comment by kellihsf** [comment]
hi @Nashev,

We believe this issue is resolved. Please let us know if you're still experiencing this behavior or open a new issue on our board. Thanks! :)
