### ISSUE TITLE
create flat version of badge

### ISSUE THREAD

**Issue by marydavis** [waffleio/waffle.io#902]

**Comment by jgranick** [comment]
I would love to see this as well, just removed the Waffle.io badge from the primary repository, because I want flat badges and it clashes too much. Thanks guys

**Comment by askmatey** [comment]
+1

**Comment by metaraine** [comment]
+1

**Comment by bmpvieira** [comment]
+1

**Comment by deepsweet** [comment]
:+1:

**Comment by Gabriel-p** [comment]
+1

**Comment by brollb** [comment]
check out img.shields.io: [![waffle](https://img.shields.io/waffle/label/evancohen/smart-mirror/ready.svg)](https://img.shields.io)

**Comment by homeyer** [comment]
Thanks to @evancohen, Waffle has shields.io support for badges, with built in flat styles!

If you’d like to use a shields badge for Waffle, use the pattern `https://img.shields.io/waffle/label/:owner/:repo/:label.svg`. This currently only works for public boards, and doesn’t support the backlog or done columns.

Here’s what a badge for Waffle’s “current iteration” column looks like: 
![badge](https://img.shields.io/waffle/label/waffleio/waffle.io/current%20iteration.svg)

The color of the badge matches the label’s color in GitHub (sweet!).

A few other style options are available, like a flat square version: 
![flat badge](https://img.shields.io/waffle/label/waffleio/waffle.io/idea.svg?style=flat-square)

Just append `?style=flat-square` to the URL.

All of the style options are defined here: http://shields.io/#styles

We’re prioritizing some additional badge enhancements, tracked on this milestone: https://github.com/waffleio/waffle.io/milestone/107
