### ISSUE TITLE
add ability to create new milestones in Waffle

### ISSUE THREAD

**Issue by marydavis** [waffleio/waffle.io#909]
create title and due date in milestone picker from detail modal and new issue, using graph date picker - same interaction as labels

**Comment by Auruss** [comment]
+1

**Comment by mohierf** [comment]
+1 for creating milestones through connected repos ! 

One board with 8 repos connected ... it is really boring to iterate through all repos ...

**Comment by austin881** [comment]
**+1**
It would be great to be able to just start typing and then ask if a new milestone should be created and assigned like it does on GitHub issues.

![image](https://cloud.githubusercontent.com/assets/961446/7276050/98422c7e-e8c4-11e4-8429-5d32c412f087.png)

**Comment by jonbrenner** [comment]
:thumbsup:

**Comment by jbencook** [comment]
+1

**Comment by iandundas** [comment]
+1

**Comment by richrdkng** [comment]
+1

We would use GitHub's milestone features **exclusively** through Waffle.io GUI. It would be quicker, better and more productive to us to use issues with milestones in a unified way.

Issues + Milestones (create, update, delete, overview, manage)

**Comment by kapkema** [comment]
:+1: This would be really helpful

**Comment by oscarmorrison** [comment]
+1

**Comment by cbumgard** [comment]
+1

**Comment by johntmyers** [comment]
+1

(seriously, 2 years old?)

**Comment by pvergne** [comment]
+1

**Comment by qswinson** [comment]
+1

**Comment by JoeWroe** [comment]
+1

**Comment by wimpers** [comment]
+1

**Comment by Entiat** [comment]
+1 I've got my (non-techie) wife using waffle to help us manage rental property tasks. Asking her to go to github and create a milestone...hahahahaha.

PLEASE bump this feature's priority to somewhere near the top!

Thanks!

**Comment by hughescr** [comment]
+1

**Comment by kaamoss** [comment]
+1 This is a great tool but I think 3 years might be reasonable enough to expect this functionality :)

**Comment by davidBBC** [comment]
+1 This NEEDS to be a feature

**Comment by Alisuehobbs** [comment]
This feature has been now been shipped! Give it a try and let us know what you think!

**Comment by davidBBC** [comment]
!!!!! Perfect. Thanks @Alisuehobbs!
