### ISSUE TITLE
improved backlog management and planning functionality

### ISSUE THREAD

**Issue by ashumz** [waffleio/waffle.io#924]
requested from several users throughout the course of our user interviews - the ability to better plan with milestones or a planning view, and improved backlog management for large backlogs

**Comment by kevinohara80** [comment]
+100000000000

A single column isn't working for us and our backlogs aren't even that large.

**Comment by OwenBrotherwood** [comment]
Backlogs are a bitch :-1: 
A backlog is often a product of taking in waffle after a backlog is accumilated and not having time or the overview of issues.
A backlog column should have some form for extra view that can take the backlog and show "interesting issues". Oldest first, most commented, least commented, newest in a highly clickable way to allow for tagging and assignment with the goal for closing the issue.

**Comment by ashumz** [comment]
@mustmodify @kevinohara80 @OwenBrotherwood - would any of you be interested in spending ~20 minutes talking with me to discuss how we can help with the pains of planning in Waffle? We'd like to learn how you're planning today, and how we can improve it for all of our users. Your feedback would be incredibly helpful! 

If interested, email ashley@waffle.io and I'll get in touch with you to set up a time. 

Thanks!

Ashley

**Comment by DS-Matt** [comment]
Like this idea - it would be great to have a "Roadmap" view that is simple drag and drop reordering of milestones from Github + the ability to add a new milestones and then a calendar overlay to show roughly when each milestone would happen. 

Plus 1 for this idea.

**Comment by AnaMSteele** [comment]
We are consolidating this card into #1153 and have moved the combined over  to help track this grouping of requested functionality overall. We are going to close this issue and would appreciate upvotes and further comments on the consolidated planning/backlog management card which is #1153. Thanks!
