### ISSUE TITLE
support GitHub @ replies / @ mentions that autocomplete the GitHub username in card description and comments

### ISSUE THREAD

**Issue by ashumz** [waffleio/waffle.io#925]
**We currently support GiHub @ mentions for collaborators only (completed in #2139.) This card is for extending the functionality to also be for anyone who has commented on the issue.**

Copy GitHub's autocomplete functionality:
- [x] typing `@` shows autocomplete
- [ ] typing login or name filters (e.g., typing `Austin` will show @IndieSquidge)
- [x] autocomplete any user that is a collaborator on the repo
- [ ] autocomplete any user who has commented on the issue
- [ ] autocomplete shows login and user

look into using https://github.com/jeff-collins/ment.io

**Comment by agibson22** [comment]
[+1](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/685608449)

**Comment by pelargir** [comment]
+1

**Comment by gillcosta** [comment]
+1

**Comment by jimwild** [comment]
+1

**Comment by booranger** [comment]
+1

**Comment by ashumz** [comment]
[+1](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/all/conversations/643961442)

"My request with the issue numbers is that it work like the entry and commenting in GH. If I type #2 I get and auto fill list of the issues and their titles when they start with 2 (e.g. 2 23, 271) . Works like code completion in a typical IDE."

**Comment by pauldiepenbrock** [comment]
+1

**Comment by ashumz** [comment]
[+1](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/711650765)

**Comment by ashumz** [comment]
[+1](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/all/conversations/713113260)

**Comment by brunosales** [comment]
+1

**Comment by brunosales** [comment]
+1

**Comment by carloshpds** [comment]
+1

**Comment by jeffling** [comment]
+1

**Comment by mustmodify** [comment]
Well people seem to have agreed with this ticket quite a lot. So two things.

First, I rather agree with @sam-github --
> I'd rather see the default behaviour of ANY click onto a card in waffle 
> be to open the card in github, rather than waffle spending time trying 
> to subsume the entire github issue/pr UI into a floating box in waffle.

And also, I would like to see @github implement a "+1" bit for their issue
tracker so we don't have to scroll through a bazillion comments with "+1".
Plus, having that as meta-data could be super-useful.

**Comment by jeffling** [comment]
@mustmodify @sam-github 

The only reason I use waffle is because that isn't the default functionality. Otherwise I would be using zenhub. This is really valuable because I can manage a project easily without leaving one UI.

**Comment by mustmodify** [comment]
@jeffling Then perhaps it could be configurable? I can totally appreciate wanting to keep it in one UI... on the other hand, reproducing a robust UI with same polish will be a chore.

**Comment by jeffling** [comment]
For sure :) Or load the github ui in an iframe ;)

**Comment by bajtos** [comment]
> Or load the github ui in an iframe

AFAIK you cannot load github in an iframe because they prohibit it via `X-FRAME-OPTIONS`.

**Comment by mjonker-embed** [comment]
+1

**Comment by mohierf** [comment]
+1

**Comment by RVMendoza** [comment]
+1 
![t0ptvtg](https://cloud.githubusercontent.com/assets/4342363/6905463/25ebcad4-d6f6-11e4-801c-b4cfe424a79c.gif)

**Comment by mpgerlek** [comment]
+1

**Comment by JeremybellEU** [comment]
+1

**Comment by ehausen** [comment]
+1

**Comment by syphar** [comment]
+1

**Comment by skotzko** [comment]
+1

**Comment by kwiens** [comment]
+1

**Comment by ndewhurst** [comment]
+1 for both @ and # seeds

**Comment by metalspawn** [comment]
+1

**Comment by jayrapson** [comment]
+1

**Comment by mjonker-embed** [comment]
+1

**Comment by jmeridth** [comment]
:+1:

**Comment by teejaynl** [comment]
+1

**Comment by timvdalen** [comment]
+1

**Comment by remcoplasmeyer** [comment]
+1

**Comment by mthomas33** [comment]
+1

**Comment by MLambropoulos** [comment]
+1

**Comment by Cor3387** [comment]
+1

**Comment by Hoejsgaard** [comment]
+1

**Comment by MFDW** [comment]
:+1: from me, thanks
(and emojis!)

**Comment by ashumz** [comment]
Hi all, 

I have created Issue #2139 (https://waffle.io/waffleio/waffle.io/cards/561e7aed0782781000d74a88) around autocomplete for collaborators only as an MVP of this functionality. We're curious to hear if this satisfies the majority of your needs for working within the Waffle issue modal? 

We'd like to provide the full functionality as detailed in the description of the card down the road, but if #2139 can help many of you in the meantime, we'd love to know! If it won't meet your needs, we'd love to know that too. Please feel free to make any additional comments on the newly created card (#2139.) 

Keep in mind that in the meantime, you can command or control + click on the issue card number OR comment icon from the board to quickly pull up GitHub's Issue view for a given card. You can click on the issue title from the detail modal to get to that GitHub view as well.


Ashley

**Comment by mustmodify** [comment]
I think including collaborators would be sufficient.

**Comment by MFDW** [comment]
an alternative would be to have a setting so that you can default to open GH issue views instead of waffles ones with a normal click..

**Comment by BlueT** [comment]
:+1:

**Comment by yaronyg** [comment]
:+1:

**Comment by katschre** [comment]
+1

**Comment by kellihsf** [comment]
Update on this issue (for those who haven't heard):
We have released the auto-complete for collaborators :)

**Comment by carloshpds** [comment]
Nice ! :)

**Comment by mustmodify** [comment]
Thank you!
