### ISSUE TITLE
Ability to see if an issue has been updated since it was categorized

### ISSUE THREAD

**Issue by ajoslin** [waffleio/waffle.io#927]
Hey waffle team,

Loving your product so far.  It's helping us work with issues a lot better.

I just had a thought a few minutes ago for a feature.

We have a 'needs user reply' column at https://waffle.io/driftyco/ionic

It would be really awesome if the issues that have had a comment/update since the time we moved them into a new column would somehow be emphasized.

For example, if I moved an issue that required the user's reply to the 'Needs user reply' column and he replied, I would be able to easily tell in Waffle that the issue has changed since I moved it.

Whatever medium is used to signify these 'has-new-updates' issues (shiny border, or a way to filter by 'updated issues', etc), it would be a great thing to have.

**Comment by TravisEz13** [comment]
+1 managing a large number of pull requests.  I need to go through a lot of requests to see if the user has replied.

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
