### ISSUE TITLE
Send bulk Waffle PRs

### ISSUE THREAD

**Issue by hemanth** [waffleio/waffle.io#929]
Want to use Waffle for several repos.

So it would be nice if there is a way to select the required repos and fire a waffle badge PR.

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
