### ISSUE TITLE
Add Asana as source option

### ISSUE THREAD

**Issue by soltveit** [waffleio/waffle.io#941]

**Comment by agibson22** [comment]
[+1](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/689454288)

**Comment by KyleChamberlin** [comment]
+1

**Comment by tonybaltovski** [comment]
+1

**Comment by itmsc** [comment]
+1

**Comment by milero** [comment]
+1

**Comment by calind** [comment]
+1

**Comment by t-ionut** [comment]
+1

**Comment by mariusveltan** [comment]
+1

**Comment by zalmanu** [comment]
:+1:

**Comment by dragostis** [comment]
:+1:

**Comment by razvanmo** [comment]
+1

**Comment by krodyrobi** [comment]
+1

**Comment by conklinbd** [comment]
:+1

**Comment by alexistruenoir** [comment]
+1

**Comment by yattias** [comment]
+1

**Comment by Merelleya** [comment]
+1

**Comment by cpostma-rally** [comment]
[+1](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/931385904)

**Comment by yattias** [comment]
Asana projects should have a 1:1 relationship between a waffle.io board. Labels in Asana should also sync over. As far as the recursive nature of Asana where tickets could have a list of tickets without end, this will require further thinking.

**Comment by gvangool** [comment]
+1

**Comment by mfarid** [comment]
+1

**Comment by djuarez** [comment]
+1

**Comment by allisonphillips** [comment]
+1

**Comment by niklasae** [comment]
+1

**Comment by nicoappel** [comment]
+1

**Comment by utkukaynar** [comment]
👍

**Comment by frostme** [comment]
+1

**Comment by adixsyukri** [comment]
+1

**Comment by guitassinari** [comment]
+1

**Comment by farlandlee** [comment]
+1

**Comment by galenstrasen** [comment]
+1

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
