### ISSUE TITLE
board should scroll when dragging cards horizontally

### ISSUE THREAD

**Issue by marydavis** [waffleio/waffle.io#958]

**Comment by tnrich** [comment]
second this! great work though guys

**Comment by ashumz** [comment]
[+1](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/720543691)

**Comment by ivarpruijn** [comment]
+1

Our board currently fits on the tablet we use during standup (barely), but to achieve that we had to remove a column we would have preferred to keep. Horizontal scrolling might make that workable again for us.

**Comment by mourner** [comment]
Yes, please!

**Comment by kelseyq** [comment]
+1! I end up having to move cards to an intermediate column to get them all the way to the right and it shows up confusingly in the issue history :(

**Comment by dpgover** [comment]
+1

**Comment by RifuI** [comment]
+1

**Comment by marydavis** [comment]
board now scrolls when dragging cards horizontally :)
