### ISSUE TITLE
Todoist integration

### ISSUE THREAD

**Issue by agibson22** [waffleio/waffle.io#962]
requested by esw9999@gmail.com

**Comment by egeerardyn** [comment]
:+1: I would very much like this.

There are currently some (partial) alternatives using [IFTTT](https://ifttt.com/recipes/search?q=GitHub+todoist&ac=false). I, e.g., have a recipe that adds a todoist task whenever I'm assigned an issue on GitHub, but apparently there are some recipes that convert Todoist tasks to issue reports (and hence cards).

**Comment by joehanna** [comment]
+1 for @agibson22 comment

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
