### ISSUE TITLE
Show person’s name in tooltip when hovering over avatar

### ISSUE THREAD

**Issue by roryokane** [waffleio/waffle.io#969]
To help teams recognize each other’s avatars that displayed at the top right of cards, a tooltip should be shown when the mouse hovers over an avatar for a second. This would be a standard tooltip displayed with the HTML `title` attribute, that only appears when the mouse is still over the target.

The tooltip should contain some combination of “assigned to”, the person’s username, and the person’s real name (if they wrote one on GitHub). For instance, the tooltip could say “Assigned to Rory O’Kane”, or it could say “roryokane (Rory O’Kane)”.

If you are trying to avoid hover effects – such as if you think it would happen accidentally a lot to people who just want to drag the entire card by the top right corner, but pause their mouse before doing so – there is a different thing you could do to make identifying people easier: putting the assignee’s name at the top of the list. When you click an avatar, a list pops up. The person whose name is checked may be far down the list, perhaps even offscreen if the card is near the bottom of the browser window. You could make it so that whatever option is checked is always right under Clear Collaborator at the top of the list. You might want to do this anyway, even if you do implement the tooltip – or perhaps the tooltip is enough to identify people easily with.

I want this for [our six-person team’s new waffle.io board](https://waffle.io/drexel-gmap-260-chain-gang/chained-escape). I imagine that when my team members start using this board and assigning people tasks in a few days, I will want to see who has been assigned to a particular task. Since I am unfamiliar with my team members’ avatars, I would like an easier way to identify them than clicking on their avatar and scrolling down so their username is visible in the list.

Also, some of my team members chose GitHub usernames very unlike their real names, which I already know. That is why it might help to put their real name in the tooltip (for team members who have entered one on GitHub). Or you might have a better solution for remembering real names, such as putting their real name in the list of people to assign the task to.

**Comment by mpgerlek** [comment]
+1

**Comment by agrizzlyadams** [comment]
+1

**Comment by marydavis** [comment]
We added tooltips on hover with the username :) Closing this issue, since we have another issue open for adding their real names, thx!
