### ISSUE TITLE
Ability to view card history (movement, status, etc)

### ISSUE THREAD

**Issue by agibson22** [waffleio/waffle.io#972]
From a customer:

We migrated from Leankit to Waffle. Leankit provides a history of all actions on a card: when the card was moved and from/to which lanes; what content/description changed from/to; who was assigned/unassigned to/from the card; changes in tags (labels) and other values such as size and priority. Much as it is possible for waffle to emulate all of these features at some point, the most useful, more pressing feature IMHO is the first - the progress through the lanes: "Card moved from Backlog to In Analysis by Richard", which could just be added as a comment to the GitHub issue. Obviously a setting would be needed because some users will not want that feature.

**Comment by timvdalen** [comment]
It would be very helpful to see this within the comment history, so you can see how card moves relate to comments.

**Comment by kellihsf** [comment]
[+1] (https://waffle.io/waffleio/waffle.io/cards/56ae7589f8a5d91e00b5e00b) from this user:

'While it is possible to use the "Show in Github" button on a card, it would be nice if the comments view showed the whole history of the issue (like it does on github - using the same icons, timeline style, etc).  

This would include: 
Label assignment and reassignment
Milestone assignment and reassignment
User assignment and reassignment
Commit message references - with the commit hash so you can see the actual code commit when clicking on the link. 

An example would be to look at the cards in Overv.io and how they show issue history.'

**Comment by pdurbin** [comment]
This all sounds great but the part that I'm especially interested in is seeing a log of who moved a card when from one column to another. A notification pops up at the top of the page ("So and so moved card 1234 from this column to that column") but I don't know where to find a log of these movements.

**Comment by rochacbruno** [comment]
+1

It would be very nice to have a timeline tab showing all the events

- user_x moved 123 from Ready to In Progress - 3 hours ago
- user_y added label ABC to 123 - 4 hours ago
- use_x removed label Ready from 123 - 5 hours ago
....

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
